# Oregon SMB Directory - Cloudflare Worker Configuration
name = "oregon-smb-directory"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Worker configuration
[env]
workers_dev = true

# D1 Database binding (same database for all environments)
[[d1_databases]]
binding = "DB"
database_name = "oregon-smb-directory"
database_id = "7fc369ad-7c69-4a2d-b5e0-825535c6a094"

# Development environment
[env.dev]
name = "oregon-smb-directory-dev"
workers_dev = true

[[env.dev.d1_databases]]
binding = "DB"
database_name = "oregon-smb-directory"
database_id = "7fc369ad-7c69-4a2d-b5e0-825535c6a094"

# Production environment
[env.production]
name = "oregon-smb-directory-prod"
workers_dev = false
routes = [
  { pattern = "oregonsmbdirectory.com/*", zone_name = "oregonsmbdirectory.com" },
  { pattern = "www.oregonsmbdirectory.com/*", zone_name = "oregonsmbdirectory.com" }
]

[[env.production.d1_databases]]
binding = "DB"
database_name = "oregon-smb-directory"
database_id = "7fc369ad-7c69-4a2d-b5e0-825535c6a094"

# Worker limits and configuration
[limits]
cpu_ms = 50

# Build configuration
[build]
command = "npm run build"