// Generated by Data Sealing Agent - 2025-08-11T04:20:19.746Z
// Total businesses: 8
// Cities: 6, Industries: 6

export interface Business {
  id: string;
  name: string;
  trade: string;
  phone: string;
  email?: string;
  website?: string;
  address: {
    street: string;
    city: string;
    state: string;
    zipCode: string;
  };
  services: string[];
  specialties?: string[];
  hours?: string;
  rating?: number;
  reviewCount?: number;
  licenseNumber?: string;
  yearsInBusiness?: number;
  verified: boolean;
  featured?: boolean;
  emergencyService?: boolean;
  bbbRating?: string;
}

// Medford ROOFERS (1 businesses)
export const MEDFORD_ROOFERS: Business[] = [
  {
    id: 'medford-premier-roofing-medford-3',
    name: 'Medford Premier Roofing',
    trade: 'Roofer',
    phone: '(541) 555-0303',
    website: 'https://medfordroofing.com',
    address: {
      street: '890 Crater Lake Ave',
      city: 'Medford',
      state: 'OR',
      zipCode: '97504'
    },
    services: ['Residential Roofing', 'Commercial Roofing', 'Roof Repair', 'Gutter Installation'],
    specialties: ['Metal Roofing', 'Emergency Storm Repair'],
    hours: 'Mon-Fri: 7AM-5PM',
    rating: 4.8,
    reviewCount: 76,
    licenseNumber: 'RF45678',
    yearsInBusiness: 28,
    verified: true,
    emergencyService: true,
  },
];

// Roseburg ELECTRICIANS (1 businesses)
export const ROSEBURG_ELECTRICIANS: Business[] = [
  {
    id: 'roseburg-electric-works-roseburg-7',
    name: 'Roseburg Electric Works',
    trade: 'Electrician',
    phone: '(541) 555-0707',
    website: 'https://roseburgelelectric.com',
    address: {
      street: '321 NE Garden Valley Blvd',
      city: 'Roseburg',
      state: 'OR',
      zipCode: '97470'
    },
    services: ['Residential Wiring', 'Commercial Electrical', 'Generator Installation', 'Electrical Troubleshooting'],
    specialties: ['Backup Generators', 'Outdoor Lighting'],
    hours: 'Mon-Fri: 8AM-5PM',
    rating: 4.3,
    reviewCount: 29,
    licenseNumber: 'EL13579',
    yearsInBusiness: 8,
    verified: true,
    emergencyService: true,
  },
];

// Eugene GENERAL CONTRACTORS (1 businesses)
export const EUGENE_GENERAL_CONTRACTORS: Business[] = [
  {
    id: 'eugene-home-builders-eugene-5',
    name: 'Eugene Home Builders',
    trade: 'General Contractor',
    phone: '(541) 555-0505',
    email: 'info@eugenehomebuilders.com',
    website: 'https://eugenehomebuilders.com',
    address: {
      street: '456 Willamette Street',
      city: 'Eugene',
      state: 'OR',
      zipCode: '97401'
    },
    services: ['New Construction', 'Home Renovations', 'Kitchen Remodeling', 'Bathroom Remodeling'],
    specialties: ['Sustainable Building', 'Custom Homes'],
    hours: 'Mon-Fri: 7AM-4PM',
    rating: 4.9,
    reviewCount: 92,
    licenseNumber: 'GC24680',
    yearsInBusiness: 35,
    verified: true,
    bbbRating: 'A'
  },
];

// Salem LAWFIRMS (1 businesses)
export const SALEM_LAWFIRMS: Business[] = [
  {
    id: 'salem-law-group-llc-salem-4',
    name: 'Salem Law Group LLC',
    trade: 'Attorney',
    phone: '(503) 555-0404',
    email: 'contact@salemlawgroup.com',
    website: 'https://www.salemlawgroup.com',
    address: {
      street: '123 State Street',
      city: 'Salem',
      state: 'OR',
      zipCode: '97301'
    },
    services: ['Personal Injury Law', 'Family Law', 'Criminal Defense', 'Business Law'],
    specialties: ['DUI Defense', 'Divorce Mediation'],
    hours: 'Mon-Fri: 8AM-5PM',
    rating: 4.6,
    reviewCount: 45,
    licenseNumber: 'LW98765',
    yearsInBusiness: 12,
    verified: true,
    featured: true,
    bbbRating: 'A+'
  },
];

// Portland PLUMBERS (1 businesses)
export const PORTLAND_PLUMBERS: Business[] = [
  {
    id: 'rose-city-plumbing-services-portland-2',
    name: 'Rose City Plumbing Services',
    trade: 'Plumber',
    phone: '(503) 555-0202',
    email: 'service@rosecityplumbing.com',
    website: 'https://rosecityplumbing.com',
    address: {
      street: '4567 NE Sandy Blvd',
      city: 'Portland',
      state: 'OR',
      zipCode: '97232'
    },
    services: ['Emergency Plumbing', 'Water Heater Repair', 'Drain Cleaning', 'Pipe Replacement'],
    specialties: ['Tankless Water Heaters', 'Sewer Line Repair'],
    hours: '24/7 Emergency Service',
    rating: 4.7,
    reviewCount: 134,
    licenseNumber: 'PL67890',
    yearsInBusiness: 15,
    verified: true,
    emergencyService: true,
    bbbRating: 'A'
  },
];

// Portland ELECTRICIANS (1 businesses)
export const PORTLAND_ELECTRICIANS: Business[] = [
  {
    id: 'pacific-northwest-electric-portland-1',
    name: 'Pacific Northwest Electric',
    trade: 'Electrician',
    phone: '(503) 555-0101',
    email: 'info@pnwelectric.com',
    website: 'https://www.pnwelectric.com',
    address: {
      street: '1234 SW Broadway',
      city: 'Portland',
      state: 'OR',
      zipCode: '97205'
    },
    services: ['Residential Electrical', 'Commercial Electrical', 'Smart Home Installation', 'Panel Upgrades'],
    specialties: ['Tesla Charger Installation', 'Solar Panel Wiring'],
    hours: 'Mon-Fri: 7AM-6PM, Sat: 8AM-4PM',
    rating: 4.9,
    reviewCount: 87,
    licenseNumber: 'EL12345',
    yearsInBusiness: 22,
    verified: true,
    featured: true,
    emergencyService: true,
    bbbRating: 'A+'
  },
];

export async function getBusinessesByCity(citySlug: string, industrySlug: string): Promise<Business[]> {
  const key = `${citySlug}_${industrySlug.replace('-', '_').toUpperCase()}`;
  
  switch (key) {
    case 'medford_ROOFERS':
      return MEDFORD_ROOFERS;
    case 'roseburg_ELECTRICIANS':
      return ROSEBURG_ELECTRICIANS;
    case 'eugene_GENERAL_CONTRACTORS':
      return EUGENE_GENERAL_CONTRACTORS;
    case 'salem_LAWFIRMS':
      return SALEM_LAWFIRMS;
    case 'portland_PLUMBERS':
      return PORTLAND_PLUMBERS;
    case 'portland_ELECTRICIANS':
      return PORTLAND_ELECTRICIANS;
    default:
      return [];
  }
}

export async function getBusinessById(id: string): Promise<Business | null> {
  const allBusinesses = [
    ...MEDFORD_ROOFERS,
    ...ROSEBURG_ELECTRICIANS,
    ...EUGENE_GENERAL_CONTRACTORS,
    ...SALEM_LAWFIRMS,
    ...PORTLAND_PLUMBERS,
    ...PORTLAND_ELECTRICIANS,
  ];
  
  return allBusinesses.find(business => business.id === id) || null;
}

// Business count summary:
// Medford roofers: 1 businesses
// Roseburg electricians: 1 businesses
// Eugene general contractors: 1 businesses
// Salem lawfirms: 1 businesses
// Portland plumbers: 1 businesses
// Portland electricians: 1 businesses
// Total: 8 businesses
