INSERT INTO businesses (
      id, name, city, state, industry, services, verified, website, 
      yearsInBusiness, phone, address, email, rating, reviewCount, 
      licenseNumber, bbbRating, emergencyService
    ) VALUES (
    'medford-General-Contractors-144',
    'Brady Lee Porter',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 227-9665',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-145',
    'Scott B. Owings Construction Inc.',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Real Estate Developers","!Brian Lee Jonhsen - Home Builders"]',
    1,
    NULL,
    26,
    '(541) 890-7863',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-146',
    'Brian Lee Jonhsen',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Moore Construction - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 261-6880',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-147',
    'Moore Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors-Commercial & Industrial","!Mahar Brothers Construction - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 840-6569',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-148',
    'Mahar Brothers Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors-Commercial & Industrial"]',
    1,
    NULL,
    NULL,
    '(541) 608-9288',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-149',
    'Alpine Construction-Remodeling',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Building Contractors-Commercial & Industrial"]',
    1,
    'https://www.alpinebuildinc.com/',
    NULL,
    '(541) 772-3307',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-150',
    'Kevin Paul Potts & Lauren Jihan Mapp',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Esparza Bros Construction - Building Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 951-2969',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-151',
    'Esparza Bros Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","!Dustin Allen Ratcliff - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 324-5075',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-152',
    'Dustin Allen Ratcliff',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 951-7640',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-153',
    'PRO Mechanical Insulation',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Insulation Contractors","Home Builders","!Mahar Homes - Interior Designers & Decorators"]',
    1,
    NULL,
    NULL,
    '(541) 601-8523',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-154',
    'Mahar Homes',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Interior Designers & Decorators","Home Builders","!Claudio Alvarez Construction - Home Builders"]',
    1,
    'http://maharhomes.com/',
    NULL,
    '(541) 776-1200',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-155',
    'Claudio Alvarez Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Altering & Remodeling Contractors","!Foresite - Home Builders"]',
    1,
    'https://www.alvarezrestoration.com/',
    NULL,
    '(541) 727-7340',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-156',
    'Foresite',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Benjaminn Rick Blank - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 245-1183',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-157',
    'Benjaminn Rick Blank',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Laduke Construction - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 941-1687',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-158',
    'Laduke Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Construction Management","!Trevor Thomas Cox - Home Builders"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 772-1277',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-159',
    'Trevor Thomas Cox',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Riverline Construction - Construction Management"]',
    1,
    NULL,
    NULL,
    '(541) 973-8735',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-160',
    'Riverline Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Construction Management","Home Builders"]',
    1,
    'https://members.buildso.com/list/member/riverline-construction-llc-50891',
    NULL,
    '(541) 727-7334',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-161',
    'Better Built Fence & Deck',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Fence-Sales, Service & Contractors","Home Builders","!Corey Robbins Painting Co - Painting Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 734-2387',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-162',
    'Corey Robbins Painting Co',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Painting Contractors","!Rick Travis Cave - Home Builders"]',
    1,
    'http://www.coreyrobbins.com/',
    52,
    '(541) 770-5275',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-163',
    'Rick Travis Cave',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Klaassen & Barnes Construction - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 301-6108',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-164',
    'Klaassen & Barnes Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Real Estate Developers"]',
    1,
    NULL,
    NULL,
    '(541) 773-3217',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-165',
    'Burl Brim Excavation Inc',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Excavation Contractors","!Dennis Williams - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 488-1095',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-166',
    'Dennis Williams',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Valley Construction - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 821-7063',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-167',
    'Valley Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Excavation Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 512-9101',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-168',
    'Rogue Valley Renovation',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Repair & Maintenance","Kitchen Planning & Remodeling Service","!Medford Gutter Co - Gutters & Downspouts"]',
    1,
    NULL,
    30,
    '(541) 646-1369',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-169',
    'Medford Gutter Co',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Gutters & Downspouts","Roofing Contractors","!Rogue Valley Tile - Tile-Contractors & Dealers"]',
    1,
    NULL,
    NULL,
    '(541) 890-4258',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-170',
    'Rogue Valley Tile',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Tile-Contractors & Dealers","Concrete Pumping Contractors","!Handymoose Home Improvements - Handyman Services"]',
    1,
    'http://roguevalleytile.com/',
    16,
    '(541) 944-1517',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-171',
    'Handymoose Home Improvements',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Handyman Services","Home Improvements"]',
    1,
    NULL,
    NULL,
    '(541) 301-7471',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-172',
    'Eric''s Custom Decks and Fences',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Landscape Contractors","!Vallente, Dane K - General Contractor Engineers"]',
    1,
    NULL,
    NULL,
    '(541) 610-9691',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-173',
    'Vallente, Dane K',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","General Contractor Engineers","Building Contractors","!Day Electric Inc - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 840-1462',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-174',
    'Day Electric Inc',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Electricians","Electric Contractors-Commercial & Industrial","!911 Handyman - Handyman Services"]',
    1,
    NULL,
    NULL,
    '(541) 857-5970',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-175',
    '911 Handyman',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Handyman Services","Siding Contractors"]',
    1,
    'http://911handyman.com/',
    17,
    '(541) 840-0353',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-176',
    'Cut''n Break Construction Inc',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Concrete Breaking, Cutting & Sawing","Concrete Contractors","!Ken Harris - Home Builders"]',
    1,
    'http://www.cutnbreak.com/cutting.htm',
    46,
    '(541) 779-1482',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-177',
    'Ken Harris',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Z to A Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 821-3318',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-178',
    'Z to A Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Altering & Remodeling Contractors"]',
    1,
    'http://alvarezrestoration.com/',
    NULL,
    '(541) 727-7607',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-179',
    'International Line Builders',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Electricians","Building Contractors","!River Run Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 830-1001',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-180',
    'River Run Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","!Harkey Homes & Design Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 261-5282',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-181',
    'Harkey Homes & Design Inc',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!Benchmark Builders - General Contractors"]',
    1,
    'http://harkeyhomesanddesign.com/',
    NULL,
    '(541) 664-5203',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-182',
    'Benchmark Builders',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors"]',
    1,
    'http://benchmarkbuilders.net/',
    NULL,
    '(541) 535-8707',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-183',
    'Evergreen Restoration and Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!Jf Shea Construction Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 613-0607',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-184',
    'Jf Shea Construction Inc',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Brian Tokar Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 664-2964',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-185',
    'Brian Tokar Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Building Contractors","!South Valley Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 664-1956',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-186',
    'South Valley Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Deck Builders","Altering & Remodeling Contractors"]',
    1,
    'https://www.svcoregon.com/',
    NULL,
    '(541) 665-3310',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-187',
    'Framing to Finish Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Home Improvements","!DaBella - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 621-7104',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-188',
    'DaBella',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!Frankenstein Builders - General Contractors"]',
    1,
    'https://dabella.us/location/medford',
    NULL,
    '(541) 293-0654',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-189',
    'Frankenstein Builders',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Windows","Kitchen Planning & Remodeling Service","!Dan Philpot Construction - General Contractors"]',
    1,
    'https://www.frankensteinbuilders.com/',
    NULL,
    '(541) 890-2513',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-190',
    'Dan Philpot Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors-Commercial & Industrial","!Arruda Built Construction - General Contractors"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 826-6144',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-191',
    'Arruda Built Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!Hanratty Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 227-4884',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-192',
    'Hanratty Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors-Commercial & Industrial","!Quail Run - General Contractors"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 826-4300',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-193',
    'Quail Run',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!Eagle Point by Holt Homes - General Contractors"]',
    1,
    'https://holthomes.com/communities/quail-run',
    NULL,
    '(971) 299-2799',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-194',
    'Eagle Point by Holt Homes',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!Southern Oregon Steel - General Contractors"]',
    1,
    'https://holthomes.com/communities/eagle-point',
    NULL,
    '(971) 299-2799',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-195',
    'Southern Oregon Steel',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Davis Construction - General Contractors"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 826-8523',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-196',
    'Davis Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","Home Builders","!Golden-Fields Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 482-3103',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-197',
    'Golden-Fields Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors-Commercial & Industrial","!D A Boldt Construction Co - General Contractors"]',
    1,
    'http://golden-fields.net/',
    NULL,
    '(541) 482-8442',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-198',
    'D A Boldt Construction Co',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Tile-Contractors & Dealers","Flooring Contractors","!Raymond R Kappell - General Contractors"]',
    1,
    'http://daboldtconstruction.com/',
    53,
    '(541) 482-4865',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-199',
    'Raymond R Kappell',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 944-6399',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-200',
    'Precision Builders-Remodeling',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors-Commercial & Industrial","!Diamondback Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 661-7116',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-201',
    'Diamondback Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 951-3818',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-202',
    'Michael J Davis Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Insulation Materials","!Diamond Home Builders Inc - General Contractors"]',
    1,
    'https://southernoregonremodels.com/contact-1',
    NULL,
    '(541) 301-0556',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-203',
    'Diamond Home Builders Inc',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!Bryan Backen Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 890-2441',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-204',
    'Bryan Backen Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Air Conditioning Contractors & Systems","!Joshua K Babb Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 664-3733',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-205',
    'Joshua K Babb Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Lochrie Construction Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 660-6963',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-206',
    'Lochrie Construction Inc',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!C C Constructors - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 292-3353',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-207',
    'C C Constructors',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors-Commercial & Industrial","!Riverdell Construction Inc - General Contractors"]',
    1,
    'https://candcconstructors.com/contact-us',
    NULL,
    '(541) 608-7123',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-208',
    'Riverdell Construction Inc',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Sargent Mechanical - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 727-7707',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-209',
    'Sargent Mechanical',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Utility Contractors","!Riverdell Construction Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 951-6543',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-210',
    'Riverdell Construction Inc',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    'https://riverdellconstruction.com/',
    NULL,
    '(541) 727-7707',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-1',
    'Penny Lee Austin, Attorney',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Elder Law Attorneys","Wills, Trusts & Estate Planning Attorneys","!Law Office of Rebecca Whitney-Smith - Attorneys"]',
    1,
    'http://www.pennyleeaustin.com/',
    44,
    '(541) 210-8141',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-2',
    'Law Office of Rebecca Whitney-Smith',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Medical Malpractice Attorneys","Child Custody Attorneys","!Legal Aid Legal Services Corp - Attorneys"]',
    1,
    'http://www.whitneysmithlaw.com/',
    27,
    '(541) 238-2986',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-3',
    'Legal Aid Legal Services Corp',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Legal Document Assistance","Paralegals","!Alexis Packer, Attorney At Law - Attorneys"]',
    1,
    'http://legalaiddocumentservicesinc.com/',
    19,
    '(844) 330-7981',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-4',
    'Alexis Packer, Attorney At Law',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Wills, Trusts & Estate Planning Attorneys","Elder Law Attorneys"]',
    1,
    'https://www.ashlanddirectory.com/listing/packer_alexis_j_attorney_at_law22495',
    31,
    '(541) 482-0570',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-5',
    'Social Security Disability Advisors',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Social Security & Disability Law Attorneys","Contact Us","!Donald Scales Law Office - Attorneys"]',
    1,
    'http://www.disabilityadvisors.com/',
    39,
    '(888) 372-7758',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-6',
    'Donald Scales Law Office',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Legal Service Plans","Criminal Law Attorneys","!Jason C Broesder Attorney - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 772-2363',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-7',
    'Jason C Broesder Attorney',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Shack, Emily, ATTY - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 773-1222',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-8',
    'Shack, Emily, ATTY',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Personal Injury Law Attorneys","Insurance Attorneys","!Craig S Galpern Attorney - Attorneys"]',
    1,
    'https://letusfightforyou.com/our-attorneys/emily-shack',
    NULL,
    '(541) 779-7955',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-9',
    'Craig S Galpern Attorney',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Family Law Attorneys"]',
    1,
    'http://www.osbar.org/',
    NULL,
    '(541) 779-5131',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-10',
    'Law Office of Edward H. Talmadge, P.C.',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Levy & Harris A Mother & Son Firm - Attorneys"]',
    1,
    'http://www.talmadgefirm.com/',
    NULL,
    '(541) 500-8082',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-11',
    'Levy & Harris A Mother & Son Firm',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Legal Service Plans","Family Law Attorneys","!Eric R Stark - Attorneys"]',
    1,
    'https://levyandharris.com/',
    NULL,
    '(541) 225-5226',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-12',
    'Eric R Stark',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Jacobson Thierolf & Dickey - Attorneys"]',
    1,
    'http://starkhammack.com/',
    NULL,
    '(541) 773-2213',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-13',
    'Jacobson Thierolf & Dickey',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Real Estate Attorneys","Estate Planning Attorneys","!Douglas M. McGeary Attorney At Law - Attorneys"]',
    1,
    'http://www.jtdlegal.com/',
    46,
    '(541) 773-2727',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-14',
    'Douglas M. McGeary Attorney At Law',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Collins Rowan, LLP - Attorneys"]',
    1,
    'http://www.douglasmmcgeary.com/',
    17,
    '(541) 779-4647',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-15',
    'Collins Rowan, LLP',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Criminal Law Attorneys","!Sarpa Law - Attorneys"]',
    1,
    'https://collinsrowan.com/',
    NULL,
    '(541) 773-3606',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-16',
    'Sarpa Law',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Immigration Law Attorneys","Legal Service Plans","!Austin, Penny L, ATTY - Attorneys"]',
    1,
    'https://www.sarpa-law.com/',
    NULL,
    '(541) 772-8635',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-17',
    'Austin, Penny L, ATTY',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Estate Planning, Probate, & Living Trusts","Business Law Attorneys","!Bryan Blodgett Attorney - Attorneys"]',
    1,
    'http://www.pennyleeaustin.com/',
    NULL,
    '(541) 770-6720',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-18',
    'Bryan Blodgett Attorney',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Criminal Law Attorneys","Family Law Attorneys","!Olsen & Daines - Attorneys"]',
    1,
    NULL,
    47,
    '(541) 618-9429',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-19',
    'Olsen & Daines',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","General Practice Attorneys","Bankruptcy Services","!Kelly  L Andersen PC - Attorneys"]',
    1,
    'https://www.olsendaines.com/',
    NULL,
    '(503) 362-9393',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-20',
    'Kelly L Andersen PC',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","General Practice Attorneys","Automobile Accident Attorneys","!Grantland Blodgett Shaw & Abel - Attorneys"]',
    1,
    'http://www.andersenlaw.com/',
    29,
    '(541) 773-7000',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-21',
    'Grantland Blodgett Shaw & Abel',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Brian Law Firm LLC - Attorneys"]',
    1,
    'http://www.medfordlegal.com/',
    33,
    '(541) 773-6855',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-22',
    'Brian Law Firm LLC',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Personal Injury Law Attorneys","General Practice Attorneys","!Rise Law Group - Attorneys"]',
    1,
    'http://www.brianlawfirm.com/',
    37,
    '(541) 772-1334',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-23',
    'Rise Law Group',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Divorce Attorneys","Family Law Attorneys","!C Casey White Attorney At Law - Attorneys"]',
    1,
    'http://www.riselawgroup.org/',
    NULL,
    '(541) 500-9058',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-24',
    'C Casey White Attorney At Law',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Bankruptcy Law Attorneys","Estate Planning, Probate, & Living Trusts","!Michael Stedman Law Office - Attorneys"]',
    1,
    'http://www.ccaseywhite.com/',
    NULL,
    '(541) 779-4912',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-25',
    'Michael Stedman Law Office',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Campbell, G, G, JD - Attorneys"]',
    1,
    'http://www.manta.com/c/mtxgz4k/michael-stedman-law-office',
    15,
    '(541) 779-1070',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-26',
    'Campbell, G, G, JD',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!RM Vanderhoof - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 776-5025',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-27',
    'RM Vanderhoof',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Law Offices - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 500-1506',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-28',
    'Law Offices',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Rennie Law - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 774-4013',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-29',
    'Rennie Law',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Legal Service Plans","!AA Bankruptcy Clinic - Attorneys"]',
    1,
    'http://www.rennielawoffice.com/',
    NULL,
    '(541) 414-0300',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-30',
    'AA Bankruptcy Clinic',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Legal Service Plans","!James Dietz Attorney - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 770-9108',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-31',
    'James Dietz Attorney',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Bankruptcy Law Attorneys","!Wallan, James A, ATY - Attorneys"]',
    1,
    NULL,
    36,
    '(541) 779-1104',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-32',
    'Wallan, James A, ATY',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Southern Oregon''s Premier Law Firm - Attorneys"]',
    1,
    'https://www.roguelaw.com/james-a-wallan',
    NULL,
    '(541) 779-8900',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-33',
    'Southern Oregon''s Premier Law Firm',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Wills, Trusts & Estate Planning Attorneys","!Mayerle, Michael J, ATY - Attorneys"]',
    1,
    'http://www.roguelaw.com/',
    NULL,
    '(541) 623-0178',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  );