INSERT INTO businesses (
      id, name, city, state, industry, services, verified, website, 
      yearsInBusiness, phone, address, email, rating, reviewCount, 
      licenseNumber, bbbRating, emergencyService
    ) VALUES (
    'eugene-Electricians-1',
    'Builder''s Electric, Inc.',
    'Eugene',
    'OR',
    'electricians',
    '["Electricians","Lighting Contractors","Security Control Systems & Monitoring","!Revolution Electric - Electricians"]',
    1,
    'http://www.builderselectric.com/',
    65,
    '(541) 543-2290',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Electricians-2',
    'Revolution Electric',
    'Eugene',
    'OR',
    'electricians',
    '["Electricians","!Ericson Electric Inc - Electricians"]',
    1,
    'https://revolutionelectric.net/',
    NULL,
    '(458) 320-0534',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Electricians-3',
    'Ericson Electric Inc',
    'Eugene',
    'OR',
    'electricians',
    '["Electricians","Irrigation Systems & Equipment","Generators","!Thornton Electric Inc - Electricians"]',
    1,
    'https://www.ericsonelect.com/',
    6,
    '(541) 632-8654',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Electricians-4',
    'Thornton Electric Inc',
    'Eugene',
    'OR',
    'electricians',
    '["Electricians","!Olsson Industrial Electric - Electricians"]',
    1,
    'https://thornton-electric.com/',
    6,
    '(541) 844-7152',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Electricians-5',
    'Olsson Industrial Electric',
    'Eugene',
    'OR',
    'electricians',
    '["Electricians","Business Coaches & Consultants","Industrial Equipment & Supplies","!Thornton Electric, Inc. - Electricians"]',
    1,
    'http://olssonelec.com/',
    43,
    '(541) 762-2902',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Electricians-6',
    'Thornton Electric, Inc.',
    'Eugene',
    'OR',
    'electricians',
    '["Electricians","!Contractors Electric - Electricians"]',
    1,
    'http://thornton-electric.com/',
    56,
    '(541) 686-1628',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Electricians-7',
    'Contractors Electric',
    'Eugene',
    'OR',
    'electricians',
    '["Electricians","!Polaris Electrical, Inc. - Electricians"]',
    1,
    'http://www.electrician-eugene.com/',
    15,
    '(541) 343-2222',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Electricians-8',
    'Polaris Electrical, Inc.',
    'Eugene',
    'OR',
    'electricians',
    '["Electricians","!Reynolds Electric Inc - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 343-0824',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Electricians-9',
    'Reynolds Electric Inc',
    'Eugene',
    'OR',
    'electricians',
    '["Electricians","Security Control Systems & Monitoring","Security Equipment & Systems Consultants","!Oregon Electric Service - Electricians"]',
    1,
    NULL,
    45,
    '(541) 343-7297',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Electricians-10',
    'Oregon Electric Service',
    'Eugene',
    'OR',
    'electricians',
    '["Electricians","Electric Equipment & Supplies","!Full Service Electric - Electricians"]',
    1,
    'https://orelectricservice.com/contact',
    70,
    '(541) 343-1681',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Electricians-11',
    'Full Service Electric',
    'Eugene',
    'OR',
    'electricians',
    '["Electricians","!Bear Mountain Electric - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 246-4755',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Electricians-12',
    'Bear Mountain Electric',
    'Eugene',
    'OR',
    'electricians',
    '["Electricians","!New Way Electric Inc - Electricians"]',
    1,
    'http://www.bearmountainelectric.com/',
    26,
    '(541) 741-8844',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Electricians-13',
    'New Way Electric Inc',
    'Eugene',
    'OR',
    'electricians',
    '["Electricians","!Stapleton Electric - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 868-1659',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Electricians-14',
    'Stapleton Electric',
    'Eugene',
    'OR',
    'electricians',
    '["Electricians","Air Conditioning Contractors & Systems","Heating Contractors & Specialties","!Beacon Electric & Lighting - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 484-7278',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Electricians-15',
    'Beacon Electric & Lighting',
    'Eugene',
    'OR',
    'electricians',
    '["Electricians","Electric Companies","Lighting Maintenance Service"]',
    1,
    'http://www.beaconlighting.com/',
    69,
    '(541) 461-0291',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Electricians-16',
    'Lane Electric Cooperative, Inc',
    'Eugene',
    'OR',
    'electricians',
    '["Electricians","Electric Companies","Utility Companies","!HCH Electric - Electricians"]',
    1,
    'https://laneelectric.com/',
    86,
    '(541) 484-1151',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Electricians-17',
    'HCH Electric',
    'Eugene',
    'OR',
    'electricians',
    '["Electricians","Air Conditioning Contractors & Systems","Heating Contractors & Specialties","!Excel Electric - Electricians"]',
    1,
    'http://hchelectric.net/',
    NULL,
    '(541) 345-2838',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Electricians-18',
    'Excel Electric',
    'Eugene',
    'OR',
    'electricians',
    '["Electricians","!Oregon Electric Group - Electricians"]',
    1,
    'https://excel-electric.com/',
    NULL,
    '(541) 234-8988',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Electricians-19',
    'Oregon Electric Group',
    'Eugene',
    'OR',
    'electricians',
    '["Electricians","!Reynolds Electric and Plumbing - Electricians"]',
    1,
    'http://oeg.us.com/',
    NULL,
    '(541) 747-0811',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Electricians-20',
    'Reynolds Electric and Plumbing',
    'Eugene',
    'OR',
    'electricians',
    '["Electricians","Home Builders","Plumbers","!New Way Electric Inc - Electricians"]',
    1,
    'https://reynoldsep.com/',
    NULL,
    '(541) 343-7297',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Electricians-21',
    'New Way Electric Inc',
    'Eugene',
    'OR',
    'electricians',
    '["Electricians","!Excel Electric - Electricians"]',
    1,
    'http://www.newwayelectric.com/',
    46,
    '(541) 686-2365',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Electricians-22',
    'Excel Electric',
    'Eugene',
    'OR',
    'electricians',
    '["Electricians"]',
    1,
    'https://www.excel-electric.com/',
    NULL,
    '(541) 952-1492',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Electricians-23',
    'Blachly-Lane County Cooperative Electric Association',
    'Eugene',
    'OR',
    'electricians',
    '["Electricians","Electric Companies","Utility Companies","!Frontier Technology Inc - Electric Companies"]',
    1,
    'https://www.blachlylane.coop/contact-us',
    NULL,
    '(541) 688-8711',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Electricians-24',
    'Frontier Technology Inc',
    'Eugene',
    'OR',
    'electricians',
    '["Electric Companies","Utility Companies"]',
    1,
    NULL,
    NULL,
    '(541) 683-5200',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Electricians-25',
    'Emerald People''s Utility District',
    'Eugene',
    'OR',
    'electricians',
    '["Electric Companies","!Electrical Contractor - Electricians"]',
    1,
    'https://www.epud.org/contact',
    NULL,
    '(541) 746-1583',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Electricians-26',
    'Electrical Contractor',
    'Eugene',
    'OR',
    'electricians',
    '["Electricians","!Eugene Water Electric Bo - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 337-6735',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Electricians-27',
    'Eugene Water Electric Bo',
    'Eugene',
    'OR',
    'electricians',
    '["Electricians","!Livewire Electric Inc - Electricians"]',
    1,
    'https://www.eweb.org/',
    NULL,
    '(541) 484-2411',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Electricians-28',
    'Livewire Electric Inc',
    'Eugene',
    'OR',
    'electricians',
    '["Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 344-4928',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Electricians-29',
    'Superior Electric and Construction',
    'Eugene',
    'OR',
    'electricians',
    '["Electricians","General Contractors","!Integrated Solutions - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 461-0387',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Electricians-30',
    'Integrated Solutions',
    'Eugene',
    'OR',
    'electricians',
    '["Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 485-7545',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-1',
    'Bell Real Estate Inc.',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","Rental Vacancy Listing Service","!Scott John L - Real Estate Agents"]',
    1,
    'http://www.bell-realty.com/',
    63,
    '(458) 320-0072',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-2',
    'Scott John L',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Clyde David Real Estate - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 344-3983',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-3',
    'Clyde David Real Estate',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate","!Realty One Grp Platinum - Real Estate Agents"]',
    1,
    'http://www.dclydere.com/',
    NULL,
    '(541) 343-9309',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-4',
    'Realty One Grp Platinum',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Walker C W & Associates - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 743-8999',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-5',
    'Walker C W & Associates',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate","!Turning Point Realty - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 484-4422',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-6',
    'Turning Point Realty',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Consultants","!Remax - Real Estate Agents"]',
    1,
    'http://www.turningpointrealtygroup.com/',
    16,
    '(541) 520-2132',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-7',
    'Remax',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","View all 5 Locations"]',
    1,
    'http://www.teamraze.com/',
    NULL,
    '(541) 284-8068',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-8',
    'Ken & Jaclyn Pettigrew, REALTORS | Team KJ | Hybrid Real Estate',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","!O''Reilly Property Group - Real Estate Agents"]',
    1,
    'https://www.kjrealty.homes/',
    6,
    '(541) 525-1196',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-9',
    'O''Reilly Property Group',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Agate Real Estate - Real Estate Agents"]',
    1,
    'https://oreillypg.com/',
    NULL,
    '(541) 287-6424',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-10',
    'Agate Real Estate',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","!Cook, Bryn, RLTR - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 337-9333',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-11',
    'Cook, Bryn, RLTR',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://www.eugeneliving.com/',
    NULL,
    '(541) 505-0691',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-12',
    'Merrill Moore Realtor at Equinox Real Estate',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Investing","Real Estate Buyer Brokers"]',
    1,
    'https://www.merrillmoorerealestate.com/',
    NULL,
    '(541) 543-8354',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-13',
    'Heart & Home Real Estate, Eugene REALTORS',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Consultants","!Off & Running Real Estate - Real Estate Agents"]',
    1,
    'https://www.lanecountyhomes.net/',
    NULL,
    '(541) 253-4090',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-14',
    'Off & Running Real Estate',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Gorilla Capital - Real Estate Agents"]',
    1,
    'https://offandrunning.net/',
    17,
    '(541) 653-6623',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-15',
    'Gorilla Capital',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate"]',
    1,
    'http://www.gorillacapital.com/',
    NULL,
    '(541) 505-8048',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-16',
    'Mario Ruiz - Eugene Realtor With Icon',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Cody Windermere Real Estate - Real Estate Agents"]',
    1,
    'https://propertiesineugene.com/',
    NULL,
    '(541) 868-4307',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-17',
    'Cody Windermere Real Estate',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate","!Jennings Group Inc - Real Estate Agents"]',
    1,
    'https://codymeans.withwre.com/',
    NULL,
    '(541) 953-0344',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-18',
    'Jennings Group Inc',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","Apartment Finder & Rental Service","!Century 21 - Real Estate Agents"]',
    1,
    'https://www.jenningsgroup.com/',
    NULL,
    '(541) 683-2271',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-19',
    'Century 21',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","View all 5 Locations","!Northland Real Estate Inc - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 344-2400',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-20',
    'Northland Real Estate Inc',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate"]',
    1,
    'https://svn.com/',
    NULL,
    '(541) 345-2361',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-21',
    'Tammy Sue Schuck - Hybrid Real Estate',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Referral & Information Service","Real Estate Investing","!John L Scott Real Estate - Real Estate Agents"]',
    1,
    'http://www.hybridrealestate.org/',
    32,
    '(503) 317-6604',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-22',
    'John L Scott Real Estate',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","!Tim Duncan Real Estate - Real Estate Agents"]',
    1,
    'http://johnlscott.com/',
    NULL,
    '(541) 687-1415',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-23',
    'Tim Duncan Real Estate',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'http://www.timduncanre.com/',
    NULL,
    '(541) 284-3741',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-24',
    'United Real Estate Properties',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Gary Raze - REMAX Integrity - Real Estate Agents"]',
    1,
    'http://www.findmyeugenehome.com/',
    NULL,
    '(541) 954-7838',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-25',
    'Gary Raze - REMAX Integrity',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Appraisers","!Paddock, Jamie - Real Estate Agents"]',
    1,
    'https://www.remax.com/realestateagentoffice/eugene-or-97401-garyraze-id11086022.html',
    NULL,
    '(541) 554-5825',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-26',
    'Paddock, Jamie',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate"]',
    1,
    NULL,
    NULL,
    '(541) 284-8038',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-27',
    'Angela Burrell, REALTOR | Triple Oaks Realty',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","Real Estate Buyer Brokers"]',
    1,
    'https://angelaburrellbroker.com/',
    9,
    '(541) 517-4038',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-28',
    'Kristina Carpenter, Real Estate Broker',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://www.coldwellbanker.com/Coldwell-Banker-Professional-Group-50671c/Kristina-Carpenter-7616019a',
    5,
    '(541) 505-6531',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-29',
    'A Worldly Goods Estate Sales Service, LLC',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    NULL,
    56,
    '(541) 686-6115',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-30',
    'Marzia Motlagh - Eugene Realtor - eXp Realty',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Core Campus Eugene - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 972-2481',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-31',
    'Core Campus Eugene',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    'http://huboncampus.com/eugene',
    10,
    '(541) 343-1128',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-32',
    'C W Walker & Associates, Inc',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Investing","Relocation Service","!Eugene Track Town Realtors - Real Estate Agents"]',
    1,
    'https://www.cwwalker.net/home.html',
    NULL,
    '(541) 484-4422',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-33',
    'Eugene Track Town Realtors',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Oregon Premier Real Estate - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 554-0324',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-34',
    'Oregon Premier Real Estate',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Allen North Properties - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 968-9658',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-35',
    'Allen North Properties',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Bullier & Bullier Of Eugene - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 359-0116',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-36',
    'Bullier & Bullier Of Eugene',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate","!Realtor''s Northwest - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 687-1434',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-37',
    'Realtor''s Northwest',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate","!Ineugene Real Estate - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 686-4290',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-38',
    'Ineugene Real Estate',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Jakabosky, Susan, AGT - Real Estate Agents"]',
    1,
    'http://ineugenere.com/',
    NULL,
    '(541) 505-9399',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-39',
    'Jakabosky, Susan, AGT',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Avery, Sara K, RLTR - Real Estate Agents"]',
    1,
    'http://hearthstonere.com/',
    NULL,
    '(541) 953-0285',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-40',
    'Avery, Sara K, RLTR',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Stellar Home Team - Real Estate Agents"]',
    1,
    'https://www.soldbuysara.com/',
    NULL,
    '(360) 513-2845',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-41',
    'Stellar Home Team',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Jennings Group Inc - Real Estate Agents"]',
    1,
    'https://www.stellarhomesonline.com/',
    NULL,
    '(541) 780-0600',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-42',
    'Jennings Group Inc',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Management"]',
    1,
    NULL,
    48,
    '(541) 683-2273',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-43',
    'Heart & Home Real Estate - Eugene Realtors',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    'https://www.lanecountyhomes.net/',
    NULL,
    '(541) 253-4090',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-44',
    'Shannon Mason - Mason & Mason brokered by eXp Realty',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Rain Dance Real Estate - Real Estate Agents"]',
    1,
    'https://shannonmason.exprealty.com/',
    NULL,
    '(541) 404-5812',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-45',
    'Rain Dance Real Estate',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Eugene Alternative Realtors - Real Estate Agents"]',
    1,
    NULL,
    12,
    '(541) 521-3283',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-46',
    'Eugene Alternative Realtors',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Beam Properties - Real Estate Agents"]',
    1,
    'http://alternativerealtor.com/',
    NULL,
    '(541) 302-5999',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-47',
    'Beam Properties',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Windermere Real Estate - Real Estate Agents"]',
    1,
    'https://www.beamdevelopment.com/broadway-commerce-center',
    NULL,
    '(541) 344-1827',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-48',
    'Windermere Real Estate',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate","!Jim Welsh Broker - Real Estate Agents"]',
    1,
    'http://www.windermere.com/',
    NULL,
    '(541) 484-2022',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-49',
    'Jim Welsh Broker',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","!M & A Real Estate - Real Estate Agents"]',
    1,
    'http://windermerecnw.com/',
    NULL,
    '(541) 554-8043',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-50',
    'M & A Real Estate',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Northwest Forest Properties - Real Estate Agents"]',
    1,
    'http://manda-partners.com/portfolio/student-housing',
    NULL,
    '(310) 802-2090',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-51',
    'Northwest Forest Properties',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://www.preferrednorthwestpm.com/shortcodes/contact-forms',
    NULL,
    '(541) 505-3377',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-52',
    'Mario Ruiz - Realtor With Icon Real Estate Group',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Paradigm Properties - Real Estate Agents"]',
    1,
    'https://propertiesineugene.com/',
    NULL,
    '(541) 868-4307',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-53',
    'Paradigm Properties',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Golden Realty - Real Estate Agents"]',
    1,
    'http://www.paradigmpropertiesnw.com/',
    NULL,
    '(541) 484-7311',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-54',
    'Golden Realty',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Von Klein Properties - Real Estate Agents"]',
    1,
    'https://www.goldensold.com/',
    NULL,
    '(541) 343-8269',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-55',
    'Von Klein Properties',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Elms, Jade - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 345-3613',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-56',
    'Elms, Jade',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate","!Caudill John & Susan - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 284-4115',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-57',
    'Caudill John & Susan',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Jodie Smith Real Estate Co - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 284-4139',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-58',
    'Jodie Smith Real Estate Co',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Hybrid Real Estate - Real Estate Agents"]',
    1,
    'http://jodiesmithrealestate.com/',
    NULL,
    '(541) 505-7128',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-59',
    'Hybrid Real Estate',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(458) 205-8464',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Eugene RealEstate Agents-60',
    'Eugene''s Alternative Realtors',
    'Eugene',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(541) 302-5999',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-1',
    'Ehlers Construction Inc',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","Fire & Water Damage Restoration","!Home Insulation Co., Inc. - General Contractors"]',
    1,
    NULL,
    74,
    '(712) 423-4248',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-2',
    'Home Insulation Co., Inc.',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    'http://homecompanies.com/',
    77,
    '(458) 320-0152',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-3',
    'Cascadia Construction and Plumbing',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Plumbers","!Homes by Hutch LLC - General Contractors"]',
    1,
    'http://www.cascadia.co/',
    NULL,
    '(541) 585-2339',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-4',
    'Homes by Hutch LLC',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Home Improvements","!Bartreau Construction - General Contractors"]',
    1,
    'https://www.homesbyhutchllc.com/',
    NULL,
    '(650) 472-5152',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-5',
    'Bartreau Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Bathroom Remodeling","Deck Builders","!Davis Home Dynamics - General Contractors"]',
    1,
    'https://www.bartreauconstruction.net/',
    8,
    '(541) 735-0341',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-6',
    'Davis Home Dynamics',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Kitchen Planning & Remodeling Service","!Fulmer Construction LLC - General Contractors"]',
    1,
    'https://www.davishomedynamics.com/',
    NULL,
    '(503) 382-8716',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-7',
    'Fulmer Construction LLC',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Bathroom Remodeling","Kitchen Planning & Remodeling Service"]',
    1,
    NULL,
    NULL,
    '(541) 221-9667',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-8',
    'Jordan & Jordan Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Garages-Building & Repairing","Deck Builders","!Yeti Contracting - General Contractors"]',
    1,
    'https://lanecountycustomhomes.com/',
    NULL,
    '(458) 320-0395',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-9',
    'Yeti Contracting',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","!Foshay Contracting - General Contractors"]',
    1,
    NULL,
    NULL,
    '(360) 609-7852',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-10',
    'Foshay Contracting',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Deck Builders","Rails, Railings & Accessories Stairway","!Lane Marble Interiors Inc - General Contractors"]',
    1,
    'https://foshaycontracting.com/',
    NULL,
    '(458) 320-0454',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  );