INSERT INTO businesses (
      id, name, city, state, industry, services, verified, website, 
      yearsInBusiness, phone, address, email, rating, reviewCount, 
      licenseNumber, bbbRating, emergencyService
    ) VALUES (
    'grantspass-Real-Estate-Agents-31',
    'Barnett, Chris, RLTR',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Realtor Mitchell Fields - Real Estate Agents"]',
    1,
    'https://www.realtyexecutives.com/agent/chris-barnett',
    NULL,
    '(541) 660-5195',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-32',
    'Realtor Mitchell Fields',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Grants Pass Real Estate - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 218-0095',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-33',
    'Grants Pass Real Estate',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Exit Realty Towne Centre - Real Estate Agents"]',
    1,
    'https://www.grantspassrealestate.us/',
    NULL,
    '(541) 660-5195',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-34',
    'Exit Realty Towne Centre',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Windermere Real Estate - Real Estate Agents"]',
    1,
    'http://exitrtc.com/',
    NULL,
    '(541) 474-1566',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-35',
    'Windermere Real Estate',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Management","!Harbeck Village - Real Estate Agents"]',
    1,
    'http://windermeregrantspass.com/',
    NULL,
    '(541) 476-2000',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-36',
    'Harbeck Village',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Real Estate Design 2Sell - Real Estate Agents"]',
    1,
    'https://www.jhcdc.net/board-information',
    NULL,
    '(541) 955-9251',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-37',
    'Real Estate Design 2Sell',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Oregon Real Estate Center - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 955-2957',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-38',
    'Oregon Real Estate Center',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Rw Reality - Real Estate Agents"]',
    1,
    'http://www.oregontravels.com/grantspass/realestate01_grantspass.html',
    NULL,
    '(541) 474-1904',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-39',
    'Rw Reality',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Management","!CNC Properties - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 479-0542',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-40',
    'CNC Properties',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Premier Realty - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 479-6708',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-41',
    'Premier Realty',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Management"]',
    1,
    'http://www.rogueweb.com/premier',
    NULL,
    '(541) 476-1879',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-42',
    'Loraditch Ranch Home Real Estate',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Darrell Allison Realtors - Real Estate Agents"]',
    1,
    'http://loraditchland.com/',
    NULL,
    '(541) 476-2860',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-43',
    'Darrell Allison Realtors',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Gary Martin Realty - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 474-5555',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-44',
    'Gary Martin Realty',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(541) 479-0411',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-45',
    'United Country Real Est-Rogue',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","!The Bifano Home Team - Real Estate Agents"]',
    1,
    'https://www.rogueauctioneers.com/',
    NULL,
    '(541) 471-0916',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-46',
    'The Bifano Home Team',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Oregon Real Estate Center - Real Estate Agents"]',
    1,
    'https://www.hedgestone.com/brokerage/the-bifano-home-team-grants-pass-real-estate-58324',
    NULL,
    '(541) 229-3966',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-47',
    'Oregon Real Estate Center',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Home Sweet Bookings - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 474-1904',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-48',
    'Home Sweet Bookings',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Josephine County Cemetery - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 500-0255',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-49',
    'Josephine County Cemetery',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://www.facebook.com/JosephineCountyFosterCareAndAdoption',
    NULL,
    '(541) 474-5285',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-50',
    'First Choice Real Estate Service',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Town & Valley Real Estate - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 474-2958',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-51',
    'Town & Valley Real Estate',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(541) 476-9991',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-52',
    'BEYOND Real Estate Brokers - Vicki Carpenter',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://www.lovesouthernoregon.com/',
    6,
    '(541) 218-1300',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-53',
    'Redwood Real Estate brokered by eXp Realty, LLC',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Misfit Property Solutions - Real Estate Agents"]',
    1,
    'https://www.redwoodrealestate.net/',
    17,
    '(541) 218-5778',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-54',
    'Misfit Property Solutions',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(541) 471-7119',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-55',
    'David West Real Estate at John L Scott Grants Pass',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Keller Williams Realty - Real Estate Agents"]',
    1,
    'http://www.grantspassrealestate.com/',
    15,
    '(541) 659-9681',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-56',
    'Keller Williams Realty',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Consultants","!Venuti Group Inc - Real Estate Agents"]',
    1,
    'http://www.kw.com/',
    42,
    '(541) 476-4160',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-57',
    'Venuti Group Inc',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","Commercial Real Estate"]',
    1,
    'http://www.grantspasshomes.com/',
    22,
    '(541) 476-9616',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-58',
    'Diana Tupper-First Choice R/E',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Vacation Homes Rentals & Sales"]',
    1,
    NULL,
    NULL,
    '(541) 474-2958',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-59',
    'John L Scott Real Estate',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","Real Estate Buyer Brokers"]',
    1,
    'http://www.johnlscott.com/',
    18,
    '(541) 476-1299',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-60',
    'Kendon Leet Real Estate',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","Real Estate Buyer Brokers"]',
    1,
    'https://www.kendonleet.com/',
    NULL,
    '(541) 659-7826',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-61',
    'John L Scott Real Estate',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","Real Estate Buyer Brokers"]',
    1,
    'http://www.johnlscott.com/',
    18,
    '(541) 476-1299',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-62',
    'Kendon Leet Real Estate',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","Real Estate Buyer Brokers"]',
    1,
    'https://www.kendonleet.com/',
    NULL,
    '(541) 659-7826',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-63',
    'Ian Conger with Remax Ideal Brokers',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Developers","Real Estate Investing"]',
    1,
    NULL,
    NULL,
    '(541) 956-5503',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-64',
    'Southern Oregon Real Estate',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","Real Estate Buyer Brokers","!Coldwell Banker - Real Estate Buyer Brokers"]',
    1,
    'https://www.rogueweb.com/soreal',
    NULL,
    '(541) 476-8228',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-65',
    'Coldwell Banker',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate","!Tamashiro Kurt PC - Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(541) 951-6550',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-66',
    'Tamashiro Kurt PC',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Platinum Financial - Real Estate Loans"]',
    1,
    'http://www.buysouthernoregon.com/',
    NULL,
    '(541) 471-4333',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-67',
    'Platinum Financial',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Loans","Real Estate Buyer Brokers"]',
    1,
    'http://www.cbs.state.or.us/dfcs',
    NULL,
    '(541) 472-1222',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-68',
    'Windermere Grants Pass',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Coldwell Banker - Real Estate Buyer Brokers"]',
    1,
    'http://windermeregrantspass.com/',
    NULL,
    '(541) 479-8686',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-69',
    'Coldwell Banker',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate","!Gtf Properties - Real Estate Management"]',
    1,
    'https://www.coldwellbanker.com/coldwell-banker-cutting-edge-50991c',
    NULL,
    '(541) 226-2070',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-70',
    'Gtf Properties',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(541) 476-8225',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-71',
    'Pat Bange, SRA Real Estate Appraiser',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Estate Appraisal & Sales","Real Estate Appraisers"]',
    1,
    NULL,
    47,
    '(541) 476-1556',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-72',
    'Diversity Home Lending a branch of Mountain West Financial, Inc',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Loans","Mortgages","!Winter Ridge Properties - Real Estate Management"]',
    1,
    'http://www.diversityhl.com/',
    NULL,
    '(541) 479-3377',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-73',
    'Winter Ridge Properties',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(541) 226-9938',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-74',
    '541 Property Management LLC',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","!Ccs Properties - Real Estate Management"]',
    1,
    'http://541propertymgmt.com/',
    NULL,
    '(541) 476-1026',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-75',
    'Ccs Properties',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","Real Estate Buyer Brokers","!Burton, Justin, RLTR - Real Estate Consultants"]',
    1,
    NULL,
    NULL,
    '(541) 226-9207',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-76',
    'Burton, Justin, RLTR',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","Real Estate Buyer Brokers"]',
    1,
    'https://oregonexp.com/team',
    NULL,
    '(541) 660-0121',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-77',
    'Liz Buys Houses',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","Video","!Sell My House Fast - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(833) 274-9691',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-78',
    'Sell My House Fast',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","!House Buyer Network - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(833) 275-0061',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-79',
    'House Buyer Network',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","!Renie Weber Realty - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(833) 274-7871',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-80',
    'Renie Weber Realty',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Bradley Realty - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(888) 757-4936',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-81',
    'Bradley Realty',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Bayless Riverview Realty - Real Estate Agents"]',
    1,
    'http://www.bradleyrealty.biz/',
    21,
    '(541) 582-0111',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-82',
    'Bayless Riverview Realty',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Blackbird Real Estate - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 582-1601',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-83',
    'Blackbird Real Estate',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Rogue River Realty - Real Estate Agents"]',
    1,
    'http://www.blackbirdrealestate.com/',
    NULL,
    '(541) 955-8180',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-84',
    'Rogue River Realty',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Windermere Real Estate - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 582-0559',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-85',
    'Windermere Real Estate',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Cornerstone Properties - Real Estate Management"]',
    1,
    'http://southernoregonhomesforsale.com/',
    NULL,
    '(541) 582-2000',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-86',
    'Cornerstone Properties',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","Real Estate Buyer Brokers","!Covered Bridge Realty - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 476-9883',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-87',
    'Covered Bridge Realty',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!1 Stop Real Estate - Real Estate Agents"]',
    1,
    'https://coveredbridgerealty.com/',
    NULL,
    '(541) 582-1670',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-88',
    '1 Stop Real Estate',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!1 Stop Real Estate - Real Estate Agents"]',
    1,
    'http://www.1stoprealestatellc.com/',
    NULL,
    '(541) 855-7867',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-89',
    '1 Stop Real Estate',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Oregon-Land.com - Real Estate Agents"]',
    1,
    'http://1stoprealestatellc.com/',
    NULL,
    '(541) 855-7867',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-90',
    'Oregon-Land.com',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    'http://www.oregon-land.com/',
    NULL,
    '(541) 846-0646',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Electricians-1',
    'Sims Electric, Inc',
    'Roseburg',
    'OR',
    'electricians',
    '["Electricians","Electric Contractors-Commercial & Industrial","Lighting Contractors","!Arrowood Insurance Agency - Electricians"]',
    1,
    'http://simselectric.com/',
    79,
    '(541) 236-4384',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Electricians-2',
    'Arrowood Insurance Agency',
    'Roseburg',
    'OR',
    'electricians',
    '["Electricians","Snow Removal Service","Landscape Designers & Consultants","!Hytech Auto Repair - Electricians"]',
    1,
    'http://arrowoodinsurance.com/',
    NULL,
    '(541) 671-5949',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Electricians-3',
    'Hytech Auto Repair',
    'Roseburg',
    'OR',
    'electricians',
    '["Electricians","Electric Companies","Retirement Communities","!Bean Electric LLC......... - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 839-9111',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Electricians-4',
    'Bean Electric LLC.........',
    'Roseburg',
    'OR',
    'electricians',
    '["Electricians","Solar Energy Equipment & Systems-Dealers","!Single Tree Electric & Consulting - Electricians"]',
    1,
    'https://www.beanelectric.com/',
    29,
    '(541) 672-6550',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Electricians-5',
    'Single Tree Electric & Consulting',
    'Roseburg',
    'OR',
    'electricians',
    '["Electricians","!Electrical Services & Cont Inc - Electricians"]',
    1,
    'http://giftdealsonline.com/',
    NULL,
    '(541) 672-1436',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Electricians-6',
    'Electrical Services & Cont Inc',
    'Roseburg',
    'OR',
    'electricians',
    '["Electricians","!Mayberry Electric Inc - Electricians"]',
    1,
    NULL,
    31,
    '(541) 679-0873',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Electricians-7',
    'Mayberry Electric Inc',
    'Roseburg',
    'OR',
    'electricians',
    '["Electricians","Switches-Electric","Lighting Fixtures","!HPS Electrical - Electricians"]',
    1,
    'https://mayberryelectricdouglascounty.weebly.com/',
    NULL,
    '(541) 817-2141',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Electricians-8',
    'HPS Electrical',
    'Roseburg',
    'OR',
    'electricians',
    '["Electricians","!North River Electric Inc - Electricians"]',
    1,
    'https://www.hpselectric.com/',
    NULL,
    '(541) 673-3162',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Electricians-9',
    'North River Electric Inc',
    'Roseburg',
    'OR',
    'electricians',
    '["Electricians","Lighting Consultants & Designers","Generators-Electric-Service & Repair","!Cascade Electric - Electricians"]',
    1,
    'https://www.northriverelectricinc.com/',
    NULL,
    '(541) 673-0800',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Electricians-10',
    'Cascade Electric',
    'Roseburg',
    'OR',
    'electricians',
    '["Electricians","Lighting Consultants & Designers","Lighting Contractors","!Red''s Electrical Service Inc - Electricians"]',
    1,
    'https://www.cascadeelectricinc.net/',
    35,
    '(541) 673-5957',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Electricians-11',
    'Red''s Electrical Service Inc',
    'Roseburg',
    'OR',
    'electricians',
    '["Electricians"]',
    1,
    NULL,
    NULL,
    '(458) 802-0856',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Electricians-12',
    'Electrical Professional Services Inc',
    'Roseburg',
    'OR',
    'electricians',
    '["Electricians","!Msc Companies - Electricians"]',
    1,
    'http://www.electricalproservices.com/',
    NULL,
    '(541) 637-5050',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Electricians-13',
    'Msc Companies',
    'Roseburg',
    'OR',
    'electricians',
    '["Electricians","!Dans Electric - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 677-3645',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Electricians-14',
    'Dans Electric',
    'Roseburg',
    'OR',
    'electricians',
    '["Electricians","!Dan''s Electric - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 672-8404',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Electricians-15',
    'Dan''s Electric',
    'Roseburg',
    'OR',
    'electricians',
    '["Electricians","!Jerry''s Electric Inc - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 672-8404',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Electricians-16',
    'Jerry''s Electric Inc',
    'Roseburg',
    'OR',
    'electricians',
    '["Electricians","!Vision Electric - Electricians"]',
    1,
    NULL,
    33,
    '(541) 672-6844',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Electricians-17',
    'Vision Electric',
    'Roseburg',
    'OR',
    'electricians',
    '["Electricians","!Cascade Electric-Home Office - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 673-4204',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Electricians-18',
    'Cascade Electric-Home Office',
    'Roseburg',
    'OR',
    'electricians',
    '["Electricians","!Keller Electrical Construction - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 440-9901',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Electricians-19',
    'Keller Electrical Construction',
    'Roseburg',
    'OR',
    'electricians',
    '["Electricians","!Prowire Electric Co - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 784-1533',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Electricians-20',
    'Prowire Electric Co',
    'Roseburg',
    'OR',
    'electricians',
    '["Electricians","!Prowire Electric Co. - Electricians"]',
    1,
    'http://prowire-electric.com/',
    NULL,
    '(541) 496-0320',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Electricians-21',
    'Prowire Electric Co.',
    'Roseburg',
    'OR',
    'electricians',
    '["Electricians","!Haynes Electric - Electricians"]',
    1,
    'http://www.prowire-electric.com/',
    NULL,
    '(541) 496-0320',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Electricians-22',
    'Haynes Electric',
    'Roseburg',
    'OR',
    'electricians',
    '["Electricians","!Vision Electric - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 679-9373',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Electricians-23',
    'Vision Electric',
    'Roseburg',
    'OR',
    'electricians',
    '["Electricians","!Eps - Electricians"]',
    1,
    'http://www.visionelectric.com/',
    NULL,
    '(541) 673-4204',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Electricians-24',
    'Eps',
    'Roseburg',
    'OR',
    'electricians',
    '["Electricians"]',
    1,
    'https://www.electricalproservices.com/',
    NULL,
    '(541) 530-3586',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Electricians-25',
    'North River Electric Inc',
    'Roseburg',
    'OR',
    'electricians',
    '["Electricians","Electric Contractors-Commercial & Industrial","Building Contractors"]',
    1,
    'http://www.northriverelectricinc.com/',
    47,
    '(541) 673-0800',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Electricians-26',
    'Kunert Electric Inc',
    'Roseburg',
    'OR',
    'electricians',
    '["Electricians","Solar Energy Equipment & Systems-Dealers","Industrial Equipment & Supplies","!Dan''s Electric - Electricians"]',
    1,
    'http://www.kunert-1.com/',
    57,
    '(541) 672-3333',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Electricians-27',
    'Dan''s Electric',
    'Roseburg',
    'OR',
    'electricians',
    '["Electricians","!Central Electrical Services - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 672-8404',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Electricians-28',
    'Central Electrical Services',
    'Roseburg',
    'OR',
    'electricians',
    '["Electricians","Electrical Power Systems-Maintenance","!Charles Swift Electric - Electricians"]',
    1,
    NULL,
    50,
    '(541) 459-7994',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Electricians-29',
    'Charles Swift Electric',
    'Roseburg',
    'OR',
    'electricians',
    '["Electricians","!Phillip T Ray Electric - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 459-5541',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Electricians-30',
    'Phillip T Ray Electric',
    'Roseburg',
    'OR',
    'electricians',
    '["Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 459-5851',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-GeneralContractors-1',
    'K & R Construction and Framing Inc.',
    'Roseburg',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Deck Builders","!B T Construction Inc - General Contractors"]',
    1,
    'https://www.kandrconstructioninc.com/',
    NULL,
    '(541) 530-1283',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-GeneralContractors-2',
    'B T Construction Inc',
    'Roseburg',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","Home Improvements","!Stumbo; Construction - General Contractors"]',
    1,
    'http://btconst.com/',
    45,
    '(844) 331-3562',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-GeneralContractors-3',
    'Stumbo; Construction',
    'Roseburg',
    'OR',
    'general-contractors',
    '["General Contractors","!Hytech Auto Repair - General Contractors"]',
    1,
    NULL,
    2,
    '(844) 570-4736',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-GeneralContractors-4',
    'Hytech Auto Repair',
    'Roseburg',
    'OR',
    'general-contractors',
    '["General Contractors","Retirement Communities","Windshield Repair"]',
    1,
    NULL,
    NULL,
    '(541) 839-9111',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-GeneralContractors-5',
    'Shelby & Miguelena Construction Co',
    'Roseburg',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Kitchen Planning & Remodeling Service","!T3 Construction - General Contractors"]',
    1,
    NULL,
    56,
    '(541) 673-1957',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-GeneralContractors-6',
    'T3 Construction',
    'Roseburg',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers"]',
    1,
    'http://manta.com/c/mt7r793/t3-construction-llc',
    NULL,
    '(541) 580-1055',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-GeneralContractors-7',
    'Harwood General Contractors Inc',
    'Roseburg',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Jack Mathis Construction - General Contractors"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 643-8419',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-GeneralContractors-8',
    'Jack Mathis Construction',
    'Roseburg',
    'OR',
    'general-contractors',
    '["General Contractors","Building Materials","Steel Erectors","!Level Line Construction - General Contractors"]',
    1,
    NULL,
    71,
    '(541) 672-1635',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-GeneralContractors-9',
    'Level Line Construction',
    'Roseburg',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Handyman Services"]',
    1,
    'http://www.levellineconstruction.biz/',
    15,
    '(541) 733-6996',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-GeneralContractors-10',
    'Keith A Cortes Construction',
    'Roseburg',
    'OR',
    'general-contractors',
    '["General Contractors","!Perine Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 464-0537',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  );