INSERT INTO businesses (
      id, name, city, state, industry, services, verified, website, 
      yearsInBusiness, phone, address, email, rating, reviewCount, 
      licenseNumber, bbbRating, emergencyService
    ) VALUES (
    'portland-Electricians-31',
    'Stoner Electric Group',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Lighting Fixtures","!Paige Colleen Yeakle, RBT - Electricians"]',
    1,
    NULL,
    55,
    '(503) 462-6500',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-32',
    'Paige Colleen Yeakle, RBT',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Electric Companies","!Lear Electric Co - Electric Companies"]',
    1,
    'http://portlandgeneral.com/',
    NULL,
    '(855) 832-6727',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-33',
    'Lear Electric Co',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Electric Companies"]',
    1,
    'https://www.learelectric.com/services/reviews',
    NULL,
    '(503) 255-0733',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-34',
    'Crescent Electric Supply Company',
    'Portland',
    'OR',
    'electricians',
    '["Electric Companies","Electrical Discharge Machines & Supplies","!Squires Electric, Inc. - Electricians"]',
    1,
    'http://www.cesco.com/',
    77,
    '(503) 222-4000',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-35',
    'Squires Electric, Inc.',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Electric Contractors-Commercial & Industrial","!Smiley Electric Inc. - Electricians"]',
    1,
    'https://www.squireselectric.com/',
    30,
    '(503) 252-1609',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-36',
    'Smiley Electric Inc.',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Automobile Electric Service","Electrical Engineers","!Portland Electric Boat Company - Electricians"]',
    1,
    'http://smileyelectric.net/',
    NULL,
    '(503) 484-7556',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-37',
    'Portland Electric Boat Company',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","!Dynalectric Oregon - Electricians"]',
    1,
    'http://www.portlandelectricboatco.com/',
    NULL,
    '(503) 673-6172',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-38',
    'Dynalectric Oregon',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","!Edi Portland - Electricians"]',
    1,
    'http://dyna-portland.com/',
    NULL,
    '(503) 226-6771',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-39',
    'Edi Portland',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Electric Equipment & Supplies","!Bell Mountain Electric - Electricians"]',
    1,
    'https://www.bascoappliances.com/',
    NULL,
    '(503) 226-4044',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-40',
    'Bell Mountain Electric',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Electric Contractors-Commercial & Industrial","!Dickinsons Electric Comp - Electricians"]',
    1,
    'http://www.bellmtn.com/',
    19,
    '(503) 254-1154',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-41',
    'Dickinsons Electric Comp',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","!Falcon Electric - Electricians"]',
    1,
    'http://dickinsonselectric.com/',
    67,
    '(503) 515-2922',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-42',
    'Falcon Electric',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Lighting Consultants & Designers","Lighting Contractors"]',
    1,
    'https://callfalcon.com/',
    12,
    '(503) 208-4709',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-43',
    'US Electrician Home Service Portland',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Wire & Cable-Electric","!Capitol Electric Company - Electricians"]',
    1,
    'https://ushomeservices.us/electrician',
    NULL,
    '(503) 694-3691',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-44',
    'Capitol Electric Company',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Computer Cable & Wire Installation","Lighting Consultants & Designers","!Prairie Electric - Electricians"]',
    1,
    'http://www.capitolelectricco.com/',
    NULL,
    '(503) 255-9488',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-45',
    'Prairie Electric',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Electrical Engineers","Electric Contractors-Commercial & Industrial","!Cache Valley Electric - Electricians"]',
    1,
    'http://www.prairielectric.com/',
    9,
    '(503) 286-9209',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-46',
    'Cache Valley Electric',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","!Christenson Electric, Inc - Electricians"]',
    1,
    'http://cve.com/',
    NULL,
    '(503) 431-6600',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-47',
    'Christenson Electric, Inc',
    'Portland',
    'OR',
    'electricians',
    '["Electricians"]',
    1,
    'https://www.christenson.com/',
    NULL,
    '(503) 419-3300',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-48',
    'Portland General Electric Company Portland General Electric Headquarters',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Electric Companies"]',
    1,
    NULL,
    NULL,
    '(503) 464-7441',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-49',
    'Northwest Requirements Utilitie',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Electric Companies","!Pngc Power - Electric Companies"]',
    1,
    'https://www.nru-nw.com/about/officers-executive-committee-directors',
    NULL,
    '(503) 233-5823',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-50',
    'Pngc Power',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Electric Companies"]',
    1,
    'http://pngcpower.com/',
    55,
    '(503) 288-1234',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-51',
    'Portland General Electric Company',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Electric Companies"]',
    1,
    'https://portlandgeneral.com/',
    NULL,
    '(503) 228-6322',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-52',
    'Portland General Electric Co',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Electric Companies"]',
    1,
    NULL,
    NULL,
    '(503) 464-7777',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-53',
    'Gravbar Electric Company Inc',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Electric Companies","Utility Companies","!Pi Electric - Electricians"]',
    1,
    'http://www.graybar.com/',
    NULL,
    '(503) 249-1345',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-54',
    'Pi Electric',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Electric Companies","!Ace Electric & Construction - Electric Companies"]',
    1,
    'http://www.cbs.state.or.us/bcd',
    NULL,
    '(503) 453-9786',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-55',
    'Ace Electric & Construction',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Electric Companies","!Vitro Electric - Electricians"]',
    1,
    NULL,
    NULL,
    '(503) 244-0078',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-56',
    'Vitro Electric',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Electric Companies","!Portland General Electric - Electricians"]',
    1,
    NULL,
    NULL,
    '(503) 208-3625',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-57',
    'Portland General Electric',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Electric Companies","!Wright 1 Electric - Electricians"]',
    1,
    'http://portlandgeneral.com/',
    NULL,
    '(503) 718-6300',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-58',
    'Wright 1 Electric',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Electric Companies","!Miller Electric Mfg Co - Electric Companies"]',
    1,
    'http://www.wright1electric.com/',
    NULL,
    '(503) 760-8522',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-59',
    'Miller Electric Mfg Co',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Electric Companies","!Portland Energy Office - Electric Companies"]',
    1,
    'http://millerwelds.com/',
    NULL,
    '(503) 256-7344',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-60',
    'Portland Energy Office',
    'Portland',
    'OR',
    'electricians',
    '["Electric Companies","City, Village & Township Government"]',
    1,
    NULL,
    NULL,
    '(503) 823-7222',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-1',
    'Aaron''s Custom Metal Fab Inc',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Mining Companies","Industrial Equipment & Supplies-Wholesale","!Hoffman Corporation - General Contractors"]',
    1,
    'http://aaronscustommetalfab.com/',
    25,
    '(503) 427-1141',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-2',
    'Hoffman Corporation',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Construction Consultants","Building Contractors"]',
    1,
    'https://www.hoffmancorp.com/',
    NULL,
    '(971) 314-8037',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-3',
    'Arrow Roofing & Sheet Metal Inc',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","Building Contractors-Commercial & Industrial","Services","!DNR Associates Inc - General Contractors"]',
    1,
    'http://www.arrow-roofing.com/',
    71,
    '(503) 460-2767',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-4',
    'DNR Associates Inc',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Carpenters","Mobile Home Repair & Service","!Gregg Roofing, Inc. - General Contractors"]',
    1,
    'http://www.dnrassociatesoregon.com/',
    27,
    '(503) 912-8729',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-5',
    'Gregg Roofing, Inc.',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Home Improvements","Roofing Contractors","Services","!Gregg Roofing LLC - Home Improvements"]',
    1,
    'http://www.greggroofing.com/',
    7,
    '(360) 859-0733',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-6',
    'Gregg Roofing LLC',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Roofing Contractors","Home Improvements","!FX Repair & Remodeling - Building Contractors"]',
    1,
    'http://www.greggroofing.com/',
    81,
    '(360) 844-8238',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-7',
    'FX Repair & Remodeling',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Home Repair & Maintenance","Building Contractors"]',
    1,
    'http://www.fxrepair.com/',
    36,
    '(503) 542-4442',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-8',
    'HOMEMASTERS Portland SW',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","Cleaning Contractors","Services","!Roof Master - Building Contractors"]',
    1,
    NULL,
    35,
    '(503) 639-7700',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-9',
    'Roof Master',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Parking Stations & Garages-Construction","Paving Contractors"]',
    1,
    NULL,
    NULL,
    '(206) 639-1137',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-10',
    'NW Square Deal Construction',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Home Improvements","Building Contractors"]',
    1,
    NULL,
    10,
    '(503) 932-1010',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-11',
    'Improvement Remodeling LLC',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Home Improvements","Home Repair & Maintenance","!Pet Doors and More - Home Repair & Maintenance"]',
    1,
    'http://www.improvementremodelingllc.com/',
    28,
    '(503) 515-3171',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-12',
    'Pet Doors and More',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Home Repair & Maintenance","Door & Window Screens","!Sanborn Construction - General Contractors"]',
    1,
    'http://www.doorrenewalandmore.com/',
    13,
    '(503) 209-4185',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-13',
    'Sanborn Construction',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Home Improvements","!O''Brien Constructors - General Contractors"]',
    1,
    'http://mjhcpdx.com/',
    NULL,
    '(503) 232-7024',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-14',
    'O''Brien Constructors',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors","!Joseph Hughes Construction - General Contractors"]',
    1,
    NULL,
    23,
    '(503) 241-2875',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-15',
    'Joseph Hughes Construction',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","!Oak Street Building - General Contractors"]',
    1,
    'http://www.jhc-companies.com/',
    44,
    '(503) 624-7100',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-16',
    'Oak Street Building',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","Altering & Remodeling Contractors","!Home One - General Contractors"]',
    1,
    'http://theoakstreetbldg.com/',
    19,
    '(503) 235-5779',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-17',
    'Home One',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","!Mac Arthur Booth Const - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 477-4356',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-18',
    'Mac Arthur Booth Const',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Plumbers","!Hess Todd Building Co - General Contractors"]',
    1,
    'https://mac-bo.com/',
    NULL,
    '(503) 282-1841',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-19',
    'Hess Todd Building Co',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Home Improvements","!A C Schommer & Sons, Inc - General Contractors"]',
    1,
    'http://toddhessbldg.com/',
    NULL,
    '(503) 220-5953',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-20',
    'A C Schommer & Sons, Inc',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","Home Builders","!Interlaken Inc - General Contractors"]',
    1,
    'http://www.schommer-sons.com/',
    NULL,
    '(503) 287-4646',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-21',
    'Interlaken Inc',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","!R & H Construction Co - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 674-7460',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-22',
    'R & H Construction Co',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors-Commercial & Industrial","!Lcg Pence - General Contractors"]',
    1,
    'http://www.rhconst.com/',
    NULL,
    '(503) 228-7177',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-23',
    'Lcg Pence',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors-Commercial & Industrial","!Reimers & Jolivette Inc - General Contractors"]',
    1,
    'http://pencekelly.com/',
    NULL,
    '(503) 252-3802',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-24',
    'Reimers & Jolivette Inc',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Home Improvements"]',
    1,
    'http://www.reimersandjolivette.com/',
    103,
    '(503) 228-7691',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-25',
    'Slater Construction Inc Contrs',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Amethyst Development LLC - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 231-7740',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-26',
    'Amethyst Development LLC',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","!B & G Builders - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 841-5925',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-27',
    'B & G Builders',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!WBS Construction Inc - General Contractors"]',
    1,
    'http://www.bngbuilders.com/',
    NULL,
    '(503) 232-6004',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-28',
    'WBS Construction Inc',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Home Improvements","!Gray Craft - General Contractors"]',
    1,
    'https://www.wbsconstructioninc.com/contact',
    NULL,
    '(503) 452-9822',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-29',
    'Gray Craft',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders"]',
    1,
    NULL,
    NULL,
    '(503) 772-1672',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-30',
    'Tunya Construction & Landscaping Maintenance',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","!Stride Construction - General Contractors"]',
    1,
    NULL,
    19,
    '(503) 309-6774',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-31',
    'Stride Construction',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Building Contractors","!Mayer Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 771-9606',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-32',
    'Mayer Construction',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors-Commercial & Industrial","!D & L Quality Construction - General Contractors"]',
    1,
    'http://h-aconstruction.com/',
    NULL,
    '(503) 620-3545',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-33',
    'D & L Quality Construction',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers"]',
    1,
    NULL,
    NULL,
    '(503) 593-7150',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-34',
    'Catalyst Construction & Remodeling',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    'http://catalystconstructionpdx.com/',
    16,
    '(503) 914-9146',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-35',
    'Beisa''s Legacy Construction, LLC',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Roofing Contractors","Siding Contractors","!Kaya General Contractors - General Contractors"]',
    1,
    'http://www.beisaslegacy.com/',
    NULL,
    '(503) 676-6702',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-36',
    'Kaya General Contractors',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Garages-Building & Repairing","Building Construction Consultants","!Keystone Industries Inc - General Contractors"]',
    1,
    'http://www.kayaconstruction.com/',
    25,
    '(503) 283-8161',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-37',
    'Keystone Industries Inc',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Handyman Services","Building Construction Consultants","!Rejuvenation Construction - General Contractors"]',
    1,
    'http://keystoneindustriesinc.pro/',
    NULL,
    '(971) 806-9000',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-38',
    'Rejuvenation Construction',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Seven, Sarah - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 342-8609',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-39',
    'Seven, Sarah',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","!Fortis Construction Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 281-0850',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-40',
    'Fortis Construction Inc',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!Western Oregon Builders - General Contractors"]',
    1,
    'http://fortisconstruct.com/',
    NULL,
    '(503) 459-4477',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-41',
    'Western Oregon Builders',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers"]',
    1,
    'http://westernoregonbuilders.com/',
    NULL,
    '(503) 382-9621',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-42',
    'Multnomah Kitchen remodeling',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","!Precision Construction Co - General Contractors"]',
    1,
    NULL,
    21,
    '(503) 676-6338',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-43',
    'Precision Construction Co',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 253-4827',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-44',
    'North Portland Constructors',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","!Kaplan_Stein Interiors - General Contractors"]',
    1,
    'http://north-portland-constructors.site123.me/',
    20,
    '(503) 217-2761',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-45',
    'Kaplan_Stein Interiors',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","!Colas Construction - General Contractors"]',
    1,
    NULL,
    19,
    '(503) 757-0612',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-46',
    'Colas Construction',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Buyer Brokers","Real Estate Developers","!PDX Brothers Roof Cleaning - General Contractors"]',
    1,
    'http://www.colasconstruction.com/home',
    NULL,
    '(503) 203-1559',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-47',
    'PDX Brothers Roof Cleaning',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","!The Grout Company - General Contractors"]',
    1,
    'https://www.pdxbrothers.com/',
    NULL,
    '(503) 381-0827',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-48',
    'The Grout Company',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Garages-Building & Repairing","Altering & Remodeling Contractors"]',
    1,
    'http://portlandcloset.com/',
    47,
    '(503) 222-5654',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-49',
    'Portland Construction and Design',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","!Robert Evans Company - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 863-1866',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-50',
    'Robert Evans Company',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Summit Construction - General Contractors"]',
    1,
    'http://www.robertevansco.com/',
    NULL,
    '(503) 648-7805',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-51',
    'Summit Construction',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Home Improvements","!Albina Construction - General Contractors"]',
    1,
    'http://sumconst.com/contact-us.html',
    NULL,
    '(503) 223-9703',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-52',
    'Albina Construction',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Real Estate Developers","!RRS Construction Inc - General Contractors"]',
    1,
    'http://www.albinaconstruction.com/contact.html',
    NULL,
    '(503) 493-3533',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-53',
    'RRS Construction Inc',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors-Commercial & Industrial","!Walsh Construction Co - General Contractors"]',
    1,
    'https://www.rhconst.com/',
    NULL,
    '(503) 228-7177',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-54',
    'Walsh Construction Co',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors-Commercial & Industrial","!Keep It Together - General Contractors"]',
    1,
    'http://hoffmancorp.com/',
    NULL,
    '(503) 222-4375',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-55',
    'Keep It Together',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Bob Merrit Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 860-7641',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-56',
    'Bob Merrit Construction',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!SFW Construction LLC - General Contractors"]',
    1,
    NULL,
    NULL,
    '(971) 570-6836',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-57',
    'SFW Construction LLC',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Kitchen Planning & Remodeling Service","!SQFT Studios - General Contractors"]',
    1,
    'http://www.sfwconstruction.com/',
    20,
    '(503) 885-0237',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-58',
    'SQFT Studios',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","!iBuildPdx Company - General Contractors"]',
    1,
    'https://www.sqftstudios.com/',
    NULL,
    '(503) 515-3834',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-59',
    'iBuildPdx Company',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Home Design & Planning","!Lindquist Homes - General Contractors"]',
    1,
    'https://www.ibuildpdx.com/',
    12,
    '(971) 333-2716',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-60',
    'Lindquist Homes',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Earthquake Tech - General Contractors"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(503) 227-8275',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-61',
    'Earthquake Tech',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors-Commercial & Industrial","!Faison Construction, Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 282-4424',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-62',
    'Faison Construction, Inc',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors"]',
    1,
    'https://www.faisonconstruction.com/',
    NULL,
    '(503) 493-0684',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-63',
    'Commercial General Contractor Portland Oregon',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","!Mega Pacific Co - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 912-2434',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-64',
    'Mega Pacific Co',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Building Construction Consultants","Building Contractors-Commercial & Industrial"]',
    1,
    'http://www.mega-pacific.com/',
    42,
    '(503) 238-3772',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-65',
    'Kibben Construction Service',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","Real Estate Developers"]',
    1,
    NULL,
    NULL,
    '(503) 221-8811',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-66',
    'Michael Gentry Construction',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Construction Management","!Wilken & Wilken Builders - General Contractors"]',
    1,
    'http://www.mgentryconstruction.com/',
    NULL,
    '(971) 230-4055',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-67',
    'Wilken & Wilken Builders',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Black Dreams Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 493-7338',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-68',
    'Black Dreams Construction',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Electricians"]',
    1,
    'https://www.blackdreamsconstruction.com/',
    NULL,
    '(503) 270-3558',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-69',
    'Changing Spaces Construction LLC',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Home Improvements","!Toby Rapp Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 512-0711',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-70',
    'Toby Rapp Construction',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","!GSI Builders, Inc. - General Contractors"]',
    1,
    'http://tobyrapp.com/contact.html',
    NULL,
    '(503) 793-5672',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  );