INSERT INTO businesses (
      id, name, city, state, industry, services, verified, website, 
      yearsInBusiness, phone, address, email, rating, reviewCount, 
      licenseNumber, bbbRating, emergencyService
    ) VALUES (
    'medford-Electricians-4',
    'Pacific Electrical Contractors',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","Electric Contractors-Commercial & Industrial","Data Communications Equipment & Systems","!Kaylor Electric - Electricians"]',
    1,
    'http://www.pacificelectrical.com/',
    65,
    '(541) 210-8358',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-5',
    'Kaylor Electric',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","Altering & Remodeling Contractors","Home Improvements","!Precision Electric - Electricians"]',
    1,
    'http://www.kaylorelectric.com/',
    60,
    '(541) 535-2600',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-6',
    'Precision Electric',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","Consumer Electronics","!Edge Electric Service & Repair - Electricians"]',
    1,
    'http://precisionelectric.info/',
    NULL,
    '(541) 773-6279',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-7',
    'Edge Electric Service & Repair',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","!Rogue Electric Service - Electricians"]',
    1,
    NULL,
    20,
    '(541) 210-5479',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-8',
    'Rogue Electric Service',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","!Aztec Electrical - Electricians"]',
    1,
    NULL,
    27,
    '(541) 842-4233',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-9',
    'Aztec Electrical',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","Electric Contractors-Commercial & Industrial","!Power-Man Electric - Electricians"]',
    1,
    'http://aztecelectrical.net/',
    12,
    '(541) 245-8560',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-10',
    'Power-Man Electric',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","!Willpower Electric - Electricians"]',
    1,
    'https://www.electricianmedfordor.com/',
    NULL,
    '(541) 951-1543',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-11',
    'Willpower Electric',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","Home Improvements","General Contractors"]',
    1,
    'http://willpowerelect.com/',
    NULL,
    '(541) 535-3965',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-12',
    'Northern Lights Electrical Contractor Inc.',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","Electrical Engineers","!K & E Electric - Electricians"]',
    1,
    'https://www.northernlightselectricoregon.com/',
    NULL,
    '(541) 326-8664',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-13',
    'K & E Electric',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","!Precision Electric Contractors - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 210-6137',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-14',
    'Precision Electric Contractors',
    'Medford',
    'OR',
    'electricians',
    '["Electricians"]',
    1,
    'http://precisionelectric.info/',
    NULL,
    '(541) 773-6279',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-15',
    'Siskiyou Plumbing & Electrical Services',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","Plumbers","!General Electric Company - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 842-4585',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-16',
    'General Electric Company',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","!Day Electric Inc - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 779-6565',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-17',
    'Day Electric Inc',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","!Rogue Electric Service - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 857-5970',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-18',
    'Rogue Electric Service',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","!Kaylor Electric - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 772-6388',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-19',
    'Kaylor Electric',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","!Winters Electric Inc - Electricians"]',
    1,
    'http://www.kaylorelectric.com/',
    60,
    '(541) 414-2025',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-20',
    'Winters Electric Inc',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","!Dave Heryford Electric - Electricians"]',
    1,
    'https://www.winterselectric.net/',
    NULL,
    '(541) 664-4505',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-21',
    'Dave Heryford Electric',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","!Read Electric Inc - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 292-0487',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-22',
    'Read Electric Inc',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","!Siskiyou Electric - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 773-2692',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-23',
    'Siskiyou Electric',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","!Eric''s Electric Service - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 951-1092',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-24',
    'Eric''s Electric Service',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","Altering & Remodeling Contractors","!MAGA Electric & Plumbing - Electricians"]',
    1,
    'http://www.ericselectricservice.com/',
    38,
    '(541) 858-2867',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-25',
    'MAGA Electric & Plumbing',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","!Day Electric Inc - Electricians"]',
    1,
    'http://magaelectric.com/',
    NULL,
    '(541) 900-5790',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-26',
    'Day Electric Inc',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","General Contractors","Electric Contractors-Commercial & Industrial","!Reece Electric Inc - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 857-5970',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-27',
    'Reece Electric Inc',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","!Rogue Electric Service - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 772-7005',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-28',
    'Rogue Electric Service',
    'Medford',
    'OR',
    'electricians',
    '["Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 772-6388',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-29',
    'Obrien Electric',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","Electric Equipment Repair & Service","Lamp & Lampshade Repair"]',
    1,
    NULL,
    50,
    '(541) 779-4062',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-30',
    'North Coast Electric',
    'Medford',
    'OR',
    'electricians',
    '["Electricians"]',
    1,
    'http://www.northcoastelectric.com/',
    NULL,
    '(541) 772-7131',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-31',
    'Consolidated Electrical Distributors',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","Electric Equipment & Supplies"]',
    1,
    'http://www.cedcareers.com/',
    NULL,
    '(541) 665-2332',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-32',
    'Central Electric Lighting Inc',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","Lighting Maintenance Service","Electric Contractors-Commercial & Industrial","!Ramsay Electric - Electricians"]',
    1,
    'http://www.centralelectriclighting.com/',
    21,
    '(541) 773-1618',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-33',
    'Ramsay Electric',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","!Perrine Electric - Electric Companies"]',
    1,
    'http://ramsayelectric.com/',
    49,
    '(541) 772-1398',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-34',
    'Perrine Electric',
    'Medford',
    'OR',
    'electricians',
    '["Electric Companies","Electric Motors","!Reliable Electric - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 826-5505',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-35',
    'Reliable Electric',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","!Landers Electric - Electricians"]',
    1,
    'https://qualityfenceco.com/about-quality-fence-company/western-vinyl-products',
    NULL,
    '(541) 664-1668',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-36',
    'Landers Electric',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","!Jac Electric Inc - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 899-8897',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-37',
    'Jac Electric Inc',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","Electric Contractors-Commercial & Industrial","!Central Point Electric Inc - Electricians"]',
    1,
    NULL,
    42,
    '(541) 826-3562',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-38',
    'Central Point Electric Inc',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","Electric Companies","!Ashland Utilities - Electric Companies"]',
    1,
    'http://www.patriotelectricoregon.com/',
    NULL,
    '(541) 826-8223',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-39',
    'Ashland Utilities',
    'Medford',
    'OR',
    'electricians',
    '["Electric Companies","Water Utility Companies","City, Village & Township Government"]',
    1,
    'http://ashland.or.us/',
    NULL,
    '(541) 488-6004',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-40',
    'Ashland City Equipment Maintenance',
    'Medford',
    'OR',
    'electricians',
    '["Electric Companies","City, Village & Township Government","Utility Companies","!Lansdown Electric - Electricians"]',
    1,
    'http://www.ashland.org/',
    NULL,
    '(541) 488-5358',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-41',
    'Lansdown Electric',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","!All Stars Electric - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 941-4801',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-42',
    'All Stars Electric',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","!Randahls Electric Service Inc - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 665-2705',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-43',
    'Randahls Electric Service Inc',
    'Medford',
    'OR',
    'electricians',
    '["Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 890-2000',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-44',
    'Infinity Electrical Contractors Inc',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","!Ramsay Electric - Electricians"]',
    1,
    'https://iecontractors.com/contact-us',
    NULL,
    '(541) 826-2430',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-45',
    'Ramsay Electric',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","!J T Electric - Electricians"]',
    1,
    'http://ramsayelectric.com/',
    NULL,
    '(541) 772-1398',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-46',
    'J T Electric',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","!Welburn Electric, Inc. - Electricians"]',
    1,
    'http://www.cbs.state.or.us/bcd',
    NULL,
    '(541) 734-5714',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-47',
    'Welburn Electric, Inc.',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","!Logtown Electric - Electricians"]',
    1,
    'http://www.welburnelectric.com/',
    34,
    '(541) 535-3727',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-48',
    'Logtown Electric',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","!Eric Keys Electric - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 941-8859',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-49',
    'Eric Keys Electric',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","Altering & Remodeling Contractors","Home Improvements","!Alan Galedrige Electric - Electricians"]',
    1,
    'http://www.ericselectricservice.com/',
    38,
    '(541) 665-2865',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-50',
    'Alan Galedrige Electric',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","!Grounded Electrical Contract - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 665-9833',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-51',
    'Grounded Electrical Contract',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","!Krug Electric Inc - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 951-6477',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-52',
    'Krug Electric Inc',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","!Advanced Electrical Contractor - Electricians"]',
    1,
    'http://krugelectric.com/',
    NULL,
    '(541) 770-5588',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-53',
    'Advanced Electrical Contractor',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","!Double D Electric - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 816-7951',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-54',
    'Double D Electric',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","Major Appliances","Air Conditioning Contractors & Systems","!RF Enterprise Inc - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 664-5483',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-55',
    'RF Enterprise Inc',
    'Medford',
    'OR',
    'electricians',
    '["Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 664-2107',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-56',
    'Southern Oregon Electrical Contractors',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","!Welburn Electric Inc - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 665-2806',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-57',
    'Welburn Electric Inc',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","!New Line Electric - Electricians"]',
    1,
    'http://welburnelectric.com/',
    NULL,
    '(541) 535-3727',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-58',
    'New Line Electric',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","!Infinity Electrical - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 944-0844',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-59',
    'Infinity Electrical',
    'Medford',
    'OR',
    'electricians',
    '["Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 826-2430',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-60',
    'Perrine Industrial Electricians Inc',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","Used Electric Motors","Electric Motors"]',
    1,
    NULL,
    88,
    '(541) 826-5505',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-1',
    'Applied Refrigeration Technology, Inc.',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Restaurant Equipment & Supplies","Heating Equipment & Systems"]',
    1,
    'http://www.appliedrefrigerationinc.net/',
    16,
    '(541) 291-9428',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-2',
    'Field Plumbing and Mechanical',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Plumbers","Heating Contractors & Specialties"]',
    1,
    'https://www.fieldplumbingandmechanical.com/',
    NULL,
    '(541) 613-1337',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-3',
    'S & T Renovation and Remodeling, LLC',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Repair & Maintenance","Building Contractors","!Batzer Construction - General Contractors"]',
    1,
    NULL,
    10,
    '(541) 631-8852',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-4',
    'Batzer Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors-Commercial & Industrial","!Brick House Construction - General Contractors"]',
    1,
    'http://www.batzerconstruction.com/',
    27,
    '(541) 773-7553',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-5',
    'Brick House Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!Adair Homes Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 531-2113',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-6',
    'Adair Homes Inc',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!Buntin Construction - General Contractors"]',
    1,
    'https://www.adairhomes.com/',
    NULL,
    '(541) 732-1560',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-7',
    'Buntin Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Building Construction Consultants","!Tim Kohler Enterprises - General Contractors"]',
    1,
    'https://www.buntinconstruction.com/fire-clean-up-rebuild',
    NULL,
    '(541) 776-0032',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-8',
    'Tim Kohler Enterprises',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 535-5455',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-9',
    'Thomas L Avalon Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!Dave Norris Contracting - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 292-2580',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-10',
    'Dave Norris Contracting',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!Verity Construction - General Contractors"]',
    1,
    'https://www.roguevalleyconstruction.com/',
    NULL,
    '(541) 941-3206',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-11',
    'Verity Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors-Commercial & Industrial","Real Estate Developers","!Ronda Construction Co - General Contractors"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 326-7242',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-12',
    'Ronda Construction Co',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Building Contractors"]',
    1,
    'http://hstrial-jronda.homestead.com/',
    35,
    '(541) 774-9121',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-13',
    'South Valley Construction, Inc.',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Deck Builders","Altering & Remodeling Contractors","!Mike & Son''s Construction - General Contractors"]',
    1,
    'http://www.svcoregon.com/',
    28,
    '(541) 930-8982',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-14',
    'Mike & Son''s Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!Esselstrom Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 227-9940',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-15',
    'Esselstrom Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Paving Contractors","Asphalt Paving & Sealcoating"]',
    1,
    NULL,
    NULL,
    '(541) 261-3111',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-16',
    'Anthony Martinez Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors-Commercial & Industrial","!Bostwick Construction - General Contractors"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 773-1600',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-17',
    'Bostwick Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    'http://bostwickconstruction.com/',
    63,
    '(541) 779-3566',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-18',
    'K2K Construction and Services',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Tile-Contractors & Dealers","Bathroom Remodeling","!Rivercross Construction - General Contractors"]',
    1,
    'https://k2kconstruction.com/',
    NULL,
    '(541) 285-5753',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-19',
    'Rivercross Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!GMA Construction - General Contractors"]',
    1,
    'https://www.facebook.com/rivercrossconstruction',
    NULL,
    '(541) 414-4301',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-20',
    'GMA Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors-Commercial & Industrial","!Gale Contractor Services - General Contractors"]',
    1,
    NULL,
    45,
    '(541) 326-4804',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-21',
    'Gale Contractor Services',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Insulation Contractors","Building Contractors","!Statewide Sales & Service - General Contractors"]',
    1,
    'https://www.truteam.com/branches/or/medford/196',
    27,
    '(541) 776-2848',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-22',
    'Statewide Sales & Service',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Concrete Contractors"]',
    1,
    'https://www.statewidesealcoat.com/contact',
    NULL,
    '(541) 772-2660',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-23',
    'Better Built Construction Inc',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!Your Design Builders - General Contractors"]',
    1,
    'https://www.bbconstructionmedford.com/',
    NULL,
    '(541) 301-7098',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-24',
    'Your Design Builders',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!Ledford Construction Co - General Contractors"]',
    1,
    'http://www.yourdesignbuilders.com/',
    NULL,
    '(541) 227-5115',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-25',
    'Ledford Construction Co',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Excavation Contractors","Road Building Contractors","!M D A Construction - General Contractors"]',
    1,
    'http://www.ledfordconstruction.com/',
    NULL,
    '(541) 535-8692',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-26',
    'M D A Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Building Foundations - General Contractors"]',
    1,
    NULL,
    45,
    '(541) 773-9497',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-27',
    'Building Foundations',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors"]',
    1,
    NULL,
    NULL,
    '(458) 226-2615',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-28',
    'Contractor Services Group Inc',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Hartsook Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 772-2413',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-29',
    'Hartsook Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!New Dimension Builders - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 773-5987',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-30',
    'New Dimension Builders',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!Jason Landis Builder Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 944-7602',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-31',
    'Jason Landis Builder Inc',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!J. B. Steel Inc. - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 821-1340',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-32',
    'J. B. Steel Inc.',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","!Rogue Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 773-8325',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-33',
    'Rogue Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 840-8366',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-34',
    'Clearheart Construction Inc',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors-Commercial & Industrial","Real Estate Developers","!Quinlan''s - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 770-2050',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-35',
    'Quinlan''s',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!JCS Alarm - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 621-1273',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-36',
    'JCS Alarm',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    'https://jacksoncountysecurity.com/cnt.html',
    NULL,
    '(541) 973-5555',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-37',
    'Homeworx Construction & Handyman Services',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!BLH construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 646-5318',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-38',
    'BLH construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!Galpin - General Contractors"]',
    1,
    NULL,
    10,
    '(541) 977-7840',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-39',
    'Galpin',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Zachariah Dale Macormic - General Contractors"]',
    1,
    'https://www.galpinhomes.com/',
    NULL,
    '(541) 779-5346',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-40',
    'Zachariah Dale Macormic',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Timothy Raymond Rhodes - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 821-3473',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-41',
    'Timothy Raymond Rhodes',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","Building Contractors-Commercial & Industrial","!Stormberg Construction Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 941-9980',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-42',
    'Stormberg Construction Inc',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!Partners Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 292-4373',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-43',
    'Partners Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    'https://www.designcenterfurniture.com/_CGI/SEARCH3.html',
    NULL,
    '(541) 770-2627',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  );