INSERT INTO businesses (
      id, name, city, state, industry, services, verified, website, 
      yearsInBusiness, phone, address, email, rating, reviewCount, 
      licenseNumber, bbbRating, emergencyService
    ) VALUES (
    'portland-RealEstateAgents-214',
    'Mercer & Bolders Apartments Leaseing Office',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Independent Brokers Realty - Real Estate Agents"]',
    1,
    'https://prometheusapartments.com/',
    NULL,
    '(925) 478-4101',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-215',
    'Independent Brokers Realty',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Sellpdx Com - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 282-3676',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-216',
    'Sellpdx Com',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Harsh Investment Properties - Real Estate Agents"]',
    1,
    'https://cityandstatere.com/contact',
    NULL,
    '(503) 703-5102',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-217',
    'Harsh Investment Properties',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Apex Real Estate Partners - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 719-7535',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-218',
    'Apex Real Estate Partners',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://apexcre.com/',
    NULL,
    '(503) 595-2840',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-219',
    'Sutherland Commercial Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://www.sutherlandcre.com/',
    NULL,
    '(503) 206-7964',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-220',
    'Windermere Cronin & Caplan Realty Group Inc',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Taylor Group Realty - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 220-4500',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-221',
    'Taylor Group Realty',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Csc Westfal Realty - Real Estate Agents"]',
    1,
    'https://www.portlandrealestateexperts.com/',
    NULL,
    '(503) 417-7800',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-222',
    'Csc Westfal Realty',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(503) 841-5560',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-223',
    'Greater Portland Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Oregon Real Estate Forms - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 227-5530',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-224',
    'Oregon Real Estate Forms',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Sircom Pacific Propertys - Real Estate Agents"]',
    1,
    'http://orefonline.com/',
    NULL,
    '(503) 459-0195',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-225',
    'Sircom Pacific Propertys',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Taylor Group Realty - Real Estate Agents"]',
    1,
    'https://www.circum-pacific.com/property/marion-court-apartments',
    NULL,
    '(503) 222-0110',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-226',
    'Taylor Group Realty',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    'http://portlandrealestateexperts.com/contact-us',
    NULL,
    '(503) 417-7800',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-227',
    'Carrie Desoto Post-Realty One Group Prestige',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Green Property Concepts - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 309-6290',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-228',
    'Green Property Concepts',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Yak Social - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 222-0555',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-229',
    'Yak Social',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Harvard Real Estate Group - Real Estate Agents"]',
    1,
    'https://www.yaksocial.com/',
    NULL,
    '(503) 305-6297',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-230',
    'Harvard Real Estate Group',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Choc N Roll Properties - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 288-5524',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-231',
    'Choc N Roll Properties',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Laurie Holland Real Estate - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 327-8012',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-232',
    'Laurie Holland Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Management","!Preece & Floberg - Real Estate Agents"]',
    1,
    'https://www.laurieholland.com/contact.html',
    NULL,
    '(503) 242-9000',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-233',
    'Preece & Floberg',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate","!Don Rasmussen Co - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 719-6571',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-234',
    'Don Rasmussen Co',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Aegis Group - Real Estate Agents"]',
    1,
    'https://www.bmwportland.com/',
    NULL,
    '(503) 226-0380',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-235',
    'Aegis Group',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Marimar Prop Everest Bdg - Real Estate Agents"]',
    1,
    'https://www.garda.com/?originaegis=',
    NULL,
    '(503) 869-4486',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-236',
    'Marimar Prop Everest Bdg',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Pdxrelocate - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 542-2930',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-237',
    'Pdxrelocate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!American Assets - Real Estate Agents"]',
    1,
    'https://www.pohlrealestate.com/headquarters.htm',
    NULL,
    '(503) 214-8750',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-238',
    'American Assets',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Investing","Real Estate Buyer Brokers","!Redfin Co - Real Estate Agents"]',
    1,
    'https://www.americanassetstrust.com/lloyd-district-portfolio?view=property&id=40:lloyd-700-portland',
    NULL,
    '(503) 233-5696',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-239',
    'Redfin Co',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Living Room Realty - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 477-7192',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-240',
    'Living Room Realty',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","!Remax - Real Estate Agents"]',
    1,
    'https://www.livingroomre.com/adu/adus-in-portland-understanding-more-getting-started',
    NULL,
    '(503) 719-5588',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-241',
    'Remax',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate","!Meridian Realty Group - Real Estate Agents"]',
    1,
    'http://equitygroup.com/',
    52,
    '(503) 287-8989',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-242',
    'Meridian Realty Group',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Wyse Real Estate Advisors - Real Estate Agents"]',
    1,
    'http://www.meridianrealtygroup.com/',
    NULL,
    '(503) 706-8306',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-243',
    'Wyse Real Estate Advisors',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","Real Estate Management","!All Things Real Estate - Real Estate Agents"]',
    1,
    'https://wyserea.com/contact',
    NULL,
    '(503) 294-0400',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-244',
    'All Things Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Commercial Properties NW - Real Estate Agents"]',
    1,
    'http://allthingsrealestatestore.com/',
    NULL,
    '(971) 266-8267',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-245',
    'Commercial Properties NW',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(503) 223-1800',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-246',
    'Jacksonbettie Properties Inc',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Killian Pacific - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 244-3292',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-247',
    'Killian Pacific',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!GRS Properties - Real Estate Agents"]',
    1,
    'https://killianpacific.com/contact-us',
    NULL,
    '(503) 746-9171',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-248',
    'GRS Properties',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Venerable Group Inc - Real Estate Agents"]',
    1,
    'http://grsproperties.com/id1.html',
    NULL,
    '(503) 220-0354',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-249',
    'Venerable Group Inc',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Developers","Real Estate Management","!Pittman Properties - Real Estate Agents"]',
    1,
    'https://merituspg.com/about',
    NULL,
    '(503) 224-2446',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-250',
    'Pittman Properties',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(503) 236-3019',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-251',
    'Oregon Real Estate Forms Inc',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Dean, Kevin - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 459-0195',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-252',
    'Dean, Kevin',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Pmar - Real Estate Agents"]',
    1,
    'https://www.classicpdxhomes.com/contact-me',
    NULL,
    '(503) 481-4400',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-253',
    'Pmar',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://pmarmc.com/contact-us',
    NULL,
    '(503) 459-2152',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-254',
    'Milestone Realty Consultants',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'http://milestonerc.com/',
    NULL,
    '(859) 245-1179',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-255',
    'Windermere Cronin & Caplan Realty Group Inc',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Abbott & Caserta-Wyckoff - Real Estate Agents"]',
    1,
    'http://www.windermereportland.com/',
    NULL,
    '(503) 284-7755',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-256',
    'Abbott & Caserta-Wyckoff',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Wrc Re/Max - Real Estate Agents"]',
    1,
    'https://www.njmls.com/',
    NULL,
    '(201) 891-2223',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-257',
    'Wrc Re/Max',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(309) 444-3121',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-258',
    'Aimee Virnig with Windermere Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!TRZ Properties - Real Estate Agents"]',
    1,
    'http://www.aimeevirnig.com/',
    NULL,
    '(503) 803-7675',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-259',
    'TRZ Properties',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Sterlingpoint Properties - Real Estate Agents"]',
    1,
    'https://www.gordon-properties.com/contact-us',
    NULL,
    '(503) 253-1515',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-260',
    'Sterlingpoint Properties',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Premiere Property Group - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(971) 271-8283',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-261',
    'Premiere Property Group',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","!Rafferty, Eric, AGT - Real Estate Agents"]',
    1,
    'http://justseefrank.com/',
    NULL,
    '(971) 202-7222',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-262',
    'Rafferty, Eric, AGT',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!L L Hawkins Block 296 - Real Estate Agents"]',
    1,
    'https://eric-thebungalowguy.com/',
    NULL,
    '(503) 890-1347',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-263',
    'L L Hawkins Block 296',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate","!Brunke Real Estate - Real Estate Agents"]',
    1,
    'https://www.thellhawkins.com/',
    NULL,
    '(503) 224-0569',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-264',
    'Brunke Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Inner City Properties Inc - Real Estate Agents"]',
    1,
    'https://icppdx.com/',
    NULL,
    '(503) 223-2200',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-265',
    'Inner City Properties Inc',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Developers","Real Estate Buyer Brokers","!Where Inc - Real Estate Agents"]',
    1,
    'http://www.icppdx.com/',
    NULL,
    '(503) 274-1035',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-266',
    'Where Inc',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Plinkos Business Center - Real Estate Agents"]',
    1,
    'http://www.where-inc.com/',
    NULL,
    '(503) 222-0223',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-267',
    'Plinkos Business Center',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate","!The Hasson Company Realtors - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 946-8298',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-268',
    'The Hasson Company Realtors',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    'http://www.hasson.com/',
    NULL,
    '(503) 228-9801',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-269',
    'Debbie Thomas Real Estate-the Waverly',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Seligman, Ross, RLTR - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 226-4300',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-270',
    'Seligman, Ross, RLTR',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://www.findyourwayhome.realestate/',
    NULL,
    '(503) 449-4022',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Roofers-1',
    'IBEX Roof',
    'Portland',
    'OR',
    'roofers',
    '["Roofing Contractors","Siding Contractors","Insulation Contractors"]',
    1,
    NULL,
    2,
    '(888) 201-8725',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Roofers-2',
    'Arrow Roofing & Sheet Metal Inc',
    'Portland',
    'OR',
    'roofers',
    '["Roofing Contractors","Building Contractors","General Contractors","Services","!Superior Roofing - Roofing Contractors"]',
    1,
    'https://arrow-roofing.com/',
    71,
    '(503) 460-2767',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Roofers-3',
    'Superior Roofing',
    'Portland',
    'OR',
    'roofers',
    '["Roofing Contractors","Gutters & Downspouts Cleaning","Roof Cleaning","!Clow Roofing & Siding Co - Roofing Contractors"]',
    1,
    'https://www.thesuperiorroofers.com/',
    16,
    '(503) 388-3252',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Roofers-4',
    'Clow Roofing & Siding Co',
    'Portland',
    'OR',
    'roofers',
    '["Roofing Contractors","Gutters & Downspouts","Insulation Materials","Services","!Gregg Roofing LLC - Roofing Contractors"]',
    1,
    'http://www.clowroofing.com/',
    97,
    '(971) 373-4720',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Roofers-5',
    'Gregg Roofing LLC',
    'Portland',
    'OR',
    'roofers',
    '["Roofing Contractors","General Contractors","Home Improvements","!Compare Roofing Experts - Roofing Contractors"]',
    1,
    'http://www.greggroofing.com/',
    81,
    '(360) 844-8238',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Roofers-6',
    'Compare Roofing Experts',
    'Portland',
    'OR',
    'roofers',
    '["Roofing Contractors","Roofing Contractors-Commercial & Industrial","!IBEX Roof - Roofing Contractors"]',
    1,
    NULL,
    NULL,
    '(888) 906-6670',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Roofers-7',
    'IBEX Roof',
    'Portland',
    'OR',
    'roofers',
    '["Roofing Contractors","Insulation Contractors","Home Improvements","!Roof Masters Inc - Roofing Contractors"]',
    1,
    NULL,
    2,
    '(888) 201-8725',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Roofers-8',
    'Roof Masters Inc',
    'Portland',
    'OR',
    'roofers',
    '["Roofing Contractors","Roof Cleaning"]',
    1,
    'http://www.roofmastersoregon.com/',
    39,
    '(503) 563-1641',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Roofers-9',
    'Allen Exterior Remodeling, Inc.',
    'Portland',
    'OR',
    'roofers',
    '["Roofing Contractors","Siding Contractors","Painting Contractors","!Mountainside Roofing LLC - Roofing Contractors"]',
    1,
    'http://allen-exterior.com/',
    38,
    '(971) 238-6336',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Roofers-10',
    'Mountainside Roofing LLC',
    'Portland',
    'OR',
    'roofers',
    '["Roofing Contractors","Roof & Floor Structures","Patio Covers & Enclosures","!DNR Associates Inc - Roofing Contractors"]',
    1,
    'http://www.mountainsideroofing.com/',
    4,
    '(360) 395-2240',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Roofers-11',
    'DNR Associates Inc',
    'Portland',
    'OR',
    'roofers',
    '["Roofing Contractors","Carpenters","Mobile Home Repair & Service","!Striver Roofing - Roofing Contractors"]',
    1,
    'http://www.dnrassociatesoregon.com/',
    27,
    '(503) 912-8729',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Roofers-12',
    'Striver Roofing',
    'Portland',
    'OR',
    'roofers',
    '["Roofing Contractors","Home Improvements","Roof Cleaning"]',
    1,
    'https://www.striverroofing.com/',
    NULL,
    '(503) 558-4093',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Roofers-13',
    'ABC Roofing and Construction LLC',
    'Portland',
    'OR',
    'roofers',
    '["Roofing Contractors"]',
    1,
    'https://www.abcroofingandconstruction.com/',
    NULL,
    '(503) 806-2831',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Roofers-14',
    'Compare Roofing Experts',
    'Portland',
    'OR',
    'roofers',
    '["Roofing Contractors","Roofing Contractors-Commercial & Industrial","Video","!Gregg Roofing, Inc. - General Contractors"]',
    1,
    NULL,
    NULL,
    '(888) 906-8599',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Roofers-15',
    'Gregg Roofing, Inc.',
    'Portland',
    'OR',
    'roofers',
    '["Roofing Contractors","General Contractors","Home Improvements","Services","!Roof Master - Building Contractors"]',
    1,
    'http://www.greggroofing.com/',
    7,
    '(360) 859-0733',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Roofers-16',
    'Roof Master',
    'Portland',
    'OR',
    'roofers',
    '["Roofing Contractors","Parking Stations & Garages-Construction","Paving Contractors","!Interstate Roofing Inc - Building Contractors"]',
    1,
    NULL,
    NULL,
    '(206) 639-1137',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Roofers-17',
    'Interstate Roofing Inc',
    'Portland',
    'OR',
    'roofers',
    '["Roofing Contractors","Building Contractors-Commercial & Industrial","Home Repair & Maintenance","!FX Repair & Remodeling - Building Contractors"]',
    1,
    'http://www.interstateroofing.com/',
    NULL,
    '(503) 684-5611',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Roofers-18',
    'FX Repair & Remodeling',
    'Portland',
    'OR',
    'roofers',
    '["Roofing Contractors","Home Repair & Maintenance","Building Contractors"]',
    1,
    'http://www.fxrepair.com/',
    36,
    '(503) 542-4442',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Roofers-19',
    'HOMEMASTERS Portland SW',
    'Portland',
    'OR',
    'roofers',
    '["Roofing Contractors","Building Contractors","Cleaning Contractors","Services","!Hasskamp Roofing - Roofing Contractors"]',
    1,
    NULL,
    35,
    '(503) 639-7700',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Roofers-20',
    'Hasskamp Roofing',
    'Portland',
    'OR',
    'roofers',
    '["Roofing Contractors","!Tom Leach Roofing - Roofing Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 645-0215',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Roofers-21',
    'Tom Leach Roofing',
    'Portland',
    'OR',
    'roofers',
    '["Roofing Contractors","Roofing Contractors-Commercial & Industrial","!Sawtooth Roofing Co - Roofing Contractors"]',
    1,
    'http://www.tomleachroofing.net/',
    NULL,
    '(503) 238-0303',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Roofers-22',
    'Sawtooth Roofing Co',
    'Portland',
    'OR',
    'roofers',
    '["Roofing Contractors","Building Contractors","!Carlos Roofing Systems - Roofing Contractors"]',
    1,
    'http://www.sawtoothroofing.com/',
    30,
    '(360) 892-8448',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Roofers-23',
    'Carlos Roofing Systems',
    'Portland',
    'OR',
    'roofers',
    '["Roofing Contractors","Roofing Services Consultants","Services","!Wood''s Roofing - Roofing Contractors"]',
    1,
    'http://www.roofingcrs.com/',
    NULL,
    '(503) 760-9000',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Roofers-24',
    'Wood''s Roofing',
    'Portland',
    'OR',
    'roofers',
    '["Roofing Contractors","General Contractors","Siding Contractors","!AA Maintenance Roof Pro - Roofing Contractors"]',
    1,
    'http://www.woodsroofing.net/',
    29,
    '(503) 317-9663',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Roofers-25',
    'AA Maintenance Roof Pro',
    'Portland',
    'OR',
    'roofers',
    '["Roofing Contractors","Services"]',
    1,
    NULL,
    NULL,
    '(503) 624-9200',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Roofers-26',
    'USA Roofing & Waterproofing',
    'Portland',
    'OR',
    'roofers',
    '["Roofing Contractors","!Roof and Nail - Roofing Contractors"]',
    1,
    'https://www.usaroofingpdx.com/',
    NULL,
    '(503) 836-5016',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Roofers-27',
    'Roof and Nail',
    'Portland',
    'OR',
    'roofers',
    '["Roofing Contractors","!Lifetime Windows & Doors - Roofing Contractors"]',
    1,
    'https://roofandnailco.com/',
    NULL,
    '(503) 270-3194',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Roofers-28',
    'Lifetime Windows & Doors',
    'Portland',
    'OR',
    'roofers',
    '["Roofing Contractors","Windows","Glass Doors"]',
    1,
    'https://www.lifetimewindows.net/',
    27,
    '(503) 230-0500',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Roofers-29',
    'All Roofing Eagle Construction Services',
    'Portland',
    'OR',
    'roofers',
    '["Roofing Contractors","Altering & Remodeling Contractors","Gutters & Downspouts","!Top Flight Roofing - Roofing Contractors"]',
    1,
    'http://www.alleagleroofing.net/',
    14,
    '(503) 847-9240',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Roofers-30',
    'Top Flight Roofing',
    'Portland',
    'OR',
    'roofers',
    '["Roofing Contractors","Gutters & Downspouts Cleaning"]',
    1,
    'https://www.topflightroofingportland.com/',
    9,
    '(503) 912-1664',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Electricians-1',
    'Rite Way Electric Inc.',
    'Salem',
    'OR',
    'electricians',
    '["Electricians","Lighting Fixtures","Electric Equipment Repair & Service","!Black Dreams Construction - Electricians"]',
    1,
    'http://www.ritewayelectric.net/',
    46,
    '(541) 801-3878',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Electricians-2',
    'Black Dreams Construction',
    'Salem',
    'OR',
    'electricians',
    '["Electricians","Painting Contractors","Power Washing","!Judson''s Inc. - Building Contractors"]',
    1,
    'https://www.blackdreamsconstruction.com/',
    NULL,
    '(971) 462-4166',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Electricians-3',
    'Judson''s Inc.',
    'Salem',
    'OR',
    'electricians',
    '["Electricians","Air Conditioning Contractors & Systems","Building Contractors","!Mission Electric - Electricians"]',
    1,
    'http://www.judsonselectric.com/',
    90,
    '(503) 363-4141',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Electricians-4',
    'Mission Electric',
    'Salem',
    'OR',
    'electricians',
    '["Electricians","!North Side Electric - Electricians"]',
    1,
    'http://www.cbs.state.or.us/bcd',
    NULL,
    '(503) 551-8497',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Electricians-5',
    'North Side Electric',
    'Salem',
    'OR',
    'electricians',
    '["Electricians","!Safety Home Services - Electricians"]',
    1,
    'https://www.northsideelectric.com/',
    NULL,
    '(503) 585-4879',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Electricians-6',
    'Safety Home Services',
    'Salem',
    'OR',
    'electricians',
    '["Electricians","Lighting Contractors","!Mr. Electric of Salem - Electricians"]',
    1,
    'https://safetyhomeservices.com/',
    16,
    '(971) 345-5650',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Electricians-7',
    'Mr. Electric of Salem',
    'Salem',
    'OR',
    'electricians',
    '["Electricians","!Safety Electric Inc - Electricians"]',
    1,
    'https://mrelectric.com/salem?cid=LSTL_MRE000256',
    3,
    '(503) 946-9518',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Electricians-8',
    'Safety Electric Inc',
    'Salem',
    'OR',
    'electricians',
    '["Electricians","!A C & E Electric Company - Electricians"]',
    1,
    'https://www.safetyelectricinc.com/',
    16,
    '(503) 585-0300',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Electricians-9',
    'A C & E Electric Company',
    'Salem',
    'OR',
    'electricians',
    '["Electricians","Electric Contractors-Commercial & Industrial","!Assured Electric LLC - Electricians"]',
    1,
    NULL,
    66,
    '(503) 363-2301',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Electricians-10',
    'Assured Electric LLC',
    'Salem',
    'OR',
    'electricians',
    '["Electricians","!Lighting Installation Electrician - Electricians"]',
    1,
    'https://assuredelectric-llc.com/',
    NULL,
    '(503) 871-4637',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Electricians-11',
    'Lighting Installation Electrician',
    'Salem',
    'OR',
    'electricians',
    '["Electricians","Electric Companies","!Cherry City Electric - Electricians"]',
    1,
    NULL,
    NULL,
    '(503) 967-9517',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Electricians-12',
    'Cherry City Electric',
    'Salem',
    'OR',
    'electricians',
    '["Electricians","Electric Companies","!Outlet Electrical Repair - Electric Companies"]',
    1,
    'http://www.cherrycityelectric.com/',
    NULL,
    '(503) 566-3085',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Electricians-13',
    'Outlet Electrical Repair',
    'Salem',
    'OR',
    'electricians',
    '["Electricians","Electric Companies","!All Electric - Electric Companies"]',
    1,
    NULL,
    NULL,
    '(503) 967-9541',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  );