INSERT INTO businesses (
      id, name, city, state, industry, services, verified, website, 
      yearsInBusiness, phone, address, email, rating, reviewCount, 
      licenseNumber, bbbRating, emergencyService
    ) VALUES (
    'portland-RealEstateAgents-114',
    'Urban Renaissance Group',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","Real Estate Buyer Brokers","!Felton Management Corp - Real Estate Agents"]',
    1,
    'http://www.urbanrengroup.com/',
    NULL,
    '(503) 241-3345',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-115',
    'Felton Management Corp',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Spalding Building - Real Estate Agents"]',
    1,
    'https://www.feltonpropertiesinc.com/properties/cascade-building',
    NULL,
    '(503) 227-2433',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-116',
    'Spalding Building',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Interaction Metrics - Real Estate Agents"]',
    1,
    'http://spaldingbuilding.com/',
    NULL,
    '(503) 223-6639',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-117',
    'Interaction Metrics',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Schlesinger Companies - Real Estate Agents"]',
    1,
    'http://interactionmetrics.com/',
    NULL,
    '(971) 266-8851',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-118',
    'Schlesinger Companies',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Melvin Mark Properties - Real Estate Agents"]',
    1,
    'http://schlesingercompanies.com/',
    NULL,
    '(503) 223-4128',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-119',
    'Melvin Mark Properties',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Elliott Associates - Real Estate Agents"]',
    1,
    'http://melvinmark.com/',
    NULL,
    '(503) 243-6864',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-120',
    'Elliott Associates',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","!Greenbridge Properties - Real Estate Agents"]',
    1,
    'http://www.elliottassociatesinc.com/',
    NULL,
    '(503) 228-3169',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-121',
    'Greenbridge Properties',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Riverscape Properties - Real Estate Agents"]',
    1,
    'https://greenbridge-properties.com/contact',
    NULL,
    '(503) 206-5892',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-122',
    'Riverscape Properties',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    'http://riverscapeproperties.com/',
    NULL,
    '(503) 295-3744',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-123',
    'Grubb & Ellis Comm Real Estat',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Eb 5 Global - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 241-1155',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-124',
    'Eb 5 Global',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate","!Keller Williams Realty - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(971) 279-5810',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-125',
    'Keller Williams Realty',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Consultants","!Arezzini Properties - Real Estate Agents"]',
    1,
    'http://www.norris-stevens.com/',
    58,
    '(800) 594-0474',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-126',
    'Arezzini Properties',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!GSL Properties - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 750-1859',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-127',
    'GSL Properties',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Van Haverbeke Property - Real Estate Agents"]',
    1,
    'https://www.gslproperties.com/Apartments/module/properties',
    NULL,
    '(503) 227-0613',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-128',
    'Van Haverbeke Property',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Apex Real Estate Partners - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 228-0222',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-129',
    'Apex Real Estate Partners',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate"]',
    1,
    'http://apexcre.com/',
    NULL,
    '(503) 595-2840',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-130',
    'Prometheus Real Estate Group',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Taylor Group Realty - Real Estate Agents"]',
    1,
    'https://prometheusapartments.com/',
    NULL,
    '(925) 478-4101',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-131',
    'Taylor Group Realty',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Strand Sales Office - Real Estate Agents"]',
    1,
    'http://portlandrealestateexperts.com/contact-us',
    NULL,
    '(503) 417-7800',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-132',
    'Strand Sales Office',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate","!Realty Trust - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 292-9119',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-133',
    'Realty Trust',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Commerical Integrity NW - Real Estate Agents"]',
    1,
    'https://windermereportland.com/listing/OR/Portland/311-NW-12th-Ave-1204-97209/165968794',
    NULL,
    '(503) 222-0058',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-134',
    'Commerical Integrity NW',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Patterson Ossey Co - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(971) 202-7271',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-135',
    'Patterson Ossey Co',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!O''Donnell Group Realty - Real Estate Agents"]',
    1,
    'https://capacitycommercial.com/contact-us',
    NULL,
    '(503) 517-7128',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-136',
    'O''Donnell Group Realty',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Century 21 Northwest Realty - Real Estate Agents"]',
    1,
    'http://odonnellgrouprealty.com/',
    NULL,
    '(503) 281-1404',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-137',
    'Century 21 Northwest Realty',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Auctioneers","!83 West Company - Real Estate Agents"]',
    1,
    'http://rmnw-auctions.com/',
    NULL,
    '(803) 868-6100',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-138',
    '83 West Company',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Morrison Street Capital - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 380-6990',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-139',
    'Morrison Street Capital',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Mainland Northwest - Real Estate Agents"]',
    1,
    'https://morrisonstreetcapital.com/',
    NULL,
    '(503) 952-0700',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-140',
    'Mainland Northwest',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Developers"]',
    1,
    NULL,
    NULL,
    '(971) 339-2911',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-141',
    'McMenamins Historic Properties',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Golik, Brad, AGT - Real Estate Agents"]',
    1,
    'http://www.mcmenamins.com/',
    42,
    '(503) 223-0109',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-142',
    'Golik, Brad, AGT',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Pearl District Properties - Real Estate Agents"]',
    1,
    'https://www.luxurycondosofportland.com/errorPage.aspx?error=404',
    NULL,
    '(503) 896-8856',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-143',
    'Pearl District Properties',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Integra Realty Resources - Real Estate Agents"]',
    1,
    'http://www.pearldp.com/',
    NULL,
    '(503) 222-1122',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-144',
    'Integra Realty Resources',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Eastern Western Corp - Real Estate Agents"]',
    1,
    'http://www.irr.com/',
    NULL,
    '(971) 277-9420',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-145',
    'Eastern Western Corp',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Developers","!Summit Real Estate - Real Estate Agents"]',
    1,
    'http://ewcorp.net/',
    NULL,
    '(503) 236-1978',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-146',
    'Summit Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(503) 223-1150',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-147',
    'Commercial Association-RLTRS',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Investing","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(503) 226-4545',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-148',
    'Cascade Hasson Sotheby''s International Realty',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Rental Service","!Reed Realty Advisors - Real Estate Agents"]',
    1,
    'https://www.cascadehasson.com/',
    NULL,
    '(503) 420-8600',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-149',
    'Reed Realty Advisors',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Consultants"]',
    1,
    NULL,
    NULL,
    '(503) 974-7555',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-150',
    'Realty Executives International',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Consultants","!Summit Real Estate - Real Estate Agents"]',
    1,
    'http://www.realtyexecutives.com/',
    NULL,
    '(503) 220-1601',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-151',
    'Summit Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Green Cities IV LP - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 227-4743',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-152',
    'Green Cities IV LP',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Rembold Companies - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 299-6000',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-153',
    'Rembold Companies',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Cheyenne Commerce Center - Real Estate Agents"]',
    1,
    'http://www.rembold.com/',
    NULL,
    '(503) 222-7258',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-154',
    'Cheyenne Commerce Center',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Paca Properties - Real Estate Agents"]',
    1,
    'http://harsch.com/',
    NULL,
    '(503) 242-2900',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-155',
    'Paca Properties',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://www.vickiarnold.com/',
    NULL,
    '(503) 492-1776',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-156',
    'New & Neville Real Estate Service',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Fischer & Co - Real Estate Agents"]',
    1,
    'http://www.newneville.com/',
    NULL,
    '(503) 241-1222',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-157',
    'Fischer & Co',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","!Commerce Properties Inc - Real Estate Agents"]',
    1,
    'http://fischercompany.com/',
    NULL,
    '(971) 202-2940',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-158',
    'Commerce Properties Inc',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Madison Ofc One Main Place - Real Estate Agents"]',
    1,
    'https://commerceproperties.com/',
    NULL,
    '(503) 224-3315',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-159',
    'Madison Ofc One Main Place',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Hoyt Street Properties - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 295-1169',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-160',
    'Hoyt Street Properties',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Developers","Real Estate Buyer Brokers","!Kehoe Northwest Properties - Real Estate Agents"]',
    1,
    'http://www.hoytstreetproperties.com/',
    NULL,
    '(503) 227-6677',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-161',
    'Kehoe Northwest Properties',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Eleete Real Estate - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 244-3838',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-162',
    'Eleete Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!McCall Properties Inc - Real Estate Agents"]',
    1,
    'https://www.leedavies.com/OR/97230',
    NULL,
    '(503) 445-1500',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-163',
    'McCall Properties Inc',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    'https://mccallterminals.com/',
    NULL,
    '(503) 221-5880',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-164',
    'Zions Commercial Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Loans","!R V Kuhns & Associates Inc - Real Estate Agents"]',
    1,
    'https://www.zionsbank.com/personal',
    NULL,
    '(503) 548-1180',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-165',
    'R V Kuhns & Associates Inc',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate"]',
    1,
    NULL,
    NULL,
    '(503) 221-4200',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-166',
    'Berkadia Real Estate Advisors',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Investing","Real Estate Buyer Brokers","!Living Room Realty - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 223-0050',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-167',
    'Living Room Realty',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Remax - Real Estate Agents"]',
    1,
    'https://www.livingroomre.com/condos/stunning-streetcar-loft-in-the-pearl',
    NULL,
    '(541) 231-5829',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-168',
    'Remax',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate","!Perreault, Lauren, AGT - Real Estate Agents"]',
    1,
    'http://www.remax.com/',
    NULL,
    '(503) 477-9745',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-169',
    'Perreault, Lauren, AGT',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Svaren Realty - Real Estate Agents"]',
    1,
    'https://www.remax.com/realestateagentoffice/portland-or-97209-laurenperreault-id29137374.html',
    NULL,
    '(503) 477-9745',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-170',
    'Svaren Realty',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","!Tokola Properties - Real Estate Agents"]',
    1,
    'http://svarenrealty.com/contact',
    NULL,
    '(503) 267-9828',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-171',
    'Tokola Properties',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Apex Real Estate Partners - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 227-4736',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-172',
    'Apex Real Estate Partners',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Dreamstreet Real Estate Inc - Real Estate Agents"]',
    1,
    'https://apexcre.com/property/105-n-main-street-myrtle-creek',
    NULL,
    '(503) 595-2840',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-173',
    'Dreamstreet Real Estate Inc',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://www.jolynne.com/portland-schools-links.html',
    NULL,
    '(503) 678-2020',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-174',
    'American Business Properties',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Convention Plaza - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 241-8300',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-175',
    'Convention Plaza',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate","!Ball Parc Properties - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 235-3457',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-176',
    'Ball Parc Properties',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Mbm Properties Inc - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 248-2255',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-177',
    'Mbm Properties Inc',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Urban Works Real Estate - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 232-7202',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-178',
    'Urban Works Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Investing","!Lavastream Real Estate - Real Estate Agents"]',
    1,
    'http://www.urbanworksrealestate.com/',
    NULL,
    '(503) 228-3080',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-179',
    'Lavastream Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Schnitzer Properties - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(800) 793-8774',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-180',
    'Schnitzer Properties',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Skb - Real Estate Agents"]',
    1,
    'https://schnitzerproperties.com/',
    NULL,
    '(503) 242-2900',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-181',
    'Skb',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!MMDC Company - Real Estate Agents"]',
    1,
    'http://skbcos.com/',
    NULL,
    '(503) 220-2600',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-182',
    'MMDC Company',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Carder, Jonathan T - Real Estate Agents"]',
    1,
    'http://www.morrisonbridgeheadblocks.mmdccompany.com/contact',
    NULL,
    '(971) 266-5544',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-183',
    'Carder, Jonathan T',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate","!WCB Commercial Properties - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 223-4777',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-184',
    'WCB Commercial Properties',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(971) 339-3351',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-185',
    'Shorenstein Realty Services LP',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Buell Properties - Real Estate Agents"]',
    1,
    'http://www.shorenstein.com/',
    NULL,
    '(503) 412-4800',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-186',
    'Buell Properties',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Vantage Point Properties - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 222-4122',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-187',
    'Vantage Point Properties',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Myers, Frank - Real Estate Agents"]',
    1,
    'http://vppihomes.com/',
    NULL,
    '(503) 243-4620',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-188',
    'Myers, Frank',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate","!Keller Williams Realty - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 241-9283',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-189',
    'Keller Williams Realty',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Consultants","!McMonies Properties - Real Estate Agents"]',
    1,
    'http://kw.com/',
    NULL,
    '(503) 546-9955',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-190',
    'McMonies Properties',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Simpson Property Group - Real Estate Agents"]',
    1,
    'https://www.mcmoniesproperties.com/',
    NULL,
    '(503) 347-5026',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-191',
    'Simpson Property Group',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","!Lavier Enterprises - Real Estate Agents"]',
    1,
    'http://simpsonhousing.com/',
    NULL,
    '(303) 283-4100',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-192',
    'Lavier Enterprises',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Developers","Real Estate Buyer Brokers","!Fairstone Properties - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 239-8927',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-193',
    'Fairstone Properties',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Turner Team Inc - Real Estate Agents"]',
    1,
    'https://www.fairstoneproperties.com/about-us/fotolia_2890102_subscription_monthly_m-1',
    NULL,
    '(503) 697-3807',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-194',
    'Turner Team Inc',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    'http://lovejoyrealestate.com/',
    NULL,
    '(503) 501-2490',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-195',
    'Riverstone Residential Group',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Futures Real Estate - Real Estate Agents"]',
    1,
    'http://www.riverstoneres.com/',
    NULL,
    '(503) 546-5300',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-196',
    'Futures Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Silver Baron Corp - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 224-6928',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-197',
    'Silver Baron Corp',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Lane Realty Works - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 810-2737',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-198',
    'Lane Realty Works',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Prem Group Inc - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(971) 229-0249',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-199',
    'Prem Group Inc',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Management","!Urban Pacific Real Estate - Real Estate Agents"]',
    1,
    'https://www.premgrp.com/',
    NULL,
    '(503) 224-1460',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-200',
    'Urban Pacific Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Coast Real Estate Services - Real Estate Agents"]',
    1,
    'http://www.urbanpacificrealestate.com/',
    NULL,
    '(503) 740-2043',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-201',
    'Coast Real Estate Services',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Rose City Realty Group - Real Estate Agents"]',
    1,
    'https://www.coastmgt.com/contact-us',
    NULL,
    '(971) 347-3987',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-202',
    'Rose City Realty Group',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Stacey O''Connell-Windermere - Real Estate Agents"]',
    1,
    'http://portlandloftscondos.com/',
    NULL,
    '(503) 764-9440',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-203',
    'Stacey O''Connell-Windermere',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://www.windermere.com/directory/offices/portland-nw-johnson',
    NULL,
    '(503) 319-1870',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-204',
    'RE/MAX Professional Associates',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Moyer Enterprises - Real Estate Agents"]',
    1,
    'http://cs.com/',
    NULL,
    '(508) 347-9595',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-205',
    'Moyer Enterprises',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate","Real Estate Management","!Ink Realty - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 241-4132',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-206',
    'Ink Realty',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Blue Sky Real Estate - Real Estate Agents"]',
    1,
    'http://inkrealtyhomes.com/',
    NULL,
    '(503) 505-9859',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-207',
    'Blue Sky Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Serpico Realty Inc - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 223-6611',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-208',
    'Serpico Realty Inc',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Home Vestors Of America - Real Estate Agents"]',
    1,
    'https://www.homesnap.com/homes/for_sale/Oregon/c_44.043225,-122.071528/z_7',
    NULL,
    '(850) 942-0500',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-209',
    'Home Vestors Of America',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Place Real Estate - Real Estate Agents"]',
    1,
    'http://homevestors.com/',
    NULL,
    '(503) 233-1310',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-210',
    'Place Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management"]',
    1,
    NULL,
    NULL,
    '(503) 709-0802',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-211',
    'Home Vestors Of America',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Place Real Estate - Real Estate Agents"]',
    1,
    'http://homevestors.com/',
    NULL,
    '(503) 233-1310',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-212',
    'Place Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","!Wendy Boso - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 709-0802',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-213',
    'Wendy Boso',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://www.wendyboso.com/',
    NULL,
    '(971) 221-3387',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  );