INSERT INTO businesses (
      id, name, city, state, industry, services, verified, website, 
      yearsInBusiness, phone, address, email, rating, reviewCount, 
      licenseNumber, bbbRating, emergencyService
    ) VALUES (
    'medford-LawFirms-34',
    'Mayerle, Michael J, ATY',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Estate Planning Attorneys","!Kellerman, Joseph E, ATY - Attorneys"]',
    1,
    'https://www.roguelaw.com/michael-j-mayerle',
    NULL,
    '(541) 779-8900',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-35',
    'Kellerman, Joseph E, ATY',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Vanderhoof, Ryan J, ATY - Attorneys"]',
    1,
    'https://www.roguelaw.com/joseph-e-kellerman',
    NULL,
    '(541) 779-8900',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-36',
    'Vanderhoof, Ryan J, ATY',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Button, Melisa A, ATY - Attorneys"]',
    1,
    'https://www.roguelaw.com/ryan-j-vanderhoof',
    NULL,
    '(541) 779-8900',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-37',
    'Button, Melisa A, ATY',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Blackhurst, John, ATY - Attorneys"]',
    1,
    'https://www.roguelaw.com/melisa-a-button',
    NULL,
    '(541) 779-8900',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-38',
    'Blackhurst, John, ATY',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Shane J Antholz Attorney - Attorneys"]',
    1,
    'https://www.roguelaw.com/john-blackhurst',
    NULL,
    '(541) 779-8900',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-39',
    'Shane J Antholz Attorney',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Bolen, Charles E, ATTY - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 779-8900',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-40',
    'Bolen, Charles E, ATTY',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Two Rivers Legal - Attorneys"]',
    1,
    'https://www.roguelaw.com/charles-e-bolen',
    NULL,
    '(541) 779-8900',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-41',
    'Two Rivers Legal',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Law Office of Shane Reed - Attorneys"]',
    1,
    'https://tworiverslegal.com/',
    NULL,
    '(541) 500-2635',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-42',
    'Law Office of Shane Reed',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","General Practice Attorneys","!Angie Lanier - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 772-3266',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-43',
    'Angie Lanier',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Yesquen Law - Attorneys"]',
    1,
    'http://angielanierlaw.com/',
    NULL,
    '(541) 770-7407',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-44',
    'Yesquen Law',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Accident & Property Damage Attorneys","Legal Service Plans","!Burkhalter, Mark W, JD - Attorneys"]',
    1,
    'http://www.yesquenlaw.com/',
    NULL,
    '(541) 816-4888',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-45',
    'Burkhalter, Mark W, JD',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Jackson County Public Defender - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 857-0932',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-46',
    'Jackson County Public Defender',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Legal Service Plans","!Engle, Douglas M - Attorneys"]',
    1,
    'http://www.osbar.org/',
    NULL,
    '(541) 779-5636',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-47',
    'Engle, Douglas M',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Legal Service Plans"]',
    1,
    NULL,
    NULL,
    '(541) 770-1187',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-48',
    'Law Office of Christopher Missiaen PC',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","General Practice Attorneys","!John C Howry Law Office PC - Attorneys"]',
    1,
    'http://missiaenlaw.com/',
    NULL,
    '(541) 494-0024',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-49',
    'John C Howry Law Office PC',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","General Practice Attorneys","!Vance M Waliser Attorney - Attorneys"]',
    1,
    'https://www.howrylaw.com/about',
    NULL,
    '(541) 816-4444',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-50',
    'Vance M Waliser Attorney',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","General Practice Attorneys","Criminal Law Attorneys","!Judicary Courts of the State Ore - Attorneys"]',
    1,
    NULL,
    29,
    '(541) 772-6914',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-51',
    'Judicary Courts of the State Ore',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!United States Government Oregon - Attorneys"]',
    1,
    'http://oregon.gov/',
    NULL,
    '(541) 776-7171',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-52',
    'United States Government Oregon',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Sarparast, Yaschar, JD - Attorneys"]',
    1,
    'http://www.medfordpd.com/',
    NULL,
    '(541) 776-3630',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-53',
    'Sarparast, Yaschar, JD',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Criminal Law Attorneys","Immigration Law Attorneys","!Billin Rich Attorney At Law - Attorneys"]',
    1,
    'http://sarpa-law.com/',
    NULL,
    '(541) 772-8635',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-54',
    'Billin Rich Attorney At Law',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Real Estate Buyer Brokers","!Annand Megan - Attorneys"]',
    1,
    NULL,
    34,
    '(541) 776-9900',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-55',
    'Annand Megan',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 779-7139',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-56',
    'The Law Office of Garren Pedemonte, PC',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Corporation & Partnership Law Attorneys","General Practice Attorneys","!Larry B Workman Attorney - Attorneys"]',
    1,
    'http://www.pedemontelaw.com/',
    NULL,
    '(541) 772-3080',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-57',
    'Larry B Workman Attorney',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Womack Law - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 858-8171',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-58',
    'Womack Law',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Moro, Tonia, ATY - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 326-6460',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-59',
    'Moro, Tonia, ATY',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Stone Robert M - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 973-2063',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-60',
    'Stone Robert M',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","The Law Offices of Michael P Bertholf","General Practice Attorneys","!Kerr Larry L - Attorneys"]',
    1,
    'http://lawofficemedford.com/',
    30,
    '(541) 734-4093',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-61',
    'Kerr Larry L',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Kellington Michael Attorney - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 779-8267',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-62',
    'Kellington Michael Attorney',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Michael P Vanderhoff Attorney - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 779-8267',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-63',
    'Michael P Vanderhoff Attorney',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Caplan Carl - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 773-1222',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-64',
    'Caplan Carl',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Legal Service Plans","!The Law Office of Justin Rosas - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 773-1672',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-65',
    'The Law Office of Justin Rosas',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Criminal Law Attorneys","DUI & DWI Attorneys","!Jason Caplan Law Office - Attorneys"]',
    1,
    'https://www.southernoregondefense.com/',
    NULL,
    '(541) 933-5972',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-66',
    'Jason Caplan Law Office',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Orf David M - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 773-1672',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-67',
    'Orf David M',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!McNair, Charles, ATTY - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 773-6790',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-68',
    'McNair, Charles, ATTY',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Divorce Attorneys","Business Law Attorneys","!Stout Law - Attorneys"]',
    1,
    NULL,
    66,
    '(541) 779-4075',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-69',
    'Stout Law',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Legal Service Plans","!Attorney Don Scales - Attorneys"]',
    1,
    'http://stoutoregonlaw.com/',
    NULL,
    '(541) 776-2020',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-70',
    'Attorney Don Scales',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Bill Schireman Law - Attorneys"]',
    1,
    'http://www.medfordattorney.com/',
    NULL,
    '(541) 772-2363',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-71',
    'Bill Schireman Law',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Family Law Attorneys","Legal Service Plans","!Boehmer, Colette, ATTY - Attorneys"]',
    1,
    'http://www.billschiremanlaw.com/',
    42,
    '(541) 779-4076',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-72',
    'Boehmer, Colette, ATTY',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Family Law Attorneys","Adoption Law Attorneys","!Debbie Vincent Attorney - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 779-7552',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-73',
    'Debbie Vincent Attorney',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Abel Robert L Attorneys at Law - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 772-3288',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-74',
    'Abel Robert L Attorneys at Law',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Guy Michael S - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 857-1778',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-75',
    'Guy Michael S',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Legal Service Plans","!William Francis PC - Attorneys"]',
    1,
    NULL,
    33,
    '(541) 770-3347',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-76',
    'William Francis PC',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Steel, Margaret, JD - Attorneys"]',
    1,
    'https://www.williamfrancis.com/dui-index/more-about-diversion',
    NULL,
    '(541) 773-4000',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-77',
    'Steel, Margaret, JD',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Snelling, Derek, ATTY - Attorneys"]',
    1,
    'http://www.letusfightforyou.com/',
    NULL,
    '(541) 210-8657',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-78',
    'Snelling, Derek, ATTY',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Personal Injury Law Attorneys","Insurance Attorneys","!Potter, Christopher, JD - Attorneys"]',
    1,
    'https://letusfightforyou.com/our-attorneys/derek-snelling',
    NULL,
    '(541) 779-7955',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-79',
    'Potter, Christopher, JD',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!John P Eckrem Law Office - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 210-8657',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-80',
    'John P Eckrem Law Office',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","General Practice Attorneys","!Michael W. Franell, Attorney at Law - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 326-0006',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-81',
    'Michael W. Franell, Attorney at Law',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!The Law Office of Keith Y Boyd - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 646-4111',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-82',
    'The Law Office of Keith Y Boyd',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","General Practice Attorneys","!TDC Family Law - Attorneys"]',
    1,
    'http://www.boydlegal.net/',
    NULL,
    '(541) 973-2422',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-83',
    'TDC Family Law',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Whitmire, Jake R - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 665-8485',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-84',
    'Whitmire, Jake R',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Family Law Attorneys","Divorce Attorneys","!Eplett, Alisha - Attorneys"]',
    1,
    'https://www.epgoregon.com/www-epgoregon-com-locations-html',
    NULL,
    '(541) 930-8035',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-85',
    'Eplett, Alisha',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Watson Law - Attorneys"]',
    1,
    'https://oregon.hotel-us.org/126802-alisha_llc.htm',
    NULL,
    '(458) 215-5806',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-86',
    'Watson Law',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Legal Service Plans","!Abel, Robert L, JD - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 494-2455',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-87',
    'Abel, Robert L, JD',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Legal Service Plans","!Robert Boyer Attorney - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 857-1778',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-88',
    'Robert Boyer Attorney',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Ahrendt Business Law-Est - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 734-5522',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-89',
    'Ahrendt Business Law-Est',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Merrill O''Sullivan Atty LLP - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 601-6401',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-90',
    'Merrill O''Sullivan Atty LLP',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys"]',
    1,
    'https://mosattorneys.com/',
    NULL,
    '(541) 773-5150',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-91',
    'Law Offices of Robert W. Boyer, Attorney at Law',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Legal Service Plans","!Minder, Debbie V, JD - Attorneys"]',
    1,
    'http://robertboyerlaw.com/',
    NULL,
    '(541) 474-6271',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-92',
    'Minder, Debbie V, JD',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Tara Millan Law Firm - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 772-3288',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-93',
    'Tara Millan Law Firm',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","General Practice Attorneys","!Feinberg, Jeni, ATY - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 772-3422',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-94',
    'Feinberg, Jeni, ATY',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","General Practice Attorneys","Criminal Law Attorneys","!The Law Office of Justin Rosas - Attorneys"]',
    1,
    'http://www.jenifeinberg.com/',
    29,
    '(541) 779-8916',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-95',
    'The Law Office of Justin Rosas',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Criminal Law Attorneys","DUI & DWI Attorneys","!Sutton, Matthew, ATY - Attorneys"]',
    1,
    'http://www.southernoregondefense.com/',
    NULL,
    '(541) 933-5972',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-96',
    'Sutton, Matthew, ATY',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","General Practice Attorneys","Appellate Practice Attorneys","!Renee Ledbetter - Attorneys"]',
    1,
    'https://matthewsuttonlaw.com/articles_links/index.html',
    33,
    '(541) 772-8050',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-97',
    'Renee Ledbetter',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Beacon Immigration - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 499-0571',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-98',
    'Beacon Immigration',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Legal Service Plans","!Robertson, Bob, ATTY - Attorneys"]',
    1,
    NULL,
    NULL,
    '(458) 225-9858',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-99',
    'Robertson, Bob, ATTY',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Carini Francis - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 772-3442',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-100',
    'Carini Francis',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Huttl John R Attorney At Law - Attorneys"]',
    1,
    'http://williamfrancis.com/',
    NULL,
    '(541) 776-1236',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-101',
    'Huttl John R Attorney At Law',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Dennis H Black Attorney - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 779-6738',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-102',
    'Dennis H Black Attorney',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Thomas N Petersen Attorney - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 772-9850',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-103',
    'Thomas N Petersen Attorney',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Robert F Webber Attorney - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 772-9850',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-104',
    'Robert F Webber Attorney',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Robert L Chapman Attorney - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 772-9850',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-105',
    'Robert L Chapman Attorney',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Frederick H Lundblade Attorney - Attorneys"]',
    1,
    'http://www.blackchapman.com/',
    NULL,
    '(541) 772-9850',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-106',
    'Frederick H Lundblade Attorney',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Kelly L Andersen PC Attorney - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 772-9850',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-107',
    'Kelly L Andersen PC Attorney',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Faith M Morse Attorney - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 773-7000',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-108',
    'Faith M Morse Attorney',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Barry N Shaw Attorney - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 773-7000',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-109',
    'Barry N Shaw Attorney',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Lucky Jonathan ESQ - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 773-6855',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-110',
    'Lucky Jonathan ESQ',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Kollie Law Group - Attorneys"]',
    1,
    NULL,
    48,
    '(541) 773-8394',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-111',
    'Kollie Law Group',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Personal Injury Law Attorneys","Criminal Law Attorneys","!Michael Brian Attorney - Attorneys"]',
    1,
    'http://www.kollielaw.com/',
    NULL,
    '(541) 227-2266',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-112',
    'Michael Brian Attorney',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Smith Jeffrey H - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 772-1334',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-113',
    'Smith Jeffrey H',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Steven P Pickens Attorney - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 772-0319',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-114',
    'Steven P Pickens Attorney',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Wilkens, Brent - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 772-1784',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-115',
    'Wilkens, Brent',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Tracy M McGovern Attorney - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 779-2333',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-116',
    'Tracy M McGovern Attorney',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Hornecker Cowling LLP - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 779-2333',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-117',
    'Hornecker Cowling LLP',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Shleinger & Devillenue - Attorneys"]',
    1,
    'http://www.roguelaw.com/',
    27,
    '(541) 779-8900',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-118',
    'Shleinger & Devillenue',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Legal Service Plans","!Lundblade Injury Law - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 973-2595',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-119',
    'Lundblade Injury Law',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!The Paulsen Group - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 200-6313',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-120',
    'The Paulsen Group',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Patrick G Huycke Attorney - Attorneys"]',
    1,
    'http://paulsen.com/',
    NULL,
    '(541) 773-6000',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-121',
    'Patrick G Huycke Attorney',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Jarvis Dreyer Glatte & Larsen LLP - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 772-1977',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-122',
    'Jarvis Dreyer Glatte & Larsen LLP',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Business Litigation Attorneys","Trust Companies","!Charles Kochlacs Attorney - Attorneys"]',
    1,
    'http://www.medfordlaw.net/',
    50,
    '(541) 772-1977',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-123',
    'Charles Kochlacs Attorney',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Dahlin, Lewis W, JD - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 608-9122',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-124',
    'Dahlin, Lewis W, JD',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Robert Stone Attorney at Law PC - Attorneys"]',
    1,
    'http://fosterdenman.com/',
    NULL,
    '(541) 770-5466',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-125',
    'Robert Stone Attorney at Law PC',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Criminal Law Attorneys","Family Law Attorneys","!Deborah K. Vincent - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 734-4093',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-126',
    'Deborah K. Vincent',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Herson, Alan R - Attorneys"]',
    1,
    'https://www.oregonlawyeronline.com/',
    NULL,
    '(541) 840-0479',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-127',
    'Herson, Alan R',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","!Pedrojetti, James J, ATTY - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 770-1372',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-128',
    'Pedrojetti, James J, ATTY',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Family Law Attorneys","Business Law Attorneys"]',
    1,
    'http://davispedrojettilaw.com/',
    NULL,
    '(541) 842-2139',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-129',
    'Shlesinger & deVilleneuve Attorneys PC',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Social Security & Disability Law Attorneys","Accident & Property Damage Attorneys","!Jamie L Hazlett LLC - Divorce Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 779-7955',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-130',
    'Jamie L Hazlett LLC',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Divorce Attorneys","Family Law Attorneys"]',
    1,
    'http://www.divorcelawyermedfordoregon.com/',
    16,
    '(541) 773-3619',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-131',
    'Arant & Broesder',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Wills, Trusts & Estate Planning Attorneys","Elder Law Attorneys"]',
    1,
    'http://www.broesderlaw.com/',
    NULL,
    '(541) 773-1222',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-132',
    'Zach Light',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Social Security & Disability Law Attorneys","Legal Service Plans"]',
    1,
    NULL,
    13,
    '(541) 494-0355',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-133',
    'Wickre James A Attorney',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Corporation & Partnership Law Attorneys","Business Law Attorneys","!Stark and Hammack, PC - Probate Law Attorneys"]',
    1,
    'http://www.jameswickre.com/',
    51,
    '(541) 772-3371',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  );