INSERT INTO businesses (
      id, name, city, state, industry, services, verified, website, 
      yearsInBusiness, phone, address, email, rating, reviewCount, 
      licenseNumber, bbbRating, emergencyService
    ) VALUES (
    'grantspass-General-Contractors-115',
    'Kenneth Richard Lucrezi',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Michael Depuglia - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 218-7686',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-116',
    'Michael Depuglia',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!House Calls Home Improvement - Home Improvements"]',
    1,
    NULL,
    NULL,
    '(541) 659-3300',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-117',
    'House Calls Home Improvement',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Improvements","Sunrooms & Solariums","!Bill Davis Roofing - Roofing Contractors"]',
    1,
    NULL,
    44,
    '(541) 472-5022',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-118',
    'Bill Davis Roofing',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Roofing Contractors","Home Builders","!First Response Restoration - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 476-0751',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-119',
    'First Response Restoration',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Brad Fox Roofing - Roofing Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 476-3995',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-120',
    'Brad Fox Roofing',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Roofing Contractors","Home Improvements","!Aaron Scott Johnson - Home Builders"]',
    1,
    'http://www.bradfoxroofing.com/',
    NULL,
    '(541) 660-6890',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-121',
    'Aaron Scott Johnson',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Scott Hendrickson - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 218-3429',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-122',
    'Scott Hendrickson',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Spectrum Design LLP - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 450-5063',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-123',
    'Spectrum Design LLP',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Jefferson Stanley Reed - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 659-8362',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-124',
    'Jefferson Stanley Reed',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Travco Incorporated - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 659-4108',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-125',
    'Travco Incorporated',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!All Right Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 660-3837',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-126',
    'All Right Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Home Improvements","!Beacon Construction - General Contractors"]',
    1,
    NULL,
    44,
    '(541) 479-9712',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-127',
    'Beacon Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","!Reel Construction Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 660-5957',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-128',
    'Reel Construction Inc',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!A New Hope Contracting - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 956-9180',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-129',
    'A New Hope Contracting',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Patio Builders"]',
    1,
    NULL,
    NULL,
    '(541) 337-2683',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-130',
    'Northwest Construction Est. Inc.',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Home Improvements","!Chapman Kirk Construction - General Contractors"]',
    1,
    NULL,
    48,
    '(541) 476-3029',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-131',
    'Chapman Kirk Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!Ed-Craft Construction - General Contractors"]',
    1,
    NULL,
    43,
    '(541) 660-1995',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-132',
    'Ed-Craft Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Home Improvements","!Northridge Homes - General Contractors"]',
    1,
    NULL,
    37,
    '(541) 218-8871',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-133',
    'Northridge Homes',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Home Builders","!Gladstone construction - General Contractors"]',
    1,
    'http://www.northridgehomesgp.com/',
    NULL,
    '(541) 472-1100',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-134',
    'Gladstone construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","!Crater Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 441-4330',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-135',
    'Crater Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Excavation Contractors","Tree Service","!Local Exterior Services - General Contractors"]',
    1,
    'https://craterconstruction.com/',
    4,
    '(541) 218-5778',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-136',
    'Local Exterior Services',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Tree Service","Excavation Contractors"]',
    1,
    'https://www.lexser.us/',
    NULL,
    '(541) 226-4256',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-137',
    'Southern Oregon Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!Fackrell''s Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 955-1818',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-138',
    'Fackrell''s Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Drywall Contractors","Home Builders","!Trautwein Construction Inc - General Contractors"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 218-3206',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-139',
    'Trautwein Construction Inc',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!SCB Quality Builders - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 471-8024',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-140',
    'SCB Quality Builders',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 659-9656',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-141',
    'Dale Woodruff Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors","!Calvary Construction - General Contractors"]',
    1,
    'https://woodruffconstruction.com/contact-us',
    NULL,
    '(541) 476-5862',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-142',
    'Calvary Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!White Jaysen Allen - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 659-4260',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-143',
    'White Jaysen Allen',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","!Accurate Construction Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 761-0709',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-144',
    'Accurate Construction Inc',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 244-1135',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-145',
    'Charley Soares Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors-Commercial & Industrial"]',
    1,
    NULL,
    NULL,
    '(541) 660-6247',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-146',
    'Tobey & Heinen Fine Homes Inc',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!Reel Construction Inc - General Contractors"]',
    1,
    'http://www.tobeydesign.com/',
    NULL,
    '(541) 862-2967',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-147',
    'Reel Construction Inc',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Homeadvisor - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 659-4490',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-148',
    'Homeadvisor',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Air Conditioning Contractors & Systems","Heating Contractors & Specialties","!Quigley Construction - General Contractors"]',
    1,
    'http://www.homeadvisor.com/YP',
    NULL,
    '(877) 492-2429',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-149',
    'Quigley Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers"]',
    1,
    NULL,
    NULL,
    '(541) 761-4049',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-1',
    'Holmbeck Law LLC',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Private Investigators & Detectives","Elder Law Attorneys","!Law Office of Rebecca Whitney-Smith - Attorneys"]',
    1,
    'https://holmbecklaw.com/',
    18,
    '(541) 787-4460',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-2',
    'Law Office of Rebecca Whitney-Smith',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Medical Malpractice Attorneys","Child Custody Attorneys","!Penny Lee Austin, Attorney - Attorneys"]',
    1,
    'http://www.whitneysmithlaw.com/',
    27,
    '(541) 238-2986',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-3',
    'Penny Lee Austin, Attorney',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Elder Law Attorneys","Wills, Trusts & Estate Planning Attorneys","!Legal Aid Legal Services Corp - Attorneys"]',
    1,
    'http://www.pennyleeaustin.com/',
    44,
    '(541) 210-8141',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-4',
    'Legal Aid Legal Services Corp',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Legal Document Assistance","Paralegals"]',
    1,
    'http://legalaiddocumentservicesinc.com/',
    19,
    '(844) 330-7981',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-5',
    'Social Security Disability Advisors',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Social Security & Disability Law Attorneys","Contact Us"]',
    1,
    'http://www.disabilityadvisors.com/',
    39,
    '(888) 372-7758',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-6',
    'Dwyer Williams Potter Attorneys LLP Atty',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","General Practice Attorneys","!Sorenson, Ransom, & Ferguson, LLP - Attorneys"]',
    1,
    'http://www.roydwyer.com/',
    NULL,
    '(541) 471-8994',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-7',
    'Sorenson, Ransom, & Ferguson, LLP',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","!Brett Claar Attorny of Law - Attorneys"]',
    1,
    'http://www.roguevalleylaw.com/',
    NULL,
    '(541) 476-3883',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-8',
    'Brett Claar Attorny of Law',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","!Dagradi, Rosalind, ATTY - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 479-3129',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-9',
    'Dagradi, Rosalind, ATTY',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Legal Service Plans","Family Law Attorneys","!Kelly L Andersen - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 479-1100',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-10',
    'Kelly L Andersen',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Accident & Property Damage Attorneys","General Practice Attorneys","!Law Office of Michael Cougar - Attorneys"]',
    1,
    'http://www.andersenlaw.com/',
    46,
    '(541) 476-6623',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-11',
    'Law Office of Michael Cougar',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Notaries Public","Estate Planning, Probate, & Living Trusts","!Black  Chapman Petersen & Stevens - Attorneys"]',
    1,
    'https://michaelcougar.com/',
    40,
    '(541) 295-8780',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-12',
    'Black Chapman Petersen & Stevens',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys"]',
    1,
    'https://blackchapman.com/',
    NULL,
    '(541) 772-9850',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-13',
    'Southern Oregon Special Education Advocacy',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Disability Services","Training Consultants","!Peterson Rebecca - Attorneys"]',
    1,
    NULL,
    12,
    '(808) 284-7463',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-14',
    'Peterson Rebecca',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Wills, Trusts & Estate Planning Attorneys","!Josephine County Defense Lawyers Inc - Attorneys"]',
    1,
    'http://www.rebeccapetersonlaw.com/',
    28,
    '(541) 472-5291',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-15',
    'Josephine County Defense Lawyers Inc',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Criminal Law Attorneys","Domestic Violence Attorneys","!Whitmire Jake R. - Attorneys"]',
    1,
    'https://www.josephinecounty.gov/searchresults.asp',
    42,
    '(541) 479-3674',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-16',
    'Whitmire Jake R.',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Legal Service Plans","!Steven Groh Attorney - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 474-0880',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-17',
    'Steven Groh Attorney',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","!Richard K Lane PC - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 955-8000',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-18',
    'Richard K Lane PC',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","!Robert A Graham Jr Attorney at Law - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 476-1108',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-19',
    'Robert A Graham Jr Attorney at Law',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","!Graham and Brown Attys - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 472-1625',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-20',
    'Graham and Brown Attys',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","General Practice Attorneys","!Rebecca Peterson Attorney - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 474-0234',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-21',
    'Rebecca Peterson Attorney',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","!Bain Robert S PC Atty - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 472-5291',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-22',
    'Bain Robert S PC Atty',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Criminal Law Attorneys","!Ransom, Willard L, ATTY - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 472-5059',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-23',
    'Ransom, Willard L, ATTY',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Patent, Trademark & Copyright Law Attorneys","!Ferguson, Kendell H, ATTY - Attorneys"]',
    1,
    'http://roguevalleylaw.com/',
    NULL,
    '(541) 476-3883',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-24',
    'Ferguson, Kendell H, ATTY',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Business Law Attorneys","Real Estate Attorneys","!E Reade John Attorney at Law - Attorneys"]',
    1,
    'http://roguevalleylaw.com/',
    NULL,
    '(541) 476-3883',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-25',
    'E Reade John Attorney at Law',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","!Mary Attorney Landers at Law - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 476-5353',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-26',
    'Mary Attorney Landers at Law',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","!Oregon Law Center - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 956-9922',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-27',
    'Oregon Law Center',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","General Practice Attorneys","Arbitration Services","!Gene Farmer Attorney - Attorneys"]',
    1,
    'https://oregonlawcenter.org/how-to-get-help/olc-offices/grants-pass',
    NULL,
    '(541) 476-1058',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-28',
    'Gene Farmer Attorney',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Legal Service Plans","!John E Reade Law Office - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 474-0567',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-29',
    'John E Reade Law Office',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Bankruptcy Services","!Preslar, Holly A, ATTY - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 476-5353',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-30',
    'Preslar, Holly A, ATTY',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Criminal Law Attorneys","Family Law Attorneys","!Day, Gregory T, ATTY - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 474-6200',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-31',
    'Day, Gregory T, ATTY',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Family Law Attorneys","Divorce Attorneys","!Clyde, Carl A, JD - Attorneys"]',
    1,
    'http://roguefirm.com/',
    44,
    '(541) 476-6627',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-32',
    'Clyde, Carl A, JD',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","!Matthew G Galli Attorney - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 476-6627',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-33',
    'Matthew G Galli Attorney',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","!John E Davis Attorney - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 476-6627',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-34',
    'John E Davis Attorney',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","!Richard D Adams Attorney - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 476-6627',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-35',
    'Richard D Adams Attorney',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","!Frank C. Rote, III - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 476-6627',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-36',
    'Frank C. Rote, III',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","!Dan Hughes Attorney - Attorneys"]',
    1,
    'https://southernoregonlawyer.com/',
    64,
    '(541) 479-2678',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-37',
    'Dan Hughes Attorney',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","!Hayward, Jason D - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 479-2678',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-38',
    'Hayward, Jason D',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","!Roy Dwyer Attorney - Attorneys"]',
    1,
    'http://www.jdhaywardlaw.com/',
    NULL,
    '(541) 476-9000',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-39',
    'Roy Dwyer Attorney',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","General Practice Attorneys","Legal Service Plans","!Sara Angeletti Law Offices - Attorneys"]',
    1,
    NULL,
    22,
    '(541) 471-8994',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-40',
    'Sara Angeletti Law Offices',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","!Shack, Emily, ATTY - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 955-8000',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-41',
    'Shack, Emily, ATTY',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Labor & Employment Law Attorneys","Personal Injury Law Attorneys","!Linthorst, David J, ATY - Attorneys"]',
    1,
    'http://letusfightforyou.com/',
    NULL,
    '(541) 474-6605',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-42',
    'Linthorst, David J, ATY',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","!Boyer Robert W - Attorneys"]',
    1,
    'https://andersenlaw.com/',
    NULL,
    '(541) 773-7000',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-43',
    'Boyer Robert W',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Legal Service Plans","!Robertson Tori - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 474-6271',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-44',
    'Robertson Tori',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Insurance","!Holt, Heather L, ATY - Attorneys"]',
    1,
    'http://www.boeckinsurance.com/',
    NULL,
    '(541) 476-2937',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-45',
    'Holt, Heather L, ATY',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Labor & Employment Law Attorneys","Social Security & Disability Law Attorneys","!Dagradi Rosalind A - Attorneys"]',
    1,
    'https://www.heatherlholtattorney.com/',
    NULL,
    '(541) 955-1690',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-46',
    'Dagradi Rosalind A',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Legal Service Plans","!Jake R Whitmire Attorney - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 479-1100',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-47',
    'Jake R Whitmire Attorney',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","!Rolfe Law Office P - Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 474-0880',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-48',
    'Rolfe Law Office P',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","!Dole Sorenson Ransom - Attorneys"]',
    1,
    NULL,
    NULL,
    '(509) 876-0002',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-49',
    'Dole Sorenson Ransom',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Legal Service Plans","!Stevens, A, ATTY - Attorneys"]',
    1,
    'http://www.roguevalleylaw.com/',
    NULL,
    '(541) 476-3883',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-50',
    'Stevens, A, ATTY',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Personal Injury Law Attorneys","Insurance Attorneys","!Carnahan Court - Attorneys"]',
    1,
    'http://blackchapman.com/',
    NULL,
    '(541) 474-3374',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-51',
    'Carnahan Court',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Legal Service Plans"]',
    1,
    NULL,
    NULL,
    '(541) 471-6363',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-52',
    'Cauble, Furr & Beguin, LLP',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Estate Planning Attorneys","Family Law Attorneys","!Myrick Lynn M - General Practice Attorneys"]',
    1,
    'https://www.thecaublefirm.com/?npcmp=dir:local:2604444:97526',
    NULL,
    '(541) 507-6407',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-53',
    'Myrick Lynn M',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","General Practice Attorneys","Family Law Attorneys"]',
    1,
    'http://www.myricklawfirm.com/',
    50,
    '(541) 479-5444',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-54',
    'Day, Driver, Fournier & Reinhart, LLP',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Bankruptcy Law Attorneys","Criminal Law Attorneys"]',
    1,
    'http://roguefirm.com/',
    NULL,
    '(541) 476-6627',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-55',
    'Heather L. Holt Attorney at Law',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Social Security & Disability Law Attorneys","General Practice Attorneys"]',
    1,
    'http://heatherlholtattorney.com/',
    30,
    '(541) 955-1690',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-56',
    'Olsen Daines',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Social Security & Disability Law Attorneys","Bankruptcy Law Attorneys"]',
    1,
    'https://olsendaines.com/',
    NULL,
    '(541) 471-1043',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-57',
    'Black Chapman Petersen & Stevens - Grants Pass Office',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Elder Law Attorneys","Family Law Attorneys"]',
    1,
    'https://www.blackchapman.com/',
    NULL,
    '(541) 474-3374',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-58',
    'Josephine County Clerk''s Office',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","County & Parish Government"]',
    1,
    'http://www.co.josephine.or.us/',
    NULL,
    '(541) 474-5243',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-59',
    'Law Office of Michael Jeskey-Cougar',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","General Practice Attorneys","Legal Service Plans","!Cumming Deborah K - Criminal Law Attorneys"]',
    1,
    'http://www.michaelcougar.com/',
    NULL,
    '(541) 956-6886',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-60',
    'Cumming Deborah K',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Criminal Law Attorneys","Legal Service Plans","!Browne Claudia E - Legal Service Plans"]',
    1,
    NULL,
    NULL,
    '(541) 479-2210',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-61',
    'Browne Claudia E',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Legal Service Plans","!Simcoe Daniel Atty - Arbitration Services"]',
    1,
    NULL,
    NULL,
    '(541) 474-0234',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-62',
    'Simcoe Daniel Atty',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Arbitration Services","Mediation Services","!Lansing Mark - General Practice Attorneys"]',
    1,
    'http://danielsimcoe.com/',
    35,
    '(541) 474-1162',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-63',
    'Lansing Mark',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","General Practice Attorneys","!Kirchoff Law - Legal Service Plans"]',
    1,
    NULL,
    NULL,
    '(541) 471-9239',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-64',
    'Kirchoff Law',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Legal Service Plans","!Preslar Holly A - Legal Service Plans"]',
    1,
    NULL,
    NULL,
    '(541) 479-4749',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-65',
    'Preslar Holly A',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Legal Service Plans"]',
    1,
    NULL,
    NULL,
    '(541) 474-6200',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  );