INSERT INTO businesses (
      id, name, city, state, industry, services, verified, website, 
      yearsInBusiness, phone, address, email, rating, reviewCount, 
      licenseNumber, bbbRating, emergencyService
    ) VALUES (
    'salem-Electricians-14',
    'All Electric',
    'Salem',
    'OR',
    'electricians',
    '["Electricians","Electric Companies","Electric Equipment & Supplies"]',
    1,
    'http://allelectricsalem.com/',
    NULL,
    '(503) 851-1704',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Electricians-15',
    'Portland General Electric Co',
    'Salem',
    'OR',
    'electricians',
    '["Electric Companies"]',
    1,
    'https://portlandgeneral.com/',
    NULL,
    '(503) 399-7717',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Electricians-16',
    'Oregon Rural Electric Cooperative Association',
    'Salem',
    'OR',
    'electricians',
    '["Electric Companies","!North Coast Electric - Electric Companies"]',
    1,
    'http://www.oreca.org/',
    NULL,
    '(971) 915-1660',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Electricians-17',
    'North Coast Electric',
    'Salem',
    'OR',
    'electricians',
    '["Electric Companies"]',
    1,
    'https://www.northcoast.com/',
    NULL,
    '(503) 363-9251',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Electricians-18',
    'Electronic Power Conditioning',
    'Salem',
    'OR',
    'electricians',
    '["Electric Companies","!B&O Electric - Electricians"]',
    1,
    NULL,
    NULL,
    '(503) 587-5200',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Electricians-19',
    'B&O Electric',
    'Salem',
    'OR',
    'electricians',
    '["Electricians","!Fuse Electric - Electricians"]',
    1,
    NULL,
    NULL,
    '(503) 832-6704',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Electricians-20',
    'Fuse Electric',
    'Salem',
    'OR',
    'electricians',
    '["Electricians","!Shiloh Electric - Electricians"]',
    1,
    NULL,
    NULL,
    '(971) 701-6287',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Electricians-21',
    'Shiloh Electric',
    'Salem',
    'OR',
    'electricians',
    '["Electricians","!Electrical Installations - Electricians"]',
    1,
    'http://www.cbs.state.or.us/bcd',
    NULL,
    '(503) 588-9205',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Electricians-22',
    'Electrical Installations',
    'Salem',
    'OR',
    'electricians',
    '["Electricians","!Eoff Electric - Electricians"]',
    1,
    NULL,
    NULL,
    '(503) 967-9542',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Electricians-23',
    'Eoff Electric',
    'Salem',
    'OR',
    'electricians',
    '["Electricians","!Seven Days Electrician - Electricians"]',
    1,
    NULL,
    NULL,
    '(503) 371-3633',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Electricians-24',
    'Seven Days Electrician',
    'Salem',
    'OR',
    'electricians',
    '["Electricians","!Doug Mansfield Electric - Electricians"]',
    1,
    NULL,
    NULL,
    '(503) 967-9475',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Electricians-25',
    'Doug Mansfield Electric',
    'Salem',
    'OR',
    'electricians',
    '["Electricians","!Safety Electric - Electricians"]',
    1,
    NULL,
    NULL,
    '(503) 990-3173',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Electricians-26',
    'Safety Electric',
    'Salem',
    'OR',
    'electricians',
    '["Electricians","!Powercompass - Electricians"]',
    1,
    NULL,
    NULL,
    '(503) 835-0565',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Electricians-27',
    'Powercompass',
    'Salem',
    'OR',
    'electricians',
    '["Electricians","!Scott Electric - Electricians"]',
    1,
    NULL,
    NULL,
    '(503) 877-0269',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Electricians-28',
    'Scott Electric',
    'Salem',
    'OR',
    'electricians',
    '["Electricians","!Cherry City Electric - Electricians"]',
    1,
    NULL,
    NULL,
    '(503) 581-1192',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Electricians-29',
    'Cherry City Electric',
    'Salem',
    'OR',
    'electricians',
    '["Electricians","!Garner Electric Salem - Electricians"]',
    1,
    'http://cherrycityelectric.com/',
    NULL,
    '(503) 385-8315',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Electricians-30',
    'Garner Electric Salem',
    'Salem',
    'OR',
    'electricians',
    '["Electricians"]',
    1,
    NULL,
    NULL,
    '(503) 385-1859',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-1',
    'C5 Construction LLC',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","!Bartreau Construction - General Contractors"]',
    1,
    'http://c5constructionor.com/',
    NULL,
    '(971) 374-5621',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-2',
    'Bartreau Construction',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Bathroom Remodeling","Kitchen Planning & Remodeling Service","!Black Dreams Construction - General Contractors"]',
    1,
    'https://www.bartreauconstruction.net/',
    8,
    '(541) 735-0341',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-3',
    'Black Dreams Construction',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Electricians","Altering & Remodeling Contractors","!Triple D Construction Inc. - General Contractors"]',
    1,
    'https://www.blackdreamsconstruction.com/',
    NULL,
    '(971) 462-4166',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-4',
    'Triple D Construction Inc.',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Siding Contractors","Windows-Repair, Replacement & Installation","!Western Pacific Roofing - Building Contractors"]',
    1,
    'http://www.tripledoregon.com/',
    NULL,
    '(971) 374-5538',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-5',
    'Western Pacific Roofing',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","Roofing Contractors","!Improvement Remodeling LLC - Home Improvements"]',
    1,
    'http://www.westpacroofing.com/roofing-contact-free-estimate',
    NULL,
    '(503) 588-7663',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-6',
    'Improvement Remodeling LLC',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Home Repair & Maintenance","Home Improvements","!CG Contractors - General Contractors"]',
    1,
    'http://www.improvementremodelingllc.com/',
    28,
    '(503) 515-3171',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-7',
    'CG Contractors',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","!Dalke Construction Co - General Contractors"]',
    1,
    'http://cgcontractorsllc.com/',
    NULL,
    '(503) 559-2203',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-8',
    'Dalke Construction Co',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Plumbers","Home Builders","!CD Redding Construction - General Contractors"]',
    1,
    'http://www.dalkeconstruction.com/',
    NULL,
    '(503) 585-7403',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-9',
    'CD Redding Construction',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Metal Buildings"]',
    1,
    'https://cdredding.com/',
    32,
    '(503) 581-0048',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-10',
    'Besand Custom Exteriors LLC',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","!DAR Construction INC - General Contractors"]',
    1,
    NULL,
    18,
    '(971) 388-3171',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-11',
    'DAR Construction INC',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 587-0814',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-12',
    'Phillip Hildreth Construction',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!DSL Builders - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 931-4623',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-13',
    'DSL Builders',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!Carter Contractor - General Contractors"]',
    1,
    'http://dsl-builders.com/',
    NULL,
    '(503) 363-0202',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-14',
    'Carter Contractor',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Countryman Homes - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 932-0982',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-15',
    'Countryman Homes',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Home Builders","!Geno Paintco - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 930-2024',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-16',
    'Geno Paintco',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","!Vera Construction - General Contractors"]',
    1,
    'https://www.genopaintcollc.com/',
    NULL,
    '(503) 567-5511',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-17',
    'Vera Construction',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers"]',
    1,
    NULL,
    NULL,
    '(503) 409-0905',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-18',
    'James O''Grady Custom Builder',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","!Alpha Construction - General Contractors"]',
    1,
    'https://www.jamesogradybuilder.com/',
    NULL,
    '(541) 659-2159',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-19',
    'Alpha Construction',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","Home Builders"]',
    1,
    'http://www.alpha4c.com/',
    NULL,
    '(503) 584-1184',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-20',
    'Colson & Colson General Contractor Inc',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers"]',
    1,
    'https://www.colson-colson.com/',
    62,
    '(503) 586-7401',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-21',
    'AC Framing & Construction Inc',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Barkas Construction Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 339-4280',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-22',
    'Barkas Construction Inc',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Curry Brandaw Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 932-2885',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-23',
    'Curry Brandaw Construction',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","!Tracy Teeters Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 399-1090',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-24',
    'Tracy Teeters Construction',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Applewhite Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 932-1031',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-25',
    'Applewhite Construction',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    NULL,
    NULL,
    '(971) 388-4297',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-26',
    'Martin Construction & Handyman Service',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Handyman Services","Home Builders"]',
    1,
    NULL,
    NULL,
    '(503) 931-1739',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-27',
    'Rich Duncan Construction Incorporated',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","!Gelco Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 390-4999',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-28',
    'Gelco Construction',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors-Commercial & Industrial"]',
    1,
    'https://www.gelcoconstruction.com/',
    NULL,
    '(503) 364-2638',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-29',
    'Laudette Construction & Maintenance',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors-Commercial & Industrial","!Westbuilt Corp - General Contractors"]',
    1,
    'https://www.laudetteconstruction.com/contact-us',
    NULL,
    '(503) 362-3395',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-30',
    'Westbuilt Corp',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Done Deal Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 881-9478',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-31',
    'Done Deal Construction',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Star Builders - General Contractors"]',
    1,
    'http://facebook.com/pages/done-deal-construction-llc/161153027241810',
    NULL,
    '(503) 507-3224',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-32',
    'Star Builders',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Bathroom Remodeling"]',
    1,
    'http://www.starbuildersllc.com/',
    NULL,
    '(503) 743-0405',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-33',
    'Western Construction Systems',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Drainage Contractors","Altering & Remodeling Contractors","!Righteous Renovations - General Contractors"]',
    1,
    'https://westernconstructionsystems.com/',
    NULL,
    '(503) 362-5052',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-34',
    'Righteous Renovations',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    'https://righteousrenovations.com/',
    NULL,
    '(503) 683-8355',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-35',
    'Willamette Valley Construction Group',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Owen Construction, Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 990-7547',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-36',
    'Owen Construction, Inc',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Excavation Contractors","!Granite & Cabinets Direct - General Contractors"]',
    1,
    'https://owenconstructioninc.com/',
    NULL,
    '(503) 390-6936',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-37',
    'Granite & Cabinets Direct',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","!Sunco Homes & Remodeling - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 581-6628',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-38',
    'Sunco Homes & Remodeling',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    'https://suncohomes.com/',
    47,
    '(503) 362-4848',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-39',
    'Emery and Sons Construction',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors-Commercial & Industrial","!TomCor Construction - General Contractors"]',
    1,
    'http://emeryandsons.com/',
    51,
    '(503) 588-7576',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-40',
    'TomCor Construction',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    NULL,
    22,
    '(503) 391-1905',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-41',
    'R.D Remodeling and Painting',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","!Allstate Construction Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 884-0920',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-42',
    'Allstate Construction Inc',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors-Commercial & Industrial","!Don Denning Homes - General Contractors"]',
    1,
    'http://www.allstate-construction.com/contactus.htm',
    NULL,
    '(503) 393-5885',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-43',
    'Don Denning Homes',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Strunk Family Construction - General Contractors"]',
    1,
    'http://www.artisanhomesanddesign.com/',
    NULL,
    '(503) 585-2008',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-44',
    'Strunk Family Construction',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","!Lane Gene Berkey Brewer - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 931-2937',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-45',
    'Lane Gene Berkey Brewer',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Bybee & Associates Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 507-4298',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-46',
    'Bybee & Associates Inc',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors","!Magdela Construction - General Contractors"]',
    1,
    'https://www.vivint.com/',
    NULL,
    '(503) 581-6884',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-47',
    'Magdela Construction',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","!Tek Construction Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(971) 600-5417',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-48',
    'Tek Construction Inc',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Corp Inc Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 551-2478',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-49',
    'Corp Inc Construction',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors-Commercial & Industrial","!Nemecek Construction Inc - General Contractors"]',
    1,
    'https://www.corpincconstruction.com/',
    NULL,
    '(503) 371-2453',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-50',
    'Nemecek Construction Inc',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Larson''s Painting - General Contractors"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(503) 932-9648',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-51',
    'Larson''s Painting',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Handyman Services","Spray Painting & Finishing"]',
    1,
    NULL,
    NULL,
    '(503) 551-4304',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-52',
    'Imperial Construction Services',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Kitchen Planning & Remodeling Service","!Humble Construction - General Contractors"]',
    1,
    'https://www.buildwithimperial.com/',
    NULL,
    '(971) 901-7141',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-53',
    'Humble Construction',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Cabinet Makers","!Hamilton Homes Inc - General Contractors"]',
    1,
    'https://www.humbleconstructionllc.com/',
    NULL,
    '(503) 782-7202',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-54',
    'Hamilton Homes Inc',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!Von Flue Construction Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 363-4651',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-55',
    'Von Flue Construction Inc',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Home Improvements","!Hartle Construction Inc - General Contractors"]',
    1,
    'https://vonflueconstruction.com/',
    NULL,
    '(503) 585-8054',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-56',
    'Hartle Construction Inc',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Owen Construction, Inc. - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 932-4596',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-57',
    'Owen Construction, Inc.',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Excavation Contractors","!Hoffman Construction Cams - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 390-6936',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-58',
    'Hoffman Construction Cams',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Valley Office Building - General Contractors"]',
    1,
    NULL,
    NULL,
    '(971) 273-7416',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-59',
    'Valley Office Building',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","!Rick & Jay Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 364-1380',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-60',
    'Rick & Jay Construction',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","!C B2 Construction - General Contractors"]',
    1,
    'http://www.rickandjaysconstruction.com/',
    NULL,
    '(503) 508-3131',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-61',
    'C B2 Construction',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!DSL Builders - General Contractors"]',
    1,
    'http://cbtwoconstruction.com/',
    NULL,
    '(503) 480-8700',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-62',
    'DSL Builders',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!The Robertson Building - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 363-0202',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-63',
    'The Robertson Building',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","!Mission Homes Inc - General Contractors"]',
    1,
    'http://robertsonbuildings.com/',
    NULL,
    '(503) 362-1259',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-64',
    'Mission Homes Inc',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Sloane Construction Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 949-7490',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-65',
    'Sloane Construction Inc',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!Tomcor Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 588-7043',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-66',
    'Tomcor Construction',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Woodridge Enteprises Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 391-1905',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-67',
    'Woodridge Enteprises Inc',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","!Kostenborder Contracting - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 559-9177',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-68',
    'Kostenborder Contracting',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors","!MRB Enterprises - General Contractors"]',
    1,
    'http://kostenborder.com/',
    NULL,
    '(503) 362-5490',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-69',
    'MRB Enterprises',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors-Commercial & Industrial","Building Contractors","!GR Smith Construction - General Contractors"]',
    1,
    NULL,
    28,
    '(503) 362-0812',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-70',
    'GR Smith Construction',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","!George Suniga - General Contractors"]',
    1,
    'https://grsmithconstruction.com/',
    NULL,
    '(503) 803-5029',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-71',
    'George Suniga',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!Andy Medcalf Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 581-2485',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-72',
    'Andy Medcalf Construction',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","!Timbercraft Homes Inc - General Contractors"]',
    1,
    'https://www.andymedcalfconstruction.com/contact-us',
    NULL,
    '(503) 910-7852',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-73',
    'Timbercraft Homes Inc',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!Russell Creative Group Inc - General Contractors"]',
    1,
    'http://www.timbercrafthomes.net/',
    NULL,
    '(503) 399-8880',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-74',
    'Russell Creative Group Inc',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","!Boss Studio - General Contractors"]',
    1,
    'https://www.ideabox.us/',
    NULL,
    '(503) 510-4789',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-75',
    'Boss Studio',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","!M & A Contracting - General Contractors"]',
    1,
    'http://bosscorvallis.com/',
    NULL,
    '(503) 689-1797',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-76',
    'M & A Contracting',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Olsen Homes and Renovation - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 581-6125',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-77',
    'Olsen Homes and Renovation',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 393-5067',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-78',
    'Green Path Construction Inc',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Construction Management","!Good Earth Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 798-0035',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-79',
    'Good Earth Construction',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Home Improvements","!DSL Builders - General Contractors"]',
    1,
    'https://www.goodearth-construction.com/',
    NULL,
    '(503) 990-6301',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-80',
    'DSL Builders',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Plumbers","!Leighs Construction - General Contractors"]',
    1,
    'https://www.dsl-builders.com/contact',
    NULL,
    '(503) 363-0202',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-81',
    'Leighs Construction',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Home Improvements","!Schutt Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 967-6961',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-82',
    'Schutt Construction',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","!Muirlands Corp - General Contractors"]',
    1,
    'https://www.schuttconstructionor.com/contact-us',
    NULL,
    '(503) 851-8220',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-83',
    'Muirlands Corp',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","!Hartle Construction Inc - General Contractors"]',
    1,
    'https://muirlandscorp.com/',
    NULL,
    '(503) 409-3142',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  );