INSERT INTO businesses (
      id, name, city, state, industry, services, verified, website, 
      yearsInBusiness, phone, address, email, rating, reviewCount, 
      licenseNumber, bbbRating, emergencyService
    ) VALUES (
    'salem-GeneralContractors-84',
    'Hartle Construction Inc',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","!3 Gs Construction Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 932-4596',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-85',
    '3 Gs Construction Inc',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Michael Louis Taylor - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 871-8434',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-86',
    'Michael Louis Taylor',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 428-1331',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-87',
    'Hearth Stone Construction Inc',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers"]',
    1,
    NULL,
    NULL,
    '(503) 269-6252',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-88',
    'A & E Construction Services',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Mj West Construction Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(971) 701-1104',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-89',
    'Mj West Construction Inc',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Century Constructors - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 390-9117',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-GeneralContractors-90',
    'Century Constructors',
    'Salem',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors-Commercial & Industrial"]',
    1,
    NULL,
    NULL,
    '(503) 589-9797',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-1',
    'Action Drain & Rooter Service',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","Septic Tanks & Systems","Sewer Cleaners & Repairers","!Roto-Rooter Plumbing & Water Cleanup - Plumbers"]',
    1,
    'https://www.actiondrainandrooterservice.com/',
    16,
    '(503) 400-6952',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-2',
    'Roto-Rooter Plumbing & Water Cleanup',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","Sewer Contractors","Water Heater Repair","Online Specials","!Titan Pumbing - Plumbers"]',
    1,
    'https://www.rotorooter.com/salemor/?utm_source=iyp&utm_medium=paid&utm_campaign=iyp',
    90,
    '(971) 449-0492',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-3',
    'Titan Pumbing',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","Septic Tanks & Systems","Drainage Contractors","!DoneRite Plumbing and Drain, LLC - Plumbers"]',
    1,
    'https://www.titanplumbingco.com/',
    NULL,
    '(971) 484-8801',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-4',
    'DoneRite Plumbing and Drain, LLC',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","Water Heaters","Plumbing, Drains & Sewer Consultants","!Jim''s Plumbing Trouble Shooters Inc - Plumbers"]',
    1,
    'https://www.doneriteplumbingsalem.com/',
    8,
    '(503) 278-4527',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-5',
    'Jim''s Plumbing Trouble Shooters Inc',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","Water Heaters","Water Heater Repair","!Roto-Rooter Plumbing & Water Cleanup - Plumbers"]',
    1,
    'https://jimplumbinginc.com/contact',
    27,
    '(503) 967-8605',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-6',
    'Roto-Rooter Plumbing & Water Cleanup',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Grease Traps","Online Specials","!Roto-Rooter Plumbing & Water Cleanup - Plumbers"]',
    1,
    'https://www.rotorooter.com/wilsonvilleor/?utm_source=iyp&utm_medium=paid&utm_campaign=iyp',
    90,
    '(971) 405-7736',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-7',
    'Roto-Rooter Plumbing & Water Cleanup',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","Water Heater Repair","Sewer Contractors","Online Specials","!Judson''s Inc. - Building Contractors"]',
    1,
    'https://www.rotorooter.com/portland/?utm_source=iyp&utm_medium=paid&utm_campaign=iyp',
    90,
    '(971) 314-0126',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-8',
    'Judson''s Inc.',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","Air Conditioning Contractors & Systems","Building Contractors","!Pintsize Plumbing - Plumbers"]',
    1,
    'http://www.judsonselectric.com/',
    90,
    '(503) 363-4141',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-9',
    'Pintsize Plumbing',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","!Reliable Plumbing Inc - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 990-6174',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-10',
    'Reliable Plumbing Inc',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","Water Heaters","Water Heater Repair","!Water Heater Greatwood TX - Plumbers"]',
    1,
    'http://www.reliableplumbingco.com/',
    6,
    '(503) 390-5634',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-11',
    'Water Heater Greatwood TX',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","!Lefty''s Plumbing Service - Plumbers"]',
    1,
    'http://www.waterheatergreatwood.com/',
    NULL,
    '(281) 766-3729',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-12',
    'Lefty''s Plumbing Service',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","Boiler Repair & Cleaning","Water Heater Repair","!Mr. Rooter Plumbing of Salem, OR - Plumbers"]',
    1,
    'http://leftysplumbing.com/',
    NULL,
    '(503) 507-9239',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-13',
    'Mr. Rooter Plumbing of Salem, OR',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Pumps","!Swell Plumbing - Plumbers"]',
    1,
    'https://www.mrrooter.com/salem/?cid=LSTL_MRR000259',
    55,
    '(503) 343-4685',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-14',
    'Swell Plumbing',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","Water Damage Emergency Service","!Einstein Plumbing and Heating - Plumbers"]',
    1,
    'https://swellplumbingco.com/?utm_source=google&utm_medium=organic&utm_campaign=gmb-profile-salem',
    NULL,
    '(503) 884-4072',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-15',
    'Einstein Plumbing and Heating',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","Heating Equipment & Systems-Repairing","Air Conditioning Contractors & Systems","!Henco Plumbing Services - Plumbers"]',
    1,
    'https://einsteinplumbing.com/salem-or',
    NULL,
    '(503) 837-8470',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-16',
    'Henco Plumbing Services',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","Water Damage Emergency Service","Air Conditioning Contractors & Systems","!1st Plumbers Salem Oregon - Plumbers"]',
    1,
    'https://www.hencoplumbing.com/',
    NULL,
    '(503) 395-5902',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-17',
    '1st Plumbers Salem Oregon',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","!Salem Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(971) 366-2492',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-18',
    'Salem Plumbing',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing Contractors-Commercial & Industrial","!Lefty''s Plumbing Service - Plumbers"]',
    1,
    'http://plumbersalemoregon.com/',
    NULL,
    '(503) 967-0017',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-19',
    'Lefty''s Plumbing Service',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Water Heater Repair","!Cherry City Plumbing Inc - Plumbers"]',
    1,
    'http://www.citysearch.com/profile/623306004/salem_or/lefty_s_plumbing_service_llc.html',
    NULL,
    '(503) 507-9239',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-20',
    'Cherry City Plumbing Inc',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","!Paladin Plumbing Inc - Plumbers"]',
    1,
    'http://www.cherrycityplumbing.com/',
    NULL,
    '(503) 371-6141',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-21',
    'Paladin Plumbing Inc',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","!Budget Rooter Plumbing Service - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 588-0235',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-22',
    'Budget Rooter Plumbing Service',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","!Oregon Cascade Plumbing & Heat - Plumbers"]',
    1,
    NULL,
    26,
    '(503) 362-0325',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-23',
    'Oregon Cascade Plumbing & Heat',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","!Vicon Mechanical Contractors Inc. - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 636-4431',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-24',
    'Vicon Mechanical Contractors Inc.',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","!Tip Top Plumbing Inc - Plumbers"]',
    1,
    'https://viconmechanical.com/',
    20,
    '(503) 589-7101',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-25',
    'Tip Top Plumbing Inc',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","Water Heater Repair","!Guaranteed Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 881-6724',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-26',
    'Guaranteed Plumbing',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","Air Conditioning Contractors & Systems","Heating Contractors & Specialties","!Plumbers and Steamfitters Local 290 - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 981-9414',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-27',
    'Plumbers and Steamfitters Local 290',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","!Evergreen Plumbing & Mechanical - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 581-1805',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-28',
    'Evergreen Plumbing & Mechanical',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","!Up A Creek Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 714-7004',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-29',
    'Up A Creek Plumbing',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","Building Contractors","General Contractors","!Budget Rooter Plumbing Service - Plumbers"]',
    1,
    'http://upacreekplumbingllc.com/',
    NULL,
    '(503) 999-1847',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-30',
    'Budget Rooter Plumbing Service',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers"]',
    1,
    NULL,
    20,
    '(503) 362-0325',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-31',
    'Oregon State Association of Plumbing',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","!Apprentice Plumbers Jatc - Plumbers"]',
    1,
    'https://www.orphcc.org/Contact',
    NULL,
    '(503) 557-1203',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-32',
    'Apprentice Plumbers Jatc',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","Apprenticeship Training Programs","!Salem Backflow Testing - Plumbers"]',
    1,
    'http://www.area2app.com/',
    NULL,
    '(503) 991-5203',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-33',
    'Salem Backflow Testing',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","!Provider Comfort Systems - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 551-4701',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-34',
    'Provider Comfort Systems',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","!Reliable Rooter Plumbing Co - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 581-6067',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-35',
    'Reliable Rooter Plumbing Co',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","Sewer Cleaners & Repairers","!Reliant K Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 362-8457',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-36',
    'Reliant K Plumbing',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","!River City Excavation Inc - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 999-2203',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-37',
    'River City Excavation Inc',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","!Plumbers Northwest Inc - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 365-0459',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-38',
    'Plumbers Northwest Inc',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","!Cortez Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 364-2896',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-39',
    'Cortez Plumbing',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing Contractors-Commercial & Industrial","!Arturo Cortez - Plumbers"]',
    1,
    NULL,
    22,
    '(503) 930-7865',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-40',
    'Arturo Cortez',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","!E-Z Flow Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 930-7865',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-41',
    'E-Z Flow Plumbing',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","!Rod''s Plumbing - Plumbers"]',
    1,
    'https://www.e-zplumbing.com/',
    NULL,
    '(503) 991-4822',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-42',
    'Rod''s Plumbing',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","!Berry Plumbing Inc - Plumbers"]',
    1,
    'http://www.rodsplumbingsalem.com/',
    NULL,
    '(971) 273-0838',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-43',
    'Berry Plumbing Inc',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","!Pure Plumbing - Plumbers"]',
    1,
    'https://berryequipment.net/',
    NULL,
    '(503) 588-0624',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-44',
    'Pure Plumbing',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","!Orion Plumbing - Plumbers"]',
    1,
    'https://pureplumbinginc.com/contact',
    NULL,
    '(503) 463-6348',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-45',
    'Orion Plumbing',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","!Pure Plumbing Inc - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 507-8032',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-46',
    'Pure Plumbing Inc',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","!Rjs Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 463-6348',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-47',
    'Rjs Plumbing',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","!Aculine - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 391-5193',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-48',
    'Aculine',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","!Reliant K Plumbing - Plumbers"]',
    1,
    'http://aculineetch.com/',
    NULL,
    '(503) 931-7797',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-49',
    'Reliant K Plumbing',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","!A1 Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 984-2485',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-50',
    'A1 Plumbing',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing Contractors-Commercial & Industrial","!Evergreen Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 585-2009',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-51',
    'Evergreen Plumbing',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers"]',
    1,
    NULL,
    NULL,
    '(888) 315-2887',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-52',
    'Jackstone Inc',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","Altering & Remodeling Contractors","Home Improvements","!Dalke Construction Co - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 364-5680',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-53',
    'Dalke Construction Co',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","General Contractors","Home Builders","!Oregon Cascade Plumbing & Htg - Heat Pumps"]',
    1,
    'http://www.dalkeconstruction.com/',
    NULL,
    '(503) 585-7403',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-54',
    'Oregon Cascade Plumbing & Htg',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","Heat Pumps","Heating Contractors & Specialties"]',
    1,
    'http://www.oregoncascade.com/',
    56,
    '(503) 588-0355',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-55',
    'C J Hansen Company, Inc.',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","Heating Contractors & Specialties","Furnaces-Heating","!Kaufman Homes, Inc - Home Builders"]',
    1,
    NULL,
    78,
    '(503) 362-3643',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-56',
    'Kaufman Homes, Inc',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","Home Builders","Altering & Remodeling Contractors"]',
    1,
    'http://www.kaufmanhomesinc.com/',
    50,
    '(503) 370-8390',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-57',
    'Wolf Pack Plumbing',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing Fixtures, Parts & Supplies"]',
    1,
    'https://www.wolfpackplumbingor.com/',
    NULL,
    '(503) 878-2524',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-58',
    'Home Services at The Home Depot',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","Home Improvements","Air Conditioning Contractors & Systems","View all 2 Locations"]',
    1,
    'https://www.homedepot.com/l/North-Salem/OR/Salem/97301/4030/services?cm_mmc=old-llm-4030-x',
    NULL,
    '(503) 908-2292',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-59',
    'Gagle''s Heating',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","Heating Contractors & Specialties","Furnaces-Heating"]',
    1,
    'http://www.gaglesheating.com/',
    59,
    '(503) 581-2972',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Plumbers-60',
    'Wolfers Heating & Air Conditioning',
    'Salem',
    'OR',
    'plumbers',
    '["Plumbers","Air Conditioning Contractors & Systems","Heating Contractors & Specialties"]',
    1,
    'http://www.wolfersheating.com/',
    124,
    '(503) 391-1901',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Salem RealEstate Agents-1',
    'Jim Houck- Sundance Reality',
    'Salem',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Ned Baker Real Estate - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 400-6654',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Salem RealEstate Agents-2',
    'Ned Baker Real Estate',
    'Salem',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Blum Real Estate - Real Estate Agents"]',
    1,
    'http://www.nedbaker.com/',
    52,
    '(503) 364-6797',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Salem RealEstate Agents-3',
    'Blum Real Estate',
    'Salem',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Re/Max - Real Estate Agents"]',
    1,
    'http://blumre.com/contact',
    NULL,
    '(503) 485-1900',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Salem RealEstate Agents-4',
    'Re/Max',
    'Salem',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Consultants","View all 9 Locations","!White Star Realty - Real Estate Agents"]',
    1,
    'http://www.remax.com/',
    NULL,
    '(503) 363-2460',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Salem RealEstate Agents-5',
    'White Star Realty',
    'Salem',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Real Estate Assistance - Real Estate Agents"]',
    1,
    'https://whitestarrealty.com/local-investors',
    NULL,
    '(503) 581-6042',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Salem RealEstate Agents-6',
    'Real Estate Assistance',
    'Salem',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Gysin Realty Group LLC - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 391-1311',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Salem RealEstate Agents-7',
    'Gysin Realty Group LLC',
    'Salem',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Management"]',
    1,
    'http://www.gysinrealty.com/',
    16,
    '(503) 585-1970',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Salem RealEstate Agents-8',
    'Richard Crafts - Keller Williams Capital City',
    'Salem',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Ridgecreek Manor - Real Estate Agents"]',
    1,
    'http://www.homesbyrichardcrafts.com/',
    NULL,
    '(503) 884-4232',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Salem RealEstate Agents-9',
    'Ridgecreek Manor',
    'Salem',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://www.josephbernard.net/ridgecreek-manor',
    NULL,
    '(503) 991-5017',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Salem RealEstate Agents-10',
    'Crystal Qian Hu - Realtor - Home Quintessential Group',
    'Salem',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://www.crystalhomeforsale.com/',
    NULL,
    '(971) 388-0511',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Salem RealEstate Agents-11',
    'Safford Carpenter, REALTOR - Premiere Property Group',
    'Salem',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","!Sean & Susan, Reed Homes NW - Real Estate Agents"]',
    1,
    'https://www.carpenter.realestate/',
    5,
    '(503) 510-1068',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Salem RealEstate Agents-12',
    'Sean & Susan, Reed Homes NW',
    'Salem',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Consultants"]',
    1,
    'https://www.reedhomesnw.com/',
    NULL,
    '(503) 201-7916',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Salem RealEstate Agents-13',
    'Coldwell Banker Mountain West Real Estate, Inc.',
    'Salem',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Developers","View all 5 Locations","!Nathan Levin Co. - Real Estate Agents"]',
    1,
    'http://www.coldwellbankermountainwest.com/',
    48,
    '(503) 364-9596',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Salem RealEstate Agents-14',
    'Nathan Levin Co.',
    'Salem',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate","!Blum Real Estate - Real Estate Agents"]',
    1,
    'https://nathanlevinco.com/',
    20,
    '(971) 707-4590',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Salem RealEstate Agents-15',
    'Blum Real Estate',
    'Salem',
    'OR',
    'real-estate',
    '["Real Estate Agents","Apartment Finder & Rental Service","Real Estate Buyer Brokers","!Tomson Burnham - Real Estate Agents"]',
    1,
    'https://blumre.com/contact',
    NULL,
    '(503) 485-1900',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Salem RealEstate Agents-16',
    'Tomson Burnham',
    'Salem',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","Real Estate Buyer Brokers"]',
    1,
    'http://www.tomsonburnham.com/',
    19,
    '(503) 371-6515',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Salem RealEstate Agents-17',
    'Paramount Real Estate Services : Savannah Casper, Realtor, Broker',
    'Salem',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Leigha Carver - Real Estate Agents"]',
    1,
    'http://www.savannahcasper.com/',
    NULL,
    '(503) 551-6699',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Salem RealEstate Agents-18',
    'Leigha Carver',
    'Salem',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Salem - Real Estate Agents"]',
    1,
    'http://leighacarver.com/',
    NULL,
    '(971) 337-9396',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Salem RealEstate Agents-19',
    'Salem',
    'Salem',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Windermere Real Estate - Real Estate Agents"]',
    1,
    'https://www.c-rem.com/salem-property-management',
    NULL,
    '(503) 588-0940',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Salem RealEstate Agents-20',
    'Windermere Real Estate',
    'Salem',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","!Wilson, Levi - Real Estate Agents"]',
    1,
    'https://salemwestoffice.johnlscott.com/about-us-west-salem-johnlscott',
    NULL,
    '(503) 399-0089',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Salem RealEstate Agents-21',
    'Wilson, Levi',
    'Salem',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Kjall, Erik, AGT - Real Estate Agents"]',
    1,
    'https://nedbaker.com/',
    NULL,
    '(503) 364-6797',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Salem RealEstate Agents-22',
    'Kjall, Erik, AGT',
    'Salem',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://erikkjall.johnlscott.com/',
    NULL,
    '(503) 917-1100',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Salem RealEstate Agents-23',
    'Dana & Alan Burk - Keller Williams Capital City',
    'Salem',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","!Sundance Realty - Real Estate Agents"]',
    1,
    'https://www.sellsalemhomes.com/',
    22,
    '(503) 409-5861',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Salem RealEstate Agents-24',
    'Sundance Realty',
    'Salem',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Tracy Sturgeon at HomeSmart - Real Estate Agents"]',
    1,
    'https://www.sundancerealtyoregon.com/',
    NULL,
    '(503) 510-6178',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Salem RealEstate Agents-25',
    'Tracy Sturgeon at HomeSmart',
    'Salem',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Katie Schmidt-Realtor - Real Estate Agents"]',
    1,
    'http://tracysturgeon.com/',
    NULL,
    '(503) 881-1939',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Salem RealEstate Agents-26',
    'Katie Schmidt-Realtor',
    'Salem',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Consultants","!Brown, Steve, RLTR - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 562-9226',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Salem RealEstate Agents-27',
    'Brown, Steve, RLTR',
    'Salem',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Keller Williams - Real Estate Agents"]',
    1,
    'https://stevenbrown.youroregonhomesearch.com/',
    NULL,
    '(503) 510-5287',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Salem RealEstate Agents-28',
    'Keller Williams',
    'Salem',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    'http://www.amymcleod.net/',
    NULL,
    '(971) 208-5093',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Salem RealEstate Agents-29',
    'The Journey Home Team, Jana Fogg & Megan Fogg Realtors',
    'Salem',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Consultants","!Aperture Group - Real Estate Agents"]',
    1,
    'https://www.thejourneyhometeam-kw.com/home',
    NULL,
    '(503) 930-1047',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'salem-Salem RealEstate Agents-30',
    'Aperture Group',
    'Salem',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://apertureabc.com/',
    NULL,
    '(503) 881-8118',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-1',
    'Ramsay Electric',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","!Bear Creek Electric Inc - Electricians"]',
    1,
    'http://www.ramsayelectric.com/',
    NULL,
    '(541) 772-1398',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-2',
    'Bear Creek Electric Inc',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","Generators","Electric Equipment Repair & Service","!Day Electric - Electric Companies"]',
    1,
    NULL,
    NULL,
    '(458) 246-3454',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Electricians-3',
    'Day Electric',
    'Medford',
    'OR',
    'electricians',
    '["Electricians","Electric Companies","Building Contractors-Commercial & Industrial","!Pacific Electrical Contractors - Electricians"]',
    1,
    NULL,
    33,
    '(541) 857-5970',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  );