INSERT INTO businesses (
      id, name, city, state, industry, services, verified, website, 
      yearsInBusiness, phone, address, email, rating, reviewCount, 
      licenseNumber, bbbRating, emergencyService
    ) VALUES (
    'grantspass-General-Contractors-15',
    'Wrc Construction Inc',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Wallace Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 218-8158',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-16',
    'Wallace Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!Eastwood Homes - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 479-5173',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-17',
    'Eastwood Homes',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!Del-J, Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 476-8640',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-18',
    'Del-J, Inc',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Carpenters","!R Crume Construction Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 476-1387',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-19',
    'R Crume Construction Inc',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Rogue General Contractors - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 660-3434',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-20',
    'Rogue General Contractors',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 880-3738',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-21',
    'Imperial Homes & Construction Co',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","!Lovelace Property - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 479-7793',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-22',
    'Lovelace Property',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Mike on the Spot - General Contractors"]',
    1,
    'http://lovelacedevelopment.com/',
    NULL,
    '(541) 479-2112',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-23',
    'Mike on the Spot',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 660-4736',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-24',
    'C-2 Utility Contractors Inc',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors","!Southern Oregon Insulation - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 479-0750',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-25',
    'Southern Oregon Insulation',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","!Valerian Homes - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 476-1101',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-26',
    'Valerian Homes',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Home Builders"]',
    1,
    'http://valerianhomes.net/contact-us',
    16,
    '(541) 955-4663',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-27',
    'Stiles Construction General Contractor',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Home Improvements"]',
    1,
    NULL,
    NULL,
    '(541) 474-2447',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-28',
    'Shawn Huddleston Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","!Brayman Builders - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 761-7185',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-29',
    'Brayman Builders',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    'https://braymanbuilders.com/',
    NULL,
    '(541) 761-7135',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-30',
    'Parkwest Construction Inc',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers"]',
    1,
    NULL,
    NULL,
    '(541) 291-0363',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-31',
    'Southern Oregon Foundation Repair',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 660-9142',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-32',
    'A Consolidated Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","!Stewart Avenue Property - General Contractors"]',
    1,
    'https://aconsolidatedconstruction.com/',
    NULL,
    '(541) 226-1740',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-33',
    'Stewart Avenue Property',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","!Northridge Enterprises - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 476-9688',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-34',
    'Northridge Enterprises',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Ben Dean Builder - General Contractors"]',
    1,
    'http://www.northridgehomesgp.com/contactus',
    NULL,
    '(541) 472-1100',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-35',
    'Ben Dean Builder',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 479-1050',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-36',
    'Spaeth Contracting & Waterproofing',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 727-1035',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-37',
    'Chuck''s Roof & Construction Service',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Roofing Contractors","Building Contractors","!Jeffrey Scott Builders Inc - General Contractors"]',
    1,
    'https://www.chucksroofservice.com/contact',
    NULL,
    '(541) 479-8789',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-38',
    'Jeffrey Scott Builders Inc',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!Ausland Construction Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 660-8899',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-39',
    'Ausland Construction Inc',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!Timeless Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 476-7475',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-40',
    'Timeless Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors-Commercial & Industrial","!Holder Homes Ll - General Contractors"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 471-4457',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-41',
    'Holder Homes Ll',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors-Commercial & Industrial"]',
    1,
    NULL,
    NULL,
    '(541) 474-6828',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-42',
    'David Snook General Contractor',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","!C Woodruff Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 218-3995',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-43',
    'C Woodruff Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Construction Management","!Eagleelk, Anthony - General Contractors"]',
    1,
    'https://woodruffconstruction.com/contact-us',
    NULL,
    '(541) 479-3621',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-44',
    'Eagleelk, Anthony',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors","!Kilborn Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 476-3770',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-45',
    'Kilborn Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Home Improvements","!West Lands Contracting Inc - General Contractors"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 476-4276',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-46',
    'West Lands Contracting Inc',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 660-9541',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-47',
    'Robert L Bellenbaum Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Drywall Contractors","Real Estate Developers"]',
    1,
    NULL,
    NULL,
    '(541) 471-0013',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-48',
    'Ross Meade Construction, Inc.',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Home Improvements","!Timber Mountain Builders - General Contractors"]',
    1,
    'http://www.rossmeade.com/',
    NULL,
    '(541) 415-0909',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-49',
    'Timber Mountain Builders',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 659-2334',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-50',
    'Bellenbaum R L Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Drywall Contractors","Real Estate Developers","!Grayback Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 471-0013',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-51',
    'Grayback Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Carling of America - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 660-9197',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-52',
    'Carling of America',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 956-1204',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-53',
    'Bostic Paul Design & General Contractor',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!Win Elder Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 474-0441',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-54',
    'Win Elder Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","!Britton Bill Construction - General Contractors"]',
    1,
    'http://www.winelderconstruction.com/',
    NULL,
    '(541) 441-3740',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-55',
    'Britton Bill Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Home Improvements"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 479-8690',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-56',
    'Timber Country Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Ted Lockwood Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 659-9172',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-57',
    'Ted Lockwood Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors-Commercial & Industrial","!Artedus Construction - General Contractors"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 479-9711',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-58',
    'Artedus Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!GB Roofing - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 479-3114',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-59',
    'GB Roofing',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 295-6901',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-60',
    'Dave Adams Designer Builder',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Building Designers","Home Builders","!Scott Ward Construction - General Contractors"]',
    1,
    NULL,
    44,
    '(541) 474-0445',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-61',
    'Scott Ward Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Double Eagle - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 660-9084',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-62',
    'Double Eagle',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Excavation Contractors","Home Builders","!Cummings Construction - General Contractors"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 479-7217',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-63',
    'Cummings Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors-Commercial & Industrial"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 471-8231',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-64',
    'Corey A Bassett Construction Lic',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Eastwood Homes - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 218-4095',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-65',
    'Eastwood Homes',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!Hillside Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 476-8640',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-66',
    'Hillside Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Building Construction Consultants","!Imperial Homes & Construction Co - Home Builders"]',
    1,
    'http://www.homesbyhillside.com/',
    NULL,
    '(541) 955-9793',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-67',
    'Imperial Homes & Construction Co',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Construction Consultants","!Diamond A Construction - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 479-7793',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-68',
    'Diamond A Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors-Commercial & Industrial","!Eric Preston Roofing - Roofing Contractors"]',
    1,
    'http://www.facebook.com/',
    NULL,
    '(541) 218-7330',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-69',
    'Eric Preston Roofing',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Roofing Contractors","Gutters & Downspouts"]',
    1,
    'https://www.ericprestonroofing.com/',
    43,
    '(541) 476-2955',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-70',
    'Matlock Construction Services',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Home Improvements"]',
    1,
    'http://www.matlockconstructionservices.com/',
    14,
    '(541) 450-9675',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-71',
    'Eric T Jewkes',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Home Improvements","!Prokleen - Water Damage Emergency Service"]',
    1,
    NULL,
    NULL,
    '(541) 944-9143',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-72',
    'Prokleen',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Water Damage Emergency Service","Mold Remediation"]',
    1,
    'http://getprokleen.com/',
    31,
    '(541) 479-7555',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-73',
    'Home Services at The Home Depot',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Improvements","Plumbers","!Pacific Building Development - Home Builders"]',
    1,
    'https://www.homedepot.com/l/Grants-Pass/OR/Grants-Pass/97526/4034/services?cm_mmc=old-llm-4034-x',
    NULL,
    '(541) 234-3881',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-74',
    'Pacific Building Development',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Michael Anthony Malara - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 479-1808',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-75',
    'Michael Anthony Malara',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Brown Bear Masonry LLC - Masonry Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 660-4736',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-76',
    'Brown Bear Masonry LLC',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Masonry Contractors","Concrete Contractors","!Ridgeline Gutters - Gutters & Downspouts"]',
    1,
    'http://www.brownbearmasonry.com/',
    NULL,
    '(541) 659-9622',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-77',
    'Ridgeline Gutters',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Gutters & Downspouts"]',
    1,
    'http://ridgelinegutters.com/',
    NULL,
    '(541) 659-7384',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-78',
    'Versatile Builders and Church Roofing',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Roofing Contractors","!John Meade Excavating - Excavation Contractors"]',
    1,
    'https://roguevalleyroofs.com/',
    NULL,
    '(541) 479-1810',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-79',
    'John Meade Excavating',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Excavation Contractors","Septic Tanks & Systems","!Ausland Group - Architectural Engineers"]',
    1,
    NULL,
    41,
    '(541) 474-0869',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-80',
    'Ausland Group',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Architectural Engineers","Architects"]',
    1,
    'https://auslandgroup.com/',
    NULL,
    '(541) 476-3788',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-81',
    'Duro Last Roofing Inc',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Roofing Equipment & Supplies","Roofing Contractors","!Bleser Construction - Home Builders"]',
    1,
    'http://www.duro-last.com/',
    NULL,
    '(541) 476-9918',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-82',
    'Bleser Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors","!Donald Andrew Lavenbarg - Home Builders"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 476-5575',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-83',
    'Donald Andrew Lavenbarg',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Jl Verser Carpentry - Carpenters"]',
    1,
    NULL,
    NULL,
    '(541) 659-2334',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-84',
    'Jl Verser Carpentry',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Carpenters","Home Builders","!Rainy Day Gutters - Gutters & Downspouts"]',
    1,
    NULL,
    NULL,
    '(541) 218-5539',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-85',
    'Rainy Day Gutters',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Gutters & Downspouts","Home Improvements","!Gilbert Earl Fulbright - Home Builders"]',
    1,
    'https://www.rainydaygutters.net/contact',
    NULL,
    '(541) 761-5217',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-86',
    'Gilbert Earl Fulbright',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Hagerman Construction - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 218-4463',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-87',
    'Hagerman Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Altering & Remodeling Contractors"]',
    1,
    'http://www.constructionsource.com/',
    NULL,
    '(541) 474-9484',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-88',
    'Home Builders Association of Josephine County',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Social Service Organizations","!Jeffrey Clark Bassett - Home Builders"]',
    1,
    'http://www.homebuildersofjoco.com/',
    NULL,
    '(541) 479-1311',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-89',
    'Jeffrey Clark Bassett',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Ayling, James W - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 441-3319',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-90',
    'Ayling, James W',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Cornerstone Construction - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 659-6674',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-91',
    'Cornerstone Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Real Estate Buyer Brokers","!Double R Products - Construction Management"]',
    1,
    NULL,
    NULL,
    '(541) 476-9883',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-92',
    'Double R Products',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Construction Management","!Northstar Development Group - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 476-1387',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-93',
    'Northstar Development Group',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 441-0540',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-94',
    'Southern Oregon Drywall and Insulation',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Insulation Contractors","Drywall Contractors","!Velazquez Sr, Juan Jose - Home Builders"]',
    1,
    'https://sodrywallandinsulation.com/',
    NULL,
    '(541) 660-1131',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-95',
    'Velazquez Sr, Juan Jose',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Jacoby Construction & Design - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 660-6538',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-96',
    'Jacoby Construction & Design',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors-Commercial & Industrial","!Davidson Carpet Care - Carpet & Rug Cleaners"]',
    1,
    NULL,
    NULL,
    '(800) 342-2927',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-97',
    'Davidson Carpet Care',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Carpet & Rug Cleaners","!Trm Construction - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 570-0901',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-98',
    'Trm Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors-Commercial & Industrial"]',
    1,
    NULL,
    17,
    '(541) 956-7521',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-99',
    'Summit Builders & Development Inc',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!McMurray & Sons Inc - Roofing Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 660-9640',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-100',
    'McMurray & Sons Inc',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Roofing Contractors","!Ra Murphy Construction - Home Builders"]',
    1,
    'https://www.mcmurrayandsons.com/',
    NULL,
    '(541) 779-9334',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-101',
    'Ra Murphy Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors","!Brownell''s Electric - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 476-1520',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-102',
    'Brownell''s Electric',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Electricians","!Lawless Roofing Inc - Roofing Contractors"]',
    1,
    'https://www.brownellselectric.com/',
    NULL,
    '(541) 476-3674',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-103',
    'Lawless Roofing Inc',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Roofing Contractors"]',
    1,
    'https://lawlessroofing.com/contact-us',
    NULL,
    '(541) 479-1839',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-104',
    'Timber Mountain Construction, Inc',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Road Building Contractors","Excavation Contractors","!House Calls Home Improvement - Home Improvements"]',
    1,
    NULL,
    NULL,
    '(541) 956-8700',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-105',
    'House Calls Home Improvement',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Improvements","Sunrooms & Solariums","!Scottfields Construction - Home Builders"]',
    1,
    'http://hchillc.com/',
    NULL,
    '(541) 476-9222',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-106',
    'Scottfields Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors-Commercial & Industrial","!Jerry''s Roofing - Roofing Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 476-1070',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-107',
    'Jerry''s Roofing',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Roofing Contractors","!Masterpiece Builders - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 476-9242',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-108',
    'Masterpiece Builders',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Real Estate Developers","!Milo Guy Maltby - Home Builders"]',
    1,
    'http://masterpiecebuildershomes.com/',
    NULL,
    '(541) 660-1536',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-109',
    'Milo Guy Maltby',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Lowe''s Construction - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 659-7414',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-110',
    'Lowe''s Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Materials","!Imel, Michael L - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 507-1212',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-111',
    'Imel, Michael L',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Peter Wade Scaglione - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 659-2732',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-112',
    'Peter Wade Scaglione',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Nicholas Boges - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 659-1247',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-113',
    'Nicholas Boges',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Rabindranath Goswami - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 476-9670',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-114',
    'Rabindranath Goswami',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Kenneth Richard Lucrezi - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 659-4089',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  );