INSERT INTO businesses (
      id, name, city, state, industry, services, verified, website, 
      yearsInBusiness, phone, address, email, rating, reviewCount, 
      licenseNumber, bbbRating, emergencyService
    ) VALUES (
    'medford-General-Contractors-44',
    'My Fathers House Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!James Earl Parnell - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 951-7720',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-45',
    'James Earl Parnell',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","!CGS Property Service Inc - General Contractors"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 840-3807',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-46',
    'CGS Property Service Inc',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Selig Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 840-2584',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-47',
    'Selig Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Door Repair"]',
    1,
    NULL,
    18,
    '(541) 608-0375',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-48',
    'S G Construction & Remodeling',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!Pacific Builders Resource - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 301-2250',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-49',
    'Pacific Builders Resource',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!Akery Construction - General Contractors"]',
    1,
    'https://www.pacific-builders.com/',
    NULL,
    '(541) 840-3161',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-50',
    'Akery Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors-Commercial & Industrial","!Joseph Edward McDermott - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 779-1963',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-51',
    'Joseph Edward McDermott',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","!Benchmark Builders - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 840-3574',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-52',
    'Benchmark Builders',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers"]',
    1,
    NULL,
    NULL,
    '(458) 225-9476',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-53',
    'Applegate Rogue Building Company',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","!Better Built Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(458) 225-9844',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-54',
    'Better Built Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 301-7098',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-55',
    'Harrington Construction Inc',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Carpenters","Real Estate Developers","!Devry Construction - General Contractors"]',
    1,
    'https://www.hyattandharringtonconstruction.com/contact',
    NULL,
    '(541) 779-5967',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-56',
    'Devry Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Jcs-Oregon - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 604-8761',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-57',
    'Jcs-Oregon',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Professional Engineers"]',
    1,
    'http://www.jcsoregon.com/',
    NULL,
    '(541) 608-7373',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-58',
    'Jays Construction & Home Improvement',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","!Nailwacker Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 944-8209',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-59',
    'Nailwacker Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!Briggs Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 951-8964',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-60',
    'Briggs Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    'http://nbriggsconstruction.com/',
    NULL,
    '(541) 601-5612',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-61',
    'David Patterson Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 890-3300',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-62',
    'Clean Cut Construction & Landscape',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!SRC Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 292-7419',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-63',
    'SRC Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 301-6175',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-64',
    'Williams Wayne Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Home Improvements","!Dean Smith Construction - General Contractors"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 779-8170',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-65',
    'Dean Smith Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!Hamilton Consulting - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 840-6746',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-66',
    'Hamilton Consulting',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","!Arrow Peak Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(215) 839-9072',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-67',
    'Arrow Peak Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Young Brother Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 890-4171',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-68',
    'Young Brother Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Yokum Builders - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 292-3500',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-69',
    'Yokum Builders',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 608-6155',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-70',
    'John A Shull Construction & Design',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!Dream Home Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 941-2209',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-71',
    'Dream Home Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!C Cota Premier Homes Lic - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 621-8525',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-72',
    'C Cota Premier Homes Lic',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Mark Kenneth Sweitzer - General Contractors"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 734-2682',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-73',
    'Mark Kenneth Sweitzer',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","!Outlier Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 890-0115',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-74',
    'Outlier Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    'https://outlierbuilt.com/',
    NULL,
    '(541) 500-1354',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-75',
    'Bertocchi Einck Builders Inc',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!Driver Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 944-7137',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-76',
    'Driver Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors"]',
    1,
    'http://www.driver-construction.com/',
    NULL,
    '(541) 621-5282',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-77',
    'Robinson Brothers Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors-Commercial & Industrial"]',
    1,
    'https://www.rbc-utility.com/company/locations',
    NULL,
    '(541) 973-2167',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-78',
    'C Costner/Residential Contractor',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!Erickson Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 601-2922',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-79',
    'Erickson Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!Medford Construction - General Contractors"]',
    1,
    'https://www.ericksonconstructionllc.com/',
    NULL,
    '(707) 845-0904',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-80',
    'Medford Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 772-5070',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-81',
    'S & B James Construction Co',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!T Scott Dunn Construction - General Contractors"]',
    1,
    'http://www.sbjames.com/',
    NULL,
    '(541) 826-5668',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-82',
    'T Scott Dunn Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!Foothills Contracting - General Contractors"]',
    1,
    'https://www.heli-dunn.com/contact-1',
    NULL,
    '(541) 841-8211',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-83',
    'Foothills Contracting',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors-Commercial & Industrial"]',
    1,
    NULL,
    NULL,
    '(541) 941-1687',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-84',
    'Bruce Development & Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!Blr Construction Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 326-9086',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-85',
    'Blr Construction Inc',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers"]',
    1,
    NULL,
    NULL,
    '(541) 772-0548',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-86',
    'Roger Langliers Construction Co',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!Jason Emerson Staneart - General Contractors"]',
    1,
    'https://www.rlcgroup.com/contact-us',
    NULL,
    '(541) 302-6648',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-87',
    'Jason Emerson Staneart',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Bishop Construction - General Contractors"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 621-2339',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-88',
    'Bishop Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!Allure Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 773-7062',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-89',
    'Allure Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Rockwell Tops - General Contractors"]',
    1,
    'https://www.allureconstructionor.com/',
    NULL,
    '(541) 772-0548',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-90',
    'Rockwell Tops',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!Josh Platt Construction - General Contractors"]',
    1,
    'http://www.demandforce.com/b/rockwelltopsllc',
    NULL,
    '(541) 601-3005',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-91',
    'Josh Platt Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors-Commercial & Industrial","!Coleman Creek Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 535-1518',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-92',
    'Coleman Creek Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!VLC General Contracting - General Contractors"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 890-2142',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-93',
    'VLC General Contracting',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!Hip house LLC - General Contractors"]',
    1,
    NULL,
    46,
    '(541) 556-8880',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-94',
    'Hip house LLC',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!Dorris Construction - General Contractors"]',
    1,
    'http://www.hiphousellc.com/',
    NULL,
    '(541) 778-4970',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-95',
    'Dorris Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 821-4199',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-96',
    'Northwest Development & Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","!Dry Creek Construction Inc - General Contractors"]',
    1,
    'http://buildingfriendsforlife.com/joomla3/contacts',
    NULL,
    '(541) 761-2323',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-97',
    'Dry Creek Construction Inc',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","Real Estate Developers","!Hadley Roofing Inc - Roofing Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 821-8454',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-98',
    'Hadley Roofing Inc',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Roofing Contractors","!Whittle Construction Inc - Home Builders"]',
    1,
    'http://www.hadleyroofinginc.com/',
    51,
    '(541) 779-9545',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-99',
    'Whittle Construction Inc',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders"]',
    1,
    'http://www.whittlehome.com/',
    73,
    '(541) 770-7325',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-100',
    'TerraFirma Foundation Systems',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Basement Contractors","Foundation Contractors","!Designer Framing - Picture Frames"]',
    1,
    NULL,
    NULL,
    '(541) 734-4049',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-101',
    'Designer Framing',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Picture Frames","Picture Frames-Wholesale & Manufacturers"]',
    1,
    NULL,
    NULL,
    '(541) 245-0123',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-102',
    'NewStalgia Construction & Inspection Services LLC',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Inspection Service","Altering & Remodeling Contractors","!TruGreen Lawn Care - Lawn Maintenance"]',
    1,
    NULL,
    15,
    '(541) 690-6198',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-103',
    'TruGreen Lawn Care',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Lawn Maintenance","Tree Service","!Elite Foundation Repair - Foundation Contractors"]',
    1,
    'https://www.trugreen.com/?y_source=1_MzI0NTI3ODAtNTUzLWxvY2F0aW9uLndlYnNpdGU%3D',
    52,
    '(541) 414-2130',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-104',
    'Elite Foundation Repair',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Foundation Contractors","Concrete Contractors"]',
    1,
    'https://www.elitefoundationsouthernoregon.com/',
    NULL,
    '(541) 631-4242',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-105',
    'Green''s Sewing & Vacuum Center',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Household Sewing Machines","Fabric Shops","!Denn Construction - Construction Estimates"]',
    1,
    'http://www.greensdirect.com/',
    71,
    '(541) 779-3411',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-106',
    'Denn Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Construction Estimates","Altering & Remodeling Contractors","!Frank Aguilar Tile - Tile-Contractors & Dealers"]',
    1,
    'https://www.dennconstruction.com/',
    50,
    '(541) 821-3807',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-107',
    'Frank Aguilar Tile',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Tile-Contractors & Dealers","!A A Insulation Co - Insulation Materials"]',
    1,
    NULL,
    NULL,
    '(541) 292-6033',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-108',
    'A A Insulation Co',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Insulation Materials","Insulation Contractors","!Unity Construction - Building Contractors"]',
    1,
    'http://www.aainsulationco.com/',
    NULL,
    '(541) 535-1818',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-109',
    'Unity Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","Construction Management"]',
    1,
    'https://unityconstructionllc.net/',
    NULL,
    '(541) 301-7635',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-110',
    'New Foundations Property Management',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Management","Property Maintenance"]',
    1,
    'http://newfoundationspm.com/',
    20,
    '(541) 499-6211',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-111',
    'ServiceMaster Restore-ServiceMaster of Ashland',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Water Damage Restoration","Janitorial Service","!Carlson Construction - Home Builders"]',
    1,
    'https://www.servicemasterrestore.com/servicemaster-of-ashland/contact-us',
    NULL,
    '(541) 393-8190',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-112',
    'Carlson Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Patio Builders","!Three Stripes Contracting - Tree Service"]',
    1,
    'http://www.carlsonconstructionso.com/',
    NULL,
    '(541) 601-3849',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-113',
    'Three Stripes Contracting',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Tree Service","!Rogue Valley Roofing - Roofing Contractors"]',
    1,
    'http://www.3stripescontracting.com/',
    NULL,
    '(541) 301-5128',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-114',
    'Rogue Valley Roofing',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Roofing Contractors","Insulation Contractors","!Better Built Construction - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 776-6620',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-115',
    'Better Built Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Deck Builders"]',
    1,
    'https://www.bbconstructionmedford.com/',
    NULL,
    '(541) 690-1100',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-116',
    'Girard Builders, LLC',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Real Estate Developers","!Promise Land Homes - Home Improvements"]',
    1,
    NULL,
    NULL,
    '(541) 301-8555',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-117',
    'Promise Land Homes',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Improvements","Bathroom Remodeling","!Curtius-Huntley Plumbing - Plumbers"]',
    1,
    NULL,
    9,
    '(541) 499-2412',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-118',
    'Curtius-Huntley Plumbing',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Plumbers","Boiler Repair & Cleaning"]',
    1,
    'https://curtiusplumbingandmechanical.com/contact',
    26,
    '(541) 857-8988',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-119',
    'CNL Maintenance Contractors',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Painting Contractors","Handyman Services"]',
    1,
    NULL,
    NULL,
    '(541) 840-9894',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-120',
    'Revolution Builders',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors-Commercial & Industrial"]',
    1,
    'https://www.revolution-builders.com/dryw',
    NULL,
    '(541) 210-3205',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-121',
    'Alex Boutacoff Construction, Inc.',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Home Builders","!Hutter''s Carpentry - Carpenters"]',
    1,
    NULL,
    NULL,
    '(541) 770-2626',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-122',
    'Hutter''s Carpentry',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Carpenters","Altering & Remodeling Contractors","!Willpower Electric - Electricians"]',
    1,
    'http://hutterscarpentry.com/',
    NULL,
    '(541) 779-6112',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-123',
    'Willpower Electric',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Electricians","Home Improvements","!Stan Harris Construction Inc - Home Builders"]',
    1,
    'http://willpowerelect.com/',
    NULL,
    '(541) 535-3965',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-124',
    'Stan Harris Construction Inc',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Rivas Construction - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 734-9090',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-125',
    'Rivas Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Roofing Contractors","!Bonaventure Construction - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 301-5212',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-126',
    'Bonaventure Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors-Commercial & Industrial","!Byron Guy McAllister - Home Builders"]',
    1,
    NULL,
    NULL,
    '(458) 225-9595',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-127',
    'Byron Guy McAllister',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!The Hamilton Building Group Inc - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 621-0846',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-128',
    'The Hamilton Building Group Inc',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 840-7884',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-129',
    'A & B Heating and Air',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Air Conditioning Contractors & Systems","Home Improvements"]',
    1,
    NULL,
    NULL,
    '(541) 601-9032',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-130',
    'Alpine Construction & Remodeling Inc',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Home Improvements","!Raymon Mark Love - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 772-3307',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-131',
    'Raymon Mark Love',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Carpenter Foundation - Carpenters"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 301-7181',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-132',
    'Carpenter Foundation',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Carpenters","!Swiss Construction - Building Contractors"]',
    1,
    'http://carpenter-foundation.org/',
    NULL,
    '(541) 772-5851',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-133',
    'Swiss Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","!Peter C Mendell - Home Builders"]',
    1,
    'http://swissconstruction.net/',
    NULL,
    '(541) 621-5459',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-134',
    'Peter C Mendell',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Valor Elite - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 210-0301',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-135',
    'Valor Elite',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Millettt Construction - Home Builders"]',
    1,
    'http://valorelite.com/',
    NULL,
    '(541) 326-0667',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-136',
    'Millettt Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors","!Tom De Ascentis Construction - Home Builders"]',
    1,
    'http://www.millettconstruction.com/',
    NULL,
    '(541) 840-6572',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-137',
    'Tom De Ascentis Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Concrete Contractors"]',
    1,
    'https://www.dirtdogexcavation.com/',
    NULL,
    '(541) 890-0374',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-138',
    'Western Pacific Building Materials',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Building Materials","Windows"]',
    1,
    'https://www.gowestpac.com/locations',
    34,
    '(541) 770-3734',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-139',
    'Advanced Scaffold Service',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Contractors Equipment Rental","Scaffolding & Aerial Lifts","!Optina - Home Builders"]',
    1,
    'http://advancedscaffoldservice.com/',
    18,
    '(541) 210-6224',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-140',
    'Optina',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Lloyd Thompson Construction - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 621-1314',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-141',
    'Lloyd Thompson Construction',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors-Commercial & Industrial","!Robert Kurovsky - Home Builders"]',
    1,
    'http://www.pinehurstvillageestates.com/',
    NULL,
    '(541) 734-5838',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-142',
    'Robert Kurovsky',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Diamond Edge - Concrete Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 840-5520',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-General-Contractors-143',
    'Diamond Edge',
    'Medford',
    'OR',
    'general-contractors',
    '["General Contractors","Concrete Contractors","Home Builders","!Brady Lee Porter - Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 601-5130',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  );