INSERT INTO businesses (
      id, name, city, state, industry, services, verified, website, 
      yearsInBusiness, phone, address, email, rating, reviewCount, 
      licenseNumber, bbbRating, emergencyService
    ) VALUES (
    'roseburg-GeneralContractors-11',
    'Perine Inc',
    'Roseburg',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","!Black Water Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 673-9843',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-GeneralContractors-12',
    'Black Water Construction',
    'Roseburg',
    'OR',
    'general-contractors',
    '["General Contractors","!Wulff Bros. Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 229-0841',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-GeneralContractors-13',
    'Wulff Bros. Construction',
    'Roseburg',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Roofing Contractors","!Scott Lee Greenwalt - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 430-4241',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-GeneralContractors-14',
    'Scott Lee Greenwalt',
    'Roseburg',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Douglas Dean Park Sample - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 817-5958',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-GeneralContractors-15',
    'Douglas Dean Park Sample',
    'Roseburg',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!I 5 Construction Inc - General Contractors"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 580-2588',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-GeneralContractors-16',
    'I 5 Construction Inc',
    'Roseburg',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers"]',
    1,
    NULL,
    NULL,
    '(541) 672-3270',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-GeneralContractors-17',
    'Dakota Construction Services Inc',
    'Roseburg',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!S & S Builders Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 580-6805',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-GeneralContractors-18',
    'S & S Builders Inc',
    'Roseburg',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","!RK Smith Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 673-1171',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-GeneralContractors-19',
    'RK Smith Construction',
    'Roseburg',
    'OR',
    'general-contractors',
    '["General Contractors","!Atkinson Construction - General Contractors"]',
    1,
    'https://www.oregonpolebarns.com/',
    NULL,
    '(541) 670-9892',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-GeneralContractors-20',
    'Atkinson Construction',
    'Roseburg',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors-Commercial & Industrial","Home Builders","!Vincent Allen Eifert - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 672-8445',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-GeneralContractors-21',
    'Vincent Allen Eifert',
    'Roseburg',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Redbolt Construction - General Contractors"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 784-8336',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-GeneralContractors-22',
    'Redbolt Construction',
    'Roseburg',
    'OR',
    'general-contractors',
    '["General Contractors","!Gc Construction - General Contractors"]',
    1,
    'https://redboltconstructionllc.com/',
    NULL,
    '(541) 671-0127',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-GeneralContractors-23',
    'Gc Construction',
    'Roseburg',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Rogers Home Restoration - General Contractors"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 643-8329',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-GeneralContractors-24',
    'Rogers Home Restoration',
    'Roseburg',
    'OR',
    'general-contractors',
    '["General Contractors","!Scott Miller Construction - General Contractors"]',
    1,
    'https://rogershomerestoration.properties/',
    NULL,
    '(541) 375-0754',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-GeneralContractors-25',
    'Scott Miller Construction',
    'Roseburg',
    'OR',
    'general-contractors',
    '["General Contractors","Plumbers","Home Builders","!Jordan Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 673-5655',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-GeneralContractors-26',
    'Jordan Construction',
    'Roseburg',
    'OR',
    'general-contractors',
    '["General Contractors","Water Damage Restoration","Fire & Water Damage Restoration","!Faith Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 459-6040',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-GeneralContractors-27',
    'Faith Construction',
    'Roseburg',
    'OR',
    'general-contractors',
    '["General Contractors","!Madrigal Builders Corp - General Contractors"]',
    1,
    'https://www.faithlaw.com/',
    NULL,
    '(541) 672-2958',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-GeneralContractors-28',
    'Madrigal Builders Corp',
    'Roseburg',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors-Commercial & Industrial","!Zerbach Construction - General Contractors"]',
    1,
    'https://www.madrigalbuilderscorporation.com/contact',
    NULL,
    '(458) 802-0555',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-GeneralContractors-29',
    'Zerbach Construction',
    'Roseburg',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Home Improvements","!dsm Contracting - General Contractors"]',
    1,
    'https://zerbachconstruction.com/',
    NULL,
    '(541) 957-9307',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-GeneralContractors-30',
    'dsm Contracting',
    'Roseburg',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 430-1568',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-1',
    'Service Tech Plumbing',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","Water Heaters","!Purist Plumbing and Excavation LLC - Plumbers"]',
    1,
    'https://www.servicetechplumbingroseburg.com/',
    32,
    '(541) 378-6476',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-2',
    'Purist Plumbing and Excavation LLC',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","Water Heater Repair","Plumbing-Drain & Sewer Cleaning","!Roto-Rooter - Plumbers"]',
    1,
    'https://www.puristplumbing.com/',
    NULL,
    '(458) 332-0026',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-3',
    'Roto-Rooter',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","Water Heaters","Water Heater Repair","Online Specials","!Arrowood Insurance Agency - Plumbers"]',
    1,
    'https://www.rotorooter.com/roseburgor/?utm_source=iyp&utm_medium=paid&utm_campaign=iyp',
    90,
    '(458) 310-2072',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-4',
    'Arrowood Insurance Agency',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","Snow Removal Service","Landscape Designers & Consultants","!Hytech Auto Repair - Plumbers"]',
    1,
    'http://arrowoodinsurance.com/',
    NULL,
    '(541) 671-5949',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-5',
    'Hytech Auto Repair',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","Retirement Communities","General Contractors","!Carson Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 839-9111',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-6',
    'Carson Plumbing',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","!Econo-Rooter - Plumbers"]',
    1,
    'http://www.cbs.state.or.us/bcd',
    NULL,
    '(541) 672-4002',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-7',
    'Econo-Rooter',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","Septic Tanks & Systems","Sewer Cleaners & Repairers","!Patriot Plumbing LLC - Plumbers"]',
    1,
    'http://www.econo-rooter.com/',
    47,
    '(541) 672-5923',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-8',
    'Patriot Plumbing LLC',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","Water Heaters","!GFD Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 672-4770',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-9',
    'GFD Plumbing',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","!Carson Plumbing Inc. - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 430-6466',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-10',
    'Carson Plumbing Inc.',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","Sewer Contractors","Sewer Cleaners & Repairers","!Shields Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 637-7575',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-11',
    'Shields Plumbing',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","!Crooch & Harris Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 530-4750',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-12',
    'Crooch & Harris Plumbing',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","!Plummers Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 672-9755',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-13',
    'Plummers Plumbing',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","!Plummers Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 679-1722',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-14',
    'Plummers Plumbing',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","!Plumb King - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 679-1722',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-15',
    'Plumb King',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","!Plummers Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 672-0011',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-16',
    'Plummers Plumbing',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","!Arm Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 679-1722',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-17',
    'Arm Plumbing',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","!Budget Rooter - Plumbers"]',
    1,
    'https://armplumbing.com/',
    NULL,
    '(541) 621-0969',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-18',
    'Budget Rooter',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Grease Traps","!A-1 American Rooter - Plumbers"]',
    1,
    'https://roseburgbudgetrooter.com/',
    27,
    '(541) 673-3454',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-19',
    'A-1 American Rooter',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","Septic Tank & System Cleaning","!Grays Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 643-6161',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-20',
    'Grays Plumbing',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","!North Umpqua Plumbing - Plumbers"]',
    1,
    'http://www.graysplumbingservice.com/',
    17,
    '(541) 957-9447',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-21',
    'North Umpqua Plumbing',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","!Trimnell Plumbing Inc - Plumbers"]',
    1,
    'https://northumpqua.org/contact-us',
    NULL,
    '(541) 672-0212',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-22',
    'Trimnell Plumbing Inc',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","!CA Mesa Plumbing, Inc - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 672-6334',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-23',
    'CA Mesa Plumbing, Inc',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","Home Improvements"]',
    1,
    'https://plumbersofamerica.com/or/roseburg/20766--c-a-mesa-plumbing-inc',
    NULL,
    '(541) 440-6372',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-24',
    'A.R.M. Plumbing',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Water Heater Repair","!Roto-Rooter - Plumbing-Drain & Sewer Cleaning"]',
    1,
    'http://armplumbing.com/',
    10,
    '(541) 621-0969',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-25',
    'Roto-Rooter',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Water Heaters"]',
    1,
    'http://www.rotorooter.com/',
    90,
    '(541) 957-5050',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-26',
    'Home Services at The Home Depot',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","Home Improvements","Flooring Contractors","!Yeager''s Plumbing - Water Heater Repair"]',
    1,
    'https://www.homedepot.com/l/Roseburg/OR/Roseburg/97470/4020/services?cm_mmc=old-llm-4020-x',
    NULL,
    '(541) 234-3710',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-27',
    'Yeager''s Plumbing',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","Water Heater Repair","Boiler Repair & Cleaning","!Scott Miller Construction - General Contractors"]',
    1,
    'http://www.yaegerplumbing.com/',
    67,
    '(541) 672-8460',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-28',
    'Scott Miller Construction',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","General Contractors","Home Builders","!A-1 Plumbing Department Inc - Water Heaters"]',
    1,
    NULL,
    NULL,
    '(541) 673-5655',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-29',
    'A-1 Plumbing Department Inc',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","Water Heaters","!Service Tech Plumbing - Water Heater Repair"]',
    1,
    NULL,
    NULL,
    '(541) 673-0873',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-30',
    'Service Tech Plumbing',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","Water Heater Repair","Leak Detecting Service","!Rokus Plumbing & Heating - Plumbers"]',
    1,
    'https://www.servicetechplumbingroseburg.com/',
    NULL,
    '(541) 378-6476',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-31',
    'Rokus Plumbing & Heating',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","Air Conditioning Contractors & Systems","Heating Contractors & Specialties","!North Valley Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 673-0333',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-32',
    'North Valley Plumbing',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","!Dj''s Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 459-9210',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-33',
    'Dj''s Plumbing',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","!D J''s Plumbing - Plumbers"]',
    1,
    'https://plumbingsearch.net/oregon/roseburg/7243450/djs-plumbing',
    NULL,
    '(541) 673-2480',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-34',
    'D J''s Plumbing',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","!Gray''s Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 863-5040',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-35',
    'Gray''s Plumbing',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","!Chuck''s Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 430-2515',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-36',
    'Chuck''s Plumbing',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","!Shepherd Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 271-9980',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-37',
    'Shepherd Plumbing',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","!North Valley Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 584-2467',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-38',
    'North Valley Plumbing',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","!Plumbing Technician Of Roseburg - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 440-5325',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-39',
    'Plumbing Technician Of Roseburg',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","!Econo-Rooter - Plumbers"]',
    1,
    'https://voxservices.net/plumbing/roseburg/or/89070/plumbing%20technician%20of%20roseburg',
    26,
    '(541) 375-0954',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-40',
    'Econo-Rooter',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Sewer Contractors","!Trimnell Plumbing Inc - Plumbers"]',
    1,
    'http://www.econo-rooter.com/',
    47,
    '(541) 672-5923',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-41',
    'Trimnell Plumbing Inc',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","!Gfd Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 863-3391',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-42',
    'Gfd Plumbing',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","!Patriot Plumbing - Water Heater Repair"]',
    1,
    NULL,
    51,
    '(541) 430-6466',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-43',
    'Patriot Plumbing',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","Water Heater Repair","Boiler Repair & Cleaning","!PEPE le PHEW - Sewer Cleaners & Repairers"]',
    1,
    NULL,
    18,
    '(541) 672-4770',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-44',
    'PEPE le PHEW',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","Sewer Cleaners & Repairers","Plumbing, Drains & Sewer Consultants"]',
    1,
    NULL,
    19,
    '(541) 817-5888',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-45',
    'Rapid Rooter Sewer and Drain Cleaning Service',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","Sewer Cleaners & Repairers","Plumbing-Drain & Sewer Cleaning","!PEPE le PHEW - Sewer Cleaners & Repairers"]',
    1,
    NULL,
    NULL,
    '(541) 860-8278',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-46',
    'PEPE le PHEW',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","Sewer Cleaners & Repairers","Plumbing, Drains & Sewer Consultants"]',
    1,
    NULL,
    19,
    '(541) 817-5888',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-47',
    'A-1 Septic & Power Rooter Service',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","Septic Tank & System Cleaning","Building Contractors"]',
    1,
    'http://a-1septicroseburg.com/',
    NULL,
    '(541) 672-8709',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Plumbers-48',
    'Pepe Le Phew Sewer-Drain Cleaning',
    'Roseburg',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Sewer Cleaners & Repairers"]',
    1,
    NULL,
    NULL,
    '(541) 817-5888',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-1',
    'Karen Volk Realty',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Appraisers","!The Integrity Team - Real Estate Agents"]',
    1,
    'http://www.karenvolkrealty.com/',
    35,
    '(541) 672-4444',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-2',
    'The Integrity Team',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Roseburg Realty - Real Estate Agents"]',
    1,
    'http://integrityteam.harcourtsusa.com/',
    NULL,
    '(541) 673-3334',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-3',
    'Roseburg Realty',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!G Stiles Realty - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 672-3344',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-4',
    'G Stiles Realty',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Management","!Garden Valley Realty - Real Estate Agents"]',
    1,
    'http://www.gstiles.com/',
    46,
    '(541) 672-1616',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-5',
    'Garden Valley Realty',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate"]',
    1,
    'http://gardenvalleyrealty.com/',
    NULL,
    '(541) 672-4888',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-6',
    'The Neil Company Real Estate',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Apartments","Real Estate Buyer Brokers","View all 2 Locations","!All-Pro Realty Advisors - Real Estate Agents"]',
    1,
    'https://www.neilco.com/',
    48,
    '(541) 673-4417',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-7',
    'All-Pro Realty Advisors',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Appraisers","Commercial Real Estate","!Norman, Jerry, RLTR - Real Estate Agents"]',
    1,
    'https://apr-advisors.com/',
    4,
    '(541) 696-1600',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-8',
    'Norman, Jerry, RLTR',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Landerer, Matt, AGT - Real Estate Agents"]',
    1,
    'https://www.sellwithnorman.com/',
    NULL,
    '(234) 855-7039',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-9',
    'Landerer, Matt, AGT',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Wehe, Kayla, RLTR - Real Estate Agents"]',
    1,
    'https://www.landeverhome.com/',
    NULL,
    '(443) 632-5195',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-10',
    'Wehe, Kayla, RLTR',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'http://oregonhomesbykayla.com/about',
    NULL,
    '(541) 580-2376',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-11',
    'The Mary Gilbert Group at Keller Williams Realty Umpqua Valley',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Consultants"]',
    1,
    'https://www.marygilbert.com/',
    NULL,
    '(541) 371-5500',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-12',
    'Julie Bancroft Real Estate Broker',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://www.neilco.com/',
    NULL,
    '(541) 680-1484',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-13',
    'Jacob Gilman, REALTOR | Gilman Homes',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants"]',
    1,
    'http://gilman-homes.com/',
    10,
    '(541) 580-1494',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-14',
    'RE/MAX; Professional Realty ESS2',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Management","!Sanddollar Properties - Real Estate Agents"]',
    1,
    'http://www.professionalrealty.com/',
    33,
    '(541) 673-3272',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-15',
    'Sanddollar Properties',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Alpine Real Estate - Real Estate Agents"]',
    1,
    'http://sanddollarproperties.blogspot.com/',
    NULL,
    '(541) 464-5849',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-16',
    'Alpine Real Estate',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(541) 229-2992',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-17',
    'Matt Landever Real Estate Agent, Oregon Life Homes',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://www.sellwithnorman.com/',
    NULL,
    '(234) 855-7039',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-18',
    'Aaron Cherry Real Estate Broker',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://www.theoregonlife.com/',
    NULL,
    '(541) 391-1623',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-19',
    'Jerry Norman Real Estate Agent, Oregon Life Homes',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","!GT Reality - Real Estate Agents"]',
    1,
    'https://www.sellwithnorman.com/',
    4,
    '(234) 855-7039',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-20',
    'GT Reality',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(541) 637-5490',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-21',
    'Mastforney Real Estate Group',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(541) 900-1298',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-22',
    'Berkshire Hathaway HomeServices Real Estate Professionals',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Prudential Real Estate - Real Estate Agents"]',
    1,
    'http://roseburghomes4u.com/',
    NULL,
    '(541) 673-1890',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-23',
    'Prudential Real Estate',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate","!Front Porch Real Estate - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 673-1890',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-24',
    'Front Porch Real Estate',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Harris Realty - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 671-2800',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-25',
    'Harris Realty',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Ryan Fox Realtor - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 900-1833',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-26',
    'Ryan Fox Realtor',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Consultants"]',
    1,
    NULL,
    NULL,
    '(541) 672-3035',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-27',
    'Chosen Properties Real Estate',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!105 Properties - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 673-5514',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-28',
    '105 Properties',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Harcourts Integrity Team - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 672-4810',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-29',
    'Harcourts Integrity Team',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Beach Life Pro Realty - Real Estate Agents"]',
    1,
    'http://integrityteam.harcourtsusa.com/',
    NULL,
    '(541) 673-3334',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-30',
    'Beach Life Pro Realty',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Bob Lamonte Group - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(239) 940-6124',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-31',
    'Bob Lamonte Group',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Prudential Real Estate - Real Estate Agents"]',
    1,
    'https://boblamontegroup.kw.com/',
    NULL,
    '(541) 670-3365',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-32',
    'Prudential Real Estate',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate"]',
    1,
    NULL,
    NULL,
    '(888) 880-2227',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  );