INSERT INTO businesses (
      id, name, city, state, industry, services, verified, website, 
      yearsInBusiness, phone, address, email, rating, reviewCount, 
      licenseNumber, bbbRating, emergencyService
    ) VALUES (
    'medford-LawFirms-134',
    'Stark and Hammack, PC',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Probate Law Attorneys","Wills, Trusts & Estate Planning Attorneys","!Hammack Larry C - General Practice Attorneys"]',
    1,
    'http://www.starkandhammack.net/',
    55,
    '(541) 773-2213',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-135',
    'Hammack Larry C',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","General Practice Attorneys","!William Francis PC - Litigation & Tort Attorneys"]',
    1,
    'http://www.starkhammack.com/',
    NULL,
    '(541) 773-2213',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-136',
    'William Francis PC',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Litigation & Tort Attorneys"]',
    1,
    NULL,
    47,
    '(541) 779-5000',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-137',
    'Abel, Gregory M, ATTY',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Litigation & Tort Attorneys","Personal Injury Law Attorneys"]',
    1,
    'http://www.medfordlegal.com/',
    47,
    '(541) 773-6855',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-138',
    'George Hoselton Bankruptcy Attorney',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Bankruptcy Law Attorneys","!Parke Gordon Law - Personal Injury Law Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 494-5422',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-139',
    'Parke Gordon Law',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Personal Injury Law Attorneys","Legal Clinics","!RISE Law Group - General Practice Attorneys"]',
    1,
    'https://www.parkegordon.com/',
    NULL,
    '(541) 827-3400',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-140',
    'RISE Law Group',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","General Practice Attorneys","Divorce Attorneys"]',
    1,
    'https://www.riselawgroup.org/',
    NULL,
    '(541) 773-3619',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-141',
    'Dwyer Williams Cherkoss Attorneys, PC',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Personal Injury Law Attorneys","Wrongful Death Attorneys"]',
    1,
    'https://www.roydwyer.com/',
    NULL,
    '(541) 842-4555',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-142',
    'Law Offices of Martial E. Henault',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Estate Planning Attorneys","Commercial Law Attorneys"]',
    1,
    'http://henaultlaw.com/',
    42,
    '(541) 779-5858',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-143',
    'Kellington & Kellington',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Accident & Property Damage Attorneys","Criminal Law Attorneys","!Penny Lee Austin, Attorney - Elder Law Attorneys"]',
    1,
    'http://kellingtonlaw.com/',
    59,
    '(541) 773-8436',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-144',
    'Penny Lee Austin, Attorney',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Elder Law Attorneys","Family Law Attorneys","!Danny Kerns | eXp Realty - Real Estate Agents"]',
    1,
    'http://www.pennyleeaustin.com/',
    NULL,
    '(541) 770-6720',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-145',
    'Danny Kerns | eXp Realty',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Real Estate Agents","Real Estate Investing","!White, Casey, ATY - Estate Planning Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 227-4222',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-146',
    'White, Casey, ATY',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Estate Planning Attorneys","Estate Planning, Probate, & Living Trusts"]',
    1,
    'http://www.ccaseywhite.com/',
    34,
    '(541) 779-4912',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-147',
    'C Casey White Attorney At Law',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Bankruptcy Law Attorneys","Estate Planning, Probate, & Living Trusts"]',
    1,
    'http://www.ccaseywhite.com/',
    39,
    '(541) 779-4912',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-148',
    'Jeffrey Foxx Atty At Law',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Real Estate Attorneys","Estate Planning, Probate, & Living Trusts"]',
    1,
    NULL,
    40,
    '(541) 773-2008',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-LawFirms-149',
    'Harder Wells Baron & Manning PC',
    'Medford',
    'OR',
    'lawfirms',
    '["Attorneys","Social Security & Disability Law Attorneys"]',
    1,
    'http://www.hwbm.net/',
    NULL,
    '(833) 245-8583',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-1',
    'Century Property Management',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","Real Estate Referral & Information Service","!Home Source Real Estate Co - Real Estate Agents"]',
    1,
    'https://centurypropmgmt.com/',
    16,
    '(541) 507-6297',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-2',
    'Home Source Real Estate Co',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Remax - Real Estate Agents"]',
    1,
    'http://www.homesourcerealestateco.com/',
    NULL,
    '(541) 772-6799',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-3',
    'Remax',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate","View all 4 Locations"]',
    1,
    'https://www.remax.com/realestateofficerealtor/medford-or-97504-remaxplatinum-id60610484.html',
    NULL,
    '(541) 734-5500',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-4',
    'General Growth Properties Regional Office',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!CPM Real Estate Service - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 858-0619',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-5',
    'CPM Real Estate Service',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","Real Estate Rental Service","!Cascade Charter Company LLC - Real Estate Agents"]',
    1,
    'http://www.cpmrealestateservices.com/',
    NULL,
    '(541) 773-6400',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-6',
    'Cascade Charter Company LLC',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Appraisers"]',
    1,
    NULL,
    25,
    '(541) 776-7530',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-7',
    'Coldwell Banker Pro West Real Estate',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Finish Line Real Estate - Real Estate Agents"]',
    1,
    'https://www.cbprowest.com/',
    NULL,
    '(541) 773-6868',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-8',
    'Finish Line Real Estate',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate","!Danny Kerns | eXp Realty - Real Estate Agents"]',
    1,
    'https://www.finishlinerealestate.com/contact',
    NULL,
    '(541) 773-3113',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-9',
    'Danny Kerns | eXp Realty',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Investing","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(541) 227-4222',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-10',
    'Skye Flora - John L. Scott Real Estate - Medford',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'http://skyeflora.com/',
    NULL,
    '(541) 301-6614',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-11',
    'Crouse & Associates Real Estate',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","!John L Scott Medford - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 840-8797',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-12',
    'John L Scott Medford',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants"]',
    1,
    'https://www.medfordportfolio.com/about',
    NULL,
    '(541) 779-3611',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-13',
    'John L Scott Real Estate Southern',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Bartell Group - Real Estate Agents"]',
    1,
    'https://donmccoy.johnlscott.com/',
    23,
    '(541) 779-3611',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-14',
    'Bartell Group',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Rental Service","Real Estate Management","!Rachel White - Real Estate Agents"]',
    1,
    'https://www.jmstranahan.com/',
    8,
    '(541) 301-4170',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-15',
    'Rachel White',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Appraisers","!Oak Tree Realtors Inc - Real Estate Agents"]',
    1,
    'https://rachelwhiteor.exprealty.com/',
    NULL,
    '(541) 951-2894',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-16',
    'Oak Tree Realtors Inc',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate"]',
    1,
    'http://www.oaktreerealtors.net/',
    42,
    '(541) 772-9040',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-17',
    'Stranhan, John Matthew, RLTR',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://www.remax.com/real-estate-agents/john-matthew-stranahan-medford-or/102188370',
    NULL,
    '(541) 301-4170',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-18',
    'Brown Chudleigh Schuler Myers & Associates',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Appraisers","Estate Planning, Probate, & Living Trusts"]',
    1,
    NULL,
    NULL,
    '(541) 776-7530',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-19',
    'Martin Outdoor Property Group',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://martinoutdoorproperties.com/',
    NULL,
    '(541) 660-5111',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-20',
    'Evan Kaseberg - Farm & Ranch Broker',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Medford Real Estate News - Real Estate Agents"]',
    1,
    'http://www.northwestranchgroup.com/',
    NULL,
    '(541) 980-8730',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-21',
    'Medford Real Estate News',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Finish Line Real Estate - Real Estate Agents"]',
    1,
    'https://www.finishlinerealestate.com/contact',
    NULL,
    '(541) 301-2802',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-22',
    'Finish Line Real Estate',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Merit Commercial Real Es - Real Estate Agents"]',
    1,
    'http://www.finishlinerealestate.com/',
    NULL,
    '(541) 773-3113',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-23',
    'Merit Commercial Real Es',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://roguecommercial.com/contact-us-1',
    NULL,
    '(541) 608-6704',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-24',
    'Coldwell Banker Commercial Pro West',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Sutton Homes Realty - Real Estate Agents"]',
    1,
    'https://www.cbcworldwide.com/offices/profile/2C5B84B9-6CA5-11D7-A2D1-00B0D0494558',
    NULL,
    '(541) 608-2050',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-25',
    'Sutton Homes Realty',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Patrick Iler Real Estate - Real Estate Agents"]',
    1,
    'https://www.suttonhomesrealty.com/Contact_SHR/page_1739381.html',
    NULL,
    '(541) 210-8763',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-26',
    'Patrick Iler Real Estate',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    'http://wildbroker.com/',
    NULL,
    '(541) 500-1859',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-27',
    'Herrmann Crawford Properties',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Medford Plaza - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 531-9799',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-28',
    'Medford Plaza',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Group Exit Realty - Real Estate Agents"]',
    1,
    'http://www.medfordplaza.com/contact-us.html',
    NULL,
    '(541) 734-2255',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-29',
    'Group Exit Realty',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Windermere Investors - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 858-1800',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-30',
    'Windermere Investors',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Rick Vander Giessen - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 618-1985',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-31',
    'Rick Vander Giessen',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://www.windermere.com/our-services/commercial',
    NULL,
    '(360) 734-7500',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-32',
    'RE/MAX Preferred Professionals',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Bm2w - Real Estate Agents"]',
    1,
    'http://citlink.net/',
    NULL,
    '(928) 718-7629',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-33',
    'Bm2w',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Ford Real Estate - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 538-4400',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-34',
    'Ford Real Estate',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Patrick Iler Real Estate - Real Estate Agents"]',
    1,
    'https://www.propertyofsouthernoregon.com/',
    NULL,
    '(541) 773-2088',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-35',
    'Patrick Iler Real Estate',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(541) 500-1859',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-36',
    'CPM Real Estate Services, Inc',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Management"]',
    1,
    'http://www.qpmcompany.com/',
    NULL,
    '(541) 773-6400',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-37',
    'Mohawk Valley 1st Choice Realt',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Gj Smith Realty - Real Estate Agents"]',
    1,
    'https://www.mv1stchoice.com/',
    NULL,
    '(315) 735-4460',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-38',
    'Gj Smith Realty',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Hamlin Properties - Real Estate Agents"]',
    1,
    'http://www.gjsmithrealty.com/',
    NULL,
    '(541) 858-9383',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-39',
    'Hamlin Properties',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Exit Realty Group - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 772-8516',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-40',
    'Exit Realty Group',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate","!Danny Kerns | eXp Realty - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 770-5200',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-41',
    'Danny Kerns | eXp Realty',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Don McCoy Real Estate - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 227-4222',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-42',
    'Don McCoy Real Estate',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Sun South Properties - Real Estate Agents"]',
    1,
    'https://www.donmccoyrealestateteam.com/contact',
    NULL,
    '(541) 773-8200',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-43',
    'Sun South Properties',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://www.alicelema.com/',
    NULL,
    '(541) 779-3611',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-44',
    'Gwen Christensen @ John L Scott',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","!Team Toner Real Estate - Real Estate Agents"]',
    1,
    'https://gwenchristenson.johnlscott.com/',
    NULL,
    '(541) 601-3602',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-45',
    'Team Toner Real Estate',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://karentoner.johnlscott.com/home',
    NULL,
    '(541) 890-5441',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-46',
    'Danielle West of Keller Williams Realty SO',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Rutledge, Adam - Real Estate Agents"]',
    1,
    'http://gjacoby.kw.com/',
    NULL,
    '(541) 951-4224',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-47',
    'Rutledge, Adam',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Fredericka A Lloyd Realtor - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 778-9677',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-48',
    'Fredericka A Lloyd Realtor',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Dreamhouse Realty - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(301) 577-2210',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-49',
    'Dreamhouse Realty',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Hokanson Group - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 826-7456',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-50',
    'Hokanson Group',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate","!Next Home Stone Leaf Realty - Real Estate Agents"]',
    1,
    'http://www.topsouthernoregonagent.com/',
    NULL,
    '(541) 772-7653',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-51',
    'Next Home Stone Leaf Realty',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Landline - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 727-6247',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-52',
    'Landline',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://www.landlinerealestate.com/',
    NULL,
    '(541) 779-1158',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-53',
    'Crouse & Associates Real Estate',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Hamlin Real Estate - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 770-1668',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-54',
    'Hamlin Real Estate',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Investing","!Dreamhouse Realty - Real Estate Agents"]',
    1,
    'http://roguevalleyre.com/',
    NULL,
    '(541) 770-1480',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-55',
    'Dreamhouse Realty',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Fry & Associates Inc - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 500-8033',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-56',
    'Fry & Associates Inc',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Appraisers","Real Estate Buyer Brokers","!Exit Realty Group - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 772-2620',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-57',
    'Exit Realty Group',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Tinsley, Kathy - Real Estate Agents"]',
    1,
    'http://exitrealty.com/',
    NULL,
    '(541) 770-5200',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-58',
    'Tinsley, Kathy',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Rachel White - Real Estate Agents"]',
    1,
    'https://www.kathytinsley4homes.com/about',
    NULL,
    '(541) 601-5287',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-59',
    'Rachel White',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://rachelwhiteor.exprealty.com/',
    NULL,
    '(541) 951-2894',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-60',
    'Patricia Cunningham Appraiser',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 690-1758',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-61',
    'Nwrecc ID Affordable Housing',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Home Tenders Inc - Real Estate Agents"]',
    1,
    'https://www.nwrecc.org/',
    NULL,
    '(208) 375-9407',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-62',
    'Home Tenders Inc',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Pulver & Leever Real Estate - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 973-2607',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-63',
    'Pulver & Leever Real Estate',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate","Real Estate Investing","!Jim Root & Co - Real Estate Agents"]',
    1,
    'https://pulverandleever.com/contact',
    NULL,
    '(541) 773-5391',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-64',
    'Jim Root & Co',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Root Properties - Real Estate Agents"]',
    1,
    'http://jimrootcompany.com/',
    NULL,
    '(541) 772-4400',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-65',
    'Root Properties',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'http://jimrootcompany.com/',
    NULL,
    '(541) 772-4400',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-66',
    'Arron Waldron - Home Quest Realty',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://www.elliegeorge.com/',
    NULL,
    '(541) 951-5081',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-67',
    'Nwrecc ID Affordable Housing',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Dwelling Place Realty - Real Estate Agents"]',
    1,
    'https://skyvista.nwrecc.org/mapsanddirections',
    NULL,
    '(208) 375-9407',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-68',
    'Dwelling Place Realty',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 772-3557',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-69',
    'Commonwealth Real Estate Service',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Daniel R Willis Real Estate - Real Estate Agents"]',
    1,
    'https://cwres.com/products/village-mobile-inn',
    NULL,
    '(503) 244-2300',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-70',
    'Daniel R Willis Real Estate',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Team Caswell Real Estate - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 500-8889',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-71',
    'Team Caswell Real Estate',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Realty Services Team - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 499-6926',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-72',
    'Realty Services Team',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Team Shannon Hall - Real Estate Agents"]',
    1,
    'https://www.rstoregon.com/',
    NULL,
    '(541) 499-6402',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-73',
    'Team Shannon Hall',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'http://www.remax.com/',
    NULL,
    '(541) 788-9027',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-74',
    'ERA Real Estate Sunrise Realty',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Key Properties - Real Estate Agents"]',
    1,
    'https://erasunriserealty.com/',
    NULL,
    '(770) 720-1515',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-75',
    'Key Properties',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate","Real Estate Buyer Brokers","!Skyline Realty Group - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 779-3100',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-76',
    'Skyline Realty Group',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate","!Sierra Real Estate - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 858-1000',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-77',
    'Sierra Real Estate',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Home Sweet Bookings - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 770-5122',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-78',
    'Home Sweet Bookings',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 500-0255',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-79',
    'Realty Executives Associates',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","!Patie Millen Realtor - Real Estate Agents"]',
    1,
    'http://realtyexecutives-associates.com/',
    NULL,
    '(865) 693-3232',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-80',
    'Patie Millen Realtor',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(541) 772-9355',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-81',
    'Contract Servicing Real Estate',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Akkette, Mark, AGT - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 779-2813',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-82',
    'Akkette, Mark, AGT',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Consultants","!Re/Max - Real Estate Agents"]',
    1,
    'http://www.remax.com/',
    NULL,
    '(541) 951-4660',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-83',
    'Re/Max',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate"]',
    1,
    'http://www.anthonysternburg.remaxagent.com/',
    NULL,
    '(541) 770-3325',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-84',
    'John L Scott Real Estate-JJ Kramer',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Hillcrest Office Park - Real Estate Agents"]',
    1,
    'https://jjkramer.johnlscott.com/',
    NULL,
    '(541) 840-2992',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  );