INSERT INTO businesses (
      id, name, city, state, industry, services, verified, website, 
      yearsInBusiness, phone, address, email, rating, reviewCount, 
      licenseNumber, bbbRating, emergencyService
    ) VALUES (
    'medford-Real-Estate-Agents-85',
    'Hillcrest Office Park',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Six Commercial Real Estate - Real Estate Agents"]',
    1,
    'https://maharhomes.com/newcomm',
    NULL,
    '(541) 210-5420',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-86',
    'Six Commercial Real Estate',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Investing","!Melody Stevens Realty - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 858-1082',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-87',
    'Melody Stevens Realty',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Home Tenders Inc - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 772-8886',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-88',
    'Home Tenders Inc',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate","!Luke Scott Real Estate Inc - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 608-9400',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-89',
    'Luke Scott Real Estate Inc',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Cornerstone Real Estate - Real Estate Agents"]',
    1,
    'http://www.lukescottrealestate.com/',
    NULL,
    '(541) 734-5252',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-90',
    'Cornerstone Real Estate',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!First Team Real Estate - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 690-1810',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-91',
    'First Team Real Estate',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Mary Sutherland Broker - Real Estate Agents"]',
    1,
    'https://huntingtonbeachsouth.firstteam.com/',
    NULL,
    '(714) 964-3311',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-92',
    'Mary Sutherland Broker',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Sierra Real Estate - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 646-0826',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-93',
    'Sierra Real Estate',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 779-8008',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-94',
    'Commercial Real Estate Services Company',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate","!CPR Real Estate Services - Real Estate Agents"]',
    1,
    'https://www.showcase.com/or/jackson-county/office-space/for-rent',
    NULL,
    '(541) 618-8566',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-95',
    'CPR Real Estate Services',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Myers Reo Team - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 772-0120',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-96',
    'Myers Reo Team',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Marshall Realtors Harry B - Real Estate Agents"]',
    1,
    'https://www.rstoregon.com/',
    NULL,
    '(541) 499-6402',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-97',
    'Marshall Realtors Harry B',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate","Real Estate Management","!Henselman Realty Group - Real Estate Agents"]',
    1,
    'http://www.somls.com/',
    NULL,
    '(541) 773-7345',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-98',
    'Henselman Realty Group',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Management","!Sunrise Real Estate - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 500-1002',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-99',
    'Sunrise Real Estate',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Esquivel and Associates - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 770-7055',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-100',
    'Esquivel and Associates',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Action Realty - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 494-4944',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-101',
    'Action Realty',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Merit Commercial Real ES - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 772-7782',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-102',
    'Merit Commercial Real ES',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Redd Mccarty Realtors - Real Estate Agents"]',
    1,
    'http://merit-commercial.com/',
    NULL,
    '(541) 608-6704',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-103',
    'Redd Mccarty Realtors',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate"]',
    1,
    NULL,
    NULL,
    '(541) 779-5420',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-104',
    'Windermere Van Vleet and Associates Inc.',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Realty Services Team - Real Estate Agents"]',
    1,
    'http://vanvleet.com/real-estate/medford-oregon',
    NULL,
    '(541) 779-6520',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-105',
    'Realty Services Team',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Bounty Hunter Real - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 499-6402',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-106',
    'Bounty Hunter Real',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Sierra Real Estate - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 245-0208',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-107',
    'Sierra Real Estate',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Remax - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 779-8008',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-108',
    'Remax',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate","!Burrill Real Estate - Real Estate Agents"]',
    1,
    'http://remax.com/',
    NULL,
    '(541) 770-3325',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-109',
    'Burrill Real Estate',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Developers","Real Estate Investing","!Atlas Group - Commercial Real Estate"]',
    1,
    'http://burrillrealestate.com/',
    NULL,
    '(541) 776-1311',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-110',
    'Atlas Group',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate","!Work Appraisal Service Inc - Appraisers"]',
    1,
    NULL,
    NULL,
    '(541) 608-9500',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-111',
    'Work Appraisal Service Inc',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Appraisers","!Medford Mortgages - Real Estate Loans"]',
    1,
    'http://www.workappraisal.com/',
    NULL,
    '(541) 890-4605',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-112',
    'Medford Mortgages',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Loans","Mortgages"]',
    1,
    NULL,
    27,
    '(541) 772-9987',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-113',
    'Sandra Schell Real Estate',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Consultants"]',
    1,
    'http://www.medfordhome4u.com/',
    NULL,
    '(541) 245-0270',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-114',
    'New Foundations Property Management',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","Property Maintenance"]',
    1,
    'http://newfoundationspm.com/',
    20,
    '(541) 499-6211',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-115',
    'Sterling West Property Management',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","Real Estate Buyer Brokers"]',
    1,
    'https://www.sterlingwestrentals.com/',
    NULL,
    '(541) 779-3615',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-116',
    'Oregon Opportunities Real Estate',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Property Maintenance","Real Estate Management"]',
    1,
    'http://orop.com/',
    36,
    '(541) 772-0000',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-117',
    'Southern Oregon Builders',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Industrial Developments","Real Estate Management"]',
    1,
    'http://sobuilders.com/',
    49,
    '(541) 779-2233',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-118',
    'Henselman Realty & Management',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","Real Estate Consultants","!Valley Properties - Real Estate Management"]',
    1,
    'http://www.henselmanrealty.com/',
    NULL,
    '(541) 772-4388',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-119',
    'Valley Properties',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","!Aris Group - Commercial Real Estate"]',
    1,
    'https://www.valleypropertiesso.com/',
    NULL,
    '(541) 772-2257',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-120',
    'Aris Group',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate","Real Estate Buyer Brokers","!Coldwell Banker - Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(541) 690-1405',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-121',
    'Coldwell Banker',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate","!Hamilton Chinook - Real Estate Buyer Brokers"]',
    1,
    'http://www.coldwellbanker.com/',
    NULL,
    '(541) 773-6868',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-122',
    'Hamilton Chinook',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(541) 779-1631',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-123',
    'Private Properties Management',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(541) 772-2177',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-124',
    'Allcities Property Management',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","Real Estate Buyer Brokers"]',
    1,
    'http://www.allcitiesprop.com/',
    50,
    '(541) 245-8811',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-125',
    'Valley Properties Southern Oregon',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","Real Estate Buyer Brokers"]',
    1,
    'https://www.valleypropertiesso.com/contact-us',
    NULL,
    '(541) 840-1279',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-126',
    'My Favorite Property Managers',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","Real Estate Rental Service","!Becker Properties - Real Estate Investing"]',
    1,
    'https://www.myfavoritepm.com/',
    NULL,
    '(541) 499-6111',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-127',
    'Becker Properties',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Investing","Real Estate Buyer Brokers","!CPM Realastate - Real Estate Buyer Brokers"]',
    1,
    'https://www.becker-properties.com/',
    NULL,
    '(541) 973-2556',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-128',
    'CPM Realastate',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(458) 225-9045',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-129',
    'The Village Apts',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Apartment Finder & Rental Service","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(541) 779-6322',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-130',
    'Fleisher, Michele, RLTR',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","!Valley Properties - Real Estate Management"]',
    1,
    'https://michelefleisher.com/',
    NULL,
    '(541) 538-8554',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-131',
    'Valley Properties',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","Real Estate Buyer Brokers","!Karcey, Jeri - Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(541) 772-2034',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-132',
    'Karcey, Jeri',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Coldwell Banker - Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(541) 326-8413',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-133',
    'Coldwell Banker',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Developers"]',
    1,
    'https://www.coldwellbanker.com/',
    NULL,
    '(541) 951-6550',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-134',
    'Remax Platinum Brokers',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Consultants"]',
    1,
    NULL,
    NULL,
    '(541) 608-9500',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-135',
    'Active Property Service',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Rental Service","!C & R Maintenance - Real Estate Buyer Brokers"]',
    1,
    NULL,
    27,
    '(541) 772-5334',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-136',
    'C & R Maintenance',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Bethel Properties - Commercial Real Estate"]',
    1,
    NULL,
    NULL,
    '(541) 608-6752',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-137',
    'Bethel Properties',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate","!Ridgeview Properties - Real Estate Management"]',
    1,
    NULL,
    NULL,
    '(541) 821-5447',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-138',
    'Ridgeview Properties',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(541) 608-2868',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-139',
    'Monson Tom & Jan, Brokers',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Lance Landers - Real Estate Consultants"]',
    1,
    NULL,
    NULL,
    '(541) 210-6698',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-140',
    'Lance Landers',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","Real Estate Buyer Brokers"]',
    1,
    'http://www.remax.com/',
    NULL,
    '(541) 941-4830',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-141',
    'Bruce Hoevet & Jan Monson Brokers',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Sanchez, Crystal, RLTR - Real Estate Consultants"]',
    1,
    NULL,
    NULL,
    '(541) 210-6697',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-142',
    'Sanchez, Crystal, RLTR',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","Real Estate Buyer Brokers"]',
    1,
    'https://www.remax.com/real-estate-agents/crystal-sanchez-medford-or/101939258',
    NULL,
    '(541) 531-8432',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-143',
    'Remax Platinum Brokers',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Consultants","!Phoenix Properties Inc - Commercial Real Estate"]',
    1,
    NULL,
    NULL,
    '(541) 608-9500',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-144',
    'Phoenix Properties Inc',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate","Real Estate Buyer Brokers","!Phoenix Properties Inc - Commercial Real Estate"]',
    1,
    NULL,
    NULL,
    '(541) 512-1215',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-145',
    'Phoenix Properties Inc',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(541) 512-1215',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-146',
    'Rogue River Valley Realty',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Investing","Real Estate Buyer Brokers"]',
    1,
    NULL,
    18,
    '(541) 761-0851',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-147',
    'Oregon Licensed Real Estate Broker',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","Real Estate Buyer Brokers","!Crouse Ronald - Real Estate Buyer Brokers"]',
    1,
    'http://www.southernoregonhouses.com/',
    NULL,
    '(541) 941-8040',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-148',
    'Crouse Ronald',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Re Man Ideal Properties - Commercial Real Estate"]',
    1,
    NULL,
    NULL,
    '(541) 770-1668',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-149',
    'Re Man Ideal Properties',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate","!Argence-Sorel Nicole - Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(541) 734-5643',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Real-Estate-Agents-150',
    'Argence-Sorel Nicole',
    'Medford',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(541) 890-1452',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-1',
    'Gordon''s Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!Compare Roofing Experts - Roofing Contractors"]',
    1,
    NULL,
    31,
    '(541) 326-4126',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-2',
    'Compare Roofing Experts',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Roofing Contractors-Commercial & Industrial"]',
    1,
    NULL,
    NULL,
    '(888) 906-6670',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-3',
    'Compare Roofing Experts',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Roofing Contractors-Commercial & Industrial","Video"]',
    1,
    NULL,
    NULL,
    '(888) 906-8599',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-4',
    'Platinum Roofing & Gutters, LLC',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Gutters & Downspouts","!Hadley Roofing Inc - Roofing Contractors"]',
    1,
    'http://platinumroofingllc.com/',
    17,
    '(541) 326-5015',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-5',
    'Hadley Roofing Inc',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","General Contractors","!Quality Roofing - Roofing Contractors"]',
    1,
    'http://www.hadleyroofinginc.com/',
    51,
    '(541) 779-9545',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-6',
    'Quality Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!Rogue Valley Roofing - Roofing Contractors"]',
    1,
    NULL,
    53,
    '(541) 535-3050',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-7',
    'Rogue Valley Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Services"]',
    1,
    'http://www.roguevalleyroofingco.com/',
    15,
    '(541) 776-6620',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-8',
    'On the Top Roofing Services',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!JAM Roofing - Roofing Contractors"]',
    1,
    'http://www.onthetoproofing.net/',
    NULL,
    '(541) 613-5314',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-9',
    'JAM Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Gutters & Downspouts","Altering & Remodeling Contractors"]',
    1,
    'https://www.jamroofing.com/',
    29,
    '(541) 773-7663',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-10',
    'Purelight Roofing of Medford',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!Roofs 4 Less - Roofing Contractors"]',
    1,
    'https://roofing.purelight.com/locations/medford-oregon',
    NULL,
    '(541) 813-8145',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-11',
    'Roofs 4 Less',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!Rogue Valley Roofing - Roofing Contractors"]',
    1,
    'https://roofs4less.net/',
    NULL,
    '(541) 210-1805',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-12',
    'Rogue Valley Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Insulation Contractors","!All Concepts Roofing - Roofing Contractors"]',
    1,
    'https://www.roguevalleyroofingco.com/',
    NULL,
    '(541) 776-6620',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-13',
    'All Concepts Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!Rogue Valley Roofing - Roofing Contractors"]',
    1,
    'https://www.allconceptsroofingor.com/',
    NULL,
    '(541) 585-3725',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-14',
    'Rogue Valley Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Insulation Contractors","Building Contractors","!RiverCross Construction - Roofing Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 776-6620',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-15',
    'RiverCross Construction',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Painting Contractors","Altering & Remodeling Contractors","!A-1 Classic Roofing - Roofing Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 224-8315',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-16',
    'A-1 Classic Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors"]',
    1,
    'https://www.a1classicroofing.com/',
    NULL,
    '(541) 821-2781',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-17',
    'Medford Perfect Roofing Now',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 210-5042',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-18',
    'Medford Professional Roof Repairs',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!Rogue Valley Roofing - Roofing Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 210-5243',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-19',
    'Rogue Valley Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors"]',
    1,
    'https://www.roguevalleyroofingco.com/',
    NULL,
    '(541) 864-9503',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-20',
    'johnminterconstruction inc.',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!Skye Roofing LLC - Roofing Contractors"]',
    1,
    NULL,
    8,
    '(541) 601-6024',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-21',
    'Skye Roofing LLC',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors"]',
    1,
    'http://skyeroofing.com/',
    12,
    '(541) 941-4630',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-22',
    'McMurray and Sons Roofing & Energy Management',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Insulation Contractors","Air Conditioning Contractors & Systems","!A1-Classic Roofing - Roofing Contractors"]',
    1,
    NULL,
    106,
    '(541) 779-9334',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-23',
    'A1-Classic Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!Alliance Roofing Of Oregon - Roofing Contractors"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 776-7905',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-24',
    'Alliance Roofing Of Oregon',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!911 Handyman - Handyman Services"]',
    1,
    NULL,
    NULL,
    '(541) 660-3646',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-25',
    '911 Handyman',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Handyman Services","Windows-Repair, Replacement & Installation","!Rivas Construction - Home Builders"]',
    1,
    'http://911handyman.com/',
    17,
    '(541) 840-0353',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-26',
    'Rivas Construction',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Home Builders","General Contractors","!Gutter  Rudder LLC - Gutters & Downspouts"]',
    1,
    NULL,
    NULL,
    '(541) 301-5212',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-27',
    'Gutter Rudder LLC',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Gutters & Downspouts","Gutters & Downspouts Cleaning","!Gutt R Done - Gutters & Downspouts"]',
    1,
    'http://www.gutterrudder.com/',
    NULL,
    '(541) 621-1553',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-28',
    'Gutt R Done',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Gutters & Downspouts","!Dabella - Windows"]',
    1,
    'https://guttrdonegutters.com/',
    NULL,
    '(541) 261-3998',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-29',
    'Dabella',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Windows","Home Improvements","!R & S Supply Inc - Roofing Equipment & Supplies"]',
    1,
    'https://dabella.us/location/medford',
    NULL,
    '(844) 322-3552',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-30',
    'R & S Supply Inc',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Roofing Equipment & Supplies","!Medford Gutter Co - Gutters & Downspouts"]',
    1,
    NULL,
    14,
    '(541) 770-1615',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-31',
    'Medford Gutter Co',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Gutters & Downspouts","Building Specialties"]',
    1,
    NULL,
    NULL,
    '(541) 890-4258',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-32',
    'Pressure Point Roofing, Inc',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Roof & Floor Structures","Building Maintenance","!Apex Roofing - Roofing Contractors"]',
    1,
    'https://pressurepointroofing.com/',
    NULL,
    '(541) 772-1945',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-33',
    'Apex Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Gutters & Downspouts","Roofing Services Consultants","!Bleser Built Roofing Inc. - Roofing Contractors"]',
    1,
    NULL,
    30,
    '(541) 890-1234',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-34',
    'Bleser Built Roofing Inc.',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors"]',
    1,
    'http://www.bleserbuiltroofing.com/',
    35,
    '(541) 245-6727',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  );