INSERT INTO businesses (
      id, name, city, state, industry, services, verified, website, 
      yearsInBusiness, phone, address, email, rating, reviewCount, 
      licenseNumber, bbbRating, emergencyService
    ) VALUES (
    'portland-GeneralContractors-71',
    'GSI Builders, Inc.',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!Tamarack Development Corp - General Contractors"]',
    1,
    'https://gsibuildersinc.com/',
    NULL,
    '(971) 407-4436',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-72',
    'Tamarack Development Corp',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","!Petrina Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 317-8332',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-73',
    'Petrina Construction',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Home Improvements","!Stutzman Construction Inc - General Contractors"]',
    1,
    'https://www.petrinaconstruction.com/contact',
    48,
    '(503) 331-1669',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-74',
    'Stutzman Construction Inc',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers"]',
    1,
    NULL,
    NULL,
    '(503) 805-3586',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-75',
    'Western Specialty Contractors',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Building Restoration & Preservation","Waterproofing Contractors"]',
    1,
    'https://thewesterngroup.com/',
    NULL,
    '(503) 222-1644',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-76',
    'Richard Gardner Construction',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!Joseph Ketner Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 789-8403',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-77',
    'Joseph Ketner Construction',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Home Improvements","!Trelstad Construction - General Contractors"]',
    1,
    'https://josephketnerconstruction.com/',
    NULL,
    '(503) 504-7031',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-78',
    'Trelstad Construction',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Watershed Residential - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 805-2199',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-79',
    'Watershed Residential',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Home Improvements","!Paul Albert Anderson - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 869-3275',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-80',
    'Paul Albert Anderson',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","Home Builders","!BMWC Constructors Inc. - General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 539-7942',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-81',
    'BMWC Constructors Inc.',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Mechanical Contractors","Building Contractors-Commercial & Industrial","!Dan Manning PC - General Contractors"]',
    1,
    'http://www.bmwc.com/',
    23,
    '(503) 240-2692',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-82',
    'Dan Manning PC',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders"]',
    1,
    'http://danmanning.com/',
    NULL,
    '(503) 309-5858',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-83',
    'Circle A Contracting & Services',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders"]',
    1,
    NULL,
    NULL,
    '(503) 621-6407',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-84',
    'Smithcraft Fine Construction',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Bathroom Remodeling","Home Improvements","!New Vision Northwest - General Contractors"]',
    1,
    'http://smithcraftpdx.com/',
    26,
    '(503) 773-8000',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-85',
    'New Vision Northwest',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","!Jojapro - General Contractors"]',
    1,
    'https://www.shumaker.com/shumaker-advisors',
    NULL,
    '(503) 810-3522',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-86',
    'Jojapro',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 432-0563',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-87',
    'Hereford Construction Co Inc',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors-Commercial & Industrial","!Goodrich Renovations - General Contractors"]',
    1,
    'https://just81.justhost.com/',
    NULL,
    '(503) 702-4110',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-88',
    'Goodrich Renovations',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 819-8000',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-89',
    'Steven Chesnek Construction',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","Baez Construction"]',
    1,
    'https://www.builtbysteve.com/',
    NULL,
    '(503) 750-9558',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-90',
    'Larry De Hut Construction',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers"]',
    1,
    NULL,
    NULL,
    '(503) 788-5263',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-91',
    'Norwest Contractors',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","Building Contractors-Commercial & Industrial"]',
    1,
    'http://www.norwestgc.com/',
    NULL,
    '(503) 291-6986',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-92',
    'Burns Air Inc',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 312-4982',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-93',
    'Noble Gases',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Gas-Industrial & Medical-Cylinder & Bulk"]',
    1,
    'http://www.noblegasesllc.com/',
    15,
    '(503) 493-7411',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-94',
    'RMJ Construction & Development Inc',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    'http://www.rmjconstruction.com/contact.html',
    NULL,
    '(503) 449-6639',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-95',
    'Baseline Industrial Construction Inc',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers"]',
    1,
    'http://baselineindustrialconstruction.com/',
    NULL,
    '(503) 287-6722',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-96',
    'TH Builders Corp',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    'https://www.thbuilderscorp.com/',
    NULL,
    '(503) 510-7450',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-97',
    'Bittercreek Development Co',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors-Commercial & Industrial"]',
    1,
    'http://bittercreek.com/',
    NULL,
    '(503) 702-9501',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-98',
    'Armac Inc',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    'http://www.armacgc.com/',
    NULL,
    '(503) 280-9657',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-99',
    'Eric Byron Broms Construction Inc',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers"]',
    1,
    NULL,
    NULL,
    '(503) 805-8495',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-100',
    'RJ Ramos Construction and Electrical Co',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Kitchen Planning & Remodeling Service"]',
    1,
    'https://www.rjramosconstruction.com/about-us.php',
    NULL,
    '(503) 233-1435',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-101',
    'FX Repair & Remodeling',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Home Improvements"]',
    1,
    'http://fxrepair.com/',
    37,
    '(503) 542-4442',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-102',
    'Triad Pacific Inc',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Construction Consultants"]',
    1,
    'https://www.triadpacific.com/',
    NULL,
    '(503) 893-2823',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-103',
    'Brandag Construction',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers"]',
    1,
    NULL,
    NULL,
    '(503) 705-2403',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-104',
    'Morrison Construction',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers"]',
    1,
    NULL,
    NULL,
    '(503) 265-8611',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-105',
    'Jasmann Group North West',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors-Commercial & Industrial"]',
    1,
    'http://jasmanngroup.com/',
    NULL,
    '(503) 245-7476',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-106',
    'Zurc Construction LLC',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    'http://www.zurcconstruction.com/',
    NULL,
    '(503) 309-5973',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-107',
    'Meng-Hannan Construction, Inc.',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors-Commercial & Industrial"]',
    1,
    NULL,
    NULL,
    '(503) 761-5290',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-108',
    'Jbw Enterprises',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders"]',
    1,
    NULL,
    NULL,
    '(503) 309-8740',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-109',
    'Senina Construction',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors-Commercial & Industrial"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(503) 756-3831',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-110',
    'Thatcher Construction',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    NULL,
    NULL,
    '(503) 229-4889',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-111',
    'Dream Makers Construction',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(971) 212-4970',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-112',
    'Porter Construction Inc',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Construction Management"]',
    1,
    'https://porterci.com/',
    NULL,
    '(503) 248-2455',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-113',
    'Revive Construction',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Plumbers","Home Builders"]',
    1,
    'http://www.reviveconstruction.net/',
    NULL,
    '(503) 544-3994',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-114',
    'Prolific Construction Service',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","Real Estate Developers"]',
    1,
    NULL,
    NULL,
    '(503) 256-6719',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-115',
    'Payne Construction',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors"]',
    1,
    'http://paynecon.com/',
    44,
    '(503) 257-8221',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-116',
    'Lo''s Contracting, Inc.',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Painting Contractors-Commercial & Industrial"]',
    1,
    'http://www.loscontracting.com/',
    23,
    '(503) 750-3804',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-117',
    'AC General Contracting Inc.',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    'https://www.acgencon.com/',
    NULL,
    '(503) 381-0030',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-GeneralContractors-118',
    'K-Designers - Home Remodeling Leader',
    'Portland',
    'OR',
    'general-contractors',
    '["General Contractors","Windows-Repair, Replacement & Installation"]',
    1,
    'https://www.k-designers.com/portland-oregon-branch',
    NULL,
    '(877) 847-0841',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-1',
    'Casey''s Plumbing Inc',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Altering & Remodeling Contractors","Plumbing-Drain & Sewer Cleaning","!Metro''s Best Electric - Consumer Electronics"]',
    1,
    'http://www.caseysplumbing.com/',
    41,
    '(503) 620-9111',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-2',
    'Metro''s Best Electric',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Consumer Electronics","Electricians"]',
    1,
    'http://www.metrosbestelectric.com/',
    NULL,
    '(503) 643-8833',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-3',
    'Apollo Drain & Rooter Service Inc',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing, Drains & Sewer Consultants","Plumbing Contractors-Commercial & Industrial"]',
    1,
    'http://apollodrain.com/',
    41,
    '(360) 713-0228',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-4',
    'Anytime Plumbing & Drain Cleaning Service',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Sewer Cleaners & Repairers","!B&G Water Heaters LLC - Water Heater Repair"]',
    1,
    'http://www.anytimeplumber.us/',
    15,
    '(503) 894-8241',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-5',
    'B&G Water Heaters LLC',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Water Heater Repair","Plumbing Engineers"]',
    1,
    'http://www.waterheatersnw.com/',
    36,
    '(503) 465-5111',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-6',
    'Pacific Crest Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Water Heaters"]',
    1,
    NULL,
    29,
    '(503) 252-8800',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-7',
    'Happy''s Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing, Drains & Sewer Consultants","Plumbing-Drain & Sewer Cleaning","!The Unplugger - Drainage Contractors"]',
    1,
    'http://happysplumbing.com/',
    23,
    '(503) 788-6947',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-8',
    'The Unplugger',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Drainage Contractors","Basement Contractors","!Paul''s Plumbing Service Co. - Water Heaters"]',
    1,
    NULL,
    17,
    '(503) 853-1421',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-9',
    'Paul''s Plumbing Service Co.',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Water Heaters","Altering & Remodeling Contractors","!Bruner Plumbing - Plumbers"]',
    1,
    'http://paulsplumbingportland.com/',
    36,
    '(503) 652-0078',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-10',
    'Bruner Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers"]',
    1,
    'https://brunerplumbing.com/contact',
    40,
    '(503) 624-4880',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-11',
    'Apollo Drain & Rooter Service Inc',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing, Drains & Sewer Consultants","Plumbing Contractors-Commercial & Industrial","!AAA Drain Cleaning - Drainage Contractors"]',
    1,
    'http://apollodrain.com/',
    NULL,
    '(360) 713-0228',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-12',
    'AAA Drain Cleaning',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Drainage Contractors","Plumbing-Drain & Sewer Cleaning"]',
    1,
    'http://aaadraincleaningportland.com/',
    22,
    '(503) 348-5932',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-13',
    'The Plumber, Inc.',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Plumbing, Drains & Sewer Consultants","!R D Plumbing Inc - Plumbers"]',
    1,
    'http://theplumbersinc.net/',
    18,
    '(503) 519-6644',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-14',
    'R D Plumbing Inc',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Crouchley Plumbing Co., Inc. - Water Heaters"]',
    1,
    NULL,
    34,
    '(503) 297-7422',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-15',
    'Crouchley Plumbing Co., Inc.',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Water Heaters","Sewer Cleaners & Repairers","!Jay Jay''s Plumbing Inc - Water Heaters"]',
    1,
    'http://www.crouchleyplumbing.com/',
    118,
    '(503) 286-4431',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-16',
    'Jay Jay''s Plumbing Inc',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Water Heaters","Sewer Contractors","!Pipe Systems Plumbing - Plumbers"]',
    1,
    NULL,
    49,
    '(503) 667-8420',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-17',
    'Pipe Systems Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Red Roo Plumbing - Plumbers"]',
    1,
    'http://pipesystems.weebly.com/photo-page.html',
    NULL,
    '(503) 895-8609',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-18',
    'Red Roo Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!ProDrain & Rooter Service - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 319-9045',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-19',
    'ProDrain & Rooter Service',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing Contractors-Commercial & Industrial","!Just Plumbing Co - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 912-8822',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-20',
    'Just Plumbing Co',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers"]',
    1,
    'https://justplumbing.co/',
    NULL,
    '(503) 260-0901',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-21',
    'Montavilla Plumbing Co',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Sewer Contractors"]',
    1,
    NULL,
    78,
    '(503) 254-2322',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-22',
    'Affordable Drain & Rooter',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Bathtubs & Sinks-Repair & Refinish","!Roto-Rooter Plumbing & Water Cleanup - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 353-0110',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-23',
    'Roto-Rooter Plumbing & Water Cleanup',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Water Heater Repair","Sewer Contractors","Online Specials","!Mick''s Plumbing - Plumbers"]',
    1,
    'https://www.rotorooter.com/portland/?utm_source=iyp&utm_medium=paid&utm_campaign=iyp',
    90,
    '(971) 314-0126',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-24',
    'Mick''s Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","!FX Repair & Remodeling - Building Contractors"]',
    1,
    'https://www.micksplumbing.com/',
    17,
    '(503) 406-8118',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-25',
    'FX Repair & Remodeling',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Home Repair & Maintenance","Building Contractors"]',
    1,
    'http://www.fxrepair.com/',
    36,
    '(503) 542-4442',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-26',
    '1st Call Plumbing & Drain Cleaning',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning"]',
    1,
    'http://www.1stcallplumbing.net/index.html',
    NULL,
    '(971) 409-7463',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-27',
    'D&F Plumbing, Heating and Cooling',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Heating Contractors & Specialties","Plumbing-Drain & Sewer Cleaning"]',
    1,
    'https://dandfplumbing.com/?utm_source=google&utm_medium=organic&utm_campaign=local+listingsportland',
    98,
    '(503) 664-0938',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-28',
    'Central Air Heating, Cooling & Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Air Conditioning Service & Repair","Air Conditioning Equipment & Systems"]',
    1,
    'https://www.centralairpdx.com/',
    24,
    '(971) 435-7303',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-29',
    'HomeTekk',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Draperies, Curtains & Window Treatments","General Contractors","!Rose City Handyman - Handyman Services"]',
    1,
    NULL,
    12,
    '(360) 609-6932',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-30',
    'Rose City Handyman',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Handyman Services","General Contractors"]',
    1,
    'https://www.rosecityhandyman.co/',
    NULL,
    '(503) 484-5741',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-31',
    'Casey''s Plumbing Inc',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Altering & Remodeling Contractors","Plumbing-Drain & Sewer Cleaning","!Metro''s Best Electric - Consumer Electronics"]',
    1,
    'http://www.caseysplumbing.com/',
    41,
    '(503) 620-9111',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-32',
    'Metro''s Best Electric',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Consumer Electronics","Electricians"]',
    1,
    'http://www.metrosbestelectric.com/',
    NULL,
    '(503) 643-8833',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-33',
    'Apollo Drain & Rooter Service Inc',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing, Drains & Sewer Consultants","Plumbing Contractors-Commercial & Industrial"]',
    1,
    'http://apollodrain.com/',
    41,
    '(360) 713-0228',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-34',
    'Anytime Plumbing & Drain Cleaning Service',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Sewer Cleaners & Repairers","!B&G Water Heaters LLC - Water Heater Repair"]',
    1,
    'http://www.anytimeplumber.us/',
    15,
    '(503) 894-8241',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-35',
    'B&G Water Heaters LLC',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Water Heater Repair","Plumbing Engineers"]',
    1,
    'http://www.waterheatersnw.com/',
    36,
    '(503) 465-5111',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-36',
    'Pacific Crest Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Water Heaters"]',
    1,
    NULL,
    29,
    '(503) 252-8800',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-37',
    'Happy''s Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing, Drains & Sewer Consultants","Plumbing-Drain & Sewer Cleaning","!The Unplugger - Drainage Contractors"]',
    1,
    'http://happysplumbing.com/',
    23,
    '(503) 788-6947',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-38',
    'The Unplugger',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Drainage Contractors","Basement Contractors","!Paul''s Plumbing Service Co. - Water Heaters"]',
    1,
    NULL,
    17,
    '(503) 853-1421',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-39',
    'Paul''s Plumbing Service Co.',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Water Heaters","Altering & Remodeling Contractors","!Bruner Plumbing - Plumbers"]',
    1,
    'http://paulsplumbingportland.com/',
    36,
    '(503) 652-0078',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-40',
    'Bruner Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers"]',
    1,
    'https://brunerplumbing.com/contact',
    40,
    '(503) 624-4880',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-41',
    'Apollo Drain & Rooter Service Inc',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing, Drains & Sewer Consultants","Plumbing Contractors-Commercial & Industrial","!AAA Drain Cleaning - Drainage Contractors"]',
    1,
    'http://apollodrain.com/',
    NULL,
    '(360) 713-0228',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-42',
    'AAA Drain Cleaning',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Drainage Contractors","Plumbing-Drain & Sewer Cleaning"]',
    1,
    'http://aaadraincleaningportland.com/',
    22,
    '(503) 348-5932',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-43',
    'The Plumber, Inc.',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Plumbing, Drains & Sewer Consultants","!R D Plumbing Inc - Plumbers"]',
    1,
    'http://theplumbersinc.net/',
    18,
    '(503) 519-6644',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-44',
    'R D Plumbing Inc',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Crouchley Plumbing Co., Inc. - Water Heaters"]',
    1,
    NULL,
    34,
    '(503) 297-7422',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-45',
    'Crouchley Plumbing Co., Inc.',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Water Heaters","Sewer Cleaners & Repairers","!Jay Jay''s Plumbing Inc - Water Heaters"]',
    1,
    'http://www.crouchleyplumbing.com/',
    118,
    '(503) 286-4431',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-46',
    'Jay Jay''s Plumbing Inc',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Water Heaters","Sewer Contractors","!Pipe Systems Plumbing - Plumbers"]',
    1,
    NULL,
    49,
    '(503) 667-8420',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-47',
    'Pipe Systems Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Red Roo Plumbing - Plumbers"]',
    1,
    'http://pipesystems.weebly.com/photo-page.html',
    NULL,
    '(503) 895-8609',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-48',
    'Red Roo Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!ProDrain & Rooter Service - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 319-9045',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-49',
    'ProDrain & Rooter Service',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing Contractors-Commercial & Industrial","!Just Plumbing Co - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 912-8822',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-50',
    'Just Plumbing Co',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers"]',
    1,
    'https://justplumbing.co/',
    NULL,
    '(503) 260-0901',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-51',
    'Montavilla Plumbing Co',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Sewer Contractors"]',
    1,
    NULL,
    78,
    '(503) 254-2322',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-52',
    'Affordable Drain & Rooter',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Bathtubs & Sinks-Repair & Refinish","!Roto-Rooter Plumbing & Water Cleanup - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 353-0110',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  );