INSERT INTO businesses (
      id, name, city, state, industry, services, verified, website, 
      yearsInBusiness, phone, address, email, rating, reviewCount, 
      licenseNumber, bbbRating, emergencyService
    ) VALUES (
    'medford-Roofers-35',
    'Renaissance Roofing Southern Oregon',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors"]',
    1,
    'http://www.renaissanceroofingso.com/contact-us',
    NULL,
    '(541) 772-1096',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-36',
    'Stephen Westfall Roofing Inc',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!Realty Roofing - Roofing Contractors"]',
    1,
    'http://www.stephenwestfallroofinginc.com/',
    NULL,
    '(541) 941-3736',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-37',
    'Realty Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!Evergreen Roofing - Roofing Contractors"]',
    1,
    'https://realtyroofingllc.com/',
    NULL,
    '(541) 261-8390',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-38',
    'Evergreen Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","General Contractors","!CamoRidge - Roofing Contractors"]',
    1,
    'http://www.evergreenroofinginc.com/',
    44,
    '(541) 826-5869',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-39',
    'CamoRidge',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!Robinson''s Quality Roofing - Roofing Contractors"]',
    1,
    'http://www.camoridge.com/',
    NULL,
    '(541) 841-3350',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-40',
    'Robinson''s Quality Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors"]',
    1,
    'https://robinsonsroofingor.wixsite.com/robinsonsroofing',
    NULL,
    '(541) 301-0987',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-41',
    'Joel Stephenson Roofing & Construction',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Carpenters"]',
    1,
    'http://www.jfsroofing.com/',
    32,
    '(541) 890-3884',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-42',
    'John Minter Construction Inc',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!Grizzly Roofing - Roofing Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 601-6024',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-43',
    'Grizzly Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!Hoag Roofing - Roofing Contractors"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 512-9699',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-44',
    'Hoag Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Building Contractors","General Contractors"]',
    1,
    'http://hoagroofing.com/',
    70,
    '(541) 779-7743',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-45',
    'Phoenix Re Roofs & Roofing Co',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!Red''s Roofing - Roofing Contractors"]',
    1,
    NULL,
    NULL,
    '(458) 214-0125',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-46',
    'Red''s Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!Fontana Roofing, Inc - Roofing Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 821-6717',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-47',
    'Fontana Roofing, Inc',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","General Contractors","!Arrons Roofing - Roofing Contractors"]',
    1,
    'http://www.fontanaroofingservices.com/',
    NULL,
    '(541) 826-5595',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-48',
    'Arrons Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!Talent Refresh Roofing - Roofing Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 613-5265',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-49',
    'Talent Refresh Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!Keppler G & S - Roofing Contractors"]',
    1,
    NULL,
    NULL,
    '(458) 214-0042',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-50',
    'Keppler G & S',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!Fontana Roofing - Roofing Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 826-5869',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-51',
    'Fontana Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!Robinson Quality Roofing - Roofing Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 826-5595',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-52',
    'Robinson Quality Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!Robinson Quality Roofing - Roofing Contractors"]',
    1,
    'https://robinsonsroofingor.wixsite.com/robinsonsroofing',
    NULL,
    '(541) 535-3050',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-53',
    'Robinson Quality Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 708-6333',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-54',
    'White City Roofing Inspection',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 210-5269',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-55',
    'affordable roofing and const',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors"]',
    1,
    NULL,
    9,
    '(541) 930-2292',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-56',
    'GB Roofing & Construction, Inc.',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!On The Top Roofing - Roofing Contractors"]',
    1,
    NULL,
    32,
    '(541) 621-7304',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-57',
    'On The Top Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!GMR Construction LLC - Roofing Contractors"]',
    1,
    'http://soroofing.com/',
    NULL,
    '(541) 613-5314',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-58',
    'GMR Construction LLC',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!Rogue Valley Roofing - Roofing Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 414-4433',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-59',
    'Rogue Valley Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!Guaranteed Roofing - Roofing Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 582-8999',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-60',
    'Guaranteed Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!Medford Roofing - Roofing Contractors"]',
    1,
    NULL,
    46,
    '(541) 535-5013',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-61',
    'Medford Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!Jam Roofing - Roofing Contractors"]',
    1,
    'http://renaissanceroofing.net/',
    NULL,
    '(541) 858-5824',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-62',
    'Jam Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!J & J Building Specialists - Roofing Contractors"]',
    1,
    'http://www.jamroofing.com/',
    29,
    '(541) 601-1221',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-63',
    'J & J Building Specialists',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!Orezona Bldg & Roofing Co. - Roofing Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 951-5002',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-64',
    'Orezona Bldg & Roofing Co.',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!Skye Roofing - Roofing Contractors"]',
    1,
    'http://www.orezonabc.com/',
    26,
    '(541) 210-5180',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-65',
    'Skye Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!Rogue Valley Roofing - Roofing Contractors"]',
    1,
    'http://www.skyeroofing.com/',
    NULL,
    '(541) 414-6004',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-66',
    'Rogue Valley Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!Robinson Roofing - Roofing Contractors"]',
    1,
    'https://www.roguevalleyroofingco.com/roofing-ashland-oregon',
    NULL,
    '(541) 821-9503',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-67',
    'Robinson Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!Fontana Roofing - Roofing Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 488-2988',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-68',
    'Fontana Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!Armadillo Roofing Inc. - Roofing Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 944-5386',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-69',
    'Armadillo Roofing Inc.',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!Riverside Roofing - Roofing Contractors"]',
    1,
    'http://www.armadilloroofinginc.com/',
    NULL,
    '(541) 512-6178',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-70',
    'Riverside Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Altering & Remodeling Contractors","Home Improvements"]',
    1,
    NULL,
    NULL,
    '(541) 535-8083',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-71',
    'Jacksonville Residential Roofing Repair',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Gutters & Downspouts"]',
    1,
    'https://voxservices.net/roofing/jacksonville/or/40323/jacksonville%20residential%20roofing%20repair',
    14,
    '(458) 459-3211',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-72',
    'Ashland Residential Roofing Repair',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Gutters & Downspouts","!Lawless Roofing Co - Roofing Contractors"]',
    1,
    'https://voxservices.net/roofing/ashland/or/32798/ashland%20residential%20roofing%20repair',
    19,
    '(458) 246-1868',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-73',
    'Lawless Roofing Co',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Home Builders","General Contractors","!Roofmasters - Roofing Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 773-8061',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-74',
    'Roofmasters',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 608-1620',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-75',
    'Henris Roofing & Supply of Oregon Inc',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","!Roof Remedy - Roof Cleaning"]',
    1,
    NULL,
    NULL,
    '(541) 776-9993',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-76',
    'Roof Remedy',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Roof Cleaning","Cleaning Contractors","!PARR Truss Phoenix - Building Materials"]',
    1,
    'https://www.roofremedy.com/',
    NULL,
    '(541) 500-0890',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-77',
    'PARR Truss Phoenix',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Building Materials","Altering & Remodeling Contractors","!SRS Building Products - Building Materials"]',
    1,
    NULL,
    95,
    '(541) 535-1533',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-78',
    'SRS Building Products',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Building Materials","Roofing Equipment & Supplies","!Norton Lumber - Building Materials"]',
    1,
    'https://www.srsdistribution.com/en/markets/our-brands/RLMED',
    NULL,
    '(541) 830-3040',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-79',
    'Norton Lumber',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Building Materials","!Adair Homes - Home Builders"]',
    1,
    'http://www.nortonlumber.com/',
    75,
    '(541) 622-2335',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-80',
    'Adair Homes',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Home Builders","Altering & Remodeling Contractors","!The Truss Co - Roof Trusses"]',
    1,
    'http://www.adairhomesmedford.com/',
    NULL,
    '(541) 879-0610',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-81',
    'The Truss Co',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Roof Trusses","Trusses-Construction","!Gentlemen Builders - Carpenters"]',
    1,
    NULL,
    32,
    '(541) 930-3300',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-82',
    'Gentlemen Builders',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Carpenters","Building Contractors","!Gutt-R-Done - Gutters & Downspouts"]',
    1,
    NULL,
    NULL,
    '(541) 531-9136',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-83',
    'Gutt-R-Done',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Gutters & Downspouts"]',
    1,
    'http://www.guttrdone.com/',
    NULL,
    '(541) 261-3998',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-84',
    'The Home Inspector Inc',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Real Estate Inspection Service","Inspection Service","!George B. Kostal Roofing - Home Improvements"]',
    1,
    'https://hillsborofood.coop/',
    NULL,
    '(541) 826-1097',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-85',
    'George B. Kostal Roofing',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Home Improvements","Services"]',
    1,
    NULL,
    NULL,
    '(541) 472-1361',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-86',
    'Bleser Built Roofing Inc',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Roofing Equipment & Supplies","Altering & Remodeling Contractors","!Gutt-R-Done Gutters - Gutters & Downspouts"]',
    1,
    'http://www.bleserbuiltroofing.com/',
    35,
    '(541) 830-0226',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-87',
    'Gutt-R-Done Gutters',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Gutters & Downspouts"]',
    1,
    'http://guttrdonegutters.com/',
    NULL,
    '(541) 261-3998',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-88',
    'Platinum Roofing & Gutters',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Gutters & Downspouts","Altering & Remodeling Contractors","!Diamond Exterior Cleaning - Roof Cleaning"]',
    1,
    'http://www.platinumroofingllc.com/',
    60,
    '(541) 622-2331',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-89',
    'Diamond Exterior Cleaning',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Roof Cleaning","Cleaning Contractors","!North Coast Construction - Home Builders"]',
    1,
    'https://diamondexteriorcleaningllc.com/',
    NULL,
    '(541) 816-0500',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'medford-Roofers-90',
    'North Coast Construction',
    'Medford',
    'OR',
    'roofers',
    '["Roofing Contractors","Home Builders","Building Contractors-Commercial & Industrial"]',
    1,
    NULL,
    NULL,
    '(541) 621-8008',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Electricians-1',
    'Double J Electric inc.',
    'Grants Pass',
    'OR',
    'electricians',
    '["Electricians","Solar Energy Equipment & Systems-Dealers","Generators-Electric-Service & Repair","!Pro Electric - Electricians"]',
    1,
    'http://www.doublejelectricinc.com/',
    12,
    '(541) 237-1224',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Electricians-2',
    'Pro Electric',
    'Grants Pass',
    'OR',
    'electricians',
    '["Electricians","Lighting Contractors","Lighting Fixtures","!Power Co - Electric Companies"]',
    1,
    'http://proelectricincgp.com/',
    34,
    '(541) 787-2074',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Electricians-3',
    'Power Co',
    'Grants Pass',
    'OR',
    'electricians',
    '["Electric Companies","!York Electic - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 660-3696',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Electricians-4',
    'York Electic',
    'Grants Pass',
    'OR',
    'electricians',
    '["Electricians","!ER Electric Service - Electricians"]',
    1,
    'http://yorkelectric.net/',
    NULL,
    '(541) 474-0507',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Electricians-5',
    'ER Electric Service',
    'Grants Pass',
    'OR',
    'electricians',
    '["Electricians","Electric Contractors-Commercial & Industrial","!Er Electric Service Inc - Electricians"]',
    1,
    NULL,
    12,
    '(541) 476-1158',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Electricians-6',
    'Er Electric Service Inc',
    'Grants Pass',
    'OR',
    'electricians',
    '["Electricians","!E R Electric Service Inc - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 476-1158',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Electricians-7',
    'E R Electric Service Inc',
    'Grants Pass',
    'OR',
    'electricians',
    '["Electricians","!Brownell''s Electric - Electricians"]',
    1,
    'https://business.grantspasschamber.org/list',
    NULL,
    '(541) 476-1158',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Electricians-8',
    'Brownell''s Electric',
    'Grants Pass',
    'OR',
    'electricians',
    '["Electricians","General Contractors","!Double J Electric Inc - Electricians"]',
    1,
    'https://www.brownellselectric.com/',
    NULL,
    '(541) 476-3674',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Electricians-9',
    'Double J Electric Inc',
    'Grants Pass',
    'OR',
    'electricians',
    '["Electricians","Solar Energy Equipment & Systems-Dealers","!Michael R Gatt Electric - Electricians"]',
    1,
    'http://www.doublejelectricinc.com/',
    NULL,
    '(541) 479-4489',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Electricians-10',
    'Michael R Gatt Electric',
    'Grants Pass',
    'OR',
    'electricians',
    '["Electricians","!Golden West Electric - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 474-0924',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Electricians-11',
    'Golden West Electric',
    'Grants Pass',
    'OR',
    'electricians',
    '["Electricians","Electric Contractors-Commercial & Industrial","!Pro Electric, Inc. - Electricians"]',
    1,
    'http://goldenweste.com/',
    NULL,
    '(541) 474-4545',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Electricians-12',
    'Pro Electric, Inc.',
    'Grants Pass',
    'OR',
    'electricians',
    '["Electricians","Solar Energy Equipment & Systems-Dealers","Building Contractors-Commercial & Industrial","!Helco Electric - Electricians"]',
    1,
    'http://www.proelectricincgp.com/',
    NULL,
    '(541) 474-7943',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Electricians-13',
    'Helco Electric',
    'Grants Pass',
    'OR',
    'electricians',
    '["Electricians","!Service Electric - Electricians"]',
    1,
    'http://www.helcoelec.com/',
    NULL,
    '(541) 474-4626',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Electricians-14',
    'Service Electric',
    'Grants Pass',
    'OR',
    'electricians',
    '["Electricians","!Truroy Electric - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 218-6430',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Electricians-15',
    'Truroy Electric',
    'Grants Pass',
    'OR',
    'electricians',
    '["Electricians","!The Power Company - Electric Companies"]',
    1,
    NULL,
    NULL,
    '(541) 479-6059',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Electricians-16',
    'The Power Company',
    'Grants Pass',
    'OR',
    'electricians',
    '["Electricians","Electric Companies"]',
    1,
    NULL,
    NULL,
    '(541) 476-1081',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Electricians-17',
    'Brownell''s Electric',
    'Grants Pass',
    'OR',
    'electricians',
    '["Electricians","Electric Equipment Repair & Service","Building Contractors"]',
    1,
    'http://www.brownellselectric.com/',
    103,
    '(541) 476-3674',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Electricians-18',
    'Boggs Electric',
    'Grants Pass',
    'OR',
    'electricians',
    '["Electricians","Electric Equipment Repair & Service","Home Theater Systems"]',
    1,
    'http://boggselectricgp.com/',
    NULL,
    '(541) 441-7900',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Electricians-19',
    'Wally Schmidt Electric Inc',
    'Grants Pass',
    'OR',
    'electricians',
    '["Electricians","Controls, Control Systems & Regulators","Industrial Equipment & Supplies","!Hy-Tech Electric Inc - Electrical Engineers"]',
    1,
    NULL,
    NULL,
    '(541) 479-8016',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Electricians-20',
    'Hy-Tech Electric Inc',
    'Grants Pass',
    'OR',
    'electricians',
    '["Electricians","Electrical Engineers","!JP Electric LLC - Electricians"]',
    1,
    'http://hy-techelectric.com/',
    NULL,
    '(541) 210-0327',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Electricians-21',
    'JP Electric LLC',
    'Grants Pass',
    'OR',
    'electricians',
    '["Electricians","Switches-Electric","Electronic Equipment & Supplies-Repair & Service","!Advanced Electrical Services - Electricians"]',
    1,
    'http://www.jpelectriconline.com/',
    NULL,
    '(541) 659-2996',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Electricians-22',
    'Advanced Electrical Services',
    'Grants Pass',
    'OR',
    'electricians',
    '["Electricians","!Parkaway Enterprises Inc - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 761-1670',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Electricians-23',
    'Parkaway Enterprises Inc',
    'Grants Pass',
    'OR',
    'electricians',
    '["Electricians","!Precision Electric - Electricians"]',
    1,
    'http://cavemanautoparts.com/',
    NULL,
    '(541) 955-5246',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Electricians-24',
    'Precision Electric',
    'Grants Pass',
    'OR',
    'electricians',
    '["Electricians","!Sky Electric Inc - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 472-1425',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Electricians-25',
    'Sky Electric Inc',
    'Grants Pass',
    'OR',
    'electricians',
    '["Electricians","!Kindys Electric - Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 659-9707',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Electricians-26',
    'Kindys Electric',
    'Grants Pass',
    'OR',
    'electricians',
    '["Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 476-1793',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Electricians-27',
    'Greenwing Electric and Solar',
    'Grants Pass',
    'OR',
    'electricians',
    '["Electricians","Solar Energy Equipment & Systems-Dealers","!Jordan Power Plus - Generators"]',
    1,
    'https://www.greenwingelectricandsolar.com/',
    NULL,
    '(541) 204-1529',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Electricians-28',
    'Jordan Power Plus',
    'Grants Pass',
    'OR',
    'electricians',
    '["Electricians","Generators","!Murphy Electric - Electricians"]',
    1,
    'http://jordanpowerplus.com/',
    14,
    '(541) 218-4580',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Electricians-29',
    'Murphy Electric',
    'Grants Pass',
    'OR',
    'electricians',
    '["Electricians","Generators","!McCarthy Electric - Electricians"]',
    1,
    'http://www.pjmurphyelectric.com/',
    47,
    '(541) 582-4186',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Electricians-30',
    'McCarthy Electric',
    'Grants Pass',
    'OR',
    'electricians',
    '["Electricians"]',
    1,
    NULL,
    NULL,
    '(541) 582-0389',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-1',
    'Oliphant Construction Inc',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers"]',
    1,
    'http://oliphant-construction.com/',
    NULL,
    '(541) 761-3644',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-2',
    'Schmitke Dennis Custom Builder',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Home Improvements"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 476-0429',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-3',
    'Nathan Davidson''s Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Carpet & Rug Cleaners","!Ryan Wilson Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 570-0901',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-4',
    'Ryan Wilson Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers"]',
    1,
    NULL,
    NULL,
    '(541) 244-0633',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-5',
    'All Phases Land Development',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors-Commercial & Industrial","!M & J Construction - General Contractors"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 476-5239',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-6',
    'M & J Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","!Johnson Builders Corp. - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 659-5304',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-7',
    'Johnson Builders Corp.',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","Home Improvements","!Shawn Cobb Construction - General Contractors"]',
    1,
    'http://oregonbuilders.com/',
    NULL,
    '(541) 479-1465',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-8',
    'Shawn Cobb Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Home Improvements","Kitchen Planning & Remodeling Service","!Jon Hughes Construction - General Contractors"]',
    1,
    'http://www.shawncobbconstructionllc.com/',
    NULL,
    '(541) 228-8654',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-9',
    'Jon Hughes Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","!JNP Construction Services - General Contractors"]',
    1,
    'https://jonhughesconstruction.com/',
    NULL,
    '(541) 660-7805',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-10',
    'JNP Construction Services',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","!R Crume Construction Inc - General Contractors"]',
    1,
    'https://www.thejnpllc.com/',
    NULL,
    '(541) 207-9988',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-11',
    'R Crume Construction Inc',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Eastwood Homes - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 660-3434',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-12',
    'Eastwood Homes',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","Real Estate Developers"]',
    1,
    NULL,
    NULL,
    '(541) 476-8640',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-13',
    'Bright & Morning Star Construction',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!J & L Builders Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 659-3896',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-General-Contractors-14',
    'J & L Builders Inc',
    'Grants Pass',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Wrc Construction Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 659-1235',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  );