INSERT INTO businesses (
      id, name, city, state, industry, services, verified, website, 
      yearsInBusiness, phone, address, email, rating, reviewCount, 
      licenseNumber, bbbRating, emergencyService
    ) VALUES (
    'portland-RealEstateAgents-14',
    'Georgetown Realty',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate","Real Estate Buyer Brokers"]',
    1,
    'http://www.gtrealty.com/',
    NULL,
    '(503) 256-1112',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-15',
    'Peter Park, J.D., Real Estate Agent',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Bellmoore Realty - Real Estate Agents"]',
    1,
    'http://www.pdxlisted.com/',
    10,
    '(503) 686-0138',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-16',
    'Bellmoore Realty',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Andy Arthur, Realtor - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 683-2626',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-17',
    'Andy Arthur, Realtor',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(971) 732-6264',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-18',
    'Coldwell Banker Bain of Portland Uptown',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Vacation Homes Rentals & Sales","Real Estate Consultants","View all 4 Locations","!Pohl Real Estate - Real Estate Agents"]',
    1,
    'http://www.coldwellbankerbain.com/portlanduptown',
    42,
    '(503) 224-7325',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-19',
    'Pohl Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Portland Digs Real Estate - Real Estate Agents"]',
    1,
    'http://pohlrealestate.com/',
    NULL,
    '(503) 488-5848',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-20',
    'Portland Digs Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Pacific Sierra Corporation - Real Estate Agents"]',
    1,
    'http://www.portlanddigs.com/',
    53,
    '(503) 239-7400',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-21',
    'Pacific Sierra Corporation',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Real Estate Roofing - Real Estate Agents"]',
    1,
    'http://homepackages.com/',
    NULL,
    '(503) 297-8242',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-22',
    'Real Estate Roofing',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Carnahan Smith & Gunter - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 284-5522',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-23',
    'Carnahan Smith & Gunter',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Century 21 Hart Realty - Real Estate Agents"]',
    1,
    'http://breakthruz.com/',
    NULL,
    '(503) 244-6701',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-24',
    'Century 21 Hart Realty',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Consultants","View all 5 Locations"]',
    1,
    'http://www.century21hart.com/',
    24,
    '(503) 939-6091',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-25',
    'Peggy Hoag Group at HOAG REAL ESTATE',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","Commercial Real Estate","!H Dwayne Davis Group - Real Estate Agents"]',
    1,
    'https://www.peggyhoag.com/',
    NULL,
    '(503) 906-1370',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-26',
    'H Dwayne Davis Group',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Corcoran Prime - Real Estate Agents"]',
    1,
    'http://portlandrealestate.team/',
    NULL,
    '(503) 319-4057',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-27',
    'Corcoran Prime',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Colliers International - Real Estate Agents"]',
    1,
    'https://corcoranprime.com/',
    NULL,
    '(503) 321-2000',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-28',
    'Colliers International',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Consultants","!Newmark - Real Estate Agents"]',
    1,
    'https://www2.colliers.com/en/United-States/Cities/Portland',
    NULL,
    '(503) 282-7888',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-29',
    'Newmark',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Schnitzer Properties - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 241-1155',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-30',
    'Schnitzer Properties',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Developers","Real Estate Buyer Brokers","!Joe Kellogg Real Estate - Real Estate Agents"]',
    1,
    'https://schnitzerproperties.com/',
    NULL,
    '(503) 242-2900',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-31',
    'Joe Kellogg Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Windermere Real Estate - Real Estate Agents"]',
    1,
    'https://joekellogg.withwre.com/columbiacounty',
    NULL,
    '(503) 621-7088',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-32',
    'Windermere Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!C B Commercial Real Estate - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 294-1101',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-33',
    'C B Commercial Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate","!Paul Sardoch - Realtor - Real Estate Agents"]',
    1,
    'http://www.bencocre.com/',
    NULL,
    '(503) 221-4851',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-34',
    'Paul Sardoch - Realtor',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Investing","Commercial Real Estate","!Collective on 4th - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 913-7615',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-35',
    'Collective on 4th',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Rental Service","!Meadows Group Inc - Real Estate Agents"]',
    1,
    'https://collectiveon4th.com/',
    NULL,
    '(503) 208-5786',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-36',
    'Meadows Group Inc',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://www.johnlscott.com/',
    NULL,
    '(503) 705-2546',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-37',
    'Paul Sardoch - Oregon Licensed Realtor - Realty ONE Group Presti',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Cbre - Real Estate Agents"]',
    1,
    'http://sardoch.com/',
    NULL,
    '(503) 913-7615',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-38',
    'Cbre',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate","!Graham Marden, Realtor - Real Estate Agents"]',
    1,
    'https://www.cbre.com/offices/corporate/portland-or',
    NULL,
    '(503) 221-1900',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-39',
    'Graham Marden, Realtor',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!The Amico Group - Real Estate Agents"]',
    1,
    'http://www.oregon-floating-homes.com/',
    NULL,
    '(503) 807-4504',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-40',
    'The Amico Group',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Jamie Gardner, REALTOR - Real Estate Agents"]',
    1,
    'http://theamicogroup.com/',
    NULL,
    '(503) 802-6446',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-41',
    'Jamie Gardner, REALTOR',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","!Susie Hunt Moran, REALTOR - Real Estate Agents"]',
    1,
    'http://jamiegardnerrealestate.com/',
    7,
    '(503) 449-8999',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-42',
    'Susie Hunt Moran, REALTOR',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","Real Estate Buyer Brokers"]',
    1,
    'https://susiehuntmoran.com/',
    18,
    '(503) 970-9866',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-43',
    'Dennison Capen Group - Windermere Realty Trust',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    'http://windermereportland.com/',
    NULL,
    '(503) 809-2876',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-44',
    'CORCORAN GLOBAL LIVING - Becky Jackson',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Own It Northwest - Real Estate Agents"]',
    1,
    'https://www.corcoran.com/real-estate-agents/detail/detail/123095/regionId/138',
    42,
    '(503) 680-1440',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-45',
    'Own It Northwest',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","!Rappold Property Management - Real Estate Agents"]',
    1,
    'http://www.ownitnorthwest.com/',
    20,
    '(503) 862-9075',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-46',
    'Rappold Property Management',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","!Brian Ramsay, Realtor - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 232-5990',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-47',
    'Brian Ramsay, Realtor',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    NULL,
    24,
    '(503) 380-6990',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-48',
    'Cascade Hasson Sotheby''s International Realty',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://www.cascadehasson.com/',
    NULL,
    '(503) 635-9801',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-49',
    'Breylan Deal-Eriksen, REALTOR',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","!Windermere Real Estate - Real Estate Agents"]',
    1,
    'https://www.breylan.com/',
    11,
    '(503) 953-0253',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-50',
    'Windermere Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Morgan Davis Homes - Real Estate Agents"]',
    1,
    'https://windermereportland.com/portland-heights',
    NULL,
    '(503) 227-5500',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-51',
    'Morgan Davis Homes',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'http://www.morgandavishomes.com/',
    29,
    '(503) 748-8200',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-52',
    'The Russell Apartments Portland',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://trionliving.com/apartments/the-russell-apartments',
    NULL,
    '(503) 234-0664',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-53',
    'Christina Hamilton, REALTOR | Re/Max Equity Group',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","Real Estate Buyer Brokers","View all 33 Locations","!Moore, Elliott, RLTR - Real Estate Agents"]',
    1,
    'http://chrishamiltononline.com/',
    35,
    '(503) 860-4498',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-54',
    'Moore, Elliott, RLTR',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://elliottmoore.com/',
    NULL,
    '(503) 320-6582',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-55',
    'Harlan Mayer, Realtor - RealEstatePDX',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Investing","Real Estate Buyer Brokers","!Day, Rachel, RLTR - Real Estate Agents"]',
    1,
    'https://realestatepdx.com/',
    22,
    '(503) 288-3979',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-56',
    'Day, Rachel, RLTR',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Sean Z Becker Real Estate - Real Estate Agents"]',
    1,
    'https://www.realtyworksgroup.com/agents/1719514/Rachel+Day',
    NULL,
    '(503) 212-0085',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-57',
    'Sean Z Becker Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Wilson Townhomes - Real Estate Agents"]',
    1,
    'http://www.seanzbecker.com/',
    NULL,
    '(503) 444-7400',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-58',
    'Wilson Townhomes',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Rental Service","!Peggy Hoag Real Estate - Real Estate Agents"]',
    1,
    'https://www.wilsonnwpdx.com/',
    NULL,
    '(855) 670-1727',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-59',
    'Peggy Hoag Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Hardy Garner Properties Inc - Real Estate Agents"]',
    1,
    'https://www.peggyhoag.com/',
    NULL,
    '(503) 906-1370',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-60',
    'Hardy Garner Properties Inc',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Paris Group Realty, LLC - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 515-3842',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-61',
    'Paris Group Realty, LLC',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Matin Real Estate - Real Estate Agents"]',
    1,
    'http://parisgrouprealty.com/',
    21,
    '(503) 998-4878',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-62',
    'Matin Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://www.portlandrealestate.com/',
    NULL,
    '(503) 622-9624',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-63',
    'Check Point Realty - Adriana Focke',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Appraisers","!Upsource - Real Estate Agents"]',
    1,
    'https://www.adrianafocke.realtor/',
    NULL,
    '(503) 755-9493',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-64',
    'Upsource',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'http://upsource.com/',
    NULL,
    '(800) 893-2590',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-65',
    'Summa Real Estate Associates',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!The Broker Network - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 477-6438',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-66',
    'The Broker Network',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Windermere Real Estate - Real Estate Agents"]',
    1,
    'http://www.thebrokernetworkrealty.com/',
    NULL,
    '(503) 928-5606',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-67',
    'Windermere Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Corporate - Real Estate Agents"]',
    1,
    'http://windermeremoreland.com/',
    NULL,
    '(503) 233-7777',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-68',
    'Corporate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Remax - Real Estate Agents"]',
    1,
    'https://www.milestonepm.net/',
    NULL,
    '(503) 297-2542',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-69',
    'Remax',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Consultants","!Eggerts Realty Team - Real Estate Agents"]',
    1,
    'http://www.remax.com/',
    NULL,
    '(503) 233-8883',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-70',
    'Eggerts Realty Team',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants"]',
    1,
    'https://www.urbannestpdx.com/anna-eggerts',
    30,
    '(503) 380-1092',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-71',
    'Love, Christopher Realtor-Chris Love Realtor',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://christopherjl.johnlscott.com/',
    NULL,
    '(503) 957-6087',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-72',
    'Dawn Cordiner Local Real Estate Team',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Shona Buys Houses - Real Estate Agents"]',
    1,
    'https://www.dawncordiner.com/',
    NULL,
    '(503) 309-0093',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-73',
    'Shona Buys Houses',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants"]',
    1,
    'https://www.shonabuyshouses.com/',
    3,
    '(503) 389-3122',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-74',
    'Nikki Del Giudice-Farrell Realty',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","Real Estate Investing","!Apa Clarke Team - Real Estate Agents"]',
    1,
    'http://farrellrealty.com/',
    NULL,
    '(503) 283-1900',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-75',
    'Apa Clarke Team',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!BHHS Northwest Real Estate - Real Estate Agents"]',
    1,
    'https://www.apaclarkerealty.com/',
    NULL,
    '(503) 300-6224',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-76',
    'BHHS Northwest Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'http://bhhsnw.com/',
    NULL,
    '(503) 646-7826',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-77',
    'Angela Gaudren-Keller Williams Professional',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Consultants","!Windermere Real Estate - Real Estate Agents"]',
    1,
    'http://kw.com/',
    NULL,
    '(503) 319-4900',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-78',
    'Windermere Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Management","!Focus Commercial Inc - Real Estate Agents"]',
    1,
    'http://www.windermereprg.com/',
    NULL,
    '(503) 286-5826',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-79',
    'Focus Commercial Inc',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","!Key Realty NW - Real Estate Agents"]',
    1,
    'https://focuscommercial.randallgroup.com/',
    NULL,
    '(503) 452-5545',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-80',
    'Key Realty NW',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Investing","Real Estate Buyer Brokers","!Cristina John - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(971) 207-4072',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-81',
    'Cristina John',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","Real Estate Buyer Brokers","!Rembold Properties - Real Estate Agents"]',
    1,
    'https://www.cristinajohn.com/',
    20,
    '(503) 939-8201',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-82',
    'Rembold Properties',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    'https://www.rembold.com/contact',
    NULL,
    '(503) 222-7258',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-83',
    'Debbie Amhaz Realtor at Oregon First',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!North West Short Sale - Real Estate Agents"]',
    1,
    'https://debbieamhaz.oregonfirst.com/',
    NULL,
    '(503) 516-4599',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-84',
    'North West Short Sale',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Investing","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(360) 852-4470',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-85',
    'For Sale By Owner & Builders',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","!Stumptown Estates - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 546-4902',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-86',
    'Stumptown Estates',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://www.stumptownestates.com/',
    NULL,
    '(503) 753-3156',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-87',
    'Wayne Lindquist & Associates Inc',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Jennifer Fidler - Real Estate Agents"]',
    1,
    'http://www.waynelindquist.com/contact.html',
    NULL,
    '(503) 255-1984',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-88',
    'Jennifer Fidler',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Tech Group Realty - Real Estate Agents"]',
    1,
    'https://jenniferfidlerhomes.com/',
    20,
    '(503) 403-8905',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-89',
    'Tech Group Realty',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(503) 318-1988',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-90',
    'Scott Taylor Broker-More Realty',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 709-3731',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-91',
    'Pacific Realty Associates, LP',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate","Real Estate Buyer Brokers"]',
    1,
    'https://www.pactrust.com/contact-us',
    NULL,
    '(503) 624-7755',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-92',
    'Toll Brothers at Hosford Farms - Terra Collection',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Developers","!Caitlin Fish Realtor - Real Estate Agents"]',
    1,
    'https://www.tollbrothers.com/luxury-homes-for-sale/Oregon/Toll-Brothers-at-Hosford-Farms-Terra-Collection?utm_source=Yext&utm_medium=Local+Listings&utm_campaign=Yext+Community+Local+Listings&utm_content=Community+Link&y_source=1_OTE2Mzg5NjEtNTUzLWxvY2F0aW9uLndlYnNpdGU%3D',
    NULL,
    '(971) 253-0900',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-93',
    'Caitlin Fish Realtor',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Fox Real Estate Group - Real Estate Agents"]',
    1,
    'https://caitlin.sites.erarealestate.com/profile/my-bio',
    NULL,
    '(503) 438-0929',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-94',
    'Fox Real Estate Group',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","Real Estate Buyer Brokers","!Roger Paul Properties Group - Real Estate Agents"]',
    1,
    'https://www.foxrealestategroups.com/agent-profile/Chris-Merz-106366942',
    20,
    '(503) 743-6661',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-95',
    'Roger Paul Properties Group',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://rogerpaulproperties.com/',
    NULL,
    '(971) 222-4929',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-96',
    'We Know Portland Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://www.weknowportland.com/',
    NULL,
    '(503) 714-1463',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-97',
    'Marcus & Millichap Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate","!Key Realty - Real Estate Agents"]',
    1,
    'http://marcusmillichap.com/',
    NULL,
    '(503) 200-2000',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-98',
    'Key Realty',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://www.networkwilmington.com/',
    NULL,
    '(910) 458-8881',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-99',
    'Venture Hospitality & Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Unico Properties - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 477-6168',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-100',
    'Unico Properties',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(503) 224-3280',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-101',
    'Interurban Real Estate Group',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Consultants","!Star One Realtors - Real Estate Agents"]',
    1,
    'https://www.interurbanre.com/Contact',
    NULL,
    '(503) 719-6950',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-102',
    'Star One Realtors',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Wagner, John - Real Estate Agents"]',
    1,
    'https://northwest.starone.com/',
    NULL,
    '(513) 385-0900',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-103',
    'Wagner, John',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate","!Commercial Furnishings Inc - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 275-5900',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-104',
    'Commercial Furnishings Inc',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Pacific Real Estates - Real Estate Agents"]',
    1,
    'https://www.hyphn.com/',
    NULL,
    '(503) 248-9100',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-105',
    'Pacific Real Estates',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate","Real Estate Buyer Brokers","!Team Swan - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(971) 544-1264',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-106',
    'Team Swan',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Hoyt Street Properties - Real Estate Agents"]',
    1,
    'https://www.teamswanmtg.com/contactus',
    NULL,
    '(503) 457-6926',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-107',
    'Hoyt Street Properties',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(503) 227-5804',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-108',
    'Fountain Village Development',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","!Pacificap Properties Group - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(971) 352-6472',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-109',
    'Pacificap Properties Group',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Teton Springs Realty - Real Estate Agents"]',
    1,
    'https://pacificapconstruction.com/contact',
    NULL,
    '(503) 288-6210',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-110',
    'Teton Springs Realty',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(208) 787-8000',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-111',
    'Design Systems/Cas Properties',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!TRG or Affordable Housing - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 241-0615',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-112',
    'TRG or Affordable Housing',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Investing","Real Estate Buyer Brokers","!BPR Properties Portland - Real Estate Agents"]',
    1,
    'http://www.therichmangroup.com/',
    NULL,
    '(503) 459-8741',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-113',
    'BPR Properties Portland',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Urban Renaissance Group - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 265-8187',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  );