INSERT INTO businesses (
      id, name, city, state, industry, services, verified, website, 
      yearsInBusiness, phone, address, email, rating, reviewCount, 
      licenseNumber, bbbRating, emergencyService
    ) VALUES (
    'eugene-GeneralContractors-11',
    'Lane Marble Interiors Inc',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Home Improvements","Bathroom Remodeling","!Brigham Construction - General Contractors"]',
    1,
    'http://www.lanemarbleinteriors.com/',
    47,
    '(541) 579-2548',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-12',
    'Brigham Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Kitchen Planning & Remodeling Service","!Schar Construction - General Contractors"]',
    1,
    'http://www.brighamconstruction.com/',
    NULL,
    '(541) 688-3648',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-13',
    'Schar Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Home Design & Planning"]',
    1,
    'https://scharconstruction.com/',
    NULL,
    '(541) 256-2293',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-14',
    'Whitewater Construction Inc',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors-Commercial & Industrial","!Radley Construction - General Contractors"]',
    1,
    'http://www.whitewaterconst.com/',
    NULL,
    '(541) 485-3937',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-15',
    'Radley Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    NULL,
    32,
    '(541) 636-7458',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-16',
    'McKenzie Commercial Contractors Inc',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Home Improvements","!Meili Construction Company - General Contractors"]',
    1,
    'http://www.mckenziecommercial.com/',
    NULL,
    '(541) 343-7143',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-17',
    'Meili Construction Company',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","!Maddock Construction Inc - General Contractors"]',
    1,
    'http://www.meiliconstruction.com/',
    17,
    '(541) 485-1417',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-18',
    'Maddock Construction Inc',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers"]',
    1,
    'http://www.citysearch.com/profile/645822340/eugene_or/maddock_construction_inc.html',
    16,
    '(541) 913-1573',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-19',
    'Essex General Construction Inc',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Home Centers","Metal Buildings","!CMW Maintenance Corp - General Contractors"]',
    1,
    'https://www.essexgc.com/',
    NULL,
    '(541) 342-4509',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-20',
    'CMW Maintenance Corp',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Handyman Services","Kitchen Planning & Remodeling Service","!Wildish Land Co - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 914-6822',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-21',
    'Wildish Land Co',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Paving Contractors","Excavation Contractors","!Parker Construction - General Contractors"]',
    1,
    'http://www.wildish.com/',
    90,
    '(541) 485-1700',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-22',
    'Parker Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Troubles Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 510-5888',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-23',
    'Troubles Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Storm Windows & Doors","Building Contractors"]',
    1,
    'http://www.troublesconstruction.com/',
    17,
    '(541) 236-3562',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-24',
    'Statewide Contract Services',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 338-7603',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-25',
    'Deer Haven Construction Inc',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Northedge Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 729-3805',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-26',
    'Northedge Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers"]',
    1,
    NULL,
    NULL,
    '(541) 246-8496',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-27',
    'Cascadia Construction & Plumbing',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Plumbers","!Castile Construction Inc - General Contractors"]',
    1,
    'http://www.cascadia.co/',
    NULL,
    '(541) 460-5060',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-28',
    'Castile Construction Inc',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Home Improvements","!A and J Construction - General Contractors"]',
    1,
    'https://castileconstructioninc.com/',
    28,
    '(541) 554-6974',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-29',
    'A and J Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Building Contractors"]',
    1,
    'https://www.aandjconstllc.com/',
    11,
    '(541) 799-1653',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-30',
    'Plan B Design & Construction Inc',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers"]',
    1,
    NULL,
    NULL,
    '(541) 543-5953',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-31',
    'To The Bone',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors","!DaBella - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 579-0953',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-32',
    'DaBella',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","!Vandelinder Construction - General Contractors"]',
    1,
    'https://dabella.us/location/eugene',
    NULL,
    '(541) 234-5610',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-33',
    'Vandelinder Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Deck Builders","Kitchen Planning & Remodeling Service"]',
    1,
    NULL,
    NULL,
    '(707) 223-2606',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-34',
    'Willamette Valley General Contractors',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Deck Builders","Patio Builders","!Windsor Construction - General Contractors"]',
    1,
    'https://willamettevalleygeneral.com/',
    32,
    '(541) 554-6771',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-35',
    'Windsor Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors-Commercial & Industrial","!Get Er Done - General Contractors"]',
    1,
    'http://www.eugeneremodeler.com/',
    NULL,
    '(541) 343-1448',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-36',
    'Get Er Done',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Deck Builders","Building Maintenance"]',
    1,
    'https://gettingerdone.com/',
    NULL,
    '(541) 915-4554',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-37',
    'Greg''s Construction Services',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    'https://gregsconstructionservices.net/',
    NULL,
    '(541) 729-6490',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-38',
    'Banks J Randall Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Restoration & Preservation","!Gansen Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 514-4317',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-39',
    'Gansen Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Building Contractors"]',
    1,
    'https://gansenhomes.com/',
    42,
    '(541) 463-1000',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-40',
    'Level and Plumb Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    'https://www.levelandplumbconstruction.com/',
    NULL,
    '(541) 221-4407',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-41',
    'Eugene General Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Excavation Contractors","Masonry Contractors"]',
    1,
    'https://www.eugenegeneralconstruction.com/',
    9,
    '(541) 788-6836',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-42',
    'Peoples Natural Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Lee-Built Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 968-2212',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-43',
    'Lee-Built Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","Construction Management","!Service Partners - General Contractors"]',
    1,
    'https://www.leebuilt.com/',
    NULL,
    '(541) 688-2042',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-44',
    'Service Partners',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Insulation Contractors","Building Contractors","!SLV Construction - General Contractors"]',
    1,
    'https://www.service-partners.com/branches/or/eugene/2201/?utm_source=extnet&utm_medium=Yext',
    NULL,
    '(541) 688-4279',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-45',
    'SLV Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","Kitchen Planning & Remodeling Service"]',
    1,
    'http://www.slvconstructionllc.com/',
    NULL,
    '(541) 971-3741',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-46',
    'Strasheim General Contracting',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Deck Builders","Altering & Remodeling Contractors","!H & J Construction, Inc. - General Contractors"]',
    1,
    'http://www.strasheimcontracting.com/',
    NULL,
    '(541) 337-6263',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-47',
    'H & J Construction, Inc.',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Utility Contractors","Building Contractors","!Stonewood Construction Inc - General Contractors"]',
    1,
    'http://www.hjconstructioninc.com/',
    NULL,
    '(541) 689-5863',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-48',
    'Stonewood Construction Inc',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors-Commercial & Industrial","!Ausland Group - General Contractors"]',
    1,
    'https://stonewoodconstruction.com/',
    NULL,
    '(541) 636-4431',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-49',
    'Ausland Group',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Construction Management","!Construction CPR - General Contractors"]',
    1,
    'https://auslandgroup.com/',
    NULL,
    '(541) 345-1094',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-50',
    'Construction CPR',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Construction Management","!Suulutaaq Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 686-8648',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-51',
    'Suulutaaq Inc',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Road Building Contractors","!Honn Design & Construction - General Contractors"]',
    1,
    'https://suulutaaq.com/',
    NULL,
    '(541) 515-7515',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-52',
    'Honn Design & Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Architects & Builders Services","Real Estate Developers","!Wingard Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 485-5150',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-53',
    'Wingard Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","!Castile Construction Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 484-9922',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-54',
    'Castile Construction Inc',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers"]',
    1,
    'http://castileconstructioninc.com/',
    NULL,
    '(541) 554-6974',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-55',
    'Western Construction Services',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers"]',
    1,
    NULL,
    NULL,
    '(541) 349-5040',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-56',
    'Six Degrees Construction Co',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","!Lease Crutcher Lewis - General Contractors"]',
    1,
    'https://sixdegreesconstruction.com/contact',
    NULL,
    '(541) 434-6510',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-57',
    'Lease Crutcher Lewis',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 505-8817',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-58',
    'Bonnie Pasquarelli Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","!Dyer Construction & Design - General Contractors"]',
    1,
    'https://pasquarelliconstruction.com/',
    NULL,
    '(541) 954-3541',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-59',
    'Dyer Construction & Design',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","!Rispler & Beck - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 485-5048',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-60',
    'Rispler & Beck',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 914-6904',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-61',
    'Meltebeke Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Construction Focus Inc - General Contractors"]',
    1,
    'http://meltebeke.com/',
    NULL,
    '(541) 686-2400',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-62',
    'Construction Focus Inc',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Ctr Builder Inc - General Contractors"]',
    1,
    'http://constructionfocus.com/',
    NULL,
    '(541) 686-2031',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-63',
    'Ctr Builder Inc',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers"]',
    1,
    NULL,
    NULL,
    '(541) 485-9167',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-64',
    'Barr Washburn Construction & Cabinets',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!Harpell Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 513-8872',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-65',
    'Harpell Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!Gemstone Builder''s Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 954-9934',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-66',
    'Gemstone Builder''s Inc',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!Gerding Builders - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 343-7400',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-67',
    'Gerding Builders',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","!Shea Built Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 654-4255',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-68',
    'Shea Built Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 326-5767',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-69',
    'Siegel Design & Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","!Castile Kitchen & Bath - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 344-5277',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-70',
    'Castile Kitchen & Bath',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    'http://castileconstructioninc.com/',
    NULL,
    '(541) 554-6974',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-71',
    'Robidoux Larry Design Construction Inc',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Waters Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 485-5996',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-72',
    'Waters Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Sherman Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 517-3400',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-73',
    'Sherman Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","!H & S Contractor - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 735-7557',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-74',
    'H & S Contractor',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","!Timothy Eric Allenbaugh - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 981-3318',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-75',
    'Timothy Eric Allenbaugh',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 510-2772',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-76',
    'Terrafirma Foundation Systems',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","!Shaft Construction - General Contractors"]',
    1,
    'https://simplecheckout.authorize.net/payment/CatalogPayment.aspx',
    NULL,
    '(541) 338-4049',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-77',
    'Shaft Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","!Precision Home Contracting - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 729-5654',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-78',
    'Precision Home Contracting',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","!J & K General Contractors - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 852-2709',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-79',
    'J & K General Contractors',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Steve Swenson Builder Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 579-4494',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-80',
    'Steve Swenson Builder Inc',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","!Imbler Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 485-5814',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-81',
    'Imbler Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Concrete Contractors","!Shane Eldor Sprenger - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 517-3446',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-82',
    'Shane Eldor Sprenger',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","Building Contractors-Commercial & Industrial","!Jorden Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 517-6656',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-83',
    'Jorden Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    'https://www.pfjconstruction.com/',
    NULL,
    '(541) 505-7231',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-84',
    'James Papez Construction Inc',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!Ives Construction Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 961-3473',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-85',
    'Ives Construction Inc',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","!Paddock Construction - General Contractors"]',
    1,
    'http://ivesconstructioninc.com/wp/contact',
    NULL,
    '(541) 343-7560',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-86',
    'Paddock Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors-Commercial & Industrial"]',
    1,
    NULL,
    NULL,
    '(541) 345-5934',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-87',
    'Middlefield Construction Inc',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Home Improvements","Real Estate Developers","!W B Leavitt Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 942-3254',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-88',
    'W B Leavitt Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","!Wheeler Construction Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 517-4755',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-89',
    'Wheeler Construction Inc',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Excavation Contractors","Real Estate Developers","!Lassen Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 344-7581',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-90',
    'Lassen Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 517-9071',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-91',
    'Boaz Sofge Construction Inc',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Hoover Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 554-3868',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-92',
    'Hoover Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 556-9469',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-93',
    'Don Offet General Contractor Inc',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Andersen Construction Co - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 606-0323',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-94',
    'Andersen Construction Co',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","!McKay Building Company - General Contractors"]',
    1,
    'https://www.andersen-const.com/location/eugene',
    NULL,
    '(541) 735-3525',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-95',
    'McKay Building Company',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors","!Dasso Construction - General Contractors"]',
    1,
    'http://www.oregon.gov/ccb',
    NULL,
    '(541) 484-4735',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-96',
    'Dasso Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers"]',
    1,
    NULL,
    NULL,
    '(541) 556-5087',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-97',
    'Westside Property Maintenance Service',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Windows","!Gerding Builders - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 683-5900',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-98',
    'Gerding Builders',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers"]',
    1,
    NULL,
    NULL,
    '(541) 654-4255',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-99',
    'Kneller Stephen General Contractor Inc',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Ministry Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 686-8141',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-100',
    'Ministry Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","!Babb Construction Co - General Contractors"]',
    1,
    'https://www.ministryconstruction.com/',
    NULL,
    '(541) 520-8051',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-101',
    'Babb Construction Co',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Excavation Contractors","!Rogue Valley Precast - General Contractors"]',
    1,
    'http://deltasg.com/',
    NULL,
    '(541) 688-2233',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-102',
    'Rogue Valley Precast',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","!Longworth Construction Inc - General Contractors"]',
    1,
    'https://rvpor.com/',
    NULL,
    '(541) 238-2500',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-103',
    'Longworth Construction Inc',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!Aloha Home Builders - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 915-1124',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-104',
    'Aloha Home Builders',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!McKenzie Commercial - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 636-3366',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-105',
    'McKenzie Commercial',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","!Paddock Construction - General Contractors"]',
    1,
    'https://www.mckenziecommercial.com/contact',
    NULL,
    '(541) 343-7143',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-106',
    'Paddock Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Masonry Contractors","!Transcendence Construction - General Contractors"]',
    1,
    'https://storacoach.com/',
    NULL,
    '(541) 345-5934',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-107',
    'Transcendence Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","!Schar Construction Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(458) 895-0973',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-108',
    'Schar Construction Inc',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","!Chris Stebbins Co Design - General Contractors"]',
    1,
    'http://scharconstruction.com/',
    NULL,
    '(541) 485-4977',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-109',
    'Chris Stebbins Co Design',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","!Cabinet Store and More - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 953-7169',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-110',
    'Cabinet Store and More',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","!Dmoir Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 203-0045',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  );