INSERT INTO businesses (
      id, name, city, state, industry, services, verified, website, 
      yearsInBusiness, phone, address, email, rating, reviewCount, 
      licenseNumber, bbbRating, emergencyService
    ) VALUES (
    'grantspass-Lawyers-66',
    'Josephine County Professional Center',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Legal Service Plans"]',
    1,
    NULL,
    NULL,
    '(541) 474-2484',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-67',
    'Southern Oregon Mediation Center',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Mediation Services","Family Law Attorneys"]',
    1,
    'https://www.southernoregonmediation.com/',
    NULL,
    '(541) 226-6654',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-68',
    'Josephine County Adult Commnty',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","County & Parish Government"]',
    1,
    'http://www.co.josephine.or.us/',
    NULL,
    '(541) 474-5165',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-69',
    'Myrick Seagraves Adams Davis & Preslar',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Legal Service Plans"]',
    1,
    NULL,
    NULL,
    '(503) 476-6627',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-70',
    'Freudenberg, Ben E, ATTY',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Litigation & Tort Attorneys","Personal Injury Law Attorneys","!Thorpe, Amanda - Litigation & Tort Attorneys"]',
    1,
    'http://roguefirm.com/',
    NULL,
    '(541) 476-6627',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-71',
    'Thorpe, Amanda',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Litigation & Tort Attorneys","Personal Injury Law Attorneys","!Patrick J Kelly Attorney - Real Estate Attorneys"]',
    1,
    'https://southernoregonlawyer.com/',
    NULL,
    '(541) 479-2678',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-72',
    'Patrick J Kelly Attorney',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Real Estate Attorneys"]',
    1,
    'http://www.avvo.com/attorneys/97526-or-patrick-kelly-1495348.html?cm_mmc=Whitepages-_-Syndication-_-Whitepages_Local-_-Patrick_J_Kelly',
    24,
    '(541) 474-1908',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-73',
    'Morse, Faith M, ATTY',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Personal Injury Law Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 476-6623',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-74',
    'Holt Heather L',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Labor & Employment Law Attorneys","Corporation & Partnership Law Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 955-1690',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-75',
    'Dwyer Williams Cherkoss',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Personal Injury Law Attorneys"]',
    1,
    'https://roydwyer.com/',
    NULL,
    '(541) 471-8994',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-76',
    'Disability Attorney Medford Or',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Social Security & Disability Law Attorneys","Estate Planning Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 474-6271',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-77',
    'Consumer Credit Counseling of Josephine County',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Credit & Debt Counseling","Bankruptcy Services"]',
    1,
    NULL,
    NULL,
    '(541) 479-6002',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-78',
    'Estate Planning Group',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Estate Planning Attorneys","Wills, Trusts & Estate Planning Attorneys"]',
    1,
    'https://www.epgoregon.com/',
    54,
    '(541) 474-0880',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-79',
    'Olsendaines',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Social Security & Disability Law Attorneys","General Practice Attorneys"]',
    1,
    'http://www.olsendaines.com/',
    NULL,
    '(541) 471-1043',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-80',
    'Wells, Manning, Eitenmiller & Taylor',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Social Security & Disability Law Attorneys"]',
    1,
    'https://wmetattorneys.com/contact-us/grants-pass-oregon-office',
    NULL,
    '(541) 450-9292',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-81',
    'Jospehine County Animal Control',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","County & Parish Government","Police Departments","!Law Office of Michael Cougar - Attorneys"]',
    1,
    'http://www.co.josephine.or.us/',
    NULL,
    '(541) 474-5458',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-82',
    'Law Office of Michael Cougar',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","Bankruptcy Law Attorneys","Estate Planning Attorneys","!Loren L Heuertz Attorney - Attorneys"]',
    1,
    'https://michaelcougar.com/',
    40,
    '(541) 808-2727',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-83',
    'Loren L Heuertz Attorney',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","!Heuertz & Monen PC - General Practice Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 582-4115',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Lawyers-84',
    'Heuertz & Monen PC',
    'Grants Pass',
    'OR',
    'lawfirms',
    '["Attorneys","General Practice Attorneys"]',
    1,
    'http://www.rogueriverlawyers.com/',
    50,
    '(541) 582-4115',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-1',
    'Murphy Plumbing LLC dba Murphy''s We Do Plumbing & Rooter',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","Water Filtration & Purification Equipment","Water Heater Repair","!Purist Plumbing and Excavation LLC - Plumbers"]',
    1,
    'https://murphyswedoplumbing.com/',
    49,
    '(541) 476-1974',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-2',
    'Purist Plumbing and Excavation LLC',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Water Heater Repair","!A-1 Speedy Plumbing Inc. - Plumbers"]',
    1,
    'https://www.puristplumbing.com/',
    NULL,
    '(458) 332-0026',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-3',
    'A-1 Speedy Plumbing Inc.',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Water Heater Repair","!Aristocrat Plumbing Inc - Plumbers"]',
    1,
    NULL,
    59,
    '(541) 479-2432',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-4',
    'Aristocrat Plumbing Inc',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","!Shamrock Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 479-7881',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-5',
    'Shamrock Plumbing',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","!GRANT''S PLUMBING LLC - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 479-1300',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-6',
    'GRANT''S PLUMBING LLC',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","!Heritage Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 761-0367',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-7',
    'Heritage Plumbing',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","!Metro Drains and Plumbing-Rnf 3 - Plumbers"]',
    1,
    'https://www.heritageplumbinggrantspass.com/',
    NULL,
    '(541) 474-7749',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-8',
    'Metro Drains and Plumbing-Rnf 3',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","!Protech Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 955-5680',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-9',
    'Protech Plumbing',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","!Al''s Plumbing Service - Plumbers"]',
    1,
    'http://www.cbs.state.or.us/bcd',
    NULL,
    '(541) 476-8589',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-10',
    'Al''s Plumbing Service',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","!Robert Lee Allen Jr - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 479-3902',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-11',
    'Robert Lee Allen Jr',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","!Sherlock Homes Plumbing - Plumbers"]',
    1,
    'http://www.cbs.state.or.us/bcd',
    NULL,
    '(541) 218-2297',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-12',
    'Sherlock Homes Plumbing',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","!Almeda Plumbing - Plumbers"]',
    1,
    'https://www.sherlockhomes.plumbing/',
    NULL,
    '(541) 479-7881',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-13',
    'Almeda Plumbing',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","!A-1 Speedy Plumbing Inc - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 226-7408',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-14',
    'A-1 Speedy Plumbing Inc',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","!My Plumber - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 479-2432',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-15',
    'My Plumber',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","!Metro Drains and Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 582-1827',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-16',
    'Metro Drains and Plumbing',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Sewer Cleaners & Repairers","!Scott''s Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 955-5680',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-17',
    'Scott''s Plumbing',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","Altering & Remodeling Contractors","Home Improvements","!Heritage Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 955-1734',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-18',
    'Heritage Plumbing',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","!David King - Plumbers"]',
    1,
    'http://www.heritageplumbinggrantspass.com/',
    NULL,
    '(541) 474-7749',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-19',
    'David King',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","!Rogue Valley Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 955-9326',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-20',
    'Rogue Valley Plumbing',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 956-8766',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-21',
    'Hardman Construction Plumbing Specialists Lic',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 659-2118',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-22',
    'Pure Water Plumbing',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","Water Filtration & Purification Equipment"]',
    1,
    'https://www.purewaterplumbing.com/',
    17,
    '(541) 660-1462',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-23',
    'Shamrock Plumbing',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing, Drains & Sewer Consultants","Kitchen Planning & Remodeling Service"]',
    1,
    NULL,
    NULL,
    '(541) 479-1300',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-24',
    'Quinn''s Well Pump & Filtration',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","Pumps-Service & Repair","Pumps"]',
    1,
    'http://www.quinnswell.com/',
    80,
    '(541) 862-9355',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-25',
    'All Seasons Heating & Air Conditioning Inc.',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","Furnaces-Heating","Heating Contractors & Specialties","!Rogue Valley Plumbing - Water Heaters"]',
    1,
    NULL,
    44,
    '(541) 479-8777',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-26',
    'Rogue Valley Plumbing',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","Water Heaters","Plumbing-Drain & Sewer Cleaning","!Michael''s Plumbing NW Inc - Water Heaters"]',
    1,
    'http://www.grantspassplumbing.com/',
    NULL,
    '(541) 471-6080',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-27',
    'Michael''s Plumbing NW Inc',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","Water Heaters","Plumbing-Drain & Sewer Cleaning"]',
    1,
    'http://www.michaelsplumbingnw.com/',
    NULL,
    '(541) 476-0724',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-28',
    'Home Services at The Home Depot',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","Home Improvements","Air Conditioning Contractors & Systems"]',
    1,
    'https://www.homedepot.com/l/Grants-Pass/OR/Grants-Pass/97526/4034/services?cm_mmc=old-llm-4034-x',
    NULL,
    '(541) 234-3881',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-29',
    'Quinns Well & Pump Service',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","Pumps-Service & Repair","Water Well Drilling & Pump Contractors"]',
    1,
    'http://www.quinnswellandpump.com/',
    80,
    '(541) 862-9355',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-30',
    'Caveman Plumbing Service',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Boiler Repair & Cleaning"]',
    1,
    NULL,
    48,
    '(541) 659-9644',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-31',
    'Rauch Plumbing & Heating',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","Heating Contractors & Specialties","Air Conditioning Contractors & Systems","!Aristocrat Plumbing Inc - Water Heaters"]',
    1,
    NULL,
    NULL,
    '(541) 476-6398',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-32',
    'Aristocrat Plumbing Inc',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","Water Heaters","Plumbing-Drain & Sewer Cleaning"]',
    1,
    NULL,
    NULL,
    '(541) 479-7881',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-33',
    'Mr. Rooter Plumbing of Josephine & Jackson Counties',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Plumbing Contractors-Commercial & Industrial","!Mat Tibbits Plumbing - Plumbers"]',
    1,
    'http://www.mrrooter.com/josephine-jackson-counties',
    31,
    '(541) 210-5437',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-34',
    'Mat Tibbits Plumbing',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","!Robert Allen Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 660-2293',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-35',
    'Robert Allen Plumbing',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","Altering & Remodeling Contractors","Bathroom Remodeling","!Speedy Rooter - Plumbers"]',
    1,
    'http://robertallenplumbingllcor.hibuwebsites.com/',
    21,
    '(541) 218-2297',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-36',
    'Speedy Rooter',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Sewer Contractors","!Heritage Plumbing - Plumbers"]',
    1,
    'https://www.speedyrooterdrains.com/contact-us',
    NULL,
    '(541) 479-5942',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-37',
    'Heritage Plumbing',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","!Castle Plumbing - Plumbers"]',
    1,
    'https://www.heritageplumbinggrantspass.com/',
    NULL,
    '(541) 474-7749',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-38',
    'Castle Plumbing',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","!Mr Rooter Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 218-6093',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-39',
    'Mr Rooter Plumbing',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","!Plumbing Technician Of Grants Pass - Plumbers"]',
    1,
    'https://www.mrrooter.com/josephine-jackson-counties',
    NULL,
    '(541) 291-9419',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-40',
    'Plumbing Technician Of Grants Pass',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","!King''s Plumbing Inc - Plumbers"]',
    1,
    'https://voxservices.net/plumbing/grants%20pass/or/38648/plumbing%20technician%20of%20grants%20pass',
    28,
    '(458) 212-2819',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-41',
    'King''s Plumbing Inc',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","Water Heater Repair"]',
    1,
    NULL,
    NULL,
    '(541) 660-6093',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-42',
    'Jim''s Septic Service.',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","Septic Tank & System Cleaning","Plumbing-Drain & Sewer Cleaning"]',
    1,
    'http://www.jimseptic.com/',
    40,
    '(541) 476-9726',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-43',
    'Stedfast Plumbing & Drains',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","!John Rice Plumbing Inc. - Water Heater Repair"]',
    1,
    'https://www.stedfastplumbing.com/',
    6,
    '(541) 660-3545',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-44',
    'John Rice Plumbing Inc.',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","Water Heater Repair","Boiler Repair & Cleaning"]',
    1,
    NULL,
    NULL,
    '(541) 787-5646',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-45',
    'McCarty Plumbing',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing Fixtures, Parts & Supplies"]',
    1,
    NULL,
    NULL,
    '(541) 474-7926',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-46',
    'Drainpros Plumbing',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Sewer Cleaners & Repairers","!Artoff Plumbing - Plumbers"]',
    1,
    'http://drainpros.info/',
    NULL,
    '(541) 474-1600',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-47',
    'Artoff Plumbing',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","!My Plumber - Plumbers"]',
    1,
    'http://www.artoffplumbing.com/contact-us',
    46,
    '(541) 582-0853',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-48',
    'My Plumber',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","!Medford Mechanical Inc - Plumbers"]',
    1,
    'https://www.myplumberoregon.com/post/4-awesome-facts-about-oregon-know-about-the-place-you-live',
    NULL,
    '(541) 601-0000',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-49',
    'Medford Mechanical Inc',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","!Applegate Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 855-7670',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-50',
    'Applegate Plumbing',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","!Murphy''s We Do Plumbing & Rooter - Water Heaters"]',
    1,
    'http://www.cbs.state.or.us/bcd',
    NULL,
    '(541) 846-0540',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Plumbers-51',
    'Murphy''s We Do Plumbing & Rooter',
    'Grants Pass',
    'OR',
    'plumbers',
    '["Plumbers","Water Heaters","Plumbing-Drain & Sewer Cleaning"]',
    1,
    'http://www.murphyswedoplumbing.com/',
    49,
    '(541) 582-2807',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-1',
    'Century 21',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","View all 2 Locations","!Redd McCarty Realtors - Real Estate Agents"]',
    1,
    'http://www.johnlscott.com/',
    NULL,
    '(541) 474-2014',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-2',
    'Redd McCarty Realtors',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    'http://www.reddmccarty.com/',
    NULL,
    '(541) 479-7003',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-3',
    'Oregon Properties Real Estate Inc',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Management"]',
    1,
    'http://oregonpropertiesre.com/',
    NULL,
    '(541) 956-5826',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-4',
    'Grants Pass Association of Realtors',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Remax - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 476-1078',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-5',
    'Remax',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate","View all 3 Locations","!Richard Ward Associates - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 955-8483',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-6',
    'Richard Ward Associates',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    'http://www.wardprojects.com/contact',
    NULL,
    '(541) 476-7218',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-7',
    'Cascade Hasson Sotheby''s International Realty',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Mockridge Real Estate - Real Estate Agents"]',
    1,
    'https://www.cascadehasson.com/',
    NULL,
    '(541) 312-4057',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-8',
    'Mockridge Real Estate',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","!AEI Group Real Estate - Real Estate Agents"]',
    1,
    'https://www.mockridgerealestate.com/',
    NULL,
    '(541) 659-3270',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-9',
    'AEI Group Real Estate',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","!ERA Prestige Homes - Real Estate Agents"]',
    1,
    'https://aei.group/',
    NULL,
    '(844) 234-8326',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-10',
    'ERA Prestige Homes',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate"]',
    1,
    NULL,
    NULL,
    '(541) 474-6017',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-11',
    'Team Mikels-Ford Real Estate',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","!The Venuti Group Inc - Real Estate Agents"]',
    1,
    'https://jolena.propertyofsouthernoregon.com/',
    NULL,
    '(541) 450-2977',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-12',
    'The Venuti Group Inc',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Era Prestige Homes - Real Estate Agents"]',
    1,
    'https://southernoregonhomes.com/',
    NULL,
    '(541) 476-9616',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-13',
    'Era Prestige Homes',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Developers","Real Estate Buyer Brokers","!Keller Williams Realty - Real Estate Agents"]',
    1,
    'http://grantspass.com/',
    NULL,
    '(541) 474-4357',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-14',
    'Keller Williams Realty',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Consultants","!Exit Realty Towne Centre - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 608-0447',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-15',
    'Exit Realty Towne Centre',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(541) 474-1566',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-16',
    'Oregon Real Estate Center Inc',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Real Estate Cafe LLC - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 474-1904',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-17',
    'Real Estate Cafe LLC',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate","!CRS Inc - Real Estate Agents"]',
    1,
    'http://www.buyinoregon.com/',
    NULL,
    '(541) 659-1620',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-18',
    'CRS Inc',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Management"]',
    1,
    'https://www.crssouthernoregon.com/',
    NULL,
    '(541) 479-3395',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-19',
    'Complete Real Estate Services',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Prudential Real Estate - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 474-7927',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-20',
    'Prudential Real Estate',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate","!Redd McCarty Realtors - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 476-6000',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-21',
    'Redd McCarty Realtors',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate"]',
    1,
    'http://www.reddmccarty.com/',
    NULL,
    '(541) 479-7003',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-22',
    'CRS Property Management & Real Estate',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","!West USA Realty - Real Estate Agents"]',
    1,
    'https://www.crssouthernoregon.com/',
    NULL,
    '(541) 507-1088',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-23',
    'West USA Realty',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'http://westusa.com/',
    NULL,
    '(480) 948-5554',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-24',
    'John L Scott Southern and Central Oregon',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(541) 476-1299',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-25',
    'Keller Williams Realty Southern Oregon',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Consultants"]',
    1,
    'http://www.kw.com/',
    NULL,
    '(541) 295-3015',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-26',
    'Live Grants Pass-A Real Estate Office',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Real Estate Cafe - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 916-4420',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-27',
    'Real Estate Cafe',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Cates Properties - Real Estate Agents"]',
    1,
    'http://ourreddoor.com/',
    NULL,
    '(541) 479-5787',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-28',
    'Cates Properties',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!CPM Real Estate Services - Real Estate Agents"]',
    1,
    'http://www.rogueweb.com/cates',
    NULL,
    '(541) 479-2767',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-29',
    'CPM Real Estate Services',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Management"]',
    1,
    'http://www.cpmrealestateservices.com/',
    NULL,
    '(541) 955-9193',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'grantspass-Real-Estate-Agents-30',
    'Realty Executives Southern Oregon',
    'Grants Pass',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Consultants","!Barnett, Chris, RLTR - Real Estate Agents"]',
    1,
    'http://www.realtyexecutives.com/',
    NULL,
    '(541) 494-3932',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  );