INSERT INTO businesses (
      id, name, city, state, industry, services, verified, website, 
      yearsInBusiness, phone, address, email, rating, reviewCount, 
      licenseNumber, bbbRating, emergencyService
    ) VALUES (
    'portland-Leads-Plumbers-Portland-53',
    'Roto-Rooter Plumbing & Water Cleanup',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Water Heater Repair","Sewer Contractors","Online Specials","!Mick''s Plumbing - Plumbers"]',
    1,
    'https://www.rotorooter.com/portland/?utm_source=iyp&utm_medium=paid&utm_campaign=iyp',
    90,
    '(971) 314-0126',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-54',
    'Mick''s Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","!FX Repair & Remodeling - Building Contractors"]',
    1,
    'https://www.micksplumbing.com/',
    17,
    '(503) 406-8118',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-55',
    'FX Repair & Remodeling',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Home Repair & Maintenance","Building Contractors"]',
    1,
    'http://www.fxrepair.com/',
    36,
    '(503) 542-4442',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-56',
    '1st Call Plumbing & Drain Cleaning',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning"]',
    1,
    'http://www.1stcallplumbing.net/index.html',
    NULL,
    '(971) 409-7463',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-57',
    'D&F Plumbing, Heating and Cooling',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Heating Contractors & Specialties","Plumbing-Drain & Sewer Cleaning"]',
    1,
    'https://dandfplumbing.com/?utm_source=google&utm_medium=organic&utm_campaign=local+listingsportland',
    98,
    '(503) 664-0938',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-58',
    'Central Air Heating, Cooling & Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Air Conditioning Service & Repair","Air Conditioning Equipment & Systems"]',
    1,
    'https://www.centralairpdx.com/',
    24,
    '(971) 435-7303',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-59',
    'HomeTekk',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Draperies, Curtains & Window Treatments","General Contractors","!Rose City Handyman - Handyman Services"]',
    1,
    NULL,
    12,
    '(360) 609-6932',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-60',
    'Rose City Handyman',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Handyman Services","General Contractors"]',
    1,
    'https://www.rosecityhandyman.co/',
    NULL,
    '(503) 484-5741',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-61',
    'Local Plumbing Contractors Portland OR',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Water Damage Restoration","Plumbing Engineers","!Benjamin Home Services - Electricians"]',
    1,
    NULL,
    20,
    '(541) 566-8184',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-62',
    'Benjamin Home Services',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Electricians","Locks & Locksmiths","!Sewer Rat Drain Cleaning - Plumbers"]',
    1,
    NULL,
    NULL,
    '(971) 259-6048',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-63',
    'Sewer Rat Drain Cleaning',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Sewer Contractors","!Chrisman Plumbing - Plumbers"]',
    1,
    'http://sewerratdrains.com/',
    45,
    '(503) 866-5756',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-64',
    'Chrisman Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Boiler Repair & Cleaning","Water Heater Repair","!Craig Anderson Plumbing Inc - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 659-3307',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-65',
    'Craig Anderson Plumbing Inc',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Water Heaters","!Cascade Plumbing - Plumbers"]',
    1,
    'http://www.craigplumbing.com/',
    31,
    '(503) 232-1060',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-66',
    'Cascade Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers"]',
    1,
    'https://cascadeplumbingcompany.com/About_us.html',
    NULL,
    '(503) 544-7454',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-67',
    'bluefrog Plumbing + Drain of Portland',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Water Heater Repair","!D & F Plumbing - Plumbers"]',
    1,
    'https://bluefrogplumbing.com/portland',
    NULL,
    '(503) 389-8426',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-68',
    'D & F Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Sewer Cleaners & Repairers","Gas Lines-Installation & Repairing","!Dean Pottle Plumbing - Plumbers"]',
    1,
    'http://www.dandfplumbing.com/',
    98,
    '(503) 282-0993',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-69',
    'Dean Pottle Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Power Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(971) 533-7936',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-70',
    'Power Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing, Drains & Sewer Consultants","Plumbing Contractors-Commercial & Industrial","!Einstein Pros Plumbing Portland - Plumbers"]',
    1,
    'http://www.powerplumbingco.com/',
    40,
    '(503) 244-1900',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-71',
    'Einstein Pros Plumbing Portland',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Leak Detecting Service","Plumbing-Drain & Sewer Cleaning","!Portland Vintage Plumbing - Plumbers"]',
    1,
    'https://einsteinprosportland.com/',
    NULL,
    '(503) 821-4070',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-72',
    'Portland Vintage Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing Fixtures, Parts & Supplies","General Contractors","!Axiom PDX - Plumbers"]',
    1,
    NULL,
    12,
    '(971) 404-8149',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-73',
    'Axiom PDX',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Roto-Rooter Plumbing & Water Cleanup - Plumbers"]',
    1,
    'http://axiompdx.com/',
    NULL,
    '(503) 869-2913',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-74',
    'Roto-Rooter Plumbing & Water Cleanup',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","View all 2 Locations","!Pacific Plumbing & Drain Services - Plumbers"]',
    1,
    'https://www.rotorooter.com/portland',
    90,
    '(503) 937-1993',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-75',
    'Pacific Plumbing & Drain Services',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Septic Tank & System Cleaning","Excavation Contractors","!Cascade Plumbing - Plumbers"]',
    1,
    'https://pacificplumbinganddrain.com/',
    NULL,
    '(503) 419-9759',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-76',
    'Cascade Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Cornel''s Plumbing Inc. - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 289-7095',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-77',
    'Cornel''s Plumbing Inc.',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Sewer Contractors","!Da Vinci''s Best Plumbing - Plumbers"]',
    1,
    'http://cornelsplumbing.com/',
    44,
    '(503) 523-4854',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-78',
    'Da Vinci''s Best Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Water Heater Repair","!Grizzly Plumbing - Plumbers"]',
    1,
    'https://davincisbestplumbing.com/',
    NULL,
    '(971) 220-8685',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-80',
    'The Heating Specialist',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Heating Contractors & Specialties","Duct Cleaning","Services"]',
    1,
    'http://www.theheatingspecialist.com/',
    44,
    '(503) 257-7000',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-81',
    'James Poggi Inc',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Altering & Remodeling Contractors","Real Estate Developers","!Charter Construction - General Contractors"]',
    1,
    'http://www.jamespoggi.com/',
    NULL,
    '(503) 244-3464',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-82',
    'Charter Construction',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","General Contractors","Building Restoration & Preservation","!Portland Plumbing Plus - Water Heater Repair"]',
    1,
    'http://www.chartercon.com/',
    NULL,
    '(503) 546-2600',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-83',
    'Portland Plumbing Plus',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Water Heater Repair","Gas Lines-Installation & Repairing","!Drains 4 Less - Sewer Pipe"]',
    1,
    'http://www.portlandplumbingplus.com/',
    NULL,
    '(503) 933-1183',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-84',
    'Drains 4 Less',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Sewer Pipe","Plumbing-Drain & Sewer Cleaning"]',
    1,
    NULL,
    24,
    '(503) 656-1070',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-85',
    'George Morlan Plumbing Supply',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing Fixtures, Parts & Supplies","Water Heaters"]',
    1,
    'http://www.georgemorlan.com/',
    98,
    '(503) 624-7381',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-86',
    'Henco Plumbing Services',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Water Heater Repair"]',
    1,
    'https://www.hencoplumbing.com/portland',
    NULL,
    '(360) 566-6959',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-87',
    'American Heating Inc',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Heating Contractors & Specialties","Insulation Contractors"]',
    1,
    'http://www.americanheating.net/',
    NULL,
    '(503) 239-4600',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-88',
    'Sunset Heating & Cooling',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Heating Contractors & Specialties","Plumbing-Drain & Sewer Cleaning","!Lovett Inc. - Septic Tank & System Cleaning"]',
    1,
    'https://www.sunsethc.com/',
    NULL,
    '(503) 234-0611',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-89',
    'Lovett Inc.',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Septic Tank & System Cleaning","Plumbing-Drain & Sewer Cleaning"]',
    1,
    'https://www.lovettservices.com/',
    28,
    '(503) 737-8423',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-90',
    'Portland Mechanical Contractors, Inc',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Mechanical Contractors","Building Contractors","Services"]',
    1,
    'http://pmc-g.com/',
    NULL,
    '(503) 656-7400',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-91',
    'Portland Mechanical Contractors, Inc',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Mechanical Contractors","Building Contractors","Services"]',
    1,
    'http://pmc-g.com/',
    NULL,
    '(503) 656-7400',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-92',
    'Home Services at The Home Depot',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Home Improvements","Flooring Contractors"]',
    1,
    'https://www.homedepot.com/l/E-Portland-Mall/OR/Portland/97216/4013/services?cm_mmc=old-llm-4013-x',
    NULL,
    '(503) 862-7763',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-93',
    'Home Services at The Home Depot',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Home Improvements","Air Conditioning Contractors & Systems"]',
    1,
    'https://www.homedepot.com/l/Jantzen-Beach/OR/Portland/97217/4007/services?cm_mmc=old-llm-4007-x',
    NULL,
    '(503) 862-6943',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-94',
    'Home Services at The Home Depot',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Home Improvements","Flooring Contractors"]',
    1,
    'https://www.homedepot.com/l/Beaverton/OR/Portland/97229/4001/services?cm_mmc=old-llm-4001-x',
    NULL,
    '(503) 862-6916',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-95',
    'Service Plus Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing Fixtures, Parts & Supplies"]',
    1,
    'https://www.serviceplusplumbingpdx.com/',
    NULL,
    '(503) 927-4482',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-96',
    'Home Services at The Home Depot',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Home Improvements","Air Conditioning Contractors & Systems"]',
    1,
    'https://www.homedepot.com/l/NE-Portland/OR/Portland/97220/4004/services?cm_mmc=old-llm-4004-x',
    NULL,
    '(503) 862-6920',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-97',
    'Precision Plumbing Products',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Metro Saw Cutting & Asphalt - Paving Contractors"]',
    1,
    'https://www.pppinc.net/contact.html',
    NULL,
    '(503) 256-4010',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-98',
    'Metro Saw Cutting & Asphalt',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Paving Contractors","Welders","!All In One Plumbing - Plumbers"]',
    1,
    NULL,
    18,
    '(503) 341-8911',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-99',
    'All In One Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Sewer Contractors","!Endeavor Plumbing Inc. - Plumbers"]',
    1,
    'http://www.allinoneplumbing.net/index.php',
    NULL,
    '(503) 344-4705',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-100',
    'Endeavor Plumbing Inc.',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!3 Mountains Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 504-6846',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-101',
    '3 Mountains Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Electricians","!Terry Massey Plumbing - Plumbers"]',
    1,
    'https://www.3mountainsplumbing.com/',
    25,
    '(503) 715-2829',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-102',
    'Terry Massey Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Pipeline Plumbing & Drains - Plumbers"]',
    1,
    'https://masseyplumbingmilwaukie.com/',
    NULL,
    '(503) 997-0324',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-103',
    'Pipeline Plumbing & Drains',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Water Heater Repair","!Simpson Plumbing - Plumbers"]',
    1,
    'https://www.pipelineplumbing.net/',
    NULL,
    '(503) 624-1906',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-104',
    'Simpson Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Happy Valley Local Locksmith - Plumbers"]',
    1,
    'https://plumbernw.com/',
    44,
    '(503) 862-7511',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-105',
    'Happy Valley Local Locksmith',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Shawnz Plumbing LLC - Plumbers"]',
    1,
    NULL,
    NULL,
    '(402) 256-6005',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-106',
    'Shawnz Plumbing LLC',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing Contractors-Commercial & Industrial","!Portland Drain and Rooter - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 492-1011',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-107',
    'Portland Drain and Rooter',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Sewer Contractors","!Nat James Klingensmith Plumbing - Plumbers"]',
    1,
    NULL,
    14,
    '(503) 998-4834',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-108',
    'Nat James Klingensmith Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Plumbminator - Plumbers"]',
    1,
    NULL,
    NULL,
    '(971) 207-5357',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-109',
    'Plumbminator',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Sarkinen Plumbing Inc - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 270-9220',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-110',
    'Sarkinen Plumbing Inc',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Water Heater Repair","!M5 Plumbing Services, Inc. - Plumbers"]',
    1,
    'https://www.sarkinenplumbing.com/',
    NULL,
    '(503) 905-9239',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-111',
    'M5 Plumbing Services, Inc.',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!A & A Drilling Service Inc. - Plumbers"]',
    1,
    'http://www.m5plumbing.com/',
    NULL,
    '(503) 926-6039',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-112',
    'A & A Drilling Service Inc.',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Water Well Drilling & Pump Contractors","Sewer Contractors"]',
    1,
    'http://aadrilling.com/',
    53,
    '(503) 284-3701',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-113',
    'Home Services at The Home Depot',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Home Improvements","Flooring Contractors"]',
    1,
    'https://www.homedepot.com/l/Clackamas/OR/Happy-Valley/97086/4040/services?cm_mmc=old-llm-4040-x',
    NULL,
    '(503) 908-2426',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-114',
    'Home Services at The Home Depot',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Home Improvements","Air Conditioning Contractors & Systems"]',
    1,
    'https://www.homedepot.com/l/Tigard/OR/Tigard/97224/4002/services?cm_mmc=old-llm-4002-x',
    NULL,
    '(503) 862-6918',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-115',
    'A Boy Electric & Plumbing Supply',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Radiators-Heating Sales, Service & Supplies"]',
    1,
    'https://www.aboysupply.com/',
    65,
    '(503) 226-1170',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-116',
    'A Better Plumbing Company',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing Contractors-Commercial & Industrial","!Cascadia Plumbing LLC - Bathroom Remodeling"]',
    1,
    NULL,
    NULL,
    '(503) 232-1664',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-117',
    'Cascadia Plumbing LLC',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Bathroom Remodeling","Water Heaters","!PNW Plumbers - Water Heater Repair"]',
    1,
    NULL,
    NULL,
    '(503) 888-7263',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-118',
    'PNW Plumbers',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Water Heater Repair","Plumbing-Drain & Sewer Cleaning","!Cascade Plumbing - Plumbers"]',
    1,
    'http://www.pnwplumbers.com/',
    22,
    '(503) 549-1324',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-119',
    'Cascade Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Hall Plumbing - Plumbing-Drain & Sewer Cleaning"]',
    1,
    NULL,
    NULL,
    '(503) 289-7095',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-120',
    'Hall Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Plumbing Contractors-Commercial & Industrial","!All American Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 891-4493',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-121',
    'All American Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Garbage Disposal Repair","Water Heater Repair","!Jack Howk Plumbing & Drain - Plumbers"]',
    1,
    'http://allamericanplumbinginc.net/',
    69,
    '(503) 281-9937',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-122',
    'Jack Howk Plumbing & Drain',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Sewer Contractors","Sewer Cleaners & Repairers","!Jack Howk - Plumbers"]',
    1,
    'http://www.jackhowk.com/',
    83,
    '(503) 303-1998',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-123',
    'Jack Howk',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Jack Howk Plumbing & Drain - Plumbers"]',
    1,
    'http://www.jackhowk.com/',
    83,
    '(503) 820-0867',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-124',
    'Jack Howk Plumbing & Drain',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Sarkinen Plumbing - Plumbers"]',
    1,
    'http://www.jackhowk.com/',
    83,
    '(503) 205-6246',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-125',
    'Sarkinen Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Paul''s Plumbing Service Co. - Plumbers"]',
    1,
    NULL,
    83,
    '(503) 462-1053',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-126',
    'Paul''s Plumbing Service Co.',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Paul''s Plumbing Service Co - Plumbers"]',
    1,
    NULL,
    36,
    '(503) 774-0179',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-127',
    'Paul''s Plumbing Service Co',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Boiler Repair & Cleaning","Plumbing-Drain & Sewer Cleaning","!Excellence Plumbing - Plumbers"]',
    1,
    NULL,
    36,
    '(503) 245-9092',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-128',
    'Excellence Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Presto Plumbing - Plumbers"]',
    1,
    'http://www.excellenceplumbing.com/',
    NULL,
    '(503) 894-7019',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-129',
    'Presto Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Apollo Drain and Rooter Service Inc - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 201-2452',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-130',
    'Apollo Drain and Rooter Service Inc',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Sewer Contractors","Sewer Cleaners & Repairers","!Donerite Plumbing & Drain - Plumbers"]',
    1,
    NULL,
    41,
    '(503) 473-0197',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-131',
    'Donerite Plumbing & Drain',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Sewer Cleaners & Repairers","!Affordable Drain and Rooter - Plumbers"]',
    1,
    'http://www.doneriteplumbingsalem.com/',
    NULL,
    '(503) 209-3950',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-132',
    'Affordable Drain and Rooter',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Sewer Cleaners & Repairers","Plumbing-Drain & Sewer Cleaning"]',
    1,
    NULL,
    NULL,
    '(503) 785-0798',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-133',
    'Heat Master Corp',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Heating Contractors & Specialties","Major Appliances"]',
    1,
    NULL,
    51,
    '(503) 761-1421',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-134',
    'Apollo Drain & Rooter Service',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Sewer Cleaners & Repairers"]',
    1,
    'https://apolloservices.com/',
    41,
    '(503) 667-5797',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-135',
    'Anytime Plumbing & Drain Cleaning',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Sewer Cleaners & Repairers","Plumbing-Drain & Sewer Cleaning","!Mike Patterson Plumbing - Water Heaters"]',
    1,
    'http://www.anytimeplumber.us/',
    NULL,
    '(971) 254-1858',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-136',
    'Mike Patterson Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Water Heaters","Water Heater Repair","!R H Heating & Cooling - Heat Pumps"]',
    1,
    NULL,
    36,
    '(503) 908-6449',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-137',
    'R H Heating & Cooling',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Heat Pumps","Major Appliances","!H & H Mechanical - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 252-9672',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-138',
    'H & H Mechanical',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!ProDrain & Rooter Service - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 975-9787',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-139',
    'ProDrain & Rooter Service',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing Contractors-Commercial & Industrial","!Skilled Technicians Plumbing - Plumbers"]',
    1,
    'http://prodrainpdx.com/',
    NULL,
    '(503) 533-0430',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-140',
    'Skilled Technicians Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Rooter Plumbers Tualatin - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 473-0095',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-141',
    'Rooter Plumbers Tualatin',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!12W Rpo - Plumbers"]',
    1,
    NULL,
    17,
    '(971) 266-5618',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-142',
    '12W Rpo',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Jack Howk Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 241-2749',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-143',
    'Jack Howk Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Motoczysz - Plumbers"]',
    1,
    'http://www.jackhowk.com/',
    NULL,
    '(503) 235-8784',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-144',
    'Motoczysz',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Mechanical Contractors","!3 Mountains Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 546-6686',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-145',
    '3 Mountains Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Consolidated Supply Co - Plumbers"]',
    1,
    NULL,
    28,
    '(503) 670-1342',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-146',
    'Consolidated Supply Co',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers"]',
    1,
    'http://consolidatedsupply.com/',
    NULL,
    '(503) 281-1251',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-147',
    'The Perfect Service Plumbing and Drain Cleaning',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Plumbing, Drains & Sewer Consultants","!Water Leak Repair - Plumbers"]',
    1,
    'https://www.theperfectservice.com/',
    NULL,
    '(503) 964-4000',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-148',
    'Water Leak Repair',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Rescue Rooter Jack Howk Portland - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 232-0414',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-149',
    'Rescue Rooter Jack Howk Portland',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Ranieri Plumbing - Plumbers"]',
    1,
    'https://www.ars.com/rescue-rooter-jack-howk-portland',
    NULL,
    '(503) 850-3122',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-150',
    'Ranieri Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers"]',
    1,
    'https://ranieriplumbing.com/',
    NULL,
    '(503) 719-6671',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-1',
    'Roto-Rooter Plumbing & Water Cleanup',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Water Heater Repair","Water Heaters","Online Specials","!Roto-Rooter Plumbing & Water Cleanup - Plumbers"]',
    1,
    'https://www.rotorooter.com/portland/?utm_source=iyp&utm_medium=paid&utm_campaign=iyp',
    90,
    '(971) 314-0126',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-2',
    'Roto-Rooter Plumbing & Water Cleanup',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Water Heater Repair","Plumbing-Drain & Sewer Cleaning","Online Specials","!Roto-Rooter Plumbing & Water Cleanup - Plumbers"]',
    1,
    'https://www.rotorooter.com/wilsonvilleor/?utm_source=iyp&utm_medium=paid&utm_campaign=iyp',
    90,
    '(971) 405-7736',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-3',
    'Roto-Rooter Plumbing & Water Cleanup',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Sewer Cleaners & Repairers","Water Damage Restoration","Online Specials","!FX Repair & Remodeling - Building Contractors"]',
    1,
    'https://www.rotorooter.com/salemor/?utm_source=iyp&utm_medium=paid&utm_campaign=iyp',
    90,
    '(971) 449-0492',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  );