INSERT INTO businesses (
      id, name, city, state, industry, services, verified, website, 
      yearsInBusiness, phone, address, email, rating, reviewCount, 
      licenseNumber, bbbRating, emergencyService
    ) VALUES (
    'eugene-GeneralContractors-111',
    'Dmoir Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","!Norwest Builders Inc - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 510-7326',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-112',
    'Norwest Builders Inc',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","!Marty Mar Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 513-6476',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-113',
    'Marty Mar Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Altering & Remodeling Contractors","!Mac Detailing Inc - General Contractors"]',
    1,
    'https://martymarconstruction.com/',
    NULL,
    '(541) 554-8181',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-114',
    'Mac Detailing Inc',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","!Goldenridge Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 461-8503',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-115',
    'Goldenridge Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","!Adept Construction - General Contractors"]',
    1,
    NULL,
    NULL,
    '(541) 688-7599',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-116',
    'Adept Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","!Kaminski Construction - General Contractors"]',
    1,
    'https://adeptconstruction.com/',
    NULL,
    '(541) 461-2401',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-117',
    'Kaminski Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Real Estate Developers","Building Contractors","!McIntyre Construction, Inc - General Contractors"]',
    1,
    'https://kaminskiconstruction.com/',
    NULL,
    '(541) 505-7535',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-118',
    'McIntyre Construction, Inc',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors-Commercial & Industrial","!Gainsborough Construction - General Contractors"]',
    1,
    'https://www.mcintyre.construction/',
    NULL,
    '(541) 687-2841',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-119',
    'Gainsborough Construction',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Home Builders","Building Contractors-Commercial & Industrial","!Camas Construction Co - General Contractors"]',
    1,
    'http://www.gainsboroughhomes.com/',
    NULL,
    '(541) 461-8569',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-GeneralContractors-120',
    'Camas Construction Co',
    'Eugene',
    'OR',
    'general-contractors',
    '["General Contractors","Building Contractors-Commercial & Industrial","Home Builders"]',
    1,
    NULL,
    NULL,
    '(541) 954-7646',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-1',
    'Baxter Plumbing & Rooter Inc',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Backflow Prevention Devices & Services","!Cascadia Construction and Plumbing - Plumbers"]',
    1,
    'http://www.baxterplumbing.com/',
    19,
    '(458) 298-2077',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-2',
    'Cascadia Construction and Plumbing',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","General Contractors","!Accurate Leak Detection - Plumbers"]',
    1,
    'http://www.cascadia.co/',
    NULL,
    '(541) 585-2339',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-3',
    'Accurate Leak Detection',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","Leak Detecting Service","!Alpine Pump Inc - Plumbers"]',
    1,
    'http://www.accurateleakdetection.org/',
    NULL,
    '(458) 247-3504',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-4',
    'Alpine Pump Inc',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","Water Pressure Cleaning","Water Filtration & Purification Equipment","!Roto-Rooter Plumbing & Water Cleanup - Plumbers"]',
    1,
    NULL,
    41,
    '(458) 239-6401',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-5',
    'Roto-Rooter Plumbing & Water Cleanup',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","Water Damage Restoration","Water Damage Emergency Service","Online Specials","!Tom''s Plumbing Service - Plumbers"]',
    1,
    'https://www.rotorooter.com/eugene/?utm_source=iyp&utm_medium=paid&utm_campaign=iyp',
    90,
    '(541) 762-4675',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-6',
    'Tom''s Plumbing Service',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","Backflow Prevention Devices & Services","Leak Detecting Service","!Bohemia Plumbing & Construction - Plumbers"]',
    1,
    'https://www.tomsplumbingserviceinc.com/',
    38,
    '(458) 221-4803',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-7',
    'Bohemia Plumbing & Construction',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","Pumps","Plumbing-Drain & Sewer Cleaning","!Roto-Rooter - Plumbers"]',
    1,
    'https://bohemiaplumbing.net/',
    42,
    '(458) 273-5031',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-8',
    'Roto-Rooter',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","Water Damage Emergency Service","Grease Traps","Online Specials"]',
    1,
    'https://www.rotorooter.com/albanyor/?utm_source=iyp&utm_medium=paid&utm_campaign=iyp',
    90,
    '(541) 918-2530',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-9',
    'Right Way Plumbing And Backflow Service, Inc',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","Water Heaters"]',
    1,
    NULL,
    NULL,
    '(541) 762-1318',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-10',
    'Twin Rivers Plumbing',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","Building Contractors-Commercial & Industrial","Backflow Prevention Devices & Services","!La Z Drains - Plumbers"]',
    1,
    'http://www.twinrp.com/',
    48,
    '(541) 688-1444',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-11',
    'La Z Drains',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Sewer Cleaners & Repairers","!John The Plumber Inc - Plumbers"]',
    1,
    NULL,
    56,
    '(541) 485-1949',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-12',
    'John The Plumber Inc',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","!Kevin Cohen Plumbing, Inc. - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 686-4888',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-13',
    'Kevin Cohen Plumbing, Inc.',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","!Ready Rooter & Chapman Plumbing - Plumbers"]',
    1,
    'http://kevincohenplumbing.com/',
    28,
    '(541) 607-9208',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-14',
    'Ready Rooter & Chapman Plumbing',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","Sewer Cleaners & Repairers","Septic Tanks & Systems","!Bronco Plumbing & Rooter - Plumbers"]',
    1,
    'https://www.eugeneplumbers.net/',
    79,
    '(541) 744-7991',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-15',
    'Bronco Plumbing & Rooter',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Water Heater Repair","!Baxter Plumbing & Rooter, Inc. - Plumbers"]',
    1,
    NULL,
    NULL,
    '(458) 245-1077',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-16',
    'Baxter Plumbing & Rooter, Inc.',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","!Einstein Plumbing and Heating - Plumbers"]',
    1,
    'http://www.baxterplumbing.com/',
    NULL,
    '(541) 334-6696',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-17',
    'Einstein Plumbing and Heating',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","Heating Equipment & Systems-Repairing","Air Conditioning Contractors & Systems","!La-Z-Drain - Plumbers"]',
    1,
    'https://einsteinplumbing.com/eugene-or',
    16,
    '(541) 632-7910',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-18',
    'La-Z-Drain',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","!Plumbers Eugene - Plumbers"]',
    1,
    'https://www.theplumbingworksor.com/',
    NULL,
    '(541) 485-1949',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-19',
    'Plumbers Eugene',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","Building Contractors-Commercial & Industrial","!Local Plumbing Eugene OR - Plumbers"]',
    1,
    NULL,
    NULL,
    '(458) 201-5105',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-20',
    'Local Plumbing Eugene OR',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","!TAR MAN - Plumbers"]',
    1,
    NULL,
    13,
    '(541) 248-6755',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-21',
    'TAR MAN',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","!Pacific Plumbing and Rooter - Plumbers"]',
    1,
    NULL,
    16,
    '(541) 607-4440',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-22',
    'Pacific Plumbing and Rooter',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Sewer Cleaners & Repairers","!Ready Rooter Chapman Plumbing - Plumbers"]',
    1,
    'https://pproregon.com/',
    12,
    '(541) 505-9312',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-23',
    'Ready Rooter Chapman Plumbing',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","Boiler Repair & Cleaning","Sewer Contractors","!Green City Construction and Plumbing - Plumbers"]',
    1,
    NULL,
    79,
    '(541) 484-5222',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-24',
    'Green City Construction and Plumbing',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","!Plumber In Eugene Local Area - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 780-6174',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-25',
    'Plumber In Eugene Local Area',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","!R S Plumbing Contractor Inc - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 525-9127',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-26',
    'R S Plumbing Contractor Inc',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","!Mike Ediger Plumbing - Plumbers"]',
    1,
    'http://rsplumbinginc.com/contact',
    NULL,
    '(541) 461-4714',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-27',
    'Mike Ediger Plumbing',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","Water Heater Repair","Water Heaters","!Reliable Plumbing and Mechanical - Plumbers"]',
    1,
    NULL,
    33,
    '(541) 510-9966',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-28',
    'Reliable Plumbing and Mechanical',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","!Nws Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 689-4235',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-29',
    'Nws Plumbing',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","!Eugene Plumbing Company - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 345-1098',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-30',
    'Eugene Plumbing Company',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","!Eugene Plumbing Company - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 484-7440',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-31',
    'Eugene Plumbing Company',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","!Mc Plumbing Service - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 484-7440',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-32',
    'Mc Plumbing Service',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","Home Improvements","!Sniders Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 689-2313',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-33',
    'Sniders Plumbing',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Sewer Contractors","!Nws Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 461-0166',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-34',
    'Nws Plumbing',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","!JD Graham Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 345-1098',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-35',
    'JD Graham Plumbing',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","!Don Lewis Plumbing Service - Plumbers"]',
    1,
    'https://www.oregon.gov/BCD/pages/index.aspx',
    NULL,
    '(541) 653-9523',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-36',
    'Don Lewis Plumbing Service',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","!Accurate Leak Detection Service - Plumbers"]',
    1,
    'http://www.cbs.state.or.us/bcd',
    NULL,
    '(541) 688-1931',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-37',
    'Accurate Leak Detection Service',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","!Dustin Dawson Plumbing - Plumbers"]',
    1,
    'http://www.accurateleak.net/',
    31,
    '(541) 654-0553',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-38',
    'Dustin Dawson Plumbing',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","!Alpha Plumbing & Rooter S - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 953-8760',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-39',
    'Alpha Plumbing & Rooter S',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","!E E Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 225-2266',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-40',
    'E E Plumbing',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","!Whitted, Shane - Plumbers"]',
    1,
    'http://eeplumbing.blogspot.com/p/contact.html',
    NULL,
    '(541) 514-3476',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-41',
    'Whitted, Shane',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","!Doug''s Plumbing Inc - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 461-1904',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-42',
    'Doug''s Plumbing Inc',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","!Green City Construction - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 688-3385',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-43',
    'Green City Construction',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","!Specialty Plumbing - Plumbers"]',
    1,
    'http://www.greencityconstruction.com/',
    NULL,
    '(541) 520-7225',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-44',
    'Specialty Plumbing',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","Altering & Remodeling Contractors","Home Improvements","!Absolute Plumbing Inc - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 686-4191',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-45',
    'Absolute Plumbing Inc',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","!Cascade Valley Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 345-3055',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-46',
    'Cascade Valley Plumbing',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","!Lancelot''s Drain Cleaning - Plumbers"]',
    1,
    NULL,
    NULL,
    '(541) 689-4291',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-47',
    'Lancelot''s Drain Cleaning',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","!Hydro Pro Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(888) 437-5439',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-48',
    'Hydro Pro Plumbing',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","Sewer Contractors","!John''s Precision Plumbing - Plumbers"]',
    1,
    'http://www.hydroproplumbing.com/',
    16,
    '(541) 335-9879',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-49',
    'John''s Precision Plumbing',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","!Specialty Plumbing Co - Plumbers"]',
    1,
    'http://www.precisionplumbing.net/',
    NULL,
    '(541) 953-1070',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-50',
    'Specialty Plumbing Co',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","Bathroom Remodeling"]',
    1,
    NULL,
    NULL,
    '(541) 686-4191',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-51',
    'Harvey & Price Mechanical Contractors',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","Mechanical Contractors","Furnaces-Heating"]',
    1,
    'http://www.harveyandprice.com/',
    63,
    '(541) 746-1621',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-52',
    'The Plumbing Works',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Altering & Remodeling Contractors"]',
    1,
    'http://theplumbingworksor.com/',
    50,
    '(541) 484-9869',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-53',
    'Pacific Plumbing E Rooter Inc',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Sewer Cleaners & Repairers","!Above All Sanitation - Portable Toilets"]',
    1,
    NULL,
    24,
    '(541) 505-9312',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-54',
    'Above All Sanitation',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","Portable Toilets","Garbage Collection"]',
    1,
    'https://www.aboveallsanitation.com/pages/about-us',
    24,
    '(541) 935-4248',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-55',
    'Cascadia Construction & Plumbing',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","General Contractors"]',
    1,
    'http://www.cascadia.co/',
    NULL,
    '(541) 460-5060',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-56',
    'Alpha Plumbing & Rooter Service',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","Sewer Cleaners & Repairers","Water Heaters"]',
    1,
    NULL,
    7,
    '(541) 225-2266',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-57',
    'Petersen Plumbing',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Sewer Cleaners & Repairers"]',
    1,
    'https://www.petersenplumbingoregon.com/',
    79,
    '(541) 343-9339',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-58',
    'Eugene Sewer and Drain Cleaning',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Plumbing, Drains & Sewer Consultants","!Plumbers Eugene OR - Water Damage Restoration"]',
    1,
    NULL,
    21,
    '(458) 201-6518',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-59',
    'Plumbers Eugene OR',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","Water Damage Restoration","Plumbing Contractors-Commercial & Industrial"]',
    1,
    NULL,
    19,
    '(541) 248-6755',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'eugene-Plumbers-60',
    'Plumbing Service In Eugene OR',
    'Eugene',
    'OR',
    'plumbers',
    '["Plumbers","Water Damage Restoration","Plumbing Contractors-Commercial & Industrial"]',
    1,
    NULL,
    25,
    '(541) 566-8184',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-1',
    'General Equipment',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Metals","Automobile & Truck Brokers"]',
    1,
    'https://www.general-equip.com/',
    68,
    '(971) 484-8802',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-2',
    'Current Electrical Construction Company',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Home Builders","General Contractors"]',
    1,
    'https://current-electrical.com/',
    38,
    '(503) 977-6528',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-3',
    'Trademark Electrical Contractors LLC',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","!EC Company - Electric Companies"]',
    1,
    'http://trademarkelectrical.com/',
    NULL,
    '(503) 997-0914',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-4',
    'EC Company',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Electric Companies","!Tice Electric - Electricians"]',
    1,
    'https://ecpowerslife.com/',
    NULL,
    '(503) 224-3511',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-5',
    'Tice Electric',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Electric Companies","Electronic Equipment & Supplies-Repair & Service","!Bergelectric Corp - Electricians"]',
    1,
    'http://ticeelectric.com/',
    NULL,
    '(503) 233-8801',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-6',
    'Bergelectric Corp',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","!IES Commercial Inc - Electricians"]',
    1,
    'https://www.bergelectric.com/locations/portland',
    79,
    '(503) 255-1818',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-7',
    'IES Commercial Inc',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","!CornerStone Electric - Electricians"]',
    1,
    'http://ies-co.com/',
    NULL,
    '(503) 648-1900',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-8',
    'CornerStone Electric',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Electrical Wire Harnesses","!ABC Electric - Electricians"]',
    1,
    'http://www.cornerstone-electric.com/',
    NULL,
    '(503) 490-9471',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-9',
    'ABC Electric',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Electrical Power Systems-Maintenance","!Oregon Electric Group - Electricians"]',
    1,
    NULL,
    NULL,
    '(503) 233-7551',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-10',
    'Oregon Electric Group',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","!A Plus Electrical Service Inc - Electricians"]',
    1,
    NULL,
    10,
    '(503) 288-5161',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-11',
    'A Plus Electrical Service Inc',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","!Electrical Construction Company - Electricians"]',
    1,
    NULL,
    NULL,
    '(503) 284-7300',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-12',
    'Electrical Construction Company',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Home Builders","General Contractors","!Merit Electric - Electricians"]',
    1,
    'http://www.ecps.com/',
    NULL,
    '(503) 224-3511',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-13',
    'Merit Electric',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","!Rose City Electric Co - Electricians"]',
    1,
    'http://meritelectric.net/',
    NULL,
    '(503) 248-1716',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-14',
    'Rose City Electric Co',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","!Tri Star Electric Inc - Electricians"]',
    1,
    NULL,
    NULL,
    '(503) 287-6164',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-15',
    'Tri Star Electric Inc',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","!Phoenix Electric - Electricians"]',
    1,
    NULL,
    NULL,
    '(503) 860-3838',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-16',
    'Phoenix Electric',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","!A & D Electric Inc - Electricians"]',
    1,
    'http://phoenixpdx.com/',
    20,
    '(503) 231-8006',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-17',
    'A & D Electric Inc',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","!North By Northwest Electric - Electricians"]',
    1,
    NULL,
    NULL,
    '(503) 227-0534',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-18',
    'North By Northwest Electric',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","!Dynalectric-Portland - Electricians"]',
    1,
    NULL,
    NULL,
    '(503) 278-5479',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-19',
    'Dynalectric-Portland',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","!O''Neill Electric - Electricians"]',
    1,
    'http://dyna-portland.com/',
    NULL,
    '(503) 226-6771',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-20',
    'O''Neill Electric',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","General Contractors","!Zapp Electric Inc - Electricians"]',
    1,
    'http://www.oneillelectricinc.com/',
    NULL,
    '(503) 493-6045',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-21',
    'Zapp Electric Inc',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","!Jet Electric Inc - Electricians"]',
    1,
    NULL,
    30,
    '(503) 253-9288',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-22',
    'Jet Electric Inc',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","General Contractors","Home Builders","!Bachofner Electric - Electricians"]',
    1,
    'http://www.jetelectric.biz/',
    25,
    '(503) 258-1715',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-23',
    'Bachofner Electric',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","!H & H Electric Inc - Electricians"]',
    1,
    'http://www.bachofnerelectric.com/',
    41,
    '(503) 327-8872',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-24',
    'H & H Electric Inc',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","!Nixon Electric - Electricians"]',
    1,
    NULL,
    NULL,
    '(503) 253-0425',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-25',
    'Nixon Electric',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","!Advantage Electric - Electricians"]',
    1,
    'http://www.cbs.state.or.us/bcd',
    NULL,
    '(503) 654-8841',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-26',
    'Advantage Electric',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Electric Contractors-Commercial & Industrial","!Badger Electric - Electricians"]',
    1,
    'http://www.advantageelectricpdx.com/',
    NULL,
    '(503) 235-5854',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-27',
    'Badger Electric',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","!Reds Electric Company Inc - Electricians"]',
    1,
    'http://www.badgerelectricinc.com/',
    21,
    '(503) 288-4756',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-28',
    'Reds Electric Company Inc',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Home Improvements","!Delstar Electric - Electricians"]',
    1,
    'http://redselectric.com/',
    61,
    '(503) 233-6467',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-29',
    'Delstar Electric',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","!Bridgetown Electric - Electricians"]',
    1,
    'http://www.cbs.state.or.us/bcd',
    NULL,
    '(503) 684-8848',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Electricians-30',
    'Bridgetown Electric',
    'Portland',
    'OR',
    'electricians',
    '["Electricians","Altering & Remodeling Contractors","Home Improvements","!Stoner Electric Group - Electricians"]',
    1,
    'http://bridgetownelectric.com/',
    31,
    '(503) 621-7122',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  );