INSERT INTO businesses (
      id, name, city, state, industry, services, verified, website, 
      yearsInBusiness, phone, address, email, rating, reviewCount, 
      licenseNumber, bbbRating, emergencyService
    ) VALUES (
    'roseburg-RealEstateAgents-33',
    'The Mary Gilbert Group at Keller Williams Realty Umpqua Valley',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Consultants","!Premium Properties - Real Estate Agents"]',
    1,
    'http://kw.com/',
    NULL,
    '(541) 371-5500',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-34',
    'Premium Properties',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Dick Meyer & Associates - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 229-0662',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-35',
    'Dick Meyer & Associates',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Currieco Real Estate Inc - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 673-0681',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-36',
    'Currieco Real Estate Inc',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","Real Estate Buyer Brokers","!Rmls - Real Estate Agents"]',
    1,
    'https://www.curriecorealestate.com/',
    32,
    '(541) 784-2284',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-37',
    'Rmls',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Linda R Jones Realty - Real Estate Agents"]',
    1,
    'http://rmls.com/',
    NULL,
    '(503) 236-7657',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-38',
    'Linda R Jones Realty',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(541) 672-2109',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-39',
    'Berkshire Half Away Home Services Real Estate Professional',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","Commercial Real Estate","!Walt Gayner Real Estate - Real Estate Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 430-5000',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-40',
    'Walt Gayner Real Estate',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Attorneys","Real Estate Buyer Brokers"]',
    1,
    'http://www.waltgayner.com/',
    21,
    '(541) 672-6205',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-41',
    'Jeremiah Perry REALTOR® - Gilman Homes',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","Real Estate Appraisers"]',
    1,
    'https://jpgilmanhomes.com/',
    NULL,
    '(541) 580-3693',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-42',
    'All Brokers Real Estate',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(541) 229-3232',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-43',
    'Douglas Multi Family Property Management Corp-Orchard Knoll',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","!Coldwell Banker - Real Estate Buyer Brokers"]',
    1,
    'https://www.hadcor.org/general/page/orchard-knoll-apartments-roseburg-or',
    NULL,
    '(541) 637-0601',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-44',
    'Coldwell Banker',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Developers"]',
    1,
    'https://www.coldwellbanker.com/coldwell-banker-platinum-54995c/roseburg-office-1253091d',
    NULL,
    '(541) 784-8959',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-45',
    'Liz Buys Houses',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","Video","!Sell My House Fast - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(833) 274-9691',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-46',
    'Sell My House Fast',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","!House Buyer Network - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(833) 275-0061',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-47',
    'House Buyer Network',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants"]',
    1,
    NULL,
    NULL,
    '(833) 274-7871',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-48',
    'Pearl Hergert Heaton, eXp Realty',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Appraisers","Real Estate Consultants","!Nancy Kruger Real Estate - Real Estate Agents"]',
    1,
    'https://www.pearlhergertheatonrealty.com/about',
    5,
    '(541) 510-5004',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-49',
    'Nancy Kruger Real Estate',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Winston Realty & Insurance - Auto Insurance"]',
    1,
    'https://nancykruger.com/',
    9,
    '(541) 643-8111',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-50',
    'Winston Realty & Insurance',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Auto Insurance","Life Insurance"]',
    1,
    NULL,
    67,
    '(541) 679-8726',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-51',
    'Currieco Real Estate Inc',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","Real Estate Buyer Brokers","!North County REALTY - Real Estate Agents"]',
    1,
    'http://curriecorealestate.com/',
    41,
    '(541) 679-4232',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-52',
    'North County REALTY',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","Real Estate Buyer Brokers","!Jeg Properties - Real Estate Agents"]',
    1,
    'http://www.northcountyrealty.net/',
    NULL,
    '(541) 459-2232',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-53',
    'Jeg Properties',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!River Valley Realty - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 863-7437',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-54',
    'River Valley Realty',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","Real Estate Buyer Brokers","!New Century Realty - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 802-1100',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-55',
    'New Century Realty',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate","!Ryan Fox Realtor - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 315-2900',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-56',
    'Ryan Fox Realtor',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Village Realty - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 315-2358',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-RealEstateAgents-57',
    'Village Realty',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Loans","Real Estate Rental Service"]',
    1,
    'http://www.corkboot.com/',
    61,
    '(541) 863-3134',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-1',
    'Karen Volk Realty',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Appraisers","!The Integrity Team - Real Estate Agents"]',
    1,
    'http://www.karenvolkrealty.com/',
    35,
    '(541) 672-4444',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-2',
    'The Integrity Team',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Roseburg Realty - Real Estate Agents"]',
    1,
    'http://integrityteam.harcourtsusa.com/',
    NULL,
    '(541) 673-3334',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-3',
    'Roseburg Realty',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!G Stiles Realty - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 672-3344',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-4',
    'G Stiles Realty',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Management","!Garden Valley Realty - Real Estate Agents"]',
    1,
    'http://www.gstiles.com/',
    46,
    '(541) 672-1616',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-5',
    'Garden Valley Realty',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate"]',
    1,
    'http://gardenvalleyrealty.com/',
    NULL,
    '(541) 672-4888',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-6',
    'The Neil Company Real Estate',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Apartments","Real Estate Buyer Brokers","View all 2 Locations","!All-Pro Realty Advisors - Real Estate Agents"]',
    1,
    'https://www.neilco.com/',
    48,
    '(541) 673-4417',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-7',
    'All-Pro Realty Advisors',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Appraisers","Commercial Real Estate","!Norman, Jerry, RLTR - Real Estate Agents"]',
    1,
    'https://apr-advisors.com/',
    4,
    '(541) 696-1600',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-8',
    'Norman, Jerry, RLTR',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Landerer, Matt, AGT - Real Estate Agents"]',
    1,
    'https://www.sellwithnorman.com/',
    NULL,
    '(234) 855-7039',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-9',
    'Landerer, Matt, AGT',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Wehe, Kayla, RLTR - Real Estate Agents"]',
    1,
    'https://www.landeverhome.com/',
    NULL,
    '(443) 632-5195',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-10',
    'Wehe, Kayla, RLTR',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'http://oregonhomesbykayla.com/about',
    NULL,
    '(541) 580-2376',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-11',
    'The Mary Gilbert Group at Keller Williams Realty Umpqua Valley',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Consultants"]',
    1,
    'https://www.marygilbert.com/',
    NULL,
    '(541) 371-5500',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-12',
    'Julie Bancroft Real Estate Broker',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://www.neilco.com/',
    NULL,
    '(541) 680-1484',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-13',
    'Jacob Gilman, REALTOR | Gilman Homes',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants"]',
    1,
    'http://gilman-homes.com/',
    10,
    '(541) 580-1494',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-14',
    'RE/MAX; Professional Realty ESS2',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Management","!Sanddollar Properties - Real Estate Agents"]',
    1,
    'http://www.professionalrealty.com/',
    33,
    '(541) 673-3272',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-15',
    'Sanddollar Properties',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Alpine Real Estate - Real Estate Agents"]',
    1,
    'http://sanddollarproperties.blogspot.com/',
    NULL,
    '(541) 464-5849',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-16',
    'Alpine Real Estate',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(541) 229-2992',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-17',
    'Matt Landever Real Estate Agent, Oregon Life Homes',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://www.sellwithnorman.com/',
    NULL,
    '(234) 855-7039',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-18',
    'Aaron Cherry Real Estate Broker',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents"]',
    1,
    'https://www.theoregonlife.com/',
    NULL,
    '(541) 391-1623',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-19',
    'Jerry Norman Real Estate Agent, Oregon Life Homes',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","!GT Reality - Real Estate Agents"]',
    1,
    'https://www.sellwithnorman.com/',
    4,
    '(234) 855-7039',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-20',
    'GT Reality',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(541) 637-5490',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-21',
    'Mastforney Real Estate Group',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(541) 900-1298',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-22',
    'Berkshire Hathaway HomeServices Real Estate Professionals',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Prudential Real Estate - Real Estate Agents"]',
    1,
    'http://roseburghomes4u.com/',
    NULL,
    '(541) 673-1890',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-23',
    'Prudential Real Estate',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate","!Front Porch Real Estate - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 673-1890',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-24',
    'Front Porch Real Estate',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Harris Realty - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 671-2800',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-25',
    'Harris Realty',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Ryan Fox Realtor - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 900-1833',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-26',
    'Ryan Fox Realtor',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Consultants"]',
    1,
    NULL,
    NULL,
    '(541) 672-3035',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-27',
    'Chosen Properties Real Estate',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!105 Properties - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 673-5514',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-28',
    '105 Properties',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Harcourts Integrity Team - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 672-4810',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-29',
    'Harcourts Integrity Team',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Beach Life Pro Realty - Real Estate Agents"]',
    1,
    'http://integrityteam.harcourtsusa.com/',
    NULL,
    '(541) 673-3334',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-30',
    'Beach Life Pro Realty',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Bob Lamonte Group - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(239) 940-6124',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-31',
    'Bob Lamonte Group',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Prudential Real Estate - Real Estate Agents"]',
    1,
    'https://boblamontegroup.kw.com/',
    NULL,
    '(541) 670-3365',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-32',
    'Prudential Real Estate',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate"]',
    1,
    NULL,
    NULL,
    '(888) 880-2227',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-33',
    'The Mary Gilbert Group at Keller Williams Realty Umpqua Valley',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Consultants","!Premium Properties - Real Estate Agents"]',
    1,
    'http://kw.com/',
    NULL,
    '(541) 371-5500',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-34',
    'Premium Properties',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Dick Meyer & Associates - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 229-0662',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-35',
    'Dick Meyer & Associates',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Currieco Real Estate Inc - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 673-0681',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-36',
    'Currieco Real Estate Inc',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","Real Estate Buyer Brokers","!Rmls - Real Estate Agents"]',
    1,
    'https://www.curriecorealestate.com/',
    32,
    '(541) 784-2284',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-37',
    'Rmls',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","!Linda R Jones Realty - Real Estate Agents"]',
    1,
    'http://rmls.com/',
    NULL,
    '(503) 236-7657',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-38',
    'Linda R Jones Realty',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(541) 672-2109',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-39',
    'Berkshire Half Away Home Services Real Estate Professional',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","Commercial Real Estate","!Walt Gayner Real Estate - Real Estate Attorneys"]',
    1,
    NULL,
    NULL,
    '(541) 430-5000',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-40',
    'Walt Gayner Real Estate',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Attorneys","Real Estate Buyer Brokers"]',
    1,
    'http://www.waltgayner.com/',
    21,
    '(541) 672-6205',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-41',
    'Jeremiah Perry REALTOR® - Gilman Homes',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","Real Estate Appraisers"]',
    1,
    'https://jpgilmanhomes.com/',
    NULL,
    '(541) 580-3693',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-42',
    'All Brokers Real Estate',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers"]',
    1,
    NULL,
    NULL,
    '(541) 229-3232',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-43',
    'Douglas Multi Family Property Management Corp-Orchard Knoll',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","!Coldwell Banker - Real Estate Buyer Brokers"]',
    1,
    'https://www.hadcor.org/general/page/orchard-knoll-apartments-roseburg-or',
    NULL,
    '(541) 637-0601',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-44',
    'Coldwell Banker',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Developers"]',
    1,
    'https://www.coldwellbanker.com/coldwell-banker-platinum-54995c/roseburg-office-1253091d',
    NULL,
    '(541) 784-8959',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-45',
    'Liz Buys Houses',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","Video","!Sell My House Fast - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(833) 274-9691',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-46',
    'Sell My House Fast',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","!House Buyer Network - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(833) 275-0061',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-47',
    'House Buyer Network',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants"]',
    1,
    NULL,
    NULL,
    '(833) 274-7871',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-48',
    'Pearl Hergert Heaton, eXp Realty',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Appraisers","Real Estate Consultants","!Nancy Kruger Real Estate - Real Estate Agents"]',
    1,
    'https://www.pearlhergertheatonrealty.com/about',
    5,
    '(541) 510-5004',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-49',
    'Nancy Kruger Real Estate',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Winston Realty & Insurance - Auto Insurance"]',
    1,
    'https://nancykruger.com/',
    9,
    '(541) 643-8111',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-50',
    'Winston Realty & Insurance',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Auto Insurance","Life Insurance"]',
    1,
    NULL,
    67,
    '(541) 679-8726',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-51',
    'Currieco Real Estate Inc',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Consultants","Real Estate Buyer Brokers","!North County REALTY - Real Estate Agents"]',
    1,
    'http://curriecorealestate.com/',
    41,
    '(541) 679-4232',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-52',
    'North County REALTY',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","Real Estate Buyer Brokers","!Jeg Properties - Real Estate Agents"]',
    1,
    'http://www.northcountyrealty.net/',
    NULL,
    '(541) 459-2232',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-53',
    'Jeg Properties',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!River Valley Realty - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 863-7437',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-54',
    'River Valley Realty',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Management","Real Estate Buyer Brokers","!New Century Realty - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 802-1100',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-55',
    'New Century Realty',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Commercial Real Estate","!Ryan Fox Realtor - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 315-2900',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-56',
    'Ryan Fox Realtor',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Village Realty - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(541) 315-2358',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'roseburg-Roseburg RealEstate Agents-57',
    'Village Realty',
    'Roseburg',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Loans","Real Estate Rental Service"]',
    1,
    'http://www.corkboot.com/',
    61,
    '(541) 863-3134',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  );