INSERT INTO businesses (
      id, name, city, state, industry, services, verified, website, 
      yearsInBusiness, phone, address, email, rating, reviewCount, 
      licenseNumber, bbbRating, emergencyService
    ) VALUES (
    'portland-Leads-Plumbers-Portland-4',
    'FX Repair & Remodeling',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Home Repair & Maintenance","Building Contractors","!Pipe Systems Plumbing - Plumbers"]',
    1,
    'http://www.fxrepair.com/',
    36,
    '(503) 542-4442',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-5',
    'Pipe Systems Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Red Roo Plumbing - Plumbers"]',
    1,
    'http://pipesystems.weebly.com/photo-page.html',
    NULL,
    '(503) 895-8609',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-6',
    'Red Roo Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!ProDrain & Rooter Service - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 319-9045',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-7',
    'ProDrain & Rooter Service',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing Contractors-Commercial & Industrial","!Just Plumbing Co - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 912-8822',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-8',
    'Just Plumbing Co',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!R D Plumbing Inc - Plumbers"]',
    1,
    'https://justplumbing.co/',
    NULL,
    '(503) 260-0901',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-9',
    'R D Plumbing Inc',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers"]',
    1,
    NULL,
    34,
    '(503) 297-7422',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-10',
    'Anytime Plumbing & Drain Cleaning Service',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Sewer Cleaners & Repairers","!D & F Plumbing - Plumbers"]',
    1,
    'http://www.anytimeplumber.us/',
    15,
    '(503) 894-8241',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-11',
    'D & F Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Sewer Cleaners & Repairers","Gas Lines-Installation & Repairing","!H & H Mechanical - Plumbers"]',
    1,
    'http://www.dandfplumbing.com/',
    98,
    '(503) 282-0993',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-12',
    'H & H Mechanical',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!ProDrain & Rooter Service - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 975-9787',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-13',
    'ProDrain & Rooter Service',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing Contractors-Commercial & Industrial","!Dean Pottle Plumbing - Plumbers"]',
    1,
    'http://prodrainpdx.com/',
    NULL,
    '(503) 533-0430',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-14',
    'Dean Pottle Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Power Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(971) 533-7936',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-15',
    'Power Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing, Drains & Sewer Consultants","Plumbing Contractors-Commercial & Industrial","!Einstein Pros Plumbing Portland - Plumbers"]',
    1,
    'http://www.powerplumbingco.com/',
    40,
    '(503) 244-1900',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-16',
    'Einstein Pros Plumbing Portland',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Leak Detecting Service","Plumbing-Drain & Sewer Cleaning","!Portland Vintage Plumbing - Plumbers"]',
    1,
    'https://einsteinprosportland.com/',
    NULL,
    '(503) 821-4070',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-17',
    'Portland Vintage Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing Fixtures, Parts & Supplies","General Contractors","!Axiom PDX - Plumbers"]',
    1,
    NULL,
    12,
    '(971) 404-8149',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-18',
    'Axiom PDX',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Roto-Rooter Plumbing & Water Cleanup - Plumbers"]',
    1,
    'http://axiompdx.com/',
    NULL,
    '(503) 869-2913',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-19',
    'Roto-Rooter Plumbing & Water Cleanup',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","View all 2 Locations","!Pacific Plumbing & Drain Services - Plumbers"]',
    1,
    'https://www.rotorooter.com/portland',
    90,
    '(503) 937-1993',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-20',
    'Pacific Plumbing & Drain Services',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Septic Tank & System Cleaning","Excavation Contractors","!Cascade Plumbing - Plumbers"]',
    1,
    'https://pacificplumbinganddrain.com/',
    NULL,
    '(503) 419-9759',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-21',
    'Cascade Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Cornel''s Plumbing Inc. - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 289-7095',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-22',
    'Cornel''s Plumbing Inc.',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Sewer Contractors","!Da Vinci''s Best Plumbing - Plumbers"]',
    1,
    'http://cornelsplumbing.com/',
    44,
    '(503) 523-4854',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-23',
    'Da Vinci''s Best Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Water Heater Repair","!Skilled Technicians Plumbing - Plumbers"]',
    1,
    'https://davincisbestplumbing.com/',
    NULL,
    '(971) 220-8685',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-24',
    'Skilled Technicians Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Rooter Plumbers Tualatin - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 473-0095',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-25',
    'Rooter Plumbers Tualatin',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!12W Rpo - Plumbers"]',
    1,
    NULL,
    17,
    '(971) 266-5618',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-26',
    '12W Rpo',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Jack Howk Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 241-2749',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-27',
    'Jack Howk Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Motoczysz - Plumbers"]',
    1,
    'http://www.jackhowk.com/',
    NULL,
    '(503) 235-8784',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-28',
    'Motoczysz',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Mechanical Contractors","!3 Mountains Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 546-6686',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-29',
    '3 Mountains Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Consolidated Supply Co - Plumbers"]',
    1,
    NULL,
    28,
    '(503) 670-1342',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-30',
    'Consolidated Supply Co',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers"]',
    1,
    'http://consolidatedsupply.com/',
    NULL,
    '(503) 281-1251',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-31',
    'The Perfect Service Plumbing and Drain Cleaning',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","Plumbing, Drains & Sewer Consultants","!Water Leak Repair - Plumbers"]',
    1,
    'https://www.theperfectservice.com/',
    NULL,
    '(503) 964-4000',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-32',
    'Water Leak Repair',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Rescue Rooter Jack Howk Portland - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 232-0414',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-33',
    'Rescue Rooter Jack Howk Portland',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Ranieri Plumbing - Plumbers"]',
    1,
    'https://www.ars.com/rescue-rooter-jack-howk-portland',
    NULL,
    '(503) 850-3122',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-34',
    'Ranieri Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Clog Pro Plumbing & Drain - Plumbers"]',
    1,
    'https://ranieriplumbing.com/',
    NULL,
    '(503) 719-6671',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-35',
    'Clog Pro Plumbing & Drain',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Excavation Contractors","Plumbing-Drain & Sewer Cleaning","!A Boy Electric & Plumbing - Plumbers"]',
    1,
    'https://clogpro.com/',
    NULL,
    '(503) 252-5500',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-36',
    'A Boy Electric & Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Rose City Contracting Inc - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 952-0015',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-37',
    'Rose City Contracting Inc',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Realistic Plumbing - Plumbers"]',
    1,
    'http://rosecitycontracting.com/',
    NULL,
    '(503) 624-6527',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-38',
    'Realistic Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Presidential Plumbing & Drain - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 742-1955',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-39',
    'Presidential Plumbing & Drain',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Agent Plumbing Inc - Plumbers"]',
    1,
    NULL,
    NULL,
    '(360) 882-3979',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-40',
    'Agent Plumbing Inc',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Ranieri Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 579-3132',
    '[object Object]',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-41',
    'Ranieri Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Unclogging Kitchen Sink - Plumbers"]',
    1,
    'http://ranieriplumbing.com/wp',
    NULL,
    '(503) 719-6671',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-42',
    'Unclogging Kitchen Sink',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Dean Warren Plumbing & Remodel - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 290-5218',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-43',
    'Dean Warren Plumbing & Remodel',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Cheap Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 236-4152',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-44',
    'Cheap Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Earl J Wisdom Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 290-5015',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-45',
    'Earl J Wisdom Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Soren - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 380-9850',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-46',
    'Soren',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Three Mountain Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 477-6232',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-47',
    'Three Mountain Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 206-8511',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-48',
    'REX L Walker Plumbing Remodeling Service',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Air Conditioning Contractors & Systems","Heating Contractors & Specialties","!Crescent Plumbing Co - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 288-5593',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-49',
    'Crescent Plumbing Co',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Services","!Caliber Plumbing & Mechanical Inc - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 233-0738',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-50',
    'Caliber Plumbing & Mechanical Inc',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Green Repipe - Plumbers"]',
    1,
    'http://calibermechanical.com/',
    NULL,
    '(503) 206-7591',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-51',
    'Green Repipe',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!A Better Plumbing Co - Plumbers"]',
    1,
    'http://www.greenrepipe.com/',
    NULL,
    '(503) 501-1469',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-52',
    'A Better Plumbing Co',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Sewer Contractors","!Walker I Corp - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 329-0702',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-53',
    'Walker I Corp',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Paramount Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 312-6173',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-54',
    'Paramount Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Michael Francis Brady - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 239-7516',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-55',
    'Michael Francis Brady',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Sellwood - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 336-1205',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-56',
    'Sellwood',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Crown Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 719-4686',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-57',
    'Crown Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Plumbers in Portland or Areas - Plumbers"]',
    1,
    'https://crownplumbingpdx.com/',
    NULL,
    '(503) 719-4686',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-58',
    'Plumbers in Portland or Areas',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!American Plumbing Service LP - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 893-5506',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-59',
    'American Plumbing Service LP',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Max Plumbing - Plumbers"]',
    1,
    'http://americanplumbingservices.com/',
    NULL,
    '(503) 289-6498',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-60',
    'Max Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Max Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 477-6232',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-61',
    'Max Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Evolution Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 477-6232',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-62',
    'Evolution Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Charlie Hall Plumbing Co - Plumbers"]',
    1,
    NULL,
    NULL,
    '(971) 302-7927',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-63',
    'Charlie Hall Plumbing Co',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Hoffman Sewer & Plumbing Contractor - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 774-2686',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-64',
    'Hoffman Sewer & Plumbing Contractor',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Sewer Contractors","Plumbing-Drain & Sewer Cleaning","!Max Plumbing - Plumbers"]',
    1,
    'http://hoffmansewers.com/',
    36,
    '(503) 243-1255',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-65',
    'Max Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Drain Away Rooter - Plumbers"]',
    1,
    NULL,
    NULL,
    '(971) 254-4391',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-66',
    'Drain Away Rooter',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Evolution Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 252-1334',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-67',
    'Evolution Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Positive Plumbing - Plumbers"]',
    1,
    'http://evoplumbing.net/',
    NULL,
    '(503) 655-3388',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-68',
    'Positive Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Larsen & Son Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 720-3849',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-69',
    'Larsen & Son Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Gates Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 246-7004',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-70',
    'Gates Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Puddletown Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 257-0602',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-71',
    'Puddletown Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!P1 Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 477-7216',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-72',
    'P1 Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Whitlock Building Services - Plumbers"]',
    1,
    'https://www.p1plumbing.com/',
    NULL,
    '(503) 406-8403',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-73',
    'Whitlock Building Services',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Puddletown Plumbing Co - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 936-3044',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-74',
    'Puddletown Plumbing Co',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Advanced Leak Detection I - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 388-2514',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-75',
    'Advanced Leak Detection I',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Mengis Heating & Cooling - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 656-1144',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-76',
    'Mengis Heating & Cooling',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Pacific Crest Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(971) 409-1805',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-77',
    'Pacific Crest Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Legacy Plumbing Inc - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 841-6631',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-78',
    'Legacy Plumbing Inc',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Armstrong Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 816-8887',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-79',
    'Armstrong Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Babbitt Plumbing Inc - Plumbers"]',
    1,
    'https://www.armstrongplumbing.net/contact',
    NULL,
    '(916) 641-0886',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-80',
    'Babbitt Plumbing Inc',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","Plumbing-Drain & Sewer Cleaning","!Black Cat Plumbing, Inc - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 244-5279',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-81',
    'Black Cat Plumbing, Inc',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Portland Plumber Service - Plumbers"]',
    1,
    'http://www.blackcatplumbing.com/',
    NULL,
    '(503) 788-0300',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-82',
    'Portland Plumber Service',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Gregory Benjamin Deane - Plumbers"]',
    1,
    NULL,
    17,
    '(971) 244-8831',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-83',
    'Gregory Benjamin Deane',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!East West Plumbing Inc - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 758-6181',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-84',
    'East West Plumbing Inc',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Everlast Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 777-1594',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-85',
    'Everlast Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Ackerman Plumbing Service - Plumbers"]',
    1,
    'https://everlastplumbingpdx.com/contact',
    NULL,
    '(971) 344-4826',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-86',
    'Ackerman Plumbing Service',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Minyard Plumbing Inc - Plumbers"]',
    1,
    'https://ackermanplumbing.com/',
    NULL,
    '(503) 465-8776',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-87',
    'Minyard Plumbing Inc',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Cascade Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(971) 600-2215',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-88',
    'Cascade Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!KKMJ Plumbing Inc - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 289-7095',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-89',
    'KKMJ Plumbing Inc',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers","!Nash Plumbing - Plumbers"]',
    1,
    NULL,
    NULL,
    '(503) 475-7043',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-Leads-Plumbers-Portland-90',
    'Nash Plumbing',
    'Portland',
    'OR',
    'plumbers',
    '["Plumbers"]',
    1,
    'https://nashplumbingportland.com/',
    NULL,
    '(503) 387-7971',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-1',
    'Maxine Cracraft-John L Scott Real Estate',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Consultants","!Oregon Realty Co - Real Estate Agents"]',
    1,
    NULL,
    43,
    '(503) 220-4243',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-2',
    'Oregon Realty Co',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate","Real Estate Buyer Brokers","!Kunkel Jim Realty - Real Estate Agents"]',
    1,
    'http://www.oregonrealty.com/agent-contact.html?listingid=8101883&aid=461',
    10,
    '(503) 288-9303',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-3',
    'Kunkel Jim Realty',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Fox, Mel - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 252-1166',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-4',
    'Fox, Mel',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Commercial Real Estate","Real Estate Buyer Brokers","!Mark S Zimel & Associates - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 256-0111',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-5',
    'Mark S Zimel & Associates',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Jill Myers Realty - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 684-2051',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-6',
    'Jill Myers Realty',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Citywide Realty - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 654-1084',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-7',
    'Citywide Realty',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Keller Williams Realty - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 253-1900',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-8',
    'Keller Williams Realty',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","Real Estate Consultants","!Realty Solutions - Real Estate Agents"]',
    1,
    'http://www.kw.com/',
    20,
    '(503) 496-5151',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-9',
    'Realty Solutions',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Medak Realty - Real Estate Agents"]',
    1,
    'http://realtysolutionspdx.com/',
    NULL,
    '(503) 292-4336',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-10',
    'Medak Realty',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Meadows Group Inc - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 287-4131',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-11',
    'Meadows Group Inc',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Bohrer Realty - Real Estate Agents"]',
    1,
    NULL,
    NULL,
    '(503) 590-1500',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-12',
    'Bohrer Realty',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Windermere Cronin & Caplan - Real Estate Agents"]',
    1,
    'http://www.bohrerrealty.com/',
    31,
    '(503) 254-7500',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  ),
(
    'portland-RealEstateAgents-13',
    'Windermere Cronin & Caplan',
    'Portland',
    'OR',
    'real-estate',
    '["Real Estate Agents","Real Estate Buyer Brokers","!Georgetown Realty - Real Estate Agents"]',
    1,
    'http://www.windermere.com/',
    NULL,
    '(503) 220-1144',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    0
  );